<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-rodneCislo</name>
   <tag></tag>
   <elementGuidId>f7f6b149-8e23-4a6a-a4c8-dfc1757842e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-rodneCislo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-rodneCislo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15f0d181-54f2-4129-b969-272b087eb9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>f9366e27-bd56-4bae-b7e6-aa482440ce16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d9885ab6-67a4-41e2-ba3f-49cd7f910dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-rodneCislo</value>
      <webElementGuid>49cb7aa3-db01-4666-8b31-fc9068d2d3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>13f819b5-5df3-408f-95fb-459be993ffc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>99eea00c-1751-4807-868d-cb905c54068d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-rodneCislo&quot;)</value>
      <webElementGuid>4dd70daf-db89-4fe2-9252-6ce00cb3dde2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-rodneCislo']</value>
      <webElementGuid>628d4a8d-a3ef-4857-9fec-907c59dfb3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rodneCislo']/div/div[2]/input</value>
      <webElementGuid>c358af24-02c0-43ac-8ad6-635b3dc23101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>e17195a1-788a-4c48-8441-99b3c5b9a4d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-rodneCislo']</value>
      <webElementGuid>2e570cdd-ad4c-419e-b9cb-3dafb0eae22d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
