<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-krstneMeno</name>
   <tag></tag>
   <elementGuidId>6b76dd86-0c59-4e7a-b0ba-91145c9d8b05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-krstneMeno</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-krstneMeno']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8bf31c5e-0c49-44ed-bba3-45ef11db7d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>2525ec62-beb1-4803-a662-8f72065b1886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4564a58d-268e-4755-b0a3-f2bfb7c943e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-krstneMeno</value>
      <webElementGuid>1a460d78-91c5-4aab-a107-e8e67cb60acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>4162742e-44ff-4a3f-9917-1f007673309d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-krstneMeno&quot;)</value>
      <webElementGuid>79ebd969-c7f6-486b-80b1-0df094c23f29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-krstneMeno']</value>
      <webElementGuid>8dbd9c51-2154-4667-942d-09bd9796333f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='krstneMeno']/div/div[2]/input</value>
      <webElementGuid>5f46bd00-c7c7-42b6-b5ee-68600eb11e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/input</value>
      <webElementGuid>3ffe3221-f0b0-4a58-909a-0e593cf4f8ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-krstneMeno']</value>
      <webElementGuid>c99f14c6-7efa-43ea-a009-c644ded926e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
