<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_govuk-input autocomplete-input</name>
   <tag></tag>
   <elementGuidId>537226e6-4e97-4d9e-8b8d-603a5104ba75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#statnaPrislusnost > div.govuk-form-group.autocomplete-control.required > div.input-wrapper > input.govuk-input.autocomplete-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0a834e9-c259-456c-978d-f589c9a0cc3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input autocomplete-input</value>
      <webElementGuid>b7dac75f-d188-4bee-92d6-e7ae6eb93321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>56f93539-d7be-4369-a394-9f15f16638df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8f0baffe-bd4d-4188-9a0f-89a3a9e292bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>bb8de67e-0969-45d1-8f47-4d47e2c21527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>autocomplete-label-statnaPrislusnost</value>
      <webElementGuid>ff01b4b7-f233-45cb-b0f4-33e49fab3347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>07a07bf0-8d42-48a2-b322-2c2936774632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>0dcfa0c7-9e8c-44c1-9032-3c8fefb4141f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;statnaPrislusnost&quot;)/div[@class=&quot;govuk-form-group autocomplete-control required&quot;]/div[@class=&quot;input-wrapper&quot;]/input[@class=&quot;govuk-input autocomplete-input&quot;]</value>
      <webElementGuid>340658a3-5541-4c4f-9dd1-abda8e1bbbdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[8]</value>
      <webElementGuid>daea3571-3557-4137-9ec3-b856ecae6c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='statnaPrislusnost']/div/div[2]/input</value>
      <webElementGuid>b7daa218-f530-42cf-9242-779a48e07048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/input</value>
      <webElementGuid>09ef0538-6336-4e13-916d-128fc8ab91e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>1230dc10-04b8-4e8e-941f-c4a4190af299</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
