<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_K2_input-kriterium-nazov-2</name>
   <tag></tag>
   <elementGuidId>e8e7d75b-4a88-45ce-9bf1-a34646462adb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-kriterium-nazov-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-kriterium-nazov-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c018f3d-103f-4a41-976c-8e15c38b9ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>.*\S.*</value>
      <webElementGuid>23c01db1-fbbd-4bf1-b342-1d785ece1045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input input-kriterium-nazov</value>
      <webElementGuid>2a0a1218-f4f8-4e7e-9e5d-7a7ef1313d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>47c097d4-3c06-4f72-a2f3-89b9ea3b0895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>04e99367-2e7c-469d-bfa2-35ad83768589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Zadajte názov</value>
      <webElementGuid>46cb201f-2320-4cee-ae50-1cffaf0d54e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-kriterium-nazov-2</value>
      <webElementGuid>abef6408-14a4-4c00-a1a3-893f5355e545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-kriterium-nazov-2&quot;)</value>
      <webElementGuid>716f06fa-a5e0-43d0-b88e-957a229c3afd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-kriterium-nazov-2']</value>
      <webElementGuid>e88e4ec4-d252-4d20-a6ce-4de9e337da49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='riaditel-kriteria-list-body']/tr[2]/td[3]/input</value>
      <webElementGuid>04ddf680-9515-4c09-9e6e-b65706a58e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/input</value>
      <webElementGuid>eb83965b-c1a7-4731-a7f6-9a0a87e8b882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Zadajte názov' and @id = 'input-kriterium-nazov-2']</value>
      <webElementGuid>3479cbff-fae7-402e-ab61-560de19c8e55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
