<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_K2_material-icons</name>
   <tag></tag>
   <elementGuidId>f719913b-4146-41a7-a3b3-25c9b43b90f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='kriterium-vypocet-button-2']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kriterium-vypocet-button-2 > span.material-icons</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f75a4abe-3559-4452-8dd9-7110ead4eda0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
      <webElementGuid>422543ab-8951-473f-9493-c2d65190c262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>89be1451-9c4f-494b-96d0-9fdaf37352cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        edit
                    </value>
      <webElementGuid>7270e0d0-edfc-4339-9c30-104c957c779c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kriterium-vypocet-button-2&quot;)/span[@class=&quot;material-icons&quot;]</value>
      <webElementGuid>ed783d1e-398f-49ab-b57a-710574277b0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='kriterium-vypocet-button-2']/span</value>
      <webElementGuid>a4b5ab2b-6941-4ef7-bb48-fd44e83e56a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K2.'])[1]/following::span[1]</value>
      <webElementGuid>52f6880b-64e5-4679-8132-07771c16a6b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K1.'])[1]/following::span[2]</value>
      <webElementGuid>df76fd34-ebdb-4a9d-b3f7-aa91169884c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pridať ďalšie kritérium'])[1]/preceding::span[2]</value>
      <webElementGuid>942b9a84-479a-476f-aeaa-dc4d490a9e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Neplatné znaky vo výpočte'])[1]/preceding::span[4]</value>
      <webElementGuid>d4803609-30f8-47fd-a9d9-1e0016d13327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/div/button/span</value>
      <webElementGuid>1d024330-dd2d-45dc-aa03-c6a84943b47a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                        edit
                    ' or . = '
                        edit
                    ')]</value>
      <webElementGuid>793a9659-984a-4d5d-8caa-0f5cc8663cef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
