<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_K1_kriterium-nazov</name>
   <tag></tag>
   <elementGuidId>4d92336b-fc64-48f1-8711-9d2e15a87e80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='riaditel-kriteria-list-body']/tr/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.kriterium-nazov</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ff101417-ef83-4acb-aa2d-26c837f78aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kriterium-nazov</value>
      <webElementGuid>52c6f6ac-d8e4-4515-9eac-bb1f967a500c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Názov kritéria</value>
      <webElementGuid>90c3cc2b-803e-486a-ae28-7b61c0e18005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required</name>
      <type>Main</type>
      <value>Toto pole je povinné.</value>
      <webElementGuid>bba6a6b9-8731-46d0-9c7a-c7aa296ccee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;riaditel-kriteria-list-body&quot;)/tr[@class=&quot;required&quot;]/td[@class=&quot;kriterium-nazov&quot;]</value>
      <webElementGuid>0c429490-dc98-4e49-8747-3c69bff12cde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='riaditel-kriteria-list-body']/tr/td[3]</value>
      <webElementGuid>c73c6577-a28f-4fcf-81d5-8f92accf51c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K1.'])[1]/following::td[2]</value>
      <webElementGuid>aafff5fa-0db4-4b59-bb43-3a2494333f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Výpočet'])[1]/following::td[3]</value>
      <webElementGuid>a4ee2027-2728-4f82-ada9-f89ba9297e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pridať ďalšie kritérium'])[1]/preceding::td[3]</value>
      <webElementGuid>cf6b41ca-8f81-4e4c-b169-fb3c6b0b2f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Neplatné znaky vo výpočte'])[1]/preceding::td[4]</value>
      <webElementGuid>fe4ce041-719f-423e-baf5-e4efde11d64d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/table/tbody/tr/td[3]</value>
      <webElementGuid>42c9bedd-f590-4599-b35e-fe375524adbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
