<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Odstrni_btn-otvorit-odbor-pre-2-kolo_dae02c</name>
   <tag></tag>
   <elementGuidId>35a1ee6d-9c5c-4f05-b234-61a267cab704</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='odbory-a-kriteria-content']/div[5]/div/div[3]/div/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn-otvorit-odbor-pre-2-kolo.govuk-button.govuk-button__basic.govuk-button__large.last-focusable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7e40dce2-deef-4e6a-9a63-6df396fe620c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-otvorit-odbor-pre-2-kolo govuk-button govuk-button__basic govuk-button__large last-focusable</value>
      <webElementGuid>6777bcfd-82ba-4004-b813-a2e26772c011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a4e4a331-e446-4fe5-9786-3169e4469775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pridať</value>
      <webElementGuid>742f186f-240b-4b97-bfca-45fd323cb5e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;odbory-a-kriteria-content&quot;)/div[@class=&quot;modal-wrapper otvorit-odbor-pre-2-kolo-wrapper&quot;]/div[@class=&quot;modal pridat-odbor-modal&quot;]/div[@class=&quot;buttons-container&quot;]/div[@class=&quot;right-buttons&quot;]/button[@class=&quot;btn-otvorit-odbor-pre-2-kolo govuk-button govuk-button__basic govuk-button__large last-focusable&quot;]</value>
      <webElementGuid>dba455ae-5e6e-466d-ba51-4687ac9e8ffe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='odbory-a-kriteria-content']/div[5]/div/div[3]/div/button[2]</value>
      <webElementGuid>1fa4f8f1-6927-4a72-bde4-1b2ba1a0a459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odstrániť'])[2]/following::button[1]</value>
      <webElementGuid>7ecfd306-7ab6-4f8b-896d-f31942a9b690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zrušiť'])[3]/following::button[2]</value>
      <webElementGuid>8bcda8b4-912c-47fa-befe-b8d29200729b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boli tieto informácie pre vás užitočné?'])[1]/preceding::button[1]</value>
      <webElementGuid>c04b5bb2-3eac-4b80-bd12-b07867f4f593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Áno'])[1]/preceding::button[1]</value>
      <webElementGuid>2d34dcbf-8bff-4c04-bc9a-c8570855e818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pridať']/parent::*</value>
      <webElementGuid>5d6aadf3-14da-4938-9f79-d67b28fd2aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button[2]</value>
      <webElementGuid>b6c80a79-ed5f-447a-a8e5-4bb1a47fef45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Pridať' or . = 'Pridať')]</value>
      <webElementGuid>cc689c6f-bf47-463d-a454-3a42a90bdb91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
