<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Nzov koly alebo jej adresa_fulltext-_b34249</name>
   <tag></tag>
   <elementGuidId>93383ea8-3aaa-488d-b6e9-af0c69728509</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fulltext-input-SS-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fulltext-input-SS-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f7dfb440-525a-43dc-87e5-9337afd5f66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fulltext-input-SS-button</value>
      <webElementGuid>4a86996b-c8f5-4606-99e1-9c5b98c25006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button govuk-button__basic fulltext-input-button</value>
      <webElementGuid>7c45c881-83da-4f81-9200-07f465c6d95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Hľadať</value>
      <webElementGuid>9117708c-a3e6-41dd-b13f-be9c0568f7f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    search
                                </value>
      <webElementGuid>5cde023f-f03d-48b3-a861-44744b64631b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fulltext-input-SS-button&quot;)</value>
      <webElementGuid>9950c210-c065-4156-94d5-a1e8ea5c48b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='fulltext-input-SS-button']</value>
      <webElementGuid>0e1a7ded-7cd1-44d0-be4c-7cd4c4d68721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fulltext-input-wrapper-SS']/div/button</value>
      <webElementGuid>ee69a099-0d09-4211-bfa3-dd48d3effa19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov školy alebo jej adresa'])[1]/following::button[1]</value>
      <webElementGuid>db6e6374-46c0-4dc4-b3e0-2bc06e21a732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtre:'])[7]/following::button[1]</value>
      <webElementGuid>1c062183-0fb2-4cd3-9961-fc95ecab72b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voľná kapacita na prijatie'])[1]/preceding::button[1]</value>
      <webElementGuid>effb1e9a-0db4-421f-8d99-8a6aef1b9cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(nepovinné)'])[24]/preceding::button[1]</value>
      <webElementGuid>ed5c25e6-ce18-4cbe-834e-66e8f7f3cc0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/button</value>
      <webElementGuid>658a4a58-bf8f-41a5-8c0e-10d392b53afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'fulltext-input-SS-button' and (text() = '
                                    search
                                ' or . = '
                                    search
                                ')]</value>
      <webElementGuid>29b41c60-f4cb-4ec3-8195-dbc699576714</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
