<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-rodnePriezvisko</name>
   <tag></tag>
   <elementGuidId>9f706993-7fd8-46e9-bb99-43254e107d37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-rodnePriezvisko</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-rodnePriezvisko']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91d26155-9136-4515-b4d6-1562fc2553b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>c9baafaf-4bd1-4787-8b1f-f4d7f1f87cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>39193d09-6847-435c-a9dc-f1a215fc5082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-rodnePriezvisko</value>
      <webElementGuid>2fca2241-311e-4b0e-88e9-dc6647def149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>9153282e-dc6e-4f7d-b74c-4dab1b4c79a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-rodnePriezvisko&quot;)</value>
      <webElementGuid>6d256c29-cbdc-4254-9cdf-554737f5079a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-rodnePriezvisko']</value>
      <webElementGuid>76df1420-9df2-40b3-8585-9a3507c34a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rodnePriezvisko']/div/div[2]/input</value>
      <webElementGuid>a7a01a37-8f85-44b8-bf79-2b73a39a0619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/input</value>
      <webElementGuid>982c5284-eb19-46e3-820f-26574e921614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-rodnePriezvisko']</value>
      <webElementGuid>085075d8-f515-4a5f-b3b6-104e53211ae3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
