<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-zastupca1InaAdresaPSC</name>
   <tag></tag>
   <elementGuidId>1e26f157-18da-4878-9e09-ddf32ed3a4bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-zastupca1InaAdresaPSC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-zastupca1InaAdresaPSC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72e1709b-b0ba-46f7-9afb-a1b1ee211d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>8d141c2c-ab93-4e6e-9ad6-b6b7de28f9f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>adf363ff-3601-4a6e-9586-ed2538230bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-zastupca1InaAdresaPSC</value>
      <webElementGuid>2d1d1e5e-ade0-4497-a6d6-eff83ce1a62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>6f16afdb-9f8a-4abd-9f5d-3710ab7de412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-zastupca1InaAdresaPSC&quot;)</value>
      <webElementGuid>a4979019-a909-47b1-898d-b24a0e2d06bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-zastupca1InaAdresaPSC']</value>
      <webElementGuid>fa0ec610-144e-490f-81d9-53d92def3f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zastupca1InaAdresaPSC']/div/div[2]/input</value>
      <webElementGuid>84d459bd-7b30-412e-8f2f-3fb258c39855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/input</value>
      <webElementGuid>d711ff37-db78-4e36-bfb2-0d2dd051f325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-zastupca1InaAdresaPSC']</value>
      <webElementGuid>fddfb907-163a-47ce-b502-137e3a299129</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
