<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zadajte telefnne slo vo formte s pred_b3430e</name>
   <tag></tag>
   <elementGuidId>fac3b7e7-7250-45e8-8dc3-9c2048d0ab17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-zastupca1Telefon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-zastupca1Telefon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2d1bd1a-cd07-43d7-9c26-8b54cecf9b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>f59612e7-247b-478f-abf2-1c2cc585ca42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>27779a32-6dbf-4b8f-8b74-30f591c85cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-zastupca1Telefon</value>
      <webElementGuid>d5da2e1c-6024-424a-9a78-cb9f35ce1992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f3a0a3c6-7cde-499e-92ce-ddd5a6d68833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>c8b03688-3fcb-4317-9643-21d9b389f466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-zastupca1Telefon&quot;)</value>
      <webElementGuid>908d571a-9f24-4891-a7c6-962e8a6c0e8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-zastupca1Telefon']</value>
      <webElementGuid>e9652d9e-b4b4-43ae-8286-5ead2f80d4e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zastupca1Telefon']/div/div[2]/input</value>
      <webElementGuid>2a07ad5a-c934-403d-9809-491eea97ee6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/input</value>
      <webElementGuid>9eb7a966-0cbe-407d-a7ed-52f8cc7bdfa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-zastupca1Telefon']</value>
      <webElementGuid>46b1df3d-0770-4e91-b2f9-36f787040fe5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
