<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Sprvanie_select-hodnotenie-1-1</name>
   <tag></tag>
   <elementGuidId>8b7a6310-2b27-435f-8e91-213f1f1f0b0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-hodnotenie-1-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select-hodnotenie-1-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bef74efd-def1-4e82-9964-460812d99263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select placeholder</value>
      <webElementGuid>4cfb35d7-bd67-46e9-8c36-4e7047d70383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4819dab-3a2b-4366-8d99-b81a41156a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-hodnotenie-1-1</value>
      <webElementGuid>9d166e40-69e7-48ae-900f-456f8e553d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vyberte hodnotenieTest nových metadátveľmi dobréuspokojivémenej uspokojivéneuspokojivé</value>
      <webElementGuid>51a4a6b1-164a-4227-935c-ea80d7fd187c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-hodnotenie-1-1&quot;)</value>
      <webElementGuid>87c61920-03ca-499f-9cf5-6a0712a54cff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select-hodnotenie-1-1']</value>
      <webElementGuid>fd4565f4-059e-459d-afda-8449247cd477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hodnotenie-1-1']/div/div/select</value>
      <webElementGuid>dfd8cb6a-c19a-4ae6-8077-a90fefdee3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Správanie'])[1]/following::select[1]</value>
      <webElementGuid>0e9790ba-b91c-429c-a653-504e412dd094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akcia'])[1]/following::select[1]</value>
      <webElementGuid>e1538aa1-2590-4457-9b01-d2c492bc356d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[115]/preceding::select[1]</value>
      <webElementGuid>278e14ec-7ab0-4e35-bd06-e945899eea6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtre:'])[63]/preceding::select[1]</value>
      <webElementGuid>90ea868e-69ef-4a16-a167-4fe1c237bcac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/select</value>
      <webElementGuid>9a41e64e-b41b-4d1e-b521-a977405404c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @id = 'select-hodnotenie-1-1' and (text() = 'Vyberte hodnotenieTest nových metadátveľmi dobréuspokojivémenej uspokojivéneuspokojivé' or . = 'Vyberte hodnotenieTest nových metadátveľmi dobréuspokojivémenej uspokojivéneuspokojivé')]</value>
      <webElementGuid>2a7c35b1-6e8a-45d5-b706-8603de649305</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
