<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Telesn a portov vchova_select-hodnot_e76c58</name>
   <tag></tag>
   <elementGuidId>aac65855-e11b-4844-9ff0-19a85f2e4148</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-hodnotenie-4-19</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select-hodnotenie-4-19']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>85327c6a-7cb1-49d7-895e-e31e2e723b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select placeholder</value>
      <webElementGuid>054c8627-c8a1-464e-96bd-605e9e339968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7960596-186a-478a-ba4e-bc2c0f040005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-hodnotenie-4-19</value>
      <webElementGuid>4d0b1bbc-e360-48a1-9658-cb9af756601c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vyberte hodnotenie1 - výborný2 - chválitebný3 - dobrý4 - dostatočný5 - nedostatočnýAbsolvovalNeabsolvovalSlovné hodnotenie</value>
      <webElementGuid>ee61ce62-6ce4-406b-a9da-35ce6b1ee5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-hodnotenie-4-19&quot;)</value>
      <webElementGuid>506e461f-36ac-4118-8e06-1ecc37bf4d22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select-hodnotenie-4-19']</value>
      <webElementGuid>8fca5c3d-4b4b-4524-8aa2-46fc6fbffcd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hodnotenie-4-19']/div/div/select</value>
      <webElementGuid>5e2e2a5e-b76d-4bc0-bdb1-3254005b5f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telesná a športová výchova'])[4]/following::select[1]</value>
      <webElementGuid>30cc7c73-7633-4f1f-b9ca-ffbe42e27b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odstrániť'])[75]/following::select[1]</value>
      <webElementGuid>907d55b5-ee6f-492d-9157-c2c7c592e1bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[190]/preceding::select[1]</value>
      <webElementGuid>7ad480e9-ce90-4bdc-8f61-e059f2d38a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtre:'])[138]/preceding::select[1]</value>
      <webElementGuid>fe432a2b-c7b2-4477-930d-d70796da47e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[4]/tbody/tr[19]/td[2]/div/div/div/select</value>
      <webElementGuid>37bf9adb-3b86-4ff5-9a80-7ac0a75c7e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @id = 'select-hodnotenie-4-19' and (text() = 'Vyberte hodnotenie1 - výborný2 - chválitebný3 - dobrý4 - dostatočný5 - nedostatočnýAbsolvovalNeabsolvovalSlovné hodnotenie' or . = 'Vyberte hodnotenie1 - výborný2 - chválitebný3 - dobrý4 - dostatočný5 - nedostatočnýAbsolvovalNeabsolvovalSlovné hodnotenie')]</value>
      <webElementGuid>30fd7bb1-2041-4131-9b56-52160d9b8bf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
