<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Prv cudz jazyk - Anglick jazyk_selec_0ba440</name>
   <tag></tag>
   <elementGuidId>89f22cec-b136-4846-8688-51ccb1667f11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-hodnotenie-2-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select-hodnotenie-2-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b8b0d4ba-832d-4404-b0dd-71cf828a4e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select placeholder</value>
      <webElementGuid>1985179d-1da5-4cbc-b2eb-a0112d97d66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>93e3acaa-a051-4046-b5b6-657d4a8206d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-hodnotenie-2-4</value>
      <webElementGuid>6197442b-b3b2-4227-843b-812e7e2574e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vyberte hodnotenie1 - výborný2 - chválitebný3 - dobrý4 - dostatočný5 - nedostatočnýAbsolvovalNeabsolvovalSlovné hodnotenie</value>
      <webElementGuid>193580b1-ba6b-4e12-8038-1d3e6e67b36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-hodnotenie-2-4&quot;)</value>
      <webElementGuid>89f94c60-ecc1-4215-8c52-66f02308cab7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select-hodnotenie-2-4']</value>
      <webElementGuid>f1202ec8-2add-4cbd-b0e2-a2ef17e0a9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hodnotenie-2-4']/div/div/select</value>
      <webElementGuid>71cb25cb-fd3f-4375-865d-ae59b54b0846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prvý cudzí jazyk - Anglický jazyk'])[2]/following::select[1]</value>
      <webElementGuid>9598a9b4-e217-4ade-9844-f88396bf0878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odstrániť'])[22]/following::select[1]</value>
      <webElementGuid>ad6bfebc-d9f2-4310-8582-71351eaabe61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[137]/preceding::select[1]</value>
      <webElementGuid>84a7cef2-7b00-4f3c-a4eb-bb1d1b89774d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtre:'])[85]/preceding::select[1]</value>
      <webElementGuid>2a64cfc4-5d56-4d5f-a1ca-0d02d69e0d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[4]/td[2]/div/div/div/select</value>
      <webElementGuid>f84ff07d-b3dd-47fc-9def-ee118454a14f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @id = 'select-hodnotenie-2-4' and (text() = 'Vyberte hodnotenie1 - výborný2 - chválitebný3 - dobrý4 - dostatočný5 - nedostatočnýAbsolvovalNeabsolvovalSlovné hodnotenie' or . = 'Vyberte hodnotenie1 - výborný2 - chválitebný3 - dobrý4 - dostatočný5 - nedostatočnýAbsolvovalNeabsolvovalSlovné hodnotenie')]</value>
      <webElementGuid>71b2a379-0ea4-4b39-ac82-ab8e25b0f119</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
