<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(nepovinn)_select-termin-prijimacej-_108023</name>
   <tag></tag>
   <elementGuidId>4fbbf68b-a2c0-43e1-bd79-94f8c0702586</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-termin-prijimacej-skusky-910001965_b4283dd2-304e-4f74-8d0a-44bd3d61cd71</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div[2]/div[2]/div[3]/div/div[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e76cd125-a94e-4546-b231-6d12c3e2a908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select</value>
      <webElementGuid>bfc5f843-9086-4f51-9f89-e933e8dd90cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c645d2c0-6ad4-41ef-a52d-d76cf274c3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-termin-prijimacej-skusky-910001965_b4283dd2-304e-4f74-8d0a-44bd3d61cd71</value>
      <webElementGuid>4cb06344-18c4-4918-9e36-3b7cc2f3366d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c23aa2cd-1247-44b2-989b-ae6a9c3f3c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1. termín (1.kolo)2. termín (1.kolo)</value>
      <webElementGuid>de7055ee-9ce9-47e6-8010-8e16889d20ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-termin-prijimacej-skusky-910001965_b4283dd2-304e-4f74-8d0a-44bd3d61cd71&quot;)</value>
      <webElementGuid>a6f27a8e-4d50-4bfb-8720-8a6e4efe0323</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select-termin-prijimacej-skusky-910001965_b4283dd2-304e-4f74-8d0a-44bd3d61cd71']</value>
      <webElementGuid>e5525caa-1ece-4919-a741-114a79883e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='termin-prijimacej-skusky-910001965_b4283dd2-304e-4f74-8d0a-44bd3d61cd71']/div/div[2]/select</value>
      <webElementGuid>c6589bf3-29ba-420b-bb8e-99f04c06a13b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(nepovinné)'])[33]/following::select[1]</value>
      <webElementGuid>3acdb941-e4de-4b48-a3ac-2d94960b8b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Termín prijímacej skúšky'])[2]/following::select[1]</value>
      <webElementGuid>0b795f30-4b46-4ed2-8309-d460cc434e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[96]/preceding::select[1]</value>
      <webElementGuid>9f880ca6-fe68-46c2-8b17-c8c0a058e971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtre:'])[25]/preceding::select[1]</value>
      <webElementGuid>7e36b6d8-7416-49e7-a3f1-b7f6d263fed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div[3]/div/div[2]/select</value>
      <webElementGuid>bef690a6-e717-4a55-aa4e-7d324abee933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @id = 'select-termin-prijimacej-skusky-910001965_b4283dd2-304e-4f74-8d0a-44bd3d61cd71' and (text() = '1. termín (1.kolo)2. termín (1.kolo)' or . = '1. termín (1.kolo)2. termín (1.kolo)')]</value>
      <webElementGuid>857fc265-00b7-4367-bb44-18b23b6776f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
