<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Druh cudz jazyk - Nemeck jazyk_selec_7b1203</name>
   <tag></tag>
   <elementGuidId>e8f69855-91e6-4ee7-a52f-bfde4936a6c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-hodnotenie-3-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select-hodnotenie-3-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3b359ee3-d05b-4764-a753-c0a7ce48fc8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select placeholder</value>
      <webElementGuid>3d67de57-85e0-4e2a-a8b4-0cc065025692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d253c42c-df49-4e32-b709-e063470f1383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-hodnotenie-3-5</value>
      <webElementGuid>ef5da25e-3477-40b6-b6d8-9eeac24b9ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vyberte hodnotenie1 - výborný2 - chválitebný3 - dobrý4 - dostatočný5 - nedostatočnýAbsolvovalNeabsolvovalSlovné hodnotenie</value>
      <webElementGuid>a01344f1-7486-4f33-9abb-4f79c3e78561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-hodnotenie-3-5&quot;)</value>
      <webElementGuid>64a7494b-e41a-4c8f-9e7b-d76432f26122</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select-hodnotenie-3-5']</value>
      <webElementGuid>66e2c54c-8703-4d70-a9d3-73b019e9d2ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hodnotenie-3-5']/div/div/select</value>
      <webElementGuid>633f79f1-7cd8-444d-82f8-69001a9c5408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Druhý cudzí jazyk - Nemecký jazyk'])[3]/following::select[1]</value>
      <webElementGuid>31299f71-c0c8-4efa-976f-714445b051ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odstrániť'])[42]/following::select[1]</value>
      <webElementGuid>2fc7344d-d804-4ee2-a923-b3f157564e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[157]/preceding::select[1]</value>
      <webElementGuid>9c897150-4c5a-417c-80ab-1bdd86dac72f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtre:'])[105]/preceding::select[1]</value>
      <webElementGuid>6111d54e-8c09-4871-94b9-615f8d2c5fe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr[5]/td[2]/div/div/div/select</value>
      <webElementGuid>88260c0a-c0fd-458d-9c5d-cfebe45ea17d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @id = 'select-hodnotenie-3-5' and (text() = 'Vyberte hodnotenie1 - výborný2 - chválitebný3 - dobrý4 - dostatočný5 - nedostatočnýAbsolvovalNeabsolvovalSlovné hodnotenie' or . = 'Vyberte hodnotenie1 - výborný2 - chválitebný3 - dobrý4 - dostatočný5 - nedostatočnýAbsolvovalNeabsolvovalSlovné hodnotenie')]</value>
      <webElementGuid>1e8ca31c-acc6-40d2-971e-da3236179d86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
