<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Prvouka, Prrodoveda, Biolgia_select-_d77479</name>
   <tag></tag>
   <elementGuidId>22da2ffa-86c7-4511-9ed4-7585ab5598ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-hodnotenie-1-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select-hodnotenie-1-8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c014881e-3a30-4c74-94b4-8edbdfedd0fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select placeholder</value>
      <webElementGuid>b1a5e136-eb0a-462a-b615-a9705c8320a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>17084ae2-8d4e-4d3d-a4ea-c9da3eaa9a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-hodnotenie-1-8</value>
      <webElementGuid>7fdccdcd-8a89-4fbe-b71f-593836a28039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vyberte hodnotenie1 - výborný2 - chválitebný3 - dobrý4 - dostatočný5 - nedostatočnýAbsolvovalNeabsolvovalSlovné hodnotenie</value>
      <webElementGuid>3baca07d-c2f7-4453-857b-d1c0d7cf8981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-hodnotenie-1-8&quot;)</value>
      <webElementGuid>2960578d-b5a6-4980-a476-4131d7eaf297</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select-hodnotenie-1-8']</value>
      <webElementGuid>e93407ec-8a45-4e2f-830c-b3cacba9059e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hodnotenie-1-8']/div/div/select</value>
      <webElementGuid>2d459c0f-bba5-4052-aa49-f80f85e0b4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prvouka, Prírodoveda, Biológia'])[1]/following::select[1]</value>
      <webElementGuid>f4e0ea74-449a-4d3a-83ef-f29d867dc926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odstrániť'])[7]/following::select[1]</value>
      <webElementGuid>91ed264b-0192-41fe-86aa-6750c5cf3bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[122]/preceding::select[1]</value>
      <webElementGuid>2764ff23-3605-4bad-a6d9-66b9be0ec09d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtre:'])[70]/preceding::select[1]</value>
      <webElementGuid>07fffa84-9c8e-4291-8a09-71a1bdd1e75c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/div/div/div/select</value>
      <webElementGuid>6c277654-a2d6-4b89-83e3-dc96f7f5fc76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @id = 'select-hodnotenie-1-8' and (text() = 'Vyberte hodnotenie1 - výborný2 - chválitebný3 - dobrý4 - dostatočný5 - nedostatočnýAbsolvovalNeabsolvovalSlovné hodnotenie' or . = 'Vyberte hodnotenie1 - výborný2 - chválitebný3 - dobrý4 - dostatočný5 - nedostatočnýAbsolvovalNeabsolvovalSlovné hodnotenie')]</value>
      <webElementGuid>af1a14e8-01a7-4aee-8b8f-976bea2dfc27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
