<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Nboensk vchova, Nboenstvo_select-hod_c79f53</name>
   <tag></tag>
   <elementGuidId>c8d18147-0938-438a-a0ab-2a6151ffbe22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-hodnotenie-3-15</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select-hodnotenie-3-15']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d5318f2b-bbf3-4484-80ce-1b0663aeb656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select placeholder</value>
      <webElementGuid>2cfae212-08b5-4ed9-af77-55f7ac7537f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb8f05c8-8f04-46c3-a3f4-b8cfd9da1878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-hodnotenie-3-15</value>
      <webElementGuid>0ab4e381-2e76-4ff9-a109-d70a36722136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vyberte hodnotenie1 - výborný2 - chválitebný3 - dobrý4 - dostatočný5 - nedostatočnýAbsolvovalNeabsolvovalSlovné hodnotenie</value>
      <webElementGuid>0f4c1737-e221-462e-a2f1-af7a97a26675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-hodnotenie-3-15&quot;)</value>
      <webElementGuid>9723f16e-3e84-4233-9f73-37f9f6bf080d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select-hodnotenie-3-15']</value>
      <webElementGuid>dacccd15-c2e3-49c7-9b33-6450546eb4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hodnotenie-3-15']/div/div/select</value>
      <webElementGuid>80b97833-969a-4178-a0ba-c2697c0c13fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Náboženská výchova, Náboženstvo'])[3]/following::select[1]</value>
      <webElementGuid>dd701d3f-707d-4d95-8c46-1438955bdac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odstrániť'])[52]/following::select[1]</value>
      <webElementGuid>181366fc-1354-4d0c-9c7e-95b1f6e6f8b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[167]/preceding::select[1]</value>
      <webElementGuid>d1f28419-8feb-4dbf-8eb9-319467fe1db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtre:'])[115]/preceding::select[1]</value>
      <webElementGuid>e436a7a9-e06f-4cba-919d-4c21bd46400a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr[15]/td[2]/div/div/div/select</value>
      <webElementGuid>24e38da3-0ea2-4400-898d-6bcb0c957e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @id = 'select-hodnotenie-3-15' and (text() = 'Vyberte hodnotenie1 - výborný2 - chválitebný3 - dobrý4 - dostatočný5 - nedostatočnýAbsolvovalNeabsolvovalSlovné hodnotenie' or . = 'Vyberte hodnotenie1 - výborný2 - chválitebný3 - dobrý4 - dostatočný5 - nedostatočnýAbsolvovalNeabsolvovalSlovné hodnotenie')]</value>
      <webElementGuid>bd205687-d8b3-4d9b-ae0e-6072d8e193a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
