<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btn-continue</name>
   <tag></tag>
   <elementGuidId>bd4da6c1-3c1a-4628-b5d4-62c70198881b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='btn-continue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;btn-continue&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8948323d-eae5-4e3c-bba1-bfdc4ab1f643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Overiť</value>
      <webElementGuid>1998246d-ff15-4f22-9ad3-f38c1830df9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-continue</value>
      <webElementGuid>3793e24e-7b7f-44f0-9715-3a6702b27156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>dbfa261b-527f-4393-9b9b-d319fba65f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button govuk-button__large govuk-!-margin-bottom-0</value>
      <webElementGuid>e5fe3aef-d07e-4820-8fff-04ce4940fc9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;two-fa-form&quot;)/div[@class=&quot;idsk-card idsk-card--vertical&quot;]/div[@class=&quot;idsk-card__content&quot;]/div[@class=&quot;govuk-form-group govuk-!-margin-bottom-0&quot;]/input[@class=&quot;govuk-button govuk-button__large govuk-!-margin-bottom-0&quot;]</value>
      <webElementGuid>dd9ec794-c3c7-4637-b1d7-f8642a65cc34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='btn-continue']</value>
      <webElementGuid>af0a570d-2a26-4c9d-b120-746705094541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='two-fa-form']/div/div/div[5]/input[2]</value>
      <webElementGuid>3aef0dd6-4545-487a-82fd-4649b1d851ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input[2]</value>
      <webElementGuid>82e4dffc-b590-4299-a9ce-808f386e632c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'btn-continue' and @type = 'submit']</value>
      <webElementGuid>72e86a77-7c8b-4a24-966c-01993f4da5f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
