<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_(nepovinn)_textarea-DPDPoznamkaText</name>
   <tag></tag>
   <elementGuidId>8e1e1719-d4e2-4f3f-bf33-0bb92385df49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='textarea-DPDPoznamkaText']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#textarea-DPDPoznamkaText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>774b8d99-99fc-48ab-a91d-f0abd06ae186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-textarea</value>
      <webElementGuid>88108385-04f1-4d2a-ac4c-11b51c9b45b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>a573dfaa-52c7-492a-9023-953b7e10c63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textarea-DPDPoznamkaText</value>
      <webElementGuid>ed07a42f-49d3-4f39-8a51-4ad05d0f357f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>ab182e30-a05e-4e7f-a89c-3db55fb24dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textarea-DPDPoznamkaText&quot;)</value>
      <webElementGuid>bd6045c3-bb7c-4fbb-98a3-c8dad9fb0e92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textarea-DPDPoznamkaText']</value>
      <webElementGuid>01a91234-32bd-44bd-863e-5d10a10923d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DPDPoznamkaText']/div/div[2]/textarea</value>
      <webElementGuid>77cf230b-bd77-46a1-8887-91f72c63c824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/textarea</value>
      <webElementGuid>3cbf02ee-3c30-4054-a588-e02166938ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'textarea-DPDPoznamkaText']</value>
      <webElementGuid>ecb8c75e-adaf-4fa3-bcfc-ded9a1e00582</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
