<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Nzov koly alebo jej adresa_fulltext-_b34249</name>
   <tag></tag>
   <elementGuidId>c13d7b7f-ecfb-407d-aced-c81fd62aa259</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fulltext-input-SS-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fulltext-input-SS-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>de81e3f7-6c37-46fc-8e93-1e60a1808b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fulltext-input-SS-button</value>
      <webElementGuid>5d4b72c2-e669-4179-82ee-08e52373ecfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button govuk-button__basic fulltext-input-button</value>
      <webElementGuid>b5be76b5-5bbe-4206-8c68-6cf32cb3b4e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Hľadať</value>
      <webElementGuid>7e460d10-ce17-4ac9-bcd2-a6cff13c7e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    search
                                </value>
      <webElementGuid>90c7dad9-b313-4338-8526-f081cb68f14d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fulltext-input-SS-button&quot;)</value>
      <webElementGuid>03c3a6ca-25ab-4b9e-8edb-0d7f53c7907c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='fulltext-input-SS-button']</value>
      <webElementGuid>028d7740-f0c2-4dfe-8aa9-45dbd34e9864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fulltext-input-wrapper-SS']/div/button</value>
      <webElementGuid>e6588257-c50c-4610-bf16-e694e9824bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov školy alebo jej adresa'])[2]/following::button[1]</value>
      <webElementGuid>cc34b7b9-4d20-4e3e-a384-69692e61e256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zobraziť výsledky'])[4]/following::button[1]</value>
      <webElementGuid>1783ca9a-c83e-4730-8c39-4f32279f62f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voľná kapacita na prijatie'])[1]/preceding::button[1]</value>
      <webElementGuid>3ac94356-4f3f-43b0-ae88-2e7d2816cfd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(nepovinné)'])[3]/preceding::button[1]</value>
      <webElementGuid>13844de9-09be-4538-bbb3-c49fffba51fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div/div[2]/div/button</value>
      <webElementGuid>e33ee7ee-ad22-4e25-87f1-3f04a1ae53fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'fulltext-input-SS-button' and (text() = '
                                    search
                                ' or . = '
                                    search
                                ')]</value>
      <webElementGuid>6bc3357b-bf35-4e9e-b2a6-a95bd11d7498</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
