<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_-_panel-item-label</name>
   <tag></tag>
   <elementGuidId>6be9b7bf-c768-4cd6-ad48-1bb65b1aa123</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zz1']/div[9]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a193d6cb-a412-4cfe-9369-bc5b2165d8df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-item-label</value>
      <webElementGuid>34f00649-d058-4c3a-9ea2-3adc54ed12c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Telefónne číslo</value>
      <webElementGuid>c2bc974a-11b2-46c9-9e6f-bc5ba5376679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zz1&quot;)/div[@class=&quot;panel-item&quot;]/div[@class=&quot;panel-item-label&quot;]</value>
      <webElementGuid>bc5f066b-083c-4602-bbcf-fb5fa40c412d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz1']/div[9]/div</value>
      <webElementGuid>1994a167-1b2a-4a4a-9c7e-6e5df1ace354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[18]/following::div[2]</value>
      <webElementGuid>8522234e-a190-4f6f-86f6-d9826ef90c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail'])[4]/following::div[3]</value>
      <webElementGuid>e0c3424a-ecd0-449d-8fbe-d253cb3a7fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Súhlas s komunikáciou výhradne so zákonným zástupcom č. 1'])[1]/preceding::div[2]</value>
      <webElementGuid>d66fe764-db28-47b8-9ec6-842b0dc78064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[19]/preceding::div[3]</value>
      <webElementGuid>471bff42-a302-4794-9380-bdad32a8fe50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[9]/div</value>
      <webElementGuid>ee52bff7-9728-4bd9-a186-51b1e6632964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Telefónne číslo' or . = 'Telefónne číslo')]</value>
      <webElementGuid>585d1752-3b1d-48d4-b27d-dea4a6eb9d0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
