<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rodn priezvisko_dietaRodnePriezviskoSuhrn</name>
   <tag></tag>
   <elementGuidId>cd394865-f8fc-412a-b975-c6b889cce066</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dietaRodnePriezviskoSuhrn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dietaRodnePriezviskoSuhrn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b0eceeaa-7d1e-4253-a035-c462574a2ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dietaRodnePriezviskoSuhrn</value>
      <webElementGuid>24d1d930-d97e-40e7-b3af-c561feac024c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>951219f5-21f1-431c-b2aa-c54440787828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dietaRodnePriezviskoSuhrn&quot;)</value>
      <webElementGuid>2722f568-b0a5-4fd7-90a3-66f524fdbcca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dietaRodnePriezviskoSuhrn']</value>
      <webElementGuid>ff9aa0c0-49b6-4480-98ec-7ba5280102c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suhrnny-prehlad']/div[3]/div[2]/div[3]/div[2]</value>
      <webElementGuid>28bd62ae-3225-4d68-a751-79bf9c4f2c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodné priezvisko'])[5]/following::div[1]</value>
      <webElementGuid>0f00fc8f-1123-4900-9782-272b08222198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gerdžo'])[2]/following::div[3]</value>
      <webElementGuid>0d684ab0-c984-4c72-bdfb-a3bdc3bf4d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodné číslo'])[6]/preceding::div[1]</value>
      <webElementGuid>e9193f22-c914-4de6-97bf-636460179db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum narodenia'])[5]/preceding::div[4]</value>
      <webElementGuid>5b1ec692-2c22-41d0-a8e5-4c3bf7291862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div[3]/div[2]/div[3]/div[2]</value>
      <webElementGuid>c211048b-32a8-4544-8e89-950138d207fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dietaRodnePriezviskoSuhrn' and (text() = '-' or . = '-')]</value>
      <webElementGuid>5fcc5d04-701a-4140-9a66-a923a507e022</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
