<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_-_zastupcaNeznamy</name>
   <tag></tag>
   <elementGuidId>a8fdaa4b-d853-488d-b289-9430fc4614be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zastupcovia']/div[2]/div/div[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.zastupcaNeznamy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>981c0218-88c4-42e7-a5c0-6fc098bfbdeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zastupcaNeznamy</value>
      <webElementGuid>e7621d9e-f4a7-4c2c-8047-af73be61a873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Druhý zákonný zástupca nie je známy.</value>
      <webElementGuid>ba2a91d0-434c-4732-8ab0-561b3ce8dca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zastupcovia&quot;)/div[@class=&quot;panel-content&quot;]/div[@class=&quot;zastupcoviaSection&quot;]/div[@class=&quot;zastupcaNeznamy&quot;]</value>
      <webElementGuid>92d05964-2ad6-457c-84ae-4643f18136ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zastupcovia']/div[2]/div/div[6]</value>
      <webElementGuid>b6d23f4d-3c19-4b8e-ab84-46d647163f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[30]/following::div[1]</value>
      <webElementGuid>9ca172cb-ebb1-4cf7-84ee-7de0bbedb014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[29]/following::div[4]</value>
      <webElementGuid>6b753f47-da1e-4e1b-b15c-c21c60572fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov zariadenia'])[2]/preceding::div[1]</value>
      <webElementGuid>37417af2-cf37-4ae6-be25-4064feb0ccf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[31]/preceding::div[2]</value>
      <webElementGuid>295438e0-a707-4acd-99b1-e84cec18e122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Druhý zákonný zástupca nie je známy.']/parent::*</value>
      <webElementGuid>02d95dab-e1de-4642-b0cb-5948ccab2582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[6]</value>
      <webElementGuid>f17a3bd6-7642-4001-8772-f83aa4e35fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Druhý zákonný zástupca nie je známy.' or . = 'Druhý zákonný zástupca nie je známy.')]</value>
      <webElementGuid>1c181f8b-c3ad-4884-8c3b-fbfcfed3c767</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
