<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Poznmka koly_poznamkaSkoly</name>
   <tag></tag>
   <elementGuidId>e417b7fe-910d-4d22-979e-7a4cbf4eab3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='poznamkaSkoly']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#poznamkaSkoly</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2ba1bc25-a8ad-40ee-9aac-a1d096d9a397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>poznamkaSkoly</value>
      <webElementGuid>3057f7a2-d4ef-4378-b105-e10ce1ea096b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiline-label</value>
      <webElementGuid>27af26a9-296a-4553-89d4-ba1d8ec0d584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(*-*)</value>
      <webElementGuid>faedbf74-1f48-4101-800c-e5233390a87a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;poznamkaSkoly&quot;)</value>
      <webElementGuid>24389750-18d6-4c84-8dd6-99589a452847</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='poznamkaSkoly']</value>
      <webElementGuid>dd98d371-fee4-4bee-8119-b490b5dec98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suhrnny-prehlad']/div[2]/div[2]/div[5]/div[2]</value>
      <webElementGuid>1fc9a9b2-75e9-4d77-8733-edcda5e0bfca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Poznámka školy'])[1]/following::div[1]</value>
      <webElementGuid>756a115a-304b-48f6-8f42-1bbbfaa8a2e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[6]/following::div[3]</value>
      <webElementGuid>03f2d2dc-4ad9-415a-8b01-4df644b4d787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kolo prijímacieho konania'])[1]/preceding::div[1]</value>
      <webElementGuid>f8f61439-5da2-4456-986e-3a48d99e4e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[7]/preceding::div[2]</value>
      <webElementGuid>c4d4ec5b-6942-4bd0-b5f6-7effe2ae7116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='(*-*)']/parent::*</value>
      <webElementGuid>d2ef8f9a-ebaf-4165-ba11-090b4a88b23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[5]/div[2]</value>
      <webElementGuid>43391437-3c1c-4b37-b862-937d77029d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'poznamkaSkoly' and (text() = '(*-*)' or . = '(*-*)')]</value>
      <webElementGuid>4f71f8d6-0e58-43d0-b622-e96e305b1da3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
