<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dtum narodenia_zakonnyZastupcaDatumNarodenia</name>
   <tag></tag>
   <elementGuidId>fb3594d3-d5d0-4550-b931-2edab347fc53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zakonnyZastupcaDatumNarodenia']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zakonnyZastupcaDatumNarodenia</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f3fd672-2715-45db-9b36-8c63b0258c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zakonnyZastupcaDatumNarodenia</value>
      <webElementGuid>a33b915b-5d28-4ec5-b5fa-5db1408de5d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>24.01.1984</value>
      <webElementGuid>5ad7feb2-d183-4478-b000-04cbf5bbfc80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zakonnyZastupcaDatumNarodenia&quot;)</value>
      <webElementGuid>42a91d22-6dc7-4517-98cb-2d2103ae6bc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zakonnyZastupcaDatumNarodenia']</value>
      <webElementGuid>ee6c0a82-5951-43ea-8880-e0a6fa6c5863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz1']/div[6]/div[2]</value>
      <webElementGuid>6d575359-49dd-4d5b-b50f-e9a2c410e07b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum narodenia'])[6]/following::div[1]</value>
      <webElementGuid>fe4c36ba-6532-4f8f-a5b5-58c6b9fda732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[17]/following::div[3]</value>
      <webElementGuid>a17bd557-5078-4d0b-a9c4-6a537f5a6caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Korešpondenčná adresa'])[3]/preceding::div[1]</value>
      <webElementGuid>b8f388b3-2f8f-4add-80b5-11b5f8e6827e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tupolevova 6287/9, 60507, Bašovce, Slovenská republika'])[3]/preceding::div[2]</value>
      <webElementGuid>656cf335-0b95-4752-a72c-03dbde3641b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='24.01.1984']/parent::*</value>
      <webElementGuid>1970860b-6931-4d4d-bbb5-e35dc7caccd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[6]/div[2]</value>
      <webElementGuid>fce3c8b4-b825-4d17-abd5-63fe110e9283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zakonnyZastupcaDatumNarodenia' and (text() = '24.01.1984' or . = '24.01.1984')]</value>
      <webElementGuid>2a9b50e1-3afd-42ee-abe2-9dbb896a3be3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
