<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ttna prslunos_dietaStatnaPrislusnostSuhrn</name>
   <tag></tag>
   <elementGuidId>aec4f5e1-360e-4bff-accf-09a9ed36c362</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dietaStatnaPrislusnostSuhrn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dietaStatnaPrislusnostSuhrn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b8fd04f3-7228-4c03-86bf-6371f05e9a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dietaStatnaPrislusnostSuhrn</value>
      <webElementGuid>ba82de22-d770-4dd7-81d1-4381be46d4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Slovenská republika</value>
      <webElementGuid>f206a5cf-f390-4f5d-9a1b-5fa8be383cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dietaStatnaPrislusnostSuhrn&quot;)</value>
      <webElementGuid>f72d2073-6996-43ff-8832-97bf642a02a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dietaStatnaPrislusnostSuhrn']</value>
      <webElementGuid>6e9d5788-2b2f-44ed-99c9-d2ffa5f4b0df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suhrnny-prehlad']/div[3]/div[2]/div[9]/div[2]</value>
      <webElementGuid>1d4aec26-f16f-42f5-b51a-e172cce63cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Štátna príslušnosť'])[3]/following::div[1]</value>
      <webElementGuid>878f0e83-b5d3-4555-8f75-2aa27826319e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='slovenská'])[3]/following::div[3]</value>
      <webElementGuid>424d4138-6a10-40bb-8e56-eb841590cfe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Materinský jazyk'])[3]/preceding::div[1]</value>
      <webElementGuid>f12197e1-53e9-4877-bc1f-2e4f0587d135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='slovenský'])[4]/preceding::div[2]</value>
      <webElementGuid>4abade9c-ec8f-48d0-b9c6-c56076eb680b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div[3]/div[2]/div[9]/div[2]</value>
      <webElementGuid>31b2f03a-0a87-42fa-85af-89ea9c2cffef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dietaStatnaPrislusnostSuhrn' and (text() = 'Slovenská republika' or . = 'Slovenská republika')]</value>
      <webElementGuid>a3caceb1-4d44-4489-8a45-ceade30623a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
