<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Diea s nadanm_dpDietataSVVPotrebySNadanim</name>
   <tag></tag>
   <elementGuidId>0fdf5b56-70a6-4b9d-bdc9-9759cd38c652</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dpDietataSVVPotrebySNadanim']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dpDietataSVVPotrebySNadanim</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dc6528cf-cf4c-4b42-8807-aa85f1a5fe3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dpDietataSVVPotrebySNadanim</value>
      <webElementGuid>5ba5a72f-e349-4eb4-b28f-7f8d36aa16ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nie</value>
      <webElementGuid>a8995162-4bd7-499e-981e-aa6162966088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dpDietataSVVPotrebySNadanim&quot;)</value>
      <webElementGuid>2f55c5e8-874f-41ea-8969-20a6a98019fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dpDietataSVVPotrebySNadanim']</value>
      <webElementGuid>3c30f30b-c29c-4410-bb48-8d36d210d62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdpDietata']/div[2]/div/div/div[6]/div[2]</value>
      <webElementGuid>64d0863e-7d06-4468-b56f-362ba22b3247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dieťa s nadaním'])[2]/following::div[1]</value>
      <webElementGuid>d16d129f-797f-42f4-8270-d68ff9936a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nie'])[9]/following::div[3]</value>
      <webElementGuid>503cc36d-b9a2-419f-a4a1-03a26f785151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Požadovaný dátum prijatia dieťaťa do materskej školy'])[2]/preceding::div[1]</value>
      <webElementGuid>d1a1cc8d-4c2e-463c-a222-053de156e286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Popis znevýhodnenia'])[2]/preceding::div[4]</value>
      <webElementGuid>34115b59-dbb1-4a5c-b312-c71228959869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[6]/div[2]</value>
      <webElementGuid>4f6402d0-8233-47a9-b902-0d5262e44c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dpDietataSVVPotrebySNadanim' and (text() = 'Nie' or . = 'Nie')]</value>
      <webElementGuid>0a78fda5-c436-4090-999a-622a65bda7f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
