<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rodn priezvisko_zakonnyZastupcaRodnePriezvisko</name>
   <tag></tag>
   <elementGuidId>73dd81fa-1a9c-44ca-9014-a5f61c13720e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zakonnyZastupcaRodnePriezvisko']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zakonnyZastupcaRodnePriezvisko</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c7df3a0f-ea2b-4a41-aa37-18c8a14c8216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zakonnyZastupcaRodnePriezvisko</value>
      <webElementGuid>ba2a36c5-747c-4de1-abd2-2be3fde70d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>58fea8a2-5fea-4e90-a422-affc72e3d86a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zakonnyZastupcaRodnePriezvisko&quot;)</value>
      <webElementGuid>fde96081-ea01-4d0f-8349-88fbe468fef0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zakonnyZastupcaRodnePriezvisko']</value>
      <webElementGuid>d09f649f-bc61-434c-a2ba-1e8987a67c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz1']/div[3]/div[2]</value>
      <webElementGuid>effc36ca-d2fe-474a-80b7-7238c9b188b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodné priezvisko'])[6]/following::div[1]</value>
      <webElementGuid>c77d87a9-aa6f-4762-ba0f-566cae72cbf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tajomná'])[1]/following::div[3]</value>
      <webElementGuid>646fc56d-7682-44ea-bbb1-90abd784e340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodné číslo'])[7]/preceding::div[1]</value>
      <webElementGuid>cbb437f3-3aa1-42b6-9d07-92988fca3ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Číslo elektronickej schránky'])[4]/preceding::div[4]</value>
      <webElementGuid>f87674e8-b4eb-48ec-8a43-f50321be60d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[3]/div[2]</value>
      <webElementGuid>56965426-4443-441b-a6dc-309652bb42c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zakonnyZastupcaRodnePriezvisko' and (text() = '-' or . = '-')]</value>
      <webElementGuid>1aa5fcb6-7306-411b-9b5a-04b46cc2ee0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
