<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Zdravotn znevhodnenie dieaa_dpDietataSV_1cfce1</name>
   <tag></tag>
   <elementGuidId>bd6b6936-a4fa-4308-8eec-2fda077e967d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dpDietataSVVPotreby']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dpDietataSVVPotreby</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>080e926b-a4d4-4a2a-b1ca-41ceddbc8b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dpDietataSVVPotreby</value>
      <webElementGuid>38d57b7d-7ae9-4f69-8f38-a5e137c96a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nie</value>
      <webElementGuid>2ca029a2-7895-4cfd-aea7-e3adbabb3b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dpDietataSVVPotreby&quot;)</value>
      <webElementGuid>b3dcdfbe-235c-4817-a324-14ce2c4834b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dpDietataSVVPotreby']</value>
      <webElementGuid>159a8223-2e3b-4a9b-9497-91299541b037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdpDietata']/div[2]/div/div/div[5]/div[2]</value>
      <webElementGuid>7edb81e9-a749-4e34-a88c-7e404f1a3212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zdravotné znevýhodnenie dieťaťa'])[2]/following::div[1]</value>
      <webElementGuid>67a9bbb1-bbe8-4f2a-98e1-cc5901d99248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Záujem o školský klub detí'])[1]/following::div[4]</value>
      <webElementGuid>1fae7eca-21e2-4d6f-8aad-a455dc9dc43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dieťa s nadaním'])[2]/preceding::div[1]</value>
      <webElementGuid>a8c210e5-e951-481f-9805-1a4ffae9fc91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nie'])[10]/preceding::div[2]</value>
      <webElementGuid>8e0df6cc-0d3a-4f27-a056-d13274115cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[5]/div[2]</value>
      <webElementGuid>0e9f066d-5ed8-44b0-b79d-c17a89f2321f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dpDietataSVVPotreby' and (text() = 'Nie' or . = 'Nie')]</value>
      <webElementGuid>0e28736d-208b-415e-a410-202bd373e5c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
