<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-adresaTPSupisneCislo</name>
   <tag></tag>
   <elementGuidId>0b2e3fad-b057-4491-9b10-dea5c2917294</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-adresaTPSupisneCislo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-adresaTPSupisneCislo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1dd199ce-437b-4b07-a448-a1b991600cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>df6bad8f-93d0-481d-8484-871d2cc22a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>16239cd3-d09a-4665-a115-a7f411e9850d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-adresaTPSupisneCislo</value>
      <webElementGuid>127311d6-e0c4-47af-a3c4-c0b7581e6efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>e26e8ca9-0b5a-4e99-8506-a251c7b96177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-adresaTPSupisneCislo&quot;)</value>
      <webElementGuid>84696871-e92d-4e5c-8d0c-df77fea07808</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-adresaTPSupisneCislo']</value>
      <webElementGuid>5fcd3a87-6968-4a3c-ad28-b3bd9dd89dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adresaTPSupisneCislo']/div/div[2]/input</value>
      <webElementGuid>60083c51-0140-40b8-8fff-5d0d3e03c9f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/input</value>
      <webElementGuid>9c9fd38e-2837-4d46-8082-16a9b16ede2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-adresaTPSupisneCislo']</value>
      <webElementGuid>028c4c0b-dd0f-46eb-a56a-7c1ea37a7f29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
