<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__DPDDietaSNadanimRadio_option_1</name>
   <tag></tag>
   <elementGuidId>da7f886e-9e08-4ae9-8c56-8362bb516e1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DPDDietaSNadanimRadio_option_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DPDDietaSNadanimRadio_option_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d60e2da-c79a-40ad-abf5-fb9d129bdfb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>a7f31d43-0edb-4f10-b521-40c66f0e1328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DPDDietaSNadanimRadio_option_1</value>
      <webElementGuid>9ca7bade-ad68-4ae3-8ea7-bec6eaefc150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DPDDietaSNadanimRadio</value>
      <webElementGuid>f6d21858-f931-4019-9b19-3cbe81132cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>35160d8b-43fe-47f4-9ecc-243edac22d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ec5efbc4-7783-40b0-b43f-1a3082c69f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DPDDietaSNadanimRadio_option_1&quot;)</value>
      <webElementGuid>eb626baa-7cb1-41f8-9c61-1dab6dc0780e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DPDDietaSNadanimRadio_option_1']</value>
      <webElementGuid>d535d117-ca25-4796-9e01-e4f3a6efb685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DPDDietaSNadanimRadio']/div/fieldset/div[3]/div[3]/input</value>
      <webElementGuid>9b97700c-41a1-4c17-9cd2-81e2b85d112f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/fieldset/div[3]/div[3]/input</value>
      <webElementGuid>244edafc-3326-4f64-b741-65c6a7206228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DPDDietaSNadanimRadio_option_1' and @name = 'DPDDietaSNadanimRadio' and @type = 'radio']</value>
      <webElementGuid>09fd0594-d596-4004-83f8-c125d95cafc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
