<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__DPDSVVPRadio_option_1</name>
   <tag></tag>
   <elementGuidId>b7d3eb27-48ce-4cc9-baa1-5865c668a9db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DPDSVVPRadio_option_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DPDSVVPRadio_option_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8602b307-70db-47e8-8db2-df7954c2fa99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>44493b52-f44f-409f-acde-84638087c20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DPDSVVPRadio_option_1</value>
      <webElementGuid>eca2ec33-7a7f-48c7-b710-903b55eb30f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DPDSVVPRadio</value>
      <webElementGuid>e8af5213-84de-4aae-920a-d296b881fc6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>691ae3fb-0f6b-471a-8470-30398e0078f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c9ca8fc5-018d-4ea8-8836-d9686f832743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DPDSVVPRadio_option_1&quot;)</value>
      <webElementGuid>bb202f38-6c43-4aa5-89bf-b13378c188a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DPDSVVPRadio_option_1']</value>
      <webElementGuid>60cccdd7-e256-4bed-ab83-1de06aa805cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DPDSVVPRadio']/div/fieldset/div[3]/div[3]/input</value>
      <webElementGuid>bac1fb67-0a3e-494a-81a2-e646fb422be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/fieldset/div[3]/div[3]/input</value>
      <webElementGuid>d86470d4-fce3-49c1-8f9d-72572c2bf377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DPDSVVPRadio_option_1' and @name = 'DPDSVVPRadio' and @type = 'radio']</value>
      <webElementGuid>9f4b2257-cda5-4850-9047-211d6b3589ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
