<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-datumPodaniaPrihlaskyRok</name>
   <tag></tag>
   <elementGuidId>6b00ba01-0576-4baa-b082-c85df8965f22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-datumPodaniaPrihlaskyRok']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-datumPodaniaPrihlaskyRok</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea0062b3-83e9-4b9b-9f07-5bce1648c9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>ec4cbd26-70bf-4a33-aae6-0d8172a9eb6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bb6400b9-7ab5-414c-b5cc-066c784144fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-datumPodaniaPrihlaskyRok</value>
      <webElementGuid>9afcdbec-2a7f-4429-bfff-5e075b0e1530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>c8f26650-9ed5-4103-a005-9f4e60b39f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>a075aba4-3326-4b0d-b2d5-720d283b6fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>YYYY</value>
      <webElementGuid>379d9645-def3-4aa8-973a-991ffe24cb84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-datumPodaniaPrihlaskyRok&quot;)</value>
      <webElementGuid>cea31621-d4f2-4026-98a5-caaf9852edee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-datumPodaniaPrihlaskyRok']</value>
      <webElementGuid>068635ea-b477-48ec-86c2-0d94dd35fecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datumPodaniaPrihlaskyRok']/div/div[2]/input</value>
      <webElementGuid>b8c5c91c-cfb5-4311-b9f6-175deb094d09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/div/div[2]/input</value>
      <webElementGuid>26b600d3-aba2-4f5d-b5db-ca6f23b71b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-datumPodaniaPrihlaskyRok' and @placeholder = 'YYYY']</value>
      <webElementGuid>7a88611f-6f6b-4eca-ba55-4ac7564139df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
