<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-pozadovanyDatumPrijatiaDen</name>
   <tag></tag>
   <elementGuidId>7f103c42-eef7-4371-b085-59d96e10f46e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-pozadovanyDatumPrijatiaDen']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-pozadovanyDatumPrijatiaDen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8eaed6eb-9198-4350-b502-687ed429b0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>41ce666c-0793-4d14-88dc-616e5fd66c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>33c3f6a1-efc0-4ade-8f16-154c7ac82e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-pozadovanyDatumPrijatiaDen</value>
      <webElementGuid>ed515bdb-8282-44dd-9122-de4ccf338116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>dee00f80-af9d-40c6-8406-652653c50aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD</value>
      <webElementGuid>dbbbbc3e-71c2-44a2-93af-ef7679236c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-pozadovanyDatumPrijatiaDen&quot;)</value>
      <webElementGuid>28a86b9b-385f-4afa-9023-e8b687c918dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-pozadovanyDatumPrijatiaDen']</value>
      <webElementGuid>cddb5e72-bf19-4e64-a6a5-4939e2f2290d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pozadovanyDatumPrijatiaDen']/div/div[2]/input</value>
      <webElementGuid>c47ac91d-42cd-48d5-8286-08a4986acfd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>00cb6247-04ec-4ec4-8f96-e841a2d2ed6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-pozadovanyDatumPrijatiaDen' and @placeholder = 'DD']</value>
      <webElementGuid>788414b0-c5e2-45c4-99c4-761a944e7ea1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
