<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-datumPrijatiaOd_1d9b_c73a26</name>
   <tag></tag>
   <elementGuidId>c8ee9b8b-42cc-4c9f-a5e7-63c81e22d054</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-datumPrijatiaOd_1d9bd68d-c055-4f27-b211-87c861c5043d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[2]/div/div[2]/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c5e7eb1-2d1b-461f-8d6f-7d98a1133f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>a322ea3f-863d-44a9-977b-9b6635775fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d60048ce-1110-44e1-a56a-ba6e499ca801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-datumPrijatiaOd_1d9bd68d-c055-4f27-b211-87c861c5043d</value>
      <webElementGuid>5d871857-954d-4123-bce3-94b3f40b8a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD.MM.YYYY</value>
      <webElementGuid>a7a90c02-a057-40e3-9922-d310d4724012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>c1d2946a-ba7d-4871-8cbf-f0a139210813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-datumPrijatiaOd_1d9bd68d-c055-4f27-b211-87c861c5043d&quot;)</value>
      <webElementGuid>b67fdc7a-80c0-468c-93ac-8aded6471a14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-datumPrijatiaOd_1d9bd68d-c055-4f27-b211-87c861c5043d']</value>
      <webElementGuid>d61819c5-98ee-48b3-97b1-6019365d5298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datumPrijatiaOd_1d9bd68d-c055-4f27-b211-87c861c5043d']/div/div[2]/span/input</value>
      <webElementGuid>f93d39eb-8d32-468f-9a70-e151ad1623d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/span/input</value>
      <webElementGuid>7ebe9d0a-1a97-4431-90da-4c4bce2e499e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-datumPrijatiaOd_1d9bd68d-c055-4f27-b211-87c861c5043d' and @placeholder = 'DD.MM.YYYY']</value>
      <webElementGuid>471739f6-2e44-4174-802e-1a1be3e58481</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
