<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-cisloRozhodnutia_1d9_6d5197</name>
   <tag></tag>
   <elementGuidId>0920178c-19ed-4c77-a2b8-0857207d832d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-cisloRozhodnutia_1d9bd68d-c055-4f27-b211-87c861c5043d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32d944e8-0e9c-49b2-8067-48a3204d37a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>2ed1d004-fdd2-4773-9ed6-ba89cef4de0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>04f23a7e-da56-4608-9ba4-56b4c301f60e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-cisloRozhodnutia_1d9bd68d-c055-4f27-b211-87c861c5043d</value>
      <webElementGuid>457afb66-9f6f-460f-a9b4-ef7154e1eef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-cisloRozhodnutia_1d9bd68d-c055-4f27-b211-87c861c5043d&quot;)</value>
      <webElementGuid>34874fb6-915f-4aa9-a7b9-3fd0d55403bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-cisloRozhodnutia_1d9bd68d-c055-4f27-b211-87c861c5043d']</value>
      <webElementGuid>224af7ce-0f9b-4c20-8ea8-0256b64e7d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cisloRozhodnutia_1d9bd68d-c055-4f27-b211-87c861c5043d']/div/div[2]/input</value>
      <webElementGuid>aa672997-1315-471f-af56-0e4e9ff3fac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>8c57e5d1-2e18-4075-ae1c-440751fe1c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-cisloRozhodnutia_1d9bd68d-c055-4f27-b211-87c861c5043d']</value>
      <webElementGuid>6ccfb656-b636-4630-b2c0-3cb000cadd01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
