<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_keyboard_arrow_up_govuk-input input-s_853611</name>
   <tag></tag>
   <elementGuidId>ce797f1b-2d3b-47d5-a0a8-770e7cc7f903</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.govuk-input.input-search-multiselect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='odbory-select-wrapper-SS']/div/div/div[3]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d53e38e-9cfa-45b4-8090-f92d35a6134a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input input-search-multiselect</value>
      <webElementGuid>2b3ac142-7825-4598-8cf8-383aa4d1ae99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d03f3f8a-1573-46a0-83c4-279c6ed17da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>83abfe20-42e6-49c4-9c68-8744c51af949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Vyhľadajte odbor</value>
      <webElementGuid>45003fc4-0118-4394-b400-630b8c15069f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;odbory-select-wrapper-SS&quot;)/div[@class=&quot;govuk-form-group input-control dtc-multiselect-wrapper&quot;]/div[@class=&quot;dtc-multiselect&quot;]/div[@class=&quot;dtc-multiselect-menu focused&quot;]/div[@class=&quot;input-search-multiselect-wrapper&quot;]/input[@class=&quot;govuk-input input-search-multiselect&quot;]</value>
      <webElementGuid>f46c180a-decb-4306-9630-414f7d2b4254</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[29]</value>
      <webElementGuid>1af02f60-0592-44e4-ae48-1cacf5f89b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='odbory-select-wrapper-SS']/div/div/div[3]/div/input</value>
      <webElementGuid>76a42150-8c29-4abf-b848-01da6af12242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/input</value>
      <webElementGuid>80a43c83-3afa-4fdd-a326-a6d0a4b52646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Vyhľadajte odbor']</value>
      <webElementGuid>18085303-c9b6-4c4f-83fa-be31eb4973c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
