analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 2163643,\\n  \\"name\\"\: \\"ePrihlasky\\",\\n  \\"teamId\\"\: 2143568,\\n  \\"organizationId\\"\: 1439923,\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 2143568\\n}"
analytics.testcloud.integration.enable=false
analytics.testreport.autoupload.enable=true
analytics.onpremise.enable=false
analytics.testcloud.hub.switchHub.enable=false
