<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Prstupn poschodia, toalety a jedle_ra_1f68a1</name>
   <tag></tag>
   <elementGuidId>73f1ba8d-87fa-49b4-bdb3-c95e65ebd002</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radioGroup-SS_DebS_option_5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radioGroup-SS_DebS_option_5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf93e3e7-02a0-4c3e-bbf7-c8b7d0e906be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>09437720-fee0-4a12-98c4-bd4e74fa6308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radioGroup-SS_DebS_option_5</value>
      <webElementGuid>42c7d128-c1fd-45eb-bb33-cca18f8c4217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radioGroup-SS_DebS</value>
      <webElementGuid>b118ba7d-cb9d-47ea-b1e0-41d506a8c2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0513fcc9-cfe0-42ae-b8c8-d9cc550c42bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>DebS_6</value>
      <webElementGuid>760d2bdc-edd6-44be-92c1-3fe268441e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radioGroup-SS_DebS_option_5&quot;)</value>
      <webElementGuid>fee1f6b7-32a0-43f1-9f90-7f550be9f0ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radioGroup-SS_DebS_option_5']</value>
      <webElementGuid>1474959d-6696-4cbe-acf0-e8a6b1739925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radioGroup-SS_DebS']/div/fieldset/div[3]/div[6]/input</value>
      <webElementGuid>6e63a064-8f7e-48c1-b5f3-0eb0994865eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>589dce19-fb39-4bfa-919c-b0b6ea6abde0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'radioGroup-SS_DebS_option_5' and @name = 'radioGroup-SS_DebS' and @type = 'radio']</value>
      <webElementGuid>35e2d888-4cdb-4dcd-bc67-957c4f407873</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
