<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Meno_dietaMeno</name>
   <tag></tag>
   <elementGuidId>d60ac949-e5cb-4bb9-b287-fe43d022862a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dietaMeno</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dietaMeno']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6e1c5440-f0c4-4e21-a81f-674bcadb64da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dietaMeno</value>
      <webElementGuid>50f55e10-088e-4744-9bb7-cb1ac7a9077c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ján</value>
      <webElementGuid>76427964-ae56-499c-90a7-4f12cc4aa525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dietaMeno&quot;)</value>
      <webElementGuid>3823659c-49bc-4bc9-b71e-0a8cd55b4727</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dietaMeno']</value>
      <webElementGuid>47cf5f34-89ec-42fc-84c8-719342662cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='detail-prihlasky-riad-SS-content']/div[5]/div[2]/div/div[2]</value>
      <webElementGuid>47d0a43e-cbca-44fb-9101-37213c5d79fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meno'])[1]/following::div[1]</value>
      <webElementGuid>3c967f38-4389-4fe4-a5ad-83374b91466a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='remove'])[2]/following::div[4]</value>
      <webElementGuid>ae9511c6-a5ef-4c2f-a07a-7c3d7e2e563f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priezvisko'])[1]/preceding::div[1]</value>
      <webElementGuid>f8884637-91d9-4d55-9e5b-c93e205f00ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Greš'])[1]/preceding::div[2]</value>
      <webElementGuid>000fc734-2dec-49cb-9b83-e6724f25d89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ján']/parent::*</value>
      <webElementGuid>6af55fb6-0f6d-4f11-b42d-b8a021e17249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div[2]</value>
      <webElementGuid>729888e4-6dd7-413c-816e-b016fd2e90c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dietaMeno' and (text() = 'Ján' or . = 'Ján')]</value>
      <webElementGuid>9469b679-133b-4711-928f-b63e57eebe54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
