<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nzov koly alebo jej adresa_fulltext-input-SS</name>
   <tag></tag>
   <elementGuidId>f9b1c5ef-ac0f-431d-8e79-78725344cbfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fulltext-input-SS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fulltext-input-SS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8a667f6-429e-45d4-9620-7964a60eb03d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fulltext-input-SS</value>
      <webElementGuid>0ce02d73-6f36-487c-9a92-21ff7b81f438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b1dc6472-3f36-4764-9a81-4b476c9ae148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>24e80c39-374a-42c6-819e-ed580209afc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fulltext-input-SS&quot;)</value>
      <webElementGuid>8e4b0275-3868-4bb6-bdab-8973a789b2b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fulltext-input-SS']</value>
      <webElementGuid>eb38d226-39f8-456e-bb19-6af2c19d1e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fulltext-input-wrapper-SS']/div/input</value>
      <webElementGuid>b221712a-e700-4e6f-940d-fc0d9c107648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div/div[2]/div/input</value>
      <webElementGuid>d8cceb16-b685-4a7f-8a89-0d4ec6f69e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fulltext-input-SS' and @type = 'text']</value>
      <webElementGuid>f09dc20b-6236-470f-a6eb-99cea69f43e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
