<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Neskontrolovan_badge</name>
   <tag></tag>
   <elementGuidId>8fc1f8eb-5620-41e7-9a44-8cd64b3dd10f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sub-riaditel-prihlasky']/div[4]/div[4]/div/div[2]/div[3]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cad38f15-ed6c-4128-90f7-630bdbc4112f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>badge</value>
      <webElementGuid>a928d5e0-35e0-4ff5-a27f-30e0ccf77cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Papierovo</value>
      <webElementGuid>b36f5990-bad6-437d-ab53-b8dd73b49c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub-riaditel-prihlasky&quot;)/div[@class=&quot;riaditel-prihlasky-ss-container&quot;]/div[@class=&quot;scrollable-middle-area&quot;]/div[@class=&quot;scroll-content-wrapper&quot;]/div[@class=&quot;row data-row&quot;]/div[@class=&quot;riaditel-prihlasky-cell&quot;]/div[@class=&quot;badge&quot;]</value>
      <webElementGuid>5654c450-b16d-4fb3-98f3-7c5a556cdf5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sub-riaditel-prihlasky']/div[4]/div[4]/div/div[2]/div[3]/div[2]</value>
      <webElementGuid>f81be9ce-910f-422c-84cd-77bfcdfb6f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Neskontrolovaná'])[2]/following::div[3]</value>
      <webElementGuid>a1a777af-df49-4faf-b527-9ba118de36e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skontrolovaná'])[1]/following::div[4]</value>
      <webElementGuid>50de9bfe-eecd-4c32-aa35-18cde6692db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='P-2026-5499'])[1]/preceding::div[1]</value>
      <webElementGuid>774011ba-b969-4f67-8d46-264cc64eb0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skontrolovaná'])[2]/preceding::div[6]</value>
      <webElementGuid>a56d9265-b0fc-4f6b-b857-2891ff8bb6b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Papierovo']/parent::*</value>
      <webElementGuid>06ec9f12-0d4e-42eb-bac1-31384d83381b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]</value>
      <webElementGuid>792abf15-633c-4f0c-a094-78b4d3794a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Papierovo' or . = 'Papierovo')]</value>
      <webElementGuid>5dd299cf-2cd8-45a9-b238-bc020c306dc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
