<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sp_btn-pridat-odbory govuk-button go_c64a56</name>
   <tag></tag>
   <elementGuidId>4bc0cd2a-e692-40d5-bd4c-318288735b23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn-pridat-odbory.govuk-button.govuk-button__basic.last-focusable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='odbory-a-kriteria-content']/div[5]/div/div[3]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ba16ca9e-8f0e-4f59-8835-230aa76e0fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-pridat-odbory govuk-button govuk-button__basic last-focusable</value>
      <webElementGuid>c0eb7216-3005-48a1-8a27-e5184c243b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dfd245aa-eb3b-4984-ada8-e3f63cd06d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pridať odbor/y</value>
      <webElementGuid>f32d2529-9a69-4410-8075-525a87aabe82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;odbory-a-kriteria-content&quot;)/div[@class=&quot;modal-wrapper pridat-odbory-modal-wrapper&quot;]/div[@class=&quot;modal pridat-odbory-modal&quot;]/div[@class=&quot;buttons-container&quot;]/div[@class=&quot;right-buttons&quot;]/button[@class=&quot;btn-pridat-odbory govuk-button govuk-button__basic last-focusable&quot;]</value>
      <webElementGuid>9cbce708-5bff-45d0-bb98-391a9ff3bbcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='odbory-a-kriteria-content']/div[5]/div/div[3]/div/button</value>
      <webElementGuid>c59d86bf-0d63-4914-b873-9daa6bcb9e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Späť'])[1]/following::button[1]</value>
      <webElementGuid>b36887ef-a109-497e-8c16-cfc8fe9c5ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='slovenský'])[2]/following::button[2]</value>
      <webElementGuid>5d006155-3c99-4b07-b75b-9323af81cf7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boli tieto informácie pre vás užitočné?'])[1]/preceding::button[1]</value>
      <webElementGuid>19dbe02e-5f6c-4275-8745-3c3ad2cbc399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Áno'])[1]/preceding::button[1]</value>
      <webElementGuid>b3a2a0d7-c86e-4814-9cd2-841faaec259f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]/div/button</value>
      <webElementGuid>5e677a75-55e2-46c3-b15d-5b182257691c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Pridať odbor/y' or . = 'Pridať odbor/y')]</value>
      <webElementGuid>be06b464-3901-4ad3-9ed6-13e4348ddbf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
