<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-modalUpravitOdborKap_547317</name>
   <tag></tag>
   <elementGuidId>f03fb0e2-cbcf-4f7e-9145-0d21fa7cf23d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-modalUpravitOdborKapacitaOdboruInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-modalUpravitOdborKapacitaOdboruInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c7cf30f-1dab-4110-88e7-97dd9afbdd43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>7179c62c-ba79-4cec-94d3-e06658f4b52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b95e6382-c771-4c31-b03f-4cc2775920b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-modalUpravitOdborKapacitaOdboruInput</value>
      <webElementGuid>8c27ded3-1a10-4ad1-b6bf-07839d44cfe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-modalUpravitOdborKapacitaOdboruInput&quot;)</value>
      <webElementGuid>91d8249f-2719-4dd7-a83b-8d01a8a66877</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-modalUpravitOdborKapacitaOdboruInput']</value>
      <webElementGuid>f32bd283-1010-43bb-a877-b89ff7403e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalUpravitOdborKapacitaOdboruInput']/div/div[2]/input</value>
      <webElementGuid>a2b5c708-4208-411b-959a-acb27d8d7509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/input</value>
      <webElementGuid>9351bbb8-bee3-417b-9be2-0cacc301abc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-modalUpravitOdborKapacitaOdboruInput']</value>
      <webElementGuid>48c17998-4723-4025-abd0-668feb7255b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
