<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_keyboard_arrow_down_zmenit-skolu-btn</name>
   <tag></tag>
   <elementGuidId>7ab773ff-4e2a-4dfe-add7-069c2ef3a024</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='zmenit-skolu-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zmenit-skolu-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>764d882d-846e-4a6b-aa67-af6157fb5d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zmenit-skolu-btn</value>
      <webElementGuid>3bfd7eb8-3717-4ae6-87a0-8f25aa41d4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button govuk-button__large margin-bottom-0</value>
      <webElementGuid>90036314-ac7b-4682-ac1e-e40b8640d066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Zmeniť školu</value>
      <webElementGuid>8967ee5c-7ddb-4131-9626-5f89d0a2fc2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zmenit-skolu-btn&quot;)</value>
      <webElementGuid>0e9390b7-f5d8-49d5-a953-6adbbe8c5267</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='zmenit-skolu-btn']</value>
      <webElementGuid>e5558502-03aa-4a91-b789-00d211c35f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zmenit-skolu-section']/div[2]/button</value>
      <webElementGuid>2240b41a-c3d3-44e1-8b10-67a415430f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[3]/following::button[1]</value>
      <webElementGuid>2582bee8-71f2-4387-b84f-d256491cfa4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(nepovinné)'])[1]/following::button[1]</value>
      <webElementGuid>29f8238c-7def-45ec-b975-2459b1b766f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boli tieto informácie pre vás užitočné?'])[1]/preceding::button[1]</value>
      <webElementGuid>9494fc75-5487-4466-a02c-ae6f311a9135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Áno'])[1]/preceding::button[1]</value>
      <webElementGuid>f0182a66-d841-4ddb-b2d0-1a2d1b5ac78b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>8f89758e-b124-46c8-b1ba-33e851be4867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'zmenit-skolu-btn' and (text() = 'Zmeniť školu' or . = 'Zmeniť školu')]</value>
      <webElementGuid>260558fc-aa14-4ee6-a925-05d30df0b262</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
