<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_E-mailov adresa_profil-riaditel-mail</name>
   <tag></tag>
   <elementGuidId>b08e15ba-1759-4889-b5f8-c84d30305524</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='profil-riaditel-mail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#profil-riaditel-mail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c7e166a8-d6f9-41f2-8738-74a9b54c4746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profil-riaditel-mail</value>
      <webElementGuid>e7341e34-9607-40ba-ae93-16a94eec540e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>katalontest987@gmail.com</value>
      <webElementGuid>52e25bee-1fd8-4f25-897d-c5bd6f0b03c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profil-riaditel-mail&quot;)</value>
      <webElementGuid>bd26bb2e-89ef-4dfa-a11c-41bf51c9ef80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='profil-riaditel-mail']</value>
      <webElementGuid>de86f45d-2cc6-476f-abe8-6b0c8180319e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profil']/div[2]/div[4]/div[2]</value>
      <webElementGuid>14d9e356-6aa7-42d3-90f5-ffce0ece3edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mailová adresa'])[1]/following::div[1]</value>
      <webElementGuid>f1a6dece-13bf-4e44-bc5d-6747f0aaee74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telefónne číslo'])[1]/following::div[4]</value>
      <webElementGuid>a8a437c8-0c81-49f3-8d86-5503cd6cc104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prihlasovacie meno'])[1]/preceding::div[1]</value>
      <webElementGuid>fdfd025e-e23e-4f46-a4b8-efdc677339f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prihlasovacie heslo'])[1]/preceding::div[4]</value>
      <webElementGuid>807a6248-f092-4bea-92dd-a56ab2871358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='katalontest987@gmail.com']/parent::*</value>
      <webElementGuid>3aeb336b-8dc7-44d9-971d-cd55d56e5183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]</value>
      <webElementGuid>ddc55bc9-75a5-49e6-a1f7-486437aa09da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'profil-riaditel-mail' and (text() = 'katalontest987@gmail.com' or . = 'katalontest987@gmail.com')]</value>
      <webElementGuid>fafc0205-de75-4d89-990c-8855eaf9e680</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
