<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_kola_profil-riaditel-skola_1</name>
   <tag></tag>
   <elementGuidId>32953a31-475e-4236-9510-8bbed1adff9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='profil-riaditel-skola']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#profil-riaditel-skola</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>696f3879-b184-4f7b-9dbf-c37f8311370e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profil-riaditel-skola</value>
      <webElementGuid>14c70933-793f-4b61-a14c-d1cf6f48ff12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Súkromná stredná odborná škola</value>
      <webElementGuid>3fce375f-5456-481e-9e2c-f2fc4a32df3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profil-riaditel-skola&quot;)</value>
      <webElementGuid>15cb2a09-d622-4b37-adde-bc37454816c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='profil-riaditel-skola']</value>
      <webElementGuid>7cbaa51c-d2fd-4953-b241-4726df99b0f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profil']/div[2]/div/div[2]</value>
      <webElementGuid>b239d521-5843-425a-999a-396d4d209ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Škola'])[1]/following::div[1]</value>
      <webElementGuid>bee16313-d88e-444d-8a07-28b063206f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upraviť údaje'])[1]/following::div[4]</value>
      <webElementGuid>19d0f5c4-a7ae-4c0c-8c90-e128a2fd104d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pozícia'])[1]/preceding::div[1]</value>
      <webElementGuid>20a08946-ee78-4eea-9b7f-7a22b997e0ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Riaditeľ'])[1]/preceding::div[2]</value>
      <webElementGuid>bb24f4b4-e615-4556-b485-9180c11fe1e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Súkromná stredná odborná škola']/parent::*</value>
      <webElementGuid>007bfb52-ec22-4fca-b726-82968378fe97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>edac8632-4eeb-4e1d-80ea-8c1e5ef6394a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'profil-riaditel-skola' and (text() = 'Súkromná stredná odborná škola' or . = 'Súkromná stredná odborná škola')]</value>
      <webElementGuid>75d245d9-994b-4b32-8735-a1990a8f80d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
