<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(nepovinn)_select-zmenitSkolu</name>
   <tag></tag>
   <elementGuidId>babc05db-16a8-4911-b464-cf95622366a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@class='govuk-input autocomplete-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select-zmenitSkolu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0b94376e-efdd-4ddc-88ed-7fc9fe40ab58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select</value>
      <webElementGuid>efbf413f-03cd-4787-8ede-dfb3cda8f2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9d5f3293-69a3-4aaf-acd0-7869b8a9e3ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-zmenitSkolu</value>
      <webElementGuid>92253e77-20c3-4bcd-baa5-943702c561be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Materská škola Košice SeverElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyGymnázium MetodovaGymnázium v BudimíreMaterská škola Košice KVPStredná odborná škola strojníckaSúkromná stredná odborná školaSúkromná stredná umelecká škola scénického výtvarníctva</value>
      <webElementGuid>fc2de82a-aec7-4cd2-a997-7b60e192a2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-zmenitSkolu&quot;)</value>
      <webElementGuid>0dde8626-5fe9-41d8-8f9d-a50d35e08cdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select-zmenitSkolu']</value>
      <webElementGuid>197add3e-e483-4353-88be-a96d3fe2351f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zmenitSkolu']/div/div[2]/select</value>
      <webElementGuid>1bb6b576-6e26-4625-b4a6-50a4144fca0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(nepovinné)'])[1]/following::select[1]</value>
      <webElementGuid>192438c3-7161-4c4c-8dc0-d855873d87b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Škola'])[2]/following::select[1]</value>
      <webElementGuid>f5dd3188-15d8-4c12-a395-306192bff504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[3]/preceding::select[1]</value>
      <webElementGuid>9a3a6232-cbbf-4a96-92e7-b31150c749e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zmeniť školu'])[2]/preceding::select[1]</value>
      <webElementGuid>5843102d-302a-40cb-9376-24ad788dda76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>1b3243e1-f6e4-4b93-a282-a780f72e1a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @id = 'select-zmenitSkolu' and (text() = 'Materská škola Košice SeverElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyGymnázium MetodovaGymnázium v BudimíreMaterská škola Košice KVPStredná odborná škola strojníckaSúkromná stredná odborná školaSúkromná stredná umelecká škola scénického výtvarníctva' or . = 'Materská škola Košice SeverElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyGymnázium MetodovaGymnázium v BudimíreMaterská škola Košice KVPStredná odborná škola strojníckaSúkromná stredná odborná školaSúkromná stredná umelecká škola scénického výtvarníctva')]</value>
      <webElementGuid>6731ed64-4e54-4012-ad11-b3e02752cc1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
