<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Adresa trvalho pobytu_dietaAdresaTrvale_3d75f1</name>
   <tag></tag>
   <elementGuidId>332f4a7e-b1d7-49df-a46b-da789ec21759</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='suhrnny-prehlad']/div[4]/div[2]/div[12]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dietaAdresaTrvalehoPobytu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ba17566-2632-4ea9-8295-24fc889ebb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dietaAdresaTrvalehoPobytu</value>
      <webElementGuid>bea5da9a-4ff2-46a0-aaf0-ebd7fa33d738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Matunákova 123/321, 75369, Bôrka, Slovenská republika</value>
      <webElementGuid>57271e4b-c73c-4472-bb9e-f398e375ea15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suhrnny-prehlad&quot;)/div[@class=&quot;panel-with-header&quot;]/div[@class=&quot;panel-content info-layout&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;dietaAdresaTrvalehoPobytu&quot;]</value>
      <webElementGuid>aca796ba-28f4-4869-81ce-b2d25a068af6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suhrnny-prehlad']/div[4]/div[2]/div[12]/div[2]</value>
      <webElementGuid>e8d284fd-a049-48e4-8254-846eceedac25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adresa trvalého pobytu'])[2]/following::div[1]</value>
      <webElementGuid>fa3ecb8d-ea5a-4e46-a7d5-53c3f4960da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[15]/following::div[3]</value>
      <webElementGuid>ae7529e6-22c2-41c9-9541-25a08093ee2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adresa miesta, kde sa dieťa obvykle zdržiava, ak je iná, než adresa trvalého pobytu'])[2]/preceding::div[1]</value>
      <webElementGuid>bb092b8d-d322-49c3-96ac-58d5884a6512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Matunákova 123/321, 75369, Bôrka, Slovenská republika'])[2]/preceding::div[2]</value>
      <webElementGuid>a07a8400-54f1-418d-8b76-f5131ec24ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Matunákova 123/321, 75369, Bôrka, Slovenská republika']/parent::*</value>
      <webElementGuid>2263386f-3b95-4ef6-87e0-4a18d998b99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[12]/div[2]</value>
      <webElementGuid>89ee1237-51a5-4382-aaad-7bcbad0bf216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Matunákova 123/321, 75369, Bôrka, Slovenská republika' or . = 'Matunákova 123/321, 75369, Bôrka, Slovenská republika')]</value>
      <webElementGuid>c85713bd-4de1-40a5-bb63-573a1ca6e3db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
