<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Korepondenn adresa_zakonnyZastupcaAdres_9d2f75</name>
   <tag></tag>
   <elementGuidId>661c2895-4c1b-4d0e-9d4b-06698b43524e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zastupcovia']/div[2]/div[2]/div[6]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.zakonnyZastupcaAdresaBydliska</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1fe57614-2232-46f8-ab11-3fe506ab8622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zakonnyZastupcaAdresaBydliska</value>
      <webElementGuid>0c515702-ebb3-41d5-8260-705c83060f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ražná 58/232, 01508, Košariská, Slovenská republika</value>
      <webElementGuid>26192579-da5a-4b76-8636-5eef16661b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zastupcovia&quot;)/div[@class=&quot;panel-content&quot;]/div[@class=&quot;zz1 info-layout&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;zakonnyZastupcaAdresaBydliska&quot;]</value>
      <webElementGuid>301e01de-a8e3-4a6e-b4b9-7dbf10a32107</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zastupcovia']/div[2]/div[2]/div[6]/div[2]</value>
      <webElementGuid>497e014d-56be-49eb-b1c5-428d3817be20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Korešpondenčná adresa'])[4]/following::div[1]</value>
      <webElementGuid>f46883ca-872d-4310-9cf5-f596163df580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum narodenia'])[8]/following::div[4]</value>
      <webElementGuid>2c7e7d76-a1f0-4c84-9020-9dee247a8579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail'])[3]/preceding::div[1]</value>
      <webElementGuid>80ecf7b0-a08c-4998-bbd6-58cfa40c3c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='katalontest987@gmail.com'])[2]/preceding::div[2]</value>
      <webElementGuid>bbe0e2a5-9058-4dea-adb9-487aa6c7fd48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div[2]/div[6]/div[2]</value>
      <webElementGuid>45bae9c6-6c35-45cb-a7a5-2657885c306d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ražná 58/232, 01508, Košariská, Slovenská republika' or . = 'Ražná 58/232, 01508, Košariská, Slovenská republika')]</value>
      <webElementGuid>c814c3d3-6912-4a33-9c04-327ed9e494cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
