<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Poadovan dtum prijatia dieaa do matersk_673c9e</name>
   <tag></tag>
   <elementGuidId>49838ee6-cc8f-4503-8e0c-2c5e51859c22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdpDietata']/div[2]/div/div/div[7]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dpPozadovanyDatumPrijatia</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0b1569fb-c5b3-4614-8c3f-70487ec2967b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dpPozadovanyDatumPrijatia</value>
      <webElementGuid>723363cb-9e58-4cbb-b065-698f068a8965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>01.09.2026</value>
      <webElementGuid>9c4ca7db-a609-4632-ab0f-22e924bf9d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suhrnny-prehlad&quot;)/div[@id=&quot;pdpDietata&quot;]/div[@class=&quot;panel-content&quot;]/div[@class=&quot;content-ms-zs&quot;]/div[@class=&quot;info-layout&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;dpPozadovanyDatumPrijatia&quot;]</value>
      <webElementGuid>db9be94c-2886-4a6a-8222-86b5007b08b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdpDietata']/div[2]/div/div/div[7]/div[2]</value>
      <webElementGuid>90be2345-ec20-4cd5-a73b-d8d9dd31a007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Požadovaný dátum prijatia dieťaťa do materskej školy'])[2]/following::div[1]</value>
      <webElementGuid>0725b9cc-f055-4723-af4c-7371c08d392e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nie'])[10]/following::div[3]</value>
      <webElementGuid>c0c61615-255e-46f2-acfc-744a82fcb898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Popis znevýhodnenia'])[2]/preceding::div[1]</value>
      <webElementGuid>e84b2fea-a495-44fa-bec5-9511e0e4d70c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[19]/preceding::div[2]</value>
      <webElementGuid>de27b0e3-aace-4a53-9413-11d8ad6c1f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='01.09.2026']/parent::*</value>
      <webElementGuid>9c05b63a-0940-4a20-b3cf-5fbc640519cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div[7]/div[2]</value>
      <webElementGuid>39b48df3-cf82-4859-a3b8-06aa473173f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '01.09.2026' or . = '01.09.2026')]</value>
      <webElementGuid>3d8a5f59-96ab-433f-9683-3f0742452b7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
