<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Adresa miesta, kde sa diea obvykle zdri_a56ee1</name>
   <tag></tag>
   <elementGuidId>58dcfc20-25f6-4f24-b944-8b53bfdecaf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='suhrnny-prehlad']/div[4]/div[2]/div[13]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dietaAdresaObvyklehoPobytu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a86f4dab-9dee-4203-b582-c67a8be96947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dietaAdresaObvyklehoPobytu</value>
      <webElementGuid>e4d7a4cf-d932-4236-b03d-f377cd5ab8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Matunákova 123/321, 75369, Bôrka, Slovenská republika</value>
      <webElementGuid>b734dc93-101e-4982-a41a-af85645d16a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suhrnny-prehlad&quot;)/div[@class=&quot;panel-with-header&quot;]/div[@class=&quot;panel-content info-layout&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;dietaAdresaObvyklehoPobytu&quot;]</value>
      <webElementGuid>80c34385-d72c-417a-8ff1-d011d7bd2f3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suhrnny-prehlad']/div[4]/div[2]/div[13]/div[2]</value>
      <webElementGuid>6222688f-39a3-41e2-b49e-e8bba3bf0cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adresa miesta, kde sa dieťa obvykle zdržiava, ak je iná, než adresa trvalého pobytu'])[2]/following::div[1]</value>
      <webElementGuid>837fc9b0-bbba-4728-ab38-0939052318f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Matunákova 123/321, 75369, Bôrka, Slovenská republika'])[1]/following::div[3]</value>
      <webElementGuid>4df772c6-ef91-44fb-8490-8bf3b969d16e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doplňujúce informácie o dieťati'])[3]/preceding::div[1]</value>
      <webElementGuid>cccbb535-c264-44da-bd97-4f3f1d706afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Žiadam o prijatie dieťaťa na'])[2]/preceding::div[3]</value>
      <webElementGuid>ebf6d5a6-3f60-4e06-86e6-8dc41fdaf316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[13]/div[2]</value>
      <webElementGuid>1cc763b7-c2c4-4b21-8ea7-9fcefcdefb8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Matunákova 123/321, 75369, Bôrka, Slovenská republika' or . = 'Matunákova 123/321, 75369, Bôrka, Slovenská republika')]</value>
      <webElementGuid>f639894e-7535-4e46-88e4-b4b4ceca84b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
