<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hada poda mojej adresy_hladat-podla-r_99fc84</name>
   <tag></tag>
   <elementGuidId>111d3c50-42cd-4b8e-8ed5-e1ddb75bdbca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hladat-podla-radio-wrapper-MS_option_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hladat-podla-radio-wrapper-MS_option_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29109802-9b94-4ac4-b60e-3af3a5547374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>00eab27f-2f21-4f31-b13b-be4e386456af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hladat-podla-radio-wrapper-MS_option_1</value>
      <webElementGuid>ab66aed5-46ee-41bf-a39b-25d365ac3779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hladat-podla-radio-wrapper-MS</value>
      <webElementGuid>96bb56b7-4d99-4151-9c8c-fe36199eb19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4cf374ef-4837-43e9-9511-e0e34b747ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>podla-nazvu-skoly-alebo-jej-adresy</value>
      <webElementGuid>87eb48b0-10a4-407a-89cc-a198dd4263a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hladat-podla-radio-wrapper-MS_option_1&quot;)</value>
      <webElementGuid>d3a0589b-70bd-47b9-b4ac-f1c3d2b06719</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hladat-podla-radio-wrapper-MS_option_1']</value>
      <webElementGuid>ef9b46ec-ac9b-4ea5-9fc3-9b73728d5a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hladat-podla-radio-wrapper-MS']/div/fieldset/div[3]/div[2]/input</value>
      <webElementGuid>24c1adae-93a4-4073-9cd2-2d3f0b74fdaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/fieldset/div[3]/div[2]/input</value>
      <webElementGuid>0727796b-0278-48cf-8ea7-1e47f71cc81d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'hladat-podla-radio-wrapper-MS_option_1' and @name = 'hladat-podla-radio-wrapper-MS' and @type = 'radio']</value>
      <webElementGuid>488301c6-74a5-4c50-8624-d4b8ccd837be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
