<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_keyboard_arrow_down_btn-vytvorit-prihlasku</name>
   <tag></tag>
   <elementGuidId>8ae8cdea-29fe-4c8a-a031-4edc66c7af72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-vytvorit-prihlasku']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-vytvorit-prihlasku</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ede2ae4a-5571-4761-aa99-7e5582ab6039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-vytvorit-prihlasku</value>
      <webElementGuid>7b94fa7b-d91e-4eb6-9789-adff8b967680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button riaditel-sprava-prihlasok-heading-button</value>
      <webElementGuid>800e4aa3-c466-41ac-9169-2f61300937f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c63b5a46-85b1-4b4e-adb1-6db3b9001b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Vytvoriť prihlášku</value>
      <webElementGuid>4cad79c2-20ed-43b8-96c5-f3ec0d36a4dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-module</name>
      <type>Main</type>
      <value>govuk-button</value>
      <webElementGuid>06b8081e-d2b9-4ecf-9d4f-355e7d9a8770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>addPridať prihlášku</value>
      <webElementGuid>af6bed8c-0560-4d24-bb41-872adb496685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-vytvorit-prihlasku&quot;)</value>
      <webElementGuid>077d095f-19c3-401e-8b83-a7e3e4d0575f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-vytvorit-prihlasku']</value>
      <webElementGuid>c4612da6-c1e1-46d2-b213-eacb01d598ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sub-riaditel-prihlasky']/div[3]/div/button</value>
      <webElementGuid>4bdb2fd4-a057-4b0d-b0de-ee60b29b94e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[4]/following::button[1]</value>
      <webElementGuid>2ee60f8e-63b9-420c-b74c-04a896242c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exportovať do'])[1]/following::button[1]</value>
      <webElementGuid>87f3946f-3151-42b8-90fc-3311e25b9a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Povinné prihlášky na prijatie'])[1]/preceding::button[1]</value>
      <webElementGuid>0f4df0eb-3bdd-4cfc-928c-e144326c0875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Povinné prihlášky na prijatie, ale kvôli nedostatku miest ich nemôžete prijať'])[1]/preceding::button[1]</value>
      <webElementGuid>c1d617b3-ee47-4238-bb7c-dae47a83502b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pridať prihlášku']/parent::*</value>
      <webElementGuid>1d77243e-2d01-4062-b8c1-67bc704e0127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>d3f6aca7-5619-41bd-a489-de04eb656686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-vytvorit-prihlasku' and @type = 'submit' and @name = 'Vytvoriť prihlášku' and (text() = 'addPridať prihlášku' or . = 'addPridať prihlášku')]</value>
      <webElementGuid>210f15d8-6981-430f-ab8c-e195dcc216f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
