<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Povinn prihlky na prijatie, ale kvli _9491e4</name>
   <tag></tag>
   <elementGuidId>65588aa4-d136-4dd3-9a9c-40e04afec998</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fulltext-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fulltext-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dce59003-eb5f-48aa-a9d2-fea3dc4be1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fulltext-input</value>
      <webElementGuid>40ff4770-d132-4137-843b-9f5fd996e45e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7f2106ba-e2d1-4c26-84b3-1c9c7c8efb75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input vyhladavanie-input</value>
      <webElementGuid>4bdd024a-bf85-49ea-9a7f-9440caa03b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Vyhľadávanie v meno, priezvisko, priezvisko zákonného zástupcu č. 1, poznámka školy</value>
      <webElementGuid>758e1add-5736-48b3-873a-8ebcd48b56c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder-desktop</name>
      <type>Main</type>
      <value>Vyhľadávanie v meno, priezvisko, priezvisko zákonného zástupcu č. 1, poznámka školy</value>
      <webElementGuid>1845d79f-6dc6-4eb6-a35c-144b5c03b37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder-mobile</name>
      <type>Main</type>
      <value>Vyhľadávanie v prihláškach</value>
      <webElementGuid>ee80bf47-9cb4-4f5c-a006-2bd2b94b6276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fulltext-input&quot;)</value>
      <webElementGuid>ca6462d1-3e45-4561-b9d6-0c2669ede0a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fulltext-input']</value>
      <webElementGuid>2647b228-8f37-4aee-8f75-89701f321612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fulltext-input-wrapper']/div/input</value>
      <webElementGuid>eb85c59b-fd64-4f94-80dc-bec32582c8cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>9f0d2706-2758-46fb-a723-4fe1a0db48b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fulltext-input' and @type = 'text' and @placeholder = 'Vyhľadávanie v meno, priezvisko, priezvisko zákonného zástupcu č. 1, poznámka školy']</value>
      <webElementGuid>10e3fbb1-4c55-4b45-885a-19948fe7c218</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
