<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nrodnos_dietaNarodnost</name>
   <tag></tag>
   <elementGuidId>67f0b41e-8101-46d1-88d0-f91cdd79f40b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='suhrnny-prehlad']/div[4]/div[2]/div[8]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dietaNarodnost</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d2e499d5-f164-45c1-8566-925f9da1618c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dietaNarodnost</value>
      <webElementGuid>abf870c1-e2e0-4882-81b8-0b942933d0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>slovenská</value>
      <webElementGuid>863e1302-be46-45e7-a815-670d4d9f101d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suhrnny-prehlad&quot;)/div[@class=&quot;panel-with-header&quot;]/div[@class=&quot;panel-content info-layout&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;dietaNarodnost&quot;]</value>
      <webElementGuid>d0b6eedf-3141-4607-b987-4ef05576d8bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suhrnny-prehlad']/div[4]/div[2]/div[8]/div[2]</value>
      <webElementGuid>412f7c20-e95a-44e3-ab79-09d2a8b90c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Národnosť'])[4]/following::div[1]</value>
      <webElementGuid>4f23c81c-5f1b-4b70-9da4-189cf9447194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slovensko'])[2]/following::div[3]</value>
      <webElementGuid>df120a0f-ec0c-49e2-84ac-ad1df1d1fea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Štátna príslušnosť'])[3]/preceding::div[1]</value>
      <webElementGuid>a58f47e1-9a6d-4935-bbbb-6ad5272ea957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slovenská republika'])[5]/preceding::div[2]</value>
      <webElementGuid>28c11ad1-cf63-4858-b8e7-3e02f211b2a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[8]/div[2]</value>
      <webElementGuid>19f56af7-925e-4292-a092-4e0810e233bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'slovenská' or . = 'slovenská')]</value>
      <webElementGuid>216655f2-d619-41a0-8100-a15220766548</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
