<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Zujem o stravovanie v kolskej jedlni_dp_ad0c47</name>
   <tag></tag>
   <elementGuidId>57f735f2-acf6-434d-ac2f-92b1342a6a73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdpDietata']/div[2]/div/div/div[3]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dpDietataStravovanie</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>143e7fb6-182f-44b7-8d19-99ef4d006e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dpDietataStravovanie</value>
      <webElementGuid>d5a96fc1-db2a-4734-ae27-56ec39f51874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nie</value>
      <webElementGuid>d51799a7-d03d-46f4-a182-e7d5450bc1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suhrnny-prehlad&quot;)/div[@id=&quot;pdpDietata&quot;]/div[@class=&quot;panel-content&quot;]/div[@class=&quot;content-ms-zs&quot;]/div[@class=&quot;info-layout&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;dpDietataStravovanie&quot;]</value>
      <webElementGuid>0c8ae469-c646-4885-a486-fd6d87095afb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdpDietata']/div[2]/div/div/div[3]/div[2]</value>
      <webElementGuid>3ef3b54c-f3bd-4379-a517-ab1304725b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Záujem o stravovanie v školskej jedálni'])[2]/following::div[1]</value>
      <webElementGuid>8fc9d136-c250-4652-83ea-d4cb95d8c1bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Etická'])[2]/following::div[3]</value>
      <webElementGuid>aff5d49f-a8cb-4f43-a4de-55853bc88961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Záujem o školský klub detí'])[2]/preceding::div[1]</value>
      <webElementGuid>25854825-9e98-4115-bd26-54ddcf771fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nie'])[10]/preceding::div[2]</value>
      <webElementGuid>8f2b2091-a49e-4342-b281-d3f6c632ff96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div[3]/div[2]</value>
      <webElementGuid>60c48746-0cfd-4e9d-9dbd-3896597ffa4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Nie' or . = 'Nie')]</value>
      <webElementGuid>584457bb-d7ea-4638-bd19-6a9d6a023e6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
