<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Telefnne slo_zakonnyZastupca2Telefon</name>
   <tag></tag>
   <elementGuidId>8a212f7f-67c7-47d2-9e74-23586105b9f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zastupcovia']/div[2]/div[5]/div[8]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.zakonnyZastupca2Telefon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>478d15d5-8d97-42d6-8bce-c4d95c66cd12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zakonnyZastupca2Telefon</value>
      <webElementGuid>71cea2f0-0390-4194-b57e-7ebc2b7ae7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+421987456321</value>
      <webElementGuid>8c817e96-1e1f-45ea-9541-97ed0146d64d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zastupcovia&quot;)/div[@class=&quot;panel-content&quot;]/div[@class=&quot;zz2 info-layout&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;zakonnyZastupca2Telefon&quot;]</value>
      <webElementGuid>2248503c-ec40-40a9-9af3-e0de10c93fcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zastupcovia']/div[2]/div[5]/div[8]/div[2]</value>
      <webElementGuid>135fa1ea-03e8-4e4d-bc00-e21cf04a9169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telefónne číslo'])[5]/following::div[1]</value>
      <webElementGuid>b2786165-8ab5-4349-8fd0-bd56cee420ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mail@mail.sk'])[1]/following::div[3]</value>
      <webElementGuid>0378ff21-8993-4d24-9c09-d276632c1fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Čestne vyhlasujem, že s podaním prihlášky súhlasí aj druhý zákonný zástupca dieťaťa'])[1]/preceding::div[1]</value>
      <webElementGuid>fc590540-90a8-489c-8cba-e6e4d184113a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Áno'])[9]/preceding::div[2]</value>
      <webElementGuid>e57131be-4e27-4f9b-b7ec-ce7d7b566a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+421987456321']/parent::*</value>
      <webElementGuid>2a022a8c-986c-48cc-aa92-d0ca61c51358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[8]/div[2]</value>
      <webElementGuid>dd8e9927-f4ef-4ff2-88c9-db6413d043d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '+421987456321' or . = '+421987456321')]</value>
      <webElementGuid>340d13b6-0894-4274-8e2c-c6fa948056e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
