<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Priezvisko_zastupca1Priezvisko</name>
   <tag></tag>
   <elementGuidId>ff46c5d8-dcc8-4596-9d62-43cbe2a78a0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zastupca1Priezvisko']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zastupca1Priezvisko</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>17c0f377-9f4f-4f1a-9e83-1db4e27ba080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zastupca1Priezvisko</value>
      <webElementGuid>b2b938d5-7f9c-4ba8-b648-1e8d4e2c350c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lukáč</value>
      <webElementGuid>75ace521-452c-4b56-926f-076e9d6cd277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zastupca1Priezvisko&quot;)</value>
      <webElementGuid>405aae91-2c38-4539-88aa-c4c7e5751d94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zastupca1Priezvisko']</value>
      <webElementGuid>4ec24e89-8b7c-43c5-97cc-396453948e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='osobne-udaje-zz1']/div[2]/div[2]/div[2]/div[2]</value>
      <webElementGuid>80a2fc1f-bfd3-41ac-8f9d-fc0bf766e22e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priezvisko'])[4]/following::div[1]</value>
      <webElementGuid>032db396-42d4-411e-9da7-90f43f5e6a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tomáš'])[1]/following::div[3]</value>
      <webElementGuid>a0b356b2-4f69-4a78-ad50-c6732e1fc49c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodné priezvisko'])[4]/preceding::div[1]</value>
      <webElementGuid>8314e0e0-1f1a-4b24-a89e-0885ef1d423d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[11]/preceding::div[2]</value>
      <webElementGuid>58bc30e2-c0c4-481e-955c-018ca8ce83a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lukáč']/parent::*</value>
      <webElementGuid>8f2cd7cb-8d62-40dc-90d3-7f8bcaf81bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div[2]/div[2]</value>
      <webElementGuid>d564707b-a0ff-4541-9dd0-d1c8f573e21c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zastupca1Priezvisko' and (text() = 'Lukáč' or . = 'Lukáč')]</value>
      <webElementGuid>78dad976-70ac-4292-8f37-c2351171dc91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
