<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_no_zsDPDStravovanieRadio_option_1</name>
   <tag></tag>
   <elementGuidId>23347312-51e5-4eac-b845-6f4e4ae779c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='zsDPDStravovanieRadio_option_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zsDPDStravovanieRadio_option_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a41c7fc6-1c7f-4c70-8230-9303ae668978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>26ef4f8a-635d-4d6e-afa9-03fd939fc219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zsDPDStravovanieRadio_option_1</value>
      <webElementGuid>9fafba33-cca0-4eeb-8cc5-664be2496320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zsDPDStravovanieRadio</value>
      <webElementGuid>b7a2473d-438a-44e5-bc7e-3d494bffd586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>027bdd33-42e8-4585-a98b-8d923306de91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>62630e61-4e0c-4839-a1f9-d475c9b4e4f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zsDPDStravovanieRadio_option_1&quot;)</value>
      <webElementGuid>8c483284-f091-44df-8eaa-f7213519c872</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zsDPDStravovanieRadio_option_1']</value>
      <webElementGuid>14955be2-dcb7-4241-be8c-e25e7585b5ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zsDPDStravovanieRadio']/div/fieldset/div[3]/div[2]/input</value>
      <webElementGuid>a5ee0c88-3484-4d4e-8b60-b7de92972ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/fieldset/div[3]/div[2]/input</value>
      <webElementGuid>891beaa2-7d60-4f36-af47-60cd25d91849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'zsDPDStravovanieRadio_option_1' and @name = 'zsDPDStravovanieRadio' and @type = 'radio']</value>
      <webElementGuid>4e4b6807-fbc3-4c07-8059-e043821ca28b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
