<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__DPDSVVPRadio_option_1</name>
   <tag></tag>
   <elementGuidId>11dd9bb2-8e29-4302-ac8e-278144c435e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DPDSVVPRadio_option_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DPDSVVPRadio_option_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4bc790c-48d5-4ff6-a756-7978fa099200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>bb3db8b9-d98a-4269-9bbe-c60ce47e33f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DPDSVVPRadio_option_1</value>
      <webElementGuid>20348390-452f-43b2-8ee2-b6aafb332c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DPDSVVPRadio</value>
      <webElementGuid>ed5d1958-4be7-4158-a983-1d3216477f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d2152179-0a57-467c-af88-5854940a945c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3acfb8a5-ddb2-4a67-9274-14f7a506ed97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DPDSVVPRadio_option_1&quot;)</value>
      <webElementGuid>3d86484a-f113-4441-9a95-39eeb1164655</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DPDSVVPRadio_option_1']</value>
      <webElementGuid>748fba51-480d-4dd5-a630-f1cf2a912b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DPDSVVPRadio']/div/fieldset/div[3]/div[3]/input</value>
      <webElementGuid>48282d5a-0939-4d6b-a4a9-8c29af3ea23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/fieldset/div[3]/div[3]/input</value>
      <webElementGuid>2b6bbc25-dcbb-46e0-be43-30395dff1150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DPDSVVPRadio_option_1' and @name = 'DPDSVVPRadio' and @type = 'radio']</value>
      <webElementGuid>0b672ec9-a14e-4177-92d8-64e6a9b675d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
