<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_zsDPDVychovaRadio_option_0</name>
   <tag></tag>
   <elementGuidId>61baa776-8ef4-4b5e-9cc3-273caa801e8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='zsDPDVychovaRadio_option_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zsDPDVychovaRadio_option_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6825b36f-6bff-4897-8470-191a020afe7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>3a946e21-a83b-40ce-a087-2398baa04eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zsDPDVychovaRadio_option_0</value>
      <webElementGuid>fce0d59c-14f0-491b-8606-c219d7782174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zsDPDVychovaRadio</value>
      <webElementGuid>3bd8feb4-9a62-40e0-afe2-55ce6a49a95f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>214eb36d-4eee-4e4a-bec2-dbb4f109e9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c2423092-d6e1-44c6-bb57-1fb3b39d7937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zsDPDVychovaRadio_option_0&quot;)</value>
      <webElementGuid>25577967-da32-42dd-8315-944babaf44b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zsDPDVychovaRadio_option_0']</value>
      <webElementGuid>d8f50c8f-30e4-4284-9223-6e34570897eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zsDPDVychovaRadio']/div/fieldset/div[3]/div/input</value>
      <webElementGuid>6df0e5fc-0e83-410b-bff2-4edea515004a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div[2]/div/fieldset/div[3]/div/input</value>
      <webElementGuid>945532bb-9a89-4b86-aa8c-a25c32336f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'zsDPDVychovaRadio_option_0' and @name = 'zsDPDVychovaRadio' and @type = 'radio']</value>
      <webElementGuid>a13f0aaf-7c89-4478-87cf-a26dcdccfa7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
