<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_agreementRadio_option_0</name>
   <tag></tag>
   <elementGuidId>5aef2dfc-e409-4a02-be98-18c031976b3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='agreementRadio_option_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#agreementRadio_option_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b92f48c8-7d10-4453-bdc7-c36a84df41f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>7251f603-6e63-45d4-bbca-c100197a902c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>agreementRadio_option_0</value>
      <webElementGuid>44df91b5-8f1a-4d15-9a43-b708d986837c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>agreementRadio</value>
      <webElementGuid>bed48786-cbd5-4e37-aa1e-a29c89073785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6405fb59-7545-4c50-a838-0ad59510dd08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ANO</value>
      <webElementGuid>a22b4641-48ea-463c-bd79-7f4b0037b500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agreementRadio_option_0&quot;)</value>
      <webElementGuid>b29b70f4-a693-49b2-915f-1b6b70d1c6ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='agreementRadio_option_0']</value>
      <webElementGuid>6126b8fe-6b13-4398-8b89-afa538d2b057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='agreementRadio']/div/fieldset/div[3]/div/input</value>
      <webElementGuid>8ef2388d-644b-4010-8890-5695083f8028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/fieldset/div[3]/div/input</value>
      <webElementGuid>a935c237-4179-4467-bb13-126ac744189a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'agreementRadio_option_0' and @name = 'agreementRadio' and @type = 'radio']</value>
      <webElementGuid>c00396cf-2c41-4658-a887-dd401f17d560</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
