<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-overenie-input</name>
   <tag></tag>
   <elementGuidId>a07533c3-6afd-4db7-b194-34146570cc64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-overenie-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-overenie-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dfc2704f-b47b-4633-ba6e-731ccc36f122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>57bb30f1-a78d-418c-8d1d-7706a3c78ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d1f19b05-2916-4ef1-bb1a-f53f8076d528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-overenie-input</value>
      <webElementGuid>ed985a83-c207-419b-ac82-b942ac619fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>4b02df68-b781-4457-b8c0-0dea95d7d5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-overenie-input&quot;)</value>
      <webElementGuid>4bf9c2c0-89f6-4d1f-962b-6d90d07ef817</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-overenie-input']</value>
      <webElementGuid>22f02282-5300-40a8-8265-c499e1fa1cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='overenie-input']/div/div[2]/input</value>
      <webElementGuid>7346418c-94aa-4b3e-913d-904790db29da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[4]/div/div/div[3]/div/div[2]/input</value>
      <webElementGuid>9f4363a5-8946-4147-ab14-f04f393b3eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-overenie-input']</value>
      <webElementGuid>03b66370-cde0-48de-a3d7-9002728ddcb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
