<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-adresaTPSupisneCislo</name>
   <tag></tag>
   <elementGuidId>a98bb970-f5c6-4c3b-bbc0-6436d8fd8f8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-adresaTPSupisneCislo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-adresaTPSupisneCislo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f213028-7f0a-458a-9854-9b078006530c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>7f37504b-6fdc-4665-bb7a-8fc4eef6b809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3f06355-f753-4db9-a84d-eca80b173130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-adresaTPSupisneCislo</value>
      <webElementGuid>22f52153-73e9-4430-9416-8cff156216db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>e93073cf-a7c2-45a5-9a8e-7cff18afdb51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-adresaTPSupisneCislo&quot;)</value>
      <webElementGuid>d11d7ff1-8750-4bca-8657-ac164dfb47b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-adresaTPSupisneCislo']</value>
      <webElementGuid>2fb75a5c-1e12-47cb-b5d2-aea943367a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adresaTPSupisneCislo']/div/div[2]/input</value>
      <webElementGuid>007bbd84-31a6-4135-b131-3f03f1dadde1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div[4]/div/div/div[2]/input</value>
      <webElementGuid>ddcb765e-f602-4693-9f1f-19c35c2c1f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-adresaTPSupisneCislo']</value>
      <webElementGuid>81212feb-94e9-4763-ae26-32e81509ad95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
