<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Priezvisko_dietaPriezvisko</name>
   <tag></tag>
   <elementGuidId>4364c8a0-784a-489d-80d7-fdefcc191d4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dietaPriezvisko']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dietaPriezvisko</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>867fe266-ec4d-4d39-aa84-f8e1d4b6f7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dietaPriezvisko</value>
      <webElementGuid>a642d29a-aa61-4b76-86de-1430d55549dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gerdžo</value>
      <webElementGuid>cfc2b691-819d-4afe-ac8e-f8934c0cf0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dietaPriezvisko&quot;)</value>
      <webElementGuid>7c0301f4-5203-4748-b6f8-ba0ac2a7becf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dietaPriezvisko']</value>
      <webElementGuid>4be1dc60-60cf-4041-8953-1b416ae5e3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='detail-prihlasky-riad-MS-ZS-content']/div[5]/div[2]/div[2]/div[2]</value>
      <webElementGuid>7fe7bd3e-2c2e-42d2-9b05-672987c4eed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priezvisko'])[1]/following::div[1]</value>
      <webElementGuid>817b3394-ea28-40ed-ae9d-9eb0699115e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rudolf'])[1]/following::div[3]</value>
      <webElementGuid>38034b7c-1d50-4134-b94b-5147fbe9d0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodné priezvisko'])[1]/preceding::div[1]</value>
      <webElementGuid>52fd77bd-5b2d-495d-a1bd-2e8043e7378a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::div[2]</value>
      <webElementGuid>c5dee0ff-6587-4282-a1a7-7a001beb8a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gerdžo']/parent::*</value>
      <webElementGuid>5864941d-e226-4181-8738-c1f9a2bd8ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[2]/div[2]</value>
      <webElementGuid>c057b59f-f25f-4dc9-97a6-6f9d1f1108b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dietaPriezvisko' and (text() = 'Gerdžo' or . = 'Gerdžo')]</value>
      <webElementGuid>c0128116-0316-4941-b6b7-9544fe8d0df8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
