<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_delete_outlineOdstrni_1_2_3</name>
   <tag></tag>
   <elementGuidId>7c354dac-9e64-4a7e-b14c-c50721192773</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prihlaska-koncept-c0dbf975-cc4b-4c65-9201-06d773040039 > div.prihlaska-koncept-sub > div.buttons > a[name=&quot;Odstranit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div[2]/div[3]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>703dcac9-b78b-4a86-8b49-44fb48fd7aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Odstranit</value>
      <webElementGuid>c1301bd7-485f-4636-946e-a2fc1dadf236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>data-prihlaska-odstranit govuk-button govuk-button__large govuk-button--sec__warning</value>
      <webElementGuid>9ea18915-3b9d-4b62-8d0e-b11da2e78f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-module</name>
      <type>Main</type>
      <value>govuk-button</value>
      <webElementGuid>6fe84bcd-55f7-4cf2-9a37-243d472f4f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-guid</name>
      <type>Main</type>
      <value>c0dbf975-cc4b-4c65-9201-06d773040039</value>
      <webElementGuid>6d06e816-1a15-4757-94b0-d9e3d4baf169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>delete_outlineOdstrániť</value>
      <webElementGuid>8e089888-94d2-4002-be35-94a084cd560d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prihlaska-koncept-c0dbf975-cc4b-4c65-9201-06d773040039&quot;)/div[@class=&quot;prihlaska-koncept-sub&quot;]/div[@class=&quot;buttons&quot;]/a[@class=&quot;data-prihlaska-odstranit govuk-button govuk-button__large govuk-button--sec__warning&quot;]</value>
      <webElementGuid>65cc2c84-802a-4b7e-bc00-3450547bb93a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@name='Odstranit'])[2]</value>
      <webElementGuid>f6b36302-d6d5-4d3a-a6de-a7fb36e71615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prihlaska-koncept-c0dbf975-cc4b-4c65-9201-06d773040039']/div[2]/div[3]/a[2]</value>
      <webElementGuid>c85dcf5a-c6a9-425c-90a6-60d0881fe1b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokračovať v podaní prihlášky'])[2]/following::a[1]</value>
      <webElementGuid>3bfa685a-c76c-4fcb-a06c-c68961824fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vaša prihláška bola uložená ako koncept. Môžete pokračovať v jej vypĺňaní kedykoľvek.'])[2]/following::a[2]</value>
      <webElementGuid>9cd0ab21-8dbc-46e9-9248-f8eed337389c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items'])[1]/preceding::a[1]</value>
      <webElementGuid>2905275c-c64d-47ff-827c-da4a14b70484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[3]/a[2]</value>
      <webElementGuid>72634440-5eb2-4e24-b001-28f37cc4cf7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@name = 'Odstranit' and (text() = 'delete_outlineOdstrániť' or . = 'delete_outlineOdstrániť')]</value>
      <webElementGuid>10109cc7-369f-4c27-a6fc-c1f4f0f00e65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
