<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_delete_outlineOdstrni_5</name>
   <tag></tag>
   <elementGuidId>a852607e-7b3c-4d33-93f7-3610ad33d590</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prihlaskapodana-71f5b199-55de-41d4-b0f0-495731b57725 > div.prihlaska-podana > div.card_prihlasky_content > div.buttons > a.data-prihlaska-odstranit.govuk-button.govuk-button__large.govuk-button--sec__warning</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[9]/div/div[2]/div[2]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>724ec4dd-2b26-4691-b120-55ff52f72726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Odstranit</value>
      <webElementGuid>29d518b6-b126-4b5a-87d3-87468bfefffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>data-prihlaska-odstranit govuk-button govuk-button__large govuk-button--sec__warning</value>
      <webElementGuid>e5079e4d-eb87-498b-94a3-d095e1f40e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-module</name>
      <type>Main</type>
      <value>govuk-button</value>
      <webElementGuid>169359d9-a14f-44e9-ad7e-3d9e6823c6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-guid</name>
      <type>Main</type>
      <value>71f5b199-55de-41d4-b0f0-495731b57725</value>
      <webElementGuid>6e6a32f2-df25-404a-977f-5bec555e96f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>delete_outlineOdstrániť</value>
      <webElementGuid>17b98fae-eeff-4480-8e57-076ca6bcd155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prihlaskapodana-71f5b199-55de-41d4-b0f0-495731b57725&quot;)/div[@class=&quot;prihlaska-podana&quot;]/div[@class=&quot;card_prihlasky_content&quot;]/div[@class=&quot;buttons&quot;]/a[@class=&quot;data-prihlaska-odstranit govuk-button govuk-button__large govuk-button--sec__warning&quot;]</value>
      <webElementGuid>4bbe890e-3746-4ad8-b792-b6fe7db1d485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript: void(0);</value>
      <webElementGuid>dac92b09-e961-4016-a525-65c765b6cc5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prihlaskapodana-71f5b199-55de-41d4-b0f0-495731b57725']/div/div[3]/div/a[2]</value>
      <webElementGuid>cd6c080c-1b5b-4da9-8f5e-e8cb0328afd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail prihlášky'])[5]/following::a[1]</value>
      <webElementGuid>db769082-551f-45b2-a9a0-7efdee16625d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Potvrdiť nástup'])[5]/following::a[2]</value>
      <webElementGuid>afc11e7b-24bb-43e4-b84e-d4e854b5fac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Martin Tlačienka'])[4]/preceding::a[1]</value>
      <webElementGuid>be602e03-341b-4e04-bff6-7b8b025f7cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript: void(0);')])[10]</value>
      <webElementGuid>ff94cc40-d8cf-4036-b2da-e8255d3b1ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[3]/div/a[2]</value>
      <webElementGuid>4c17c56c-d938-4c3f-95ce-3b54e8960973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript: void(0);' and (text() = 'delete_outlineOdstrániť' or . = 'delete_outlineOdstrániť')]</value>
      <webElementGuid>bf2ed5e1-207c-40f8-979a-9aa3390ad5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@name='Odstranit'])[3]</value>
      <webElementGuid>8bb307dd-eee3-435c-bf3c-bead2f72f7f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prihlaska-koncept-f6a1d751-fef6-4c03-8aa4-1e7f890188e1']/div[2]/div[3]/a[2]</value>
      <webElementGuid>f1b3bb03-f6b7-4fcd-a7fc-cd47dae82e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokračovať v podaní prihlášky'])[3]/following::a[1]</value>
      <webElementGuid>cfecfd54-8483-44f0-b376-2ee31580017b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vaša prihláška bola uložená ako koncept. Môžete pokračovať v jej vypĺňaní kedykoľvek.'])[3]/following::a[2]</value>
      <webElementGuid>55ed90a7-0427-4c11-a5cc-d7b589b2d16a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eleonóra Schwarzwaldská'])[2]/preceding::a[1]</value>
      <webElementGuid>53167839-20ea-4f14-956b-b67559b9358b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[3]/a[2]</value>
      <webElementGuid>3aafe6ca-d6d5-43f4-8aea-f6d9b1fe7266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@name = 'Odstranit' and (text() = 'delete_outlineOdstrániť' or . = 'delete_outlineOdstrániť')]</value>
      <webElementGuid>12b536f5-47d3-4821-b947-6c6c8684cc20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
