<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Shlasm</name>
   <tag></tag>
   <elementGuidId>7acde545-fdb2-49d2-abb4-61d096365a1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Súhlasím')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1a1dd529-ce08-44fb-8903-e58e5b5c87cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button green govuk-!-margin-bottom-0 button</value>
      <webElementGuid>35992b3d-1699-4350-b7a2-7e0bbe97d6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>23ada8c9-42b2-44a8-89f1-bb5f06b04b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Súhlasím</value>
      <webElementGuid>f96d51cc-bd3e-4222-b2bd-d30c17cc2422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;govuk-frontend-supported&quot;]/div[@class=&quot;page-overlay fade-in-500&quot;]/div[@class=&quot;cookie-wrapper&quot;]/div[@class=&quot;box&quot;]/a[@class=&quot;govuk-button green govuk-!-margin-bottom-0 button&quot;]</value>
      <webElementGuid>2e1bfa07-9dcc-4d44-8bbf-6ac8508c86aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Súhlasím')]</value>
      <webElementGuid>f3335dc9-1fc7-4b8a-8c2c-ca151ee16ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Potvrdenie súhlasu s cookies'])[1]/following::a[1]</value>
      <webElementGuid>4199d5b6-5d93-482b-a3ae-65bba0f18eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013 - 2025, eprihlasky.iedu.sk'])[1]/following::a[3]</value>
      <webElementGuid>fe4845d3-903c-49a4-bf41-382811685537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nesúhlasím'])[1]/preceding::a[1]</value>
      <webElementGuid>250f6bd9-487c-4900-a732-d6e27b4517c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Súhlasím']/parent::*</value>
      <webElementGuid>6228fc69-15f7-451c-bb2d-a3cce7c79ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a[2]</value>
      <webElementGuid>6a76eb0e-7b18-4830-be79-c93ad2d590b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Súhlasím' or . = 'Súhlasím')]</value>
      <webElementGuid>96d36d7f-fd83-4fb9-a16d-d13af9a837fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
