<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(nepovinn)_select-TypPrilohySelect</name>
   <tag></tag>
   <elementGuidId>b15a6551-3877-424b-a6ec-8a76f8db1525</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select-TypPrilohySelect']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select-TypPrilohySelect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>824aa866-ccd1-43e7-955b-3c82b3b82374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select placeholder</value>
      <webElementGuid>e00ca4f3-b353-4be6-a69d-df00b722a826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3d757c7f-70ef-420e-9724-2189ff30fa8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-TypPrilohySelect</value>
      <webElementGuid>07c1d5d2-7663-48e2-954c-2e7f07510e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vyberte zo zoznamuRozhodnutie súduPotvrdenie od všeobecného lekára zákonného zástupcu (ktorý nie je schopný sa podpísať)Čestné vyhlásenie zákonného zástupcuOdporúčanie všeobecného lekára pre deti a dorastInáPísomné vyhlásenie k podaniam týkajúcich sa výchovy a vzdelávania, o ktorých sa rozhoduje v správnom konaníPotvrdenie o zdravotnej spôsobilosti (materská škola)Správa z diagnostického vyšetrenia</value>
      <webElementGuid>24825523-5f68-4414-afba-5c62e9d93190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-TypPrilohySelect&quot;)</value>
      <webElementGuid>6a025f4f-5b4a-4ad2-84e1-bab0ec02eac6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select-TypPrilohySelect']</value>
      <webElementGuid>df850d64-4333-4ef8-ab35-761f0ae81ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TypPrilohySelect']/div/div[2]/select</value>
      <webElementGuid>3b0b9b57-fd65-48ae-a377-71a15405eca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(nepovinné)'])[1]/following::select[1]</value>
      <webElementGuid>770eb075-b196-4797-92de-50239e080bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Typ prílohy'])[1]/following::select[1]</value>
      <webElementGuid>dd49e986-5c53-4ca7-993a-141ec298201e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[3]/preceding::select[1]</value>
      <webElementGuid>dfbab06c-8c4a-4384-896c-aa86f2203909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtre:'])[1]/preceding::select[1]</value>
      <webElementGuid>a3c51524-9699-450f-9eca-fe4b1e4e276f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>8613f1b7-5f7f-4731-8b36-38fb272b57c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @id = 'select-TypPrilohySelect' and (text() = 'Vyberte zo zoznamuRozhodnutie súduPotvrdenie od všeobecného lekára zákonného zástupcu (ktorý nie je schopný sa podpísať)Čestné vyhlásenie zákonného zástupcuOdporúčanie všeobecného lekára pre deti a dorastInáPísomné vyhlásenie k podaniam týkajúcich sa výchovy a vzdelávania, o ktorých sa rozhoduje v správnom konaníPotvrdenie o zdravotnej spôsobilosti (materská škola)Správa z diagnostického vyšetrenia' or . = 'Vyberte zo zoznamuRozhodnutie súduPotvrdenie od všeobecného lekára zákonného zástupcu (ktorý nie je schopný sa podpísať)Čestné vyhlásenie zákonného zástupcuOdporúčanie všeobecného lekára pre deti a dorastInáPísomné vyhlásenie k podaniam týkajúcich sa výchovy a vzdelávania, o ktorých sa rozhoduje v správnom konaníPotvrdenie o zdravotnej spôsobilosti (materská škola)Správa z diagnostického vyšetrenia')]</value>
      <webElementGuid>54c9a3de-3ce6-495a-bb54-d96538514f33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
