<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Dvod_data-prihlaska-odvolat-ziadost _a29034</name>
   <tag></tag>
   <elementGuidId>d8214403-a69a-4ad2-8015-11e12e45fd32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(text(),'Odvolať žiadosť')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fb90e1c3-a39b-48f8-8c32-12c6b7f74058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>data-prihlaska-odvolat-ziadost govuk-button govuk-button__large govuk-!-margin-bottom-0 </value>
      <webElementGuid>484ca19f-cb23-487d-8181-e0d8f3902a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-module</name>
      <type>Main</type>
      <value>govuk-button</value>
      <webElementGuid>82b8a241-5986-4915-bdd8-5312d0646286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sprava-guid</name>
      <type>Main</type>
      <value>4b70f470-b4b7-4299-a3c1-10448ae5114e</value>
      <webElementGuid>0865dfb7-641f-46d4-9aba-35200e535e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-guid</name>
      <type>Main</type>
      <value>d18ab430-f81e-4ed0-8f94-4cb00769ef6e</value>
      <webElementGuid>e9d6f35a-e15c-4693-b01c-d870daaf1f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>b78b874d-019c-416a-b2b6-ec3d9fd66f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Odvolať žiadosť</value>
      <webElementGuid>df6841ca-6ff9-4cd9-9a3c-4ac70d4dd4ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skoly&quot;)/div[@class=&quot;panel-content&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;sprava-item&quot;]/div[@class=&quot;sprava-body&quot;]/div[@class=&quot;sprava-panel&quot;]/button[@class=&quot;data-prihlaska-odvolat-ziadost govuk-button govuk-button__large govuk-!-margin-bottom-0&quot;]</value>
      <webElementGuid>1778c5f5-8de4-4f11-b4ee-71f45f5dc1e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='skoly']/div[2]/div[7]/div/div[2]/div/button</value>
      <webElementGuid>e456b5a6-e8f8-47a4-815b-c328f6d7cd8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dôvod:'])[1]/following::button[1]</value>
      <webElementGuid>f6777332-ebe8-4b5c-8122-34b4ce77f3c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Čestné vyhlásenie zákonného zástupcu'])[1]/following::button[1]</value>
      <webElementGuid>0d82a49d-801e-4d24-aae2-df82e232431e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info'])[7]/preceding::button[1]</value>
      <webElementGuid>c1d3f396-9104-4489-aa47-7703e8948ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Odvolať žiadosť']/parent::*</value>
      <webElementGuid>5ffac3bb-d38f-4519-b0f5-caa679488a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div/button</value>
      <webElementGuid>f14f80e4-c02a-4061-b524-32a0f3dd1f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@href = 'javascript:void(0);' and (text() = 'Odvolať žiadosť' or . = 'Odvolať žiadosť')]</value>
      <webElementGuid>1318b8c2-1ffc-4101-9216-86725b4a2bc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
