<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Stav prihlky_skola-status-badge red</name>
   <tag></tag>
   <elementGuidId>8699a0b0-9460-4116-b792-0cdc849e22a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.skola-status-badge.red</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'skola-status-badge red']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='skoly']/div[2]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4c4eb96c-aed7-46e1-b9ef-609f0df17db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>skola-status-badge red</value>
      <webElementGuid>b2bba1a3-3ff7-4de8-bb35-2b3ff757c033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Neúplná</value>
      <webElementGuid>07b8d099-4ced-44a6-9d28-7651b21b5d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skoly&quot;)/div[@class=&quot;panel-content&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;skola-status-badge red&quot;]</value>
      <webElementGuid>e0de6a7c-4416-4d25-9d02-78ccea8caed5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='skoly']/div[2]/div[2]/div[2]</value>
      <webElementGuid>60c7c7c6-78bf-494c-808d-19d22cd3c6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stav prihlášky'])[2]/following::div[1]</value>
      <webElementGuid>10767ef7-1a56-430a-ac15-da5900e2ccc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EDUID školy'])[1]/preceding::div[1]</value>
      <webElementGuid>2e7da292-5298-4309-ac31-ec3e288cb38f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov školy'])[1]/preceding::div[4]</value>
      <webElementGuid>38b6429b-3807-4b49-9490-a4ad8994242c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div[2]/div[2]</value>
      <webElementGuid>fbb02a29-1a3b-4366-b8bf-b7937172046e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Neúplná' or . = 'Neúplná')]</value>
      <webElementGuid>9bc8ae05-0f96-49f9-b9e0-c5c2c9654b11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
