<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Povinn prihlky na prijatie, ale kvli _9491e4</name>
   <tag></tag>
   <elementGuidId>d30df2fa-5a51-4214-8b09-5d343b103c79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fulltext-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fulltext-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02e38ba0-e725-459c-ace7-ed92ca5abd39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fulltext-input</value>
      <webElementGuid>64bc0288-9640-4249-9910-77a4274770d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c408775-7967-495f-b1fd-530dbd9cc044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input vyhladavanie-input</value>
      <webElementGuid>08609b73-0507-475e-9133-ce0778fc8169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Vyhľadávanie v meno, priezvisko, priezvisko zákonného zástupcu č. 1, poznámka školy</value>
      <webElementGuid>2cf2f999-31eb-4e0b-836b-0f5342aaf3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder-desktop</name>
      <type>Main</type>
      <value>Vyhľadávanie v meno, priezvisko, priezvisko zákonného zástupcu č. 1, poznámka školy</value>
      <webElementGuid>10d559d2-5af3-43ab-ac56-6077978f6d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder-mobile</name>
      <type>Main</type>
      <value>Vyhľadávanie v prihláškach</value>
      <webElementGuid>34173e0b-e61f-42b1-a322-82ae7f11289b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fulltext-input&quot;)</value>
      <webElementGuid>6bcd7c19-33fc-4be5-a3a4-c2c889f26336</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fulltext-input']</value>
      <webElementGuid>7257e7a3-af85-47e1-9c59-53be3a93efd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fulltext-input-wrapper']/div/input</value>
      <webElementGuid>cb508e37-34bf-4914-8c3f-07e963743931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>0edb9fd3-6fa6-458a-bf46-61ea75faffcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fulltext-input' and @type = 'text' and @placeholder = 'Vyhľadávanie v meno, priezvisko, priezvisko zákonného zástupcu č. 1, poznámka školy']</value>
      <webElementGuid>951870f7-4697-41e1-acaa-353ce5fc7583</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
