<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_addPrida prihlku</name>
   <tag></tag>
   <elementGuidId>6ac9dfbd-c7fe-4bad-9b87-50f98e3992c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-vytvorit-prihlasku</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn-vytvorit-prihlasku']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0d63b494-2084-4c21-8e32-4fdaf2a3c065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button riaditel-sprava-prihlasok-heading-button</value>
      <webElementGuid>6a1accd2-1b51-4d8b-aaaa-81c434366334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-vytvorit-prihlasku</value>
      <webElementGuid>37f6296f-cb9d-445f-9239-a15c06f87ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4bb1153b-9378-48dc-91f4-f74373f907cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Vytvoriť prihlášku</value>
      <webElementGuid>e3b63ad1-fd27-43f0-9d38-1ace7d50f204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-module</name>
      <type>Main</type>
      <value>govuk-button</value>
      <webElementGuid>238cdc24-231b-4ed1-a814-cc002bb306c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Ziadost</value>
      <webElementGuid>e5bf2a82-3464-44a3-8b69-40083005205d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>addPridať prihlášku</value>
      <webElementGuid>7a0c5a86-fe15-4bc4-b53c-5e202ca45048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-vytvorit-prihlasku&quot;)</value>
      <webElementGuid>0525dec6-22ae-440f-9fa0-395311873033</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn-vytvorit-prihlasku']</value>
      <webElementGuid>a687a4a9-40a2-49ef-887b-9b67bd437252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sub-riaditel-prihlasky']/div[3]/div/a</value>
      <webElementGuid>75a0a4ec-c97d-4bad-8dfe-9e2cfb8d11e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export do xlsx'])[1]/following::a[1]</value>
      <webElementGuid>7eb925aa-b038-4611-bf40-b622a1ed2646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Povinné prihlášky na prijatie'])[1]/preceding::a[1]</value>
      <webElementGuid>88eaf088-0855-4be1-9b5a-3c30293e7a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Povinné prihlášky na prijatie, ale kvôli nedostatku miest ich nemôžete prijať'])[1]/preceding::a[1]</value>
      <webElementGuid>ad84b14f-1ddd-4f21-9c94-a6c200e8745b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pridať prihlášku']/parent::*</value>
      <webElementGuid>007608dc-9813-4dbf-adc1-4b47cc3ea457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Ziadost')]</value>
      <webElementGuid>4f765e4d-ae44-46ff-a74f-38b04a723d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/a</value>
      <webElementGuid>8e177f38-a526-42f3-8c2a-e50d909e4724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn-vytvorit-prihlasku' and @type = 'submit' and @name = 'Vytvoriť prihlášku' and @href = '/Ziadost' and (text() = 'addPridať prihlášku' or . = 'addPridať prihlášku')]</value>
      <webElementGuid>9203de9c-25fa-4a22-93f1-0eb64ed113c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
