<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-denPodania</name>
   <tag></tag>
   <elementGuidId>6056535e-e5d2-4a7d-84be-a9f762e52c7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-denPodania</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-denPodania']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7da999d4-62f3-4bca-921b-9d40c6bbb5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>37caae0f-4db7-4286-8242-1da8ec5860a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c774ce07-5f36-465e-ae1c-552789ff3c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-denPodania</value>
      <webElementGuid>5c442a5f-e2f8-4658-83c6-4ba5c593142a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-denPodania&quot;)</value>
      <webElementGuid>d7e81c72-f70d-4db7-b1a2-9d4e7455c8cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-denPodania']</value>
      <webElementGuid>dabc6602-6610-40a0-91a0-ba48c0b78d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='denPodania']/div/div[2]/input</value>
      <webElementGuid>96928d97-0103-40cc-8cb9-288133a3e917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/input</value>
      <webElementGuid>aa723a4d-8a45-4db2-bb66-64cc93d61e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-denPodania']</value>
      <webElementGuid>aa9377bc-66aa-479a-8b6f-0045d3251776</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
