<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Odhlsi</name>
   <tag></tag>
   <elementGuidId>748cad79-2e97-447b-8fce-50eda629c9c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logoutBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='logoutBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4081cfe7-a50d-4a90-8a02-c7bffd7e24e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logoutBtn</value>
      <webElementGuid>7683e9fb-2047-4dd9-834e-a189695d7ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/logout?returnurl=%2F</value>
      <webElementGuid>cd317e32-e3f6-48bd-9d75-a2ff9ebfc19a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Odhlásiť</value>
      <webElementGuid>82bd0857-93d5-4ae5-9ff9-582003d0ccda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logoutBtn&quot;)</value>
      <webElementGuid>6795bc9e-a9d2-4d03-a181-18f5789cb129</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='logoutBtn']</value>
      <webElementGuid>a72560cb-2ec5-4ed9-a2f9-b0d7b04f4aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Odhlásiť')]</value>
      <webElementGuid>0a65e513-bd07-4ccb-9728-689262cde7e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oznámenia'])[1]/following::a[1]</value>
      <webElementGuid>adf9be44-f4fa-4154-b9d5-6f2df2762e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Môj profil'])[1]/following::a[2]</value>
      <webElementGuid>34b0d09d-4a3c-4bb4-9877-4b044bc38d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[2]/preceding::a[1]</value>
      <webElementGuid>802a9cbd-b418-49d3-8e96-2ce4c175fe84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prihlášky a rozhodnutia'])[1]/preceding::a[1]</value>
      <webElementGuid>29d0869a-59c9-4d8a-a9a8-7f59d1d33c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Odhlásiť']/parent::*</value>
      <webElementGuid>d28ec512-4997-4dfb-9d41-d7da831da77b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/logout?returnurl=%2F')]</value>
      <webElementGuid>9a70dbbf-9207-4f4d-bbb3-4af04b77d6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>90979f88-6100-4857-835c-4b1a31e87bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'logoutBtn' and @href = '/logout?returnurl=%2F' and (text() = 'Odhlásiť' or . = 'Odhlásiť')]</value>
      <webElementGuid>e97e7e36-282c-4fa1-ad03-9dc0297cae6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
