<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Akcia_checkmark</name>
   <tag></tag>
   <elementGuidId>04e1b7e9-eb84-4da2-bdea-286b12ec9185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.checkmark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div[5]/div[2]/div[2]/div/div/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;select-1d9bd68d-c055-4f27-b211-87c861c5043d&quot;)/div[@class=&quot;govuk-form-group checkbox-control&quot;]/span[@class=&quot;checkmark&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>41f0030d-e255-4e98-a320-d76f7de05ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>49911eb2-a16c-4b23-9e5e-d0dd2eb34540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-guid</name>
      <type>Main</type>
      <value>1d9bd68d-c055-4f27-b211-87c861c5043d</value>
      <webElementGuid>08f8d608-1c10-42fa-b784-908591262365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-1d9bd68d-c055-4f27-b211-87c861c5043d&quot;)/div[@class=&quot;govuk-form-group checkbox-control&quot;]/span[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>43ee98ba-a415-49e2-adee-8c4c27bccf65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select-1d9bd68d-c055-4f27-b211-87c861c5043d']/div/span</value>
      <webElementGuid>e284f80c-9050-4185-9fbb-d4e34a218e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[5]/div[2]/div[2]/div/div/span</value>
      <webElementGuid>2f8e241a-548d-4519-b99a-9706326ddfdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
