<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Multifunkn vonkajie ihrisko_radioGrou_7146f4</name>
   <tag></tag>
   <elementGuidId>fc332d34-b84d-40a7-8100-211c7d3b8663</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radioGroup-MS_VonV_option_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radioGroup-MS_VonV_option_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7910314-38ca-4c9f-bd1c-cf5683e6e72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>e55dd78e-68cd-4437-b467-21b1b991411a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radioGroup-MS_VonV_option_3</value>
      <webElementGuid>48344680-d0c2-48e2-8702-a382f9123870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radioGroup-MS_VonV</value>
      <webElementGuid>e8b7a043-f814-447a-b85f-dc0969d547f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>97aefb18-d63d-4764-a531-6c33370b1d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>VonV_5</value>
      <webElementGuid>bc5de32a-7889-4aa9-8346-ce6685daa357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radioGroup-MS_VonV_option_3&quot;)</value>
      <webElementGuid>40da629f-8578-439c-b6cf-0ef5874b25f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radioGroup-MS_VonV_option_3']</value>
      <webElementGuid>0f0038f9-09c2-4869-bc40-ff58dcb4c61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radioGroup-MS_VonV']/div/fieldset/div[3]/div[4]/input</value>
      <webElementGuid>78e5bf30-2fc3-4ce4-adc6-a26984abe4ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/fieldset/div[3]/div[4]/input</value>
      <webElementGuid>83d35311-cfd9-4675-8bba-fbd488935814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'radioGroup-MS_VonV_option_3' and @name = 'radioGroup-MS_VonV' and @type = 'radio']</value>
      <webElementGuid>c1af49d7-e2ff-4e4f-96c4-61f3caf58030</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
