<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Prstupn poschodia, toalety a jedle_ra_8cdb32</name>
   <tag></tag>
   <elementGuidId>7d5ed028-19ed-489e-be93-32c5baece8f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radioGroup-MS_DebS_option_5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radioGroup-MS_DebS_option_5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e8d2f8f-2185-4d36-a50e-8cb44507e3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>e790c822-72e6-429d-af1c-67ada210505e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radioGroup-MS_DebS_option_5</value>
      <webElementGuid>53d842b2-d1c3-4604-a734-793ba5c336d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radioGroup-MS_DebS</value>
      <webElementGuid>e8e7a232-0405-46e9-b07e-5a25561b5a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d834bf95-b547-48d7-aafe-30768ba4ad06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>DebS_6</value>
      <webElementGuid>51b7180a-182a-427e-bf8a-96f90e7a751d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radioGroup-MS_DebS_option_5&quot;)</value>
      <webElementGuid>f2efcbae-0de4-48ec-b999-ceba127468e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radioGroup-MS_DebS_option_5']</value>
      <webElementGuid>bf4eac27-2b4b-4726-aaf8-421ef2e43efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radioGroup-MS_DebS']/div/fieldset/div[3]/div[6]/input</value>
      <webElementGuid>6aaade6e-d864-4481-b2f4-4a415e4ec8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>3498d272-9f5b-490e-be6a-9734b5861b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'radioGroup-MS_DebS_option_5' and @name = 'radioGroup-MS_DebS' and @type = 'radio']</value>
      <webElementGuid>9b162d48-9e41-406c-8188-b7f160e4d491</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
