<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Telefnne slo_profil-tel</name>
   <tag></tag>
   <elementGuidId>5b6d0d8e-fa4d-4f87-859d-6b47a170cc34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profil-tel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='profil-tel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e747d34a-9e5a-4552-808d-161f62ab1879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profil-tel</value>
      <webElementGuid>ccacf14c-8365-4351-b4d4-35d238aa5aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>9b4b1430-f9cb-4629-83f8-2200cc75a1f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profil-tel&quot;)</value>
      <webElementGuid>1adcb59c-e4ff-4145-a29d-642372b04c6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='profil-tel']</value>
      <webElementGuid>78986399-5747-4bde-af5c-fd3608be16b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profil']/div[2]/div[4]/div[2]</value>
      <webElementGuid>b1e57448-a9d0-410a-8ed1-e44ef814b2f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telefónne číslo'])[1]/following::div[1]</value>
      <webElementGuid>cbc9e014-3438-4798-8761-db82218712fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum narodenia'])[1]/following::div[4]</value>
      <webElementGuid>db93d129-daf3-4ad0-b252-2ddf74703858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kontaktný e-mail'])[1]/preceding::div[1]</value>
      <webElementGuid>89e6274b-4578-45f5-b1a8-da5ab8993982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='aejlac645i@tiffincrane.com'])[1]/preceding::div[2]</value>
      <webElementGuid>b46b1878-a1af-4025-8f53-2a57304e9fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]</value>
      <webElementGuid>9a6951ca-bf11-4b8e-9f13-ccd5aa601968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'profil-tel' and (text() = '-' or . = '-')]</value>
      <webElementGuid>3b9e8b1d-9740-4ed7-9ad3-bd26cd55e1eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
