<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Odosla na stredn koly_btn-zrusit-prihlasku</name>
   <tag></tag>
   <elementGuidId>698e1f59-568b-4ae9-a123-d67979dd738a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-zrusit-prihlasku</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-zrusit-prihlasku']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eedb8138-31d5-42f8-a6cb-93a231a0c77f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-zrusit-prihlasku</value>
      <webElementGuid>f2593320-e8cb-44b6-8997-5f13e6cc7ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button zrusit-prihlasku</value>
      <webElementGuid>ea0ae88d-4f14-4c7d-ab02-a575aaa7d65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d2ade09a-4ae6-4cef-88ae-6274a9d2ff32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Zrušiť prihlášku</value>
      <webElementGuid>ecf6af2a-3c3d-46e1-babb-7d917603a88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-module</name>
      <type>Main</type>
      <value>govuk-button</value>
      <webElementGuid>14c7e454-45cb-4e73-b8dc-cc627f7a97a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Zrušiť prihlášku</value>
      <webElementGuid>7ca1f34f-bf5f-4795-ad4e-8d5fad856d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-zrusit-prihlasku&quot;)</value>
      <webElementGuid>170f2dbb-edeb-4d3c-878f-8626f7ce4369</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-zrusit-prihlasku']</value>
      <webElementGuid>eb2d7b06-9663-48f2-99fd-1de9f32d99c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='detail-prihlasky-riad-SS-content']/div[2]/button[6]</value>
      <webElementGuid>af697a30-df27-404c-91e7-05223339170a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odoslať na stredné školy'])[1]/following::button[1]</value>
      <webElementGuid>5bfeac8e-7263-4699-bc89-0b7af71e127d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zmeniť aktívnu prihlášku'])[1]/following::button[2]</value>
      <webElementGuid>3331d367-7efc-471d-ae06-768545108120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duplicitné prihlášky'])[1]/preceding::button[1]</value>
      <webElementGuid>0b406272-d3f4-4474-a5c3-132f91830c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identifikátor prihlášky'])[1]/preceding::button[1]</value>
      <webElementGuid>4f012d5c-ee25-456a-9050-799d4c5001c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Zrušiť prihlášku']/parent::*</value>
      <webElementGuid>f3bb6ff5-bd59-4ccd-a66f-42fa7cf8365b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[6]</value>
      <webElementGuid>c4615982-eeda-448d-9203-f90fa4aacb5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-zrusit-prihlasku' and @type = 'submit' and @name = 'Zrušiť prihlášku' and (text() = 'Zrušiť prihlášku' or . = 'Zrušiť prihlášku')]</value>
      <webElementGuid>57ff8ffb-d0b3-4002-a742-ba40519bea32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
