<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Prstupn przemie a toalety_radioGroup-_dcd5ca</name>
   <tag></tag>
   <elementGuidId>6d0b8bc3-c574-4be1-876d-de3bdfdef0c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radioGroup-ZS_DebS_option_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radioGroup-ZS_DebS_option_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c359655f-6d0d-4f63-9702-9dd90aa8e000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>4afa4561-4e15-4220-b6c1-7eca3399dd0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radioGroup-ZS_DebS_option_3</value>
      <webElementGuid>83e6d0b3-6559-4cd0-88da-eeea89373bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radioGroup-ZS_DebS</value>
      <webElementGuid>9a353b58-4988-4a80-8dbc-ea1619bc550e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>dada654f-deed-495e-ad2a-94c37db8dcdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>DebS_4</value>
      <webElementGuid>e23bc824-cfdc-4e62-9fd2-6bd487556946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radioGroup-ZS_DebS_option_3&quot;)</value>
      <webElementGuid>0869b56c-7812-40c1-9719-6c1361f1be31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radioGroup-ZS_DebS_option_3']</value>
      <webElementGuid>bfbab499-5f92-45ad-a44f-50efd6449fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radioGroup-ZS_DebS']/div/fieldset/div[3]/div[4]/input</value>
      <webElementGuid>d436b2ac-b473-41e5-acf1-61b05aeaf26e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>cde25c11-7bcd-4ff8-9b34-455dcec5a516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'radioGroup-ZS_DebS_option_3' and @name = 'radioGroup-ZS_DebS' and @type = 'radio']</value>
      <webElementGuid>e540fd68-9763-4cb9-ad55-a53214870b30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
