<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_radioGroup-ZS_DigR_option_2</name>
   <tag></tag>
   <elementGuidId>64c9fa44-c69a-45b8-a6dc-7d75f712e2e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radioGroup-ZS_DigR_option_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radioGroup-ZS_DigR_option_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c84eaf11-f5bb-469d-89c8-6d49bb60d5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>4c60a3b5-92f7-44f8-89d1-7b7a9a5572e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radioGroup-ZS_DigR_option_2</value>
      <webElementGuid>2aeec1bb-786b-4276-9b8a-032de7c6a777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radioGroup-ZS_DigR</value>
      <webElementGuid>55d84a47-4f09-40d7-8ea0-237526f9e68a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>bf2a2eef-cd46-435d-9f6e-7b4f4bde1797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>DigR_3</value>
      <webElementGuid>27990895-9bdd-429e-aaf8-2954fcf6afe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radioGroup-ZS_DigR_option_2&quot;)</value>
      <webElementGuid>d9ece5b6-b2f6-49c7-b95d-75f3e92422a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radioGroup-ZS_DigR_option_2']</value>
      <webElementGuid>46f72cc1-fed4-470b-a9f1-f688ccf133e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radioGroup-ZS_DigR']/div/fieldset/div[3]/div[3]/input</value>
      <webElementGuid>e8431e03-3ac5-45ad-a5f0-5aa17fd71c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/fieldset/div[3]/div[3]/input</value>
      <webElementGuid>7c598cd1-6b11-4e4c-92cc-025557ab2574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'radioGroup-ZS_DigR_option_2' and @name = 'radioGroup-ZS_DigR' and @type = 'radio']</value>
      <webElementGuid>86ead116-8174-4e98-9b02-32d42dfe405b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
