<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telocvia do 400 m2_radioGroup-ZS_VnuV_172c64</name>
   <tag></tag>
   <elementGuidId>2d04da2c-3ecc-49f7-8bcf-b802970bcd3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radioGroup-ZS_VnuV_option_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radioGroup-ZS_VnuV_option_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fbc5a00e-b276-4ea4-a954-fee0853360cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>72b88f27-2f4a-47e2-9273-3b8a2d19b8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radioGroup-ZS_VnuV_option_3</value>
      <webElementGuid>854afff2-ba06-435a-92eb-0e9c61308ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radioGroup-ZS_VnuV</value>
      <webElementGuid>f0c87cda-1547-4966-b401-1b395e086ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9e08ea2c-25ac-40b8-a63f-7bae0f9ed72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>VnuV_4</value>
      <webElementGuid>e5ab7afd-3ad9-4b51-84ab-7836dd39f154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radioGroup-ZS_VnuV_option_3&quot;)</value>
      <webElementGuid>f88a3930-2b2d-4478-a4fc-d23a3e7437b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radioGroup-ZS_VnuV_option_3']</value>
      <webElementGuid>dde54f4e-5ec9-40ef-aee6-f75b70c89d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radioGroup-ZS_VnuV']/div/fieldset/div[3]/div[4]/input</value>
      <webElementGuid>eff79f48-2b88-46a2-b736-38e8ea82341d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/fieldset/div[3]/div[4]/input</value>
      <webElementGuid>27107b2a-b598-4513-bb8a-94d8f2c43eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'radioGroup-ZS_VnuV_option_3' and @name = 'radioGroup-ZS_VnuV' and @type = 'radio']</value>
      <webElementGuid>9484c747-3d10-42e6-bd40-38fefd923f51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
