<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_radioGroup-ZS_DigR_option_3</name>
   <tag></tag>
   <elementGuidId>8d877629-7483-4f26-a654-906732b685b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radioGroup-ZS_DigR_option_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radioGroup-ZS_DigR_option_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ab4a88c-6359-4cb6-986a-d6d66d798b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>8a12ef87-af09-42a9-9677-165b2a425391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radioGroup-ZS_DigR_option_3</value>
      <webElementGuid>e1dd8ff2-2e50-47a0-bee4-a6f8b609d873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radioGroup-ZS_DigR</value>
      <webElementGuid>a29767a0-d836-4d26-8a7b-ae7d78e44e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d3d33bb0-7c16-4e3b-ae4a-02310f0673dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>DigR_4</value>
      <webElementGuid>ee102873-db26-4ae9-a069-92708d487a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radioGroup-ZS_DigR_option_3&quot;)</value>
      <webElementGuid>625a3223-5e20-4aee-b163-9759777216ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radioGroup-ZS_DigR_option_3']</value>
      <webElementGuid>462cfe74-5abc-41a8-b9b5-25d771c53c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radioGroup-ZS_DigR']/div/fieldset/div[3]/div[4]/input</value>
      <webElementGuid>ba0b6d0d-c54e-47dd-beb8-4abc075e0a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/fieldset/div[3]/div[4]/input</value>
      <webElementGuid>8973dcb7-3a0f-429e-8057-e72cbe67b50b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'radioGroup-ZS_DigR_option_3' and @name = 'radioGroup-ZS_DigR' and @type = 'radio']</value>
      <webElementGuid>2fa740e2-6b5e-4cdb-a3ed-5eda52f13397</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
