<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bez vonkajieho ihriska_radioGroup-ZS__0cbda3</name>
   <tag></tag>
   <elementGuidId>d8999957-b741-48e8-b810-07414b30b775</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radioGroup-ZS_VonV_option_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radioGroup-ZS_VonV_option_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>058b2968-d546-4ee2-a498-e4540de4dc73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>5aabce5d-7417-43ed-b4fe-38b8c3d4065d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radioGroup-ZS_VonV_option_1</value>
      <webElementGuid>25187a1f-12f9-41ae-9cc7-8a36a88b7005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radioGroup-ZS_VonV</value>
      <webElementGuid>e1acfb78-1595-4030-b68b-f55ad7d78601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2d868919-c405-4754-84d3-c4c63280297c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>VonV_2</value>
      <webElementGuid>83ba39c5-d85f-4cf5-83d6-72c514c65d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radioGroup-ZS_VonV_option_1&quot;)</value>
      <webElementGuid>d4d6c3b4-4ba9-4d18-b444-734656108381</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radioGroup-ZS_VonV_option_1']</value>
      <webElementGuid>a29bb67f-ffce-454b-9556-3910e449266b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radioGroup-ZS_VonV']/div/fieldset/div[3]/div[2]/input</value>
      <webElementGuid>2fcc706e-769d-4158-ac35-502c0fcd3eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/fieldset/div[3]/div[2]/input</value>
      <webElementGuid>bd295db6-99a6-47b4-9035-7a514b451a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'radioGroup-ZS_VonV_option_1' and @name = 'radioGroup-ZS_VonV' and @type = 'radio']</value>
      <webElementGuid>b3015781-55be-4847-9494-d88a92ec1231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
