<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Menu_inicialy-osoby-header</name>
   <tag></tag>
   <elementGuidId>44674f39-bc77-4784-bf2e-0f1a7b9dee32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inicialy-osoby-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='inicialy-osoby-header']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e8c24baa-e0e2-4f4d-af7c-fbff897bb5c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inicialy-osoby-header</value>
      <webElementGuid>1459d3fc-4796-43ad-a6aa-e75fcf918abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JN</value>
      <webElementGuid>fcea8d63-0a8e-463d-b6ca-b85be0a1e437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inicialy-osoby-header&quot;)</value>
      <webElementGuid>9601d28e-f413-43e6-9118-2beb86864b41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='inicialy-osoby-header']</value>
      <webElementGuid>fa85aad1-3524-449f-9eb6-f20b99cd8262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/following::span[4]</value>
      <webElementGuid>0e1decce-2abe-4783-877e-ffa0468855f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elektronické prihlášky do škôl'])[1]/following::span[5]</value>
      <webElementGuid>5fbfdccf-c66b-4acf-98bc-94013cf0d0c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Môj profil'])[1]/preceding::span[1]</value>
      <webElementGuid>1b307db8-09cc-47e1-b303-ad2cb9ff7e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oznámenia'])[1]/preceding::span[1]</value>
      <webElementGuid>0bf4d498-0a39-47ab-ab37-0b81a6805831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='JN']/parent::*</value>
      <webElementGuid>46845a0a-a06c-44b9-a159-68c3948a479d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/span</value>
      <webElementGuid>4cba8ff4-1f82-4d1d-aa3d-dfa7f50250b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'inicialy-osoby-header' and (text() = 'JN' or . = 'JN')]</value>
      <webElementGuid>a5fe4300-58f0-41e0-8bb4-64d296305fc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
