<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Zkladn vonkajie ihrisko_btn-zavriet _3c66e8</name>
   <tag></tag>
   <elementGuidId>43d4ab78-c809-4fb4-94df-1fb778216409</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.modal.profil-skoly-modal > div.buttons-container > button.btn-zavriet.govuk-button.govuk-button--sec.left-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='najst-skolu-content']/div[7]/div/div[3]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b51781e6-5a61-4632-803b-864a84caada6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-zavriet govuk-button govuk-button--sec left-button</value>
      <webElementGuid>333aff35-fa51-4e1e-ba63-aa9117c294d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d7034637-8c9e-4196-81c8-c971302f2fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Zavrieť</value>
      <webElementGuid>052a0b05-668a-4296-acff-b59525df826b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;najst-skolu-content&quot;)/div[@class=&quot;modal-wrapper profil-skoly-modal-wrapper&quot;]/div[@class=&quot;modal profil-skoly-modal&quot;]/div[@class=&quot;buttons-container&quot;]/button[@class=&quot;btn-zavriet govuk-button govuk-button--sec left-button&quot;]</value>
      <webElementGuid>a254247d-3e9c-434f-b72b-6bc7a9b69ab3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='najst-skolu-content']/div[7]/div/div[3]/button</value>
      <webElementGuid>6ecb83a4-3857-48e2-bbae-d77df3be60ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Základné vonkajšie ihrisko'])[1]/following::button[1]</value>
      <webElementGuid>864afacf-14c6-4d1d-967c-581ef67d5110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stupeň vonkajšieho športového vybavenia a infraštruktúry v areáli školy'])[1]/following::button[1]</value>
      <webElementGuid>3fb3e365-b00e-488f-97db-3a94cbddb5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boli tieto informácie pre vás užitočné?'])[1]/preceding::button[1]</value>
      <webElementGuid>34d322fb-bedf-48bd-a918-0c5bc20fc4b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Áno'])[1]/preceding::button[1]</value>
      <webElementGuid>389e53ac-e899-43a2-ab0e-0bc3a141a75f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[3]/button</value>
      <webElementGuid>0ca39f5e-5408-47e1-b4e7-7f9f0723f72c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Zavrieť' or . = 'Zavrieť')]</value>
      <webElementGuid>a0871fb1-b469-4a01-94a0-1e8f82bcc751</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
