<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hada poda mojej adresy_hladat-podla-r_99fc84</name>
   <tag></tag>
   <elementGuidId>97b01266-3cfa-4620-a846-cc0730e674fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hladat-podla-radio-wrapper-MS_option_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hladat-podla-radio-wrapper-MS_option_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>534f72a4-0d36-47c5-9310-a1dc191906a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>a036cb85-6958-4837-aff0-65a060bcedf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hladat-podla-radio-wrapper-MS_option_1</value>
      <webElementGuid>00bb937b-447c-4a04-a2c2-ba0a9e9600af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hladat-podla-radio-wrapper-MS</value>
      <webElementGuid>cf523c09-4cd0-4601-8f56-4eb73af1ec05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>08b61bfd-4fee-427e-8b05-265f57b2b0bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>podla-nazvu-skoly-alebo-jej-adresy</value>
      <webElementGuid>b3e5a45a-0abc-4d2e-92bb-763b7152a4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hladat-podla-radio-wrapper-MS_option_1&quot;)</value>
      <webElementGuid>bf305942-ec67-4135-9ce6-095e22bf284d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hladat-podla-radio-wrapper-MS_option_1']</value>
      <webElementGuid>b5ee387f-3b33-4f73-9faf-1b65128633fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hladat-podla-radio-wrapper-MS']/div/fieldset/div[3]/div[2]/input</value>
      <webElementGuid>b26fe588-6c3a-4f77-b41d-5035963f0ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>581e988d-a719-4ec5-ae8e-526a677870a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'hladat-podla-radio-wrapper-MS_option_1' and @name = 'hladat-podla-radio-wrapper-MS' and @type = 'radio']</value>
      <webElementGuid>211d4856-dfc0-486a-81bb-31ff03f39942</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
