<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ronk_rocnikSuhrnZiadost</name>
   <tag></tag>
   <elementGuidId>99055865-46e6-4a1c-8e28-a6d5c277a0f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rocnikSuhrnZiadost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rocnikSuhrnZiadost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>114fb4d8-d79b-4eb1-830c-1752c85c634a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rocnikSuhrnZiadost</value>
      <webElementGuid>54302045-b951-4fe7-9712-857b7529ecb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>9.</value>
      <webElementGuid>736a4309-026a-4543-9404-cb355d5f3cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rocnikSuhrnZiadost&quot;)</value>
      <webElementGuid>99c50d2f-b2fa-4ce4-8a37-1a36a3d08ecb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='rocnikSuhrnZiadost']</value>
      <webElementGuid>741fa823-952e-4797-8d70-3ab114b0b637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='info-o-zs']/div[2]/div[4]/div[2]</value>
      <webElementGuid>37c59dcb-0e6b-41eb-86da-e36810612db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ročník'])[6]/following::div[1]</value>
      <webElementGuid>d127861a-d39b-4410-96b8-5792d65ed86a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Základná škola s materskou školou, Soblahov 404'])[1]/following::div[3]</value>
      <webElementGuid>fc0b93e3-baff-4c5c-8b39-def12fbeee3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trieda'])[3]/preceding::div[1]</value>
      <webElementGuid>1fdcf46d-ed27-4c09-9483-b78f79e4b12e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rok školskej dochádzky'])[4]/preceding::div[4]</value>
      <webElementGuid>00a22d4b-06f1-44c7-a215-41d77283cd29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[7]/div[2]/div[4]/div[2]</value>
      <webElementGuid>8a1fa578-0e12-4b2f-b1fd-7feaf8315ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'rocnikSuhrnZiadost' and (text() = '9.' or . = '9.')]</value>
      <webElementGuid>c61f1b23-7c41-48a5-a43d-e8cecc858c6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
