<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nrodnos_dietaNarodnostSuhrn</name>
   <tag></tag>
   <elementGuidId>56bc7bf7-13c5-42fc-893e-f0b04a03640a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dietaNarodnostSuhrn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dietaNarodnostSuhrn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1df8a934-4593-47bd-865a-f82cdf6ca86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dietaNarodnostSuhrn</value>
      <webElementGuid>3263462f-69d8-48f2-bbb4-cf8f887b9215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>slovenská</value>
      <webElementGuid>85921d79-c43c-4e57-a6c0-ce1504fd1313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dietaNarodnostSuhrn&quot;)</value>
      <webElementGuid>4e5b05e1-911c-4ae9-b2da-ad82fa6b419b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dietaNarodnostSuhrn']</value>
      <webElementGuid>9fe3d3c4-1df9-4fe5-a269-3e0c40d13b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suhrnny-prehlad']/div[3]/div[2]/div[8]/div[2]</value>
      <webElementGuid>2a63efb3-96cc-45e8-bc57-de7bd556323a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Národnosť'])[3]/following::div[1]</value>
      <webElementGuid>706946bd-7460-4ac8-9202-4e7eba6087f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nitra'])[2]/following::div[3]</value>
      <webElementGuid>ee4aa5da-ef64-407c-a1af-2c85616d5709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Štátna príslušnosť'])[3]/preceding::div[1]</value>
      <webElementGuid>9ddba23c-a4c4-4bad-8088-9acdeffd3538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slovenská republika'])[4]/preceding::div[2]</value>
      <webElementGuid>78677304-5eee-47e6-955f-a272c63cb506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[3]/div[2]/div[8]/div[2]</value>
      <webElementGuid>3108e0ca-c933-4b03-993d-b95c0b86bc74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dietaNarodnostSuhrn' and (text() = 'slovenská' or . = 'slovenská')]</value>
      <webElementGuid>0d75d30a-01da-4ccc-9827-040b8899b915</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
