<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Materinsk jazyk_dietaMaterinskyJazykSuhrn</name>
   <tag></tag>
   <elementGuidId>01f3a8af-89a8-4c74-8303-6065ff28c88e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dietaMaterinskyJazykSuhrn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dietaMaterinskyJazykSuhrn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e45c8707-252c-477a-9754-6fb8e581c449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dietaMaterinskyJazykSuhrn</value>
      <webElementGuid>387d2ee2-3290-4da9-b01f-3510d00259e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>slovenský</value>
      <webElementGuid>893a40b9-c5b2-4c1e-8c85-a3189499edf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dietaMaterinskyJazykSuhrn&quot;)</value>
      <webElementGuid>3ed3551b-8028-493b-8553-eee49c9cae07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dietaMaterinskyJazykSuhrn']</value>
      <webElementGuid>e712a409-4028-492e-9ee2-386b331b1d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suhrnny-prehlad']/div[3]/div[2]/div[10]/div[2]</value>
      <webElementGuid>1e956735-3d7c-4652-8f29-19a2f7bd23b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Materinský jazyk'])[3]/following::div[1]</value>
      <webElementGuid>c8f48060-90fd-4f8a-bcd7-d23fd47d1bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slovenská republika'])[4]/following::div[3]</value>
      <webElementGuid>ece6d6c2-d41c-44d4-8d42-bfc4604c2ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iný materinský jazyk'])[3]/preceding::div[1]</value>
      <webElementGuid>46dfa140-af9b-4ac7-bf3d-c5f10de327cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[7]/preceding::div[2]</value>
      <webElementGuid>87af290b-47ad-423c-ae23-0bd6b223fbe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[3]/div[2]/div[10]/div[2]</value>
      <webElementGuid>fbde4558-79f6-4d0a-9ff4-71962e884b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dietaMaterinskyJazykSuhrn' and (text() = 'slovenský' or . = 'slovenský')]</value>
      <webElementGuid>fcc88045-afbe-4aca-96b5-4505fe90140c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
