<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Zmenen pracovn schopnos_dpZmenenaPracov_8af9b9</name>
   <tag></tag>
   <elementGuidId>b97254f6-4ba2-43df-90e2-26789730bd70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dpZmenenaPracovnaSchopnost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dpZmenenaPracovnaSchopnost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cdbfb5cf-1db5-4e9d-8eda-21f304eafe94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dpZmenenaPracovnaSchopnost</value>
      <webElementGuid>f2b50e32-15b4-4fa8-b7c0-96bfc39bb81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nie</value>
      <webElementGuid>d6519801-bb9d-4361-a71a-566cc850bebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dpZmenenaPracovnaSchopnost&quot;)</value>
      <webElementGuid>79c2a379-0934-4e96-815f-18ca440ab6a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dpZmenenaPracovnaSchopnost']</value>
      <webElementGuid>acbd673e-53d6-443b-bda6-27ba4cabbec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdpDietata']/div[2]/div[2]/div/div/div[2]</value>
      <webElementGuid>5609c442-fb66-486b-9a35-799be0380e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zmenená pracovná schopnosť'])[1]/following::div[1]</value>
      <webElementGuid>36836eda-48df-4d9b-9050-2cb478d6c6cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Poznámka'])[1]/following::div[6]</value>
      <webElementGuid>e1a756cc-01e7-497a-a851-89c84a0cff2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upravené podmienky prijímacieho konania (Špeciálne výchovno-vzdelávacie potreby)'])[1]/preceding::div[1]</value>
      <webElementGuid>084e5843-9f8e-4bec-911d-eeaf63071fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nie'])[10]/preceding::div[2]</value>
      <webElementGuid>79b285ce-b096-4105-bd3d-feb9124f2dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/div/div/div[2]</value>
      <webElementGuid>37cde105-b394-4c32-8164-361f3d20684b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dpZmenenaPracovnaSchopnost' and (text() = 'Nie' or . = 'Nie')]</value>
      <webElementGuid>a9f56793-bb5b-490f-9c93-3dd37a35f504</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
