<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Meno_zakonnyZastupcaMeno</name>
   <tag></tag>
   <elementGuidId>4819f276-bb04-488c-8516-0e4fc869827d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zakonnyZastupcaMeno</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zakonnyZastupcaMeno']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e0024d5b-9143-4be7-ab1b-2fa63319187e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zakonnyZastupcaMeno</value>
      <webElementGuid>0e53e926-df0e-4ead-a668-e8cacccc98de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Samuel</value>
      <webElementGuid>d7a5f448-e4a9-4839-80a9-d580dbd3491f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zakonnyZastupcaMeno&quot;)</value>
      <webElementGuid>0b79ce00-7d51-4780-aa5c-ae91f53c38c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zakonnyZastupcaMeno']</value>
      <webElementGuid>2d740ce5-fead-4a8b-a9e1-4749bcc295b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz1']/div/div[2]</value>
      <webElementGuid>9a24ddae-b250-42b9-be1b-0d324660398f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meno'])[6]/following::div[1]</value>
      <webElementGuid>0f1342a3-1919-4a96-8e12-abc3da241292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Osobné údaje zákonného zástupcu č. 1'])[2]/following::div[4]</value>
      <webElementGuid>75c8c201-a443-4d37-977c-73ede98f588d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priezvisko'])[6]/preceding::div[1]</value>
      <webElementGuid>7e56258a-5405-4e3a-88a9-48d24f2a46ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Horváth'])[5]/preceding::div[2]</value>
      <webElementGuid>a6063038-c236-47ce-aa42-8a316b440e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/div/div[2]</value>
      <webElementGuid>4b9a3bf4-f37b-4732-a84c-50cbc8c568c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zakonnyZastupcaMeno' and (text() = 'Samuel' or . = 'Samuel')]</value>
      <webElementGuid>13e2a315-f982-4a04-b576-8d2c6ca147be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
