<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_EDUID zkladnej koly_eduidZSSuhrnZiadost</name>
   <tag></tag>
   <elementGuidId>82705115-03ad-4a5f-9b47-7674855d842e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eduidZSSuhrnZiadost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='eduidZSSuhrnZiadost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dc755699-210c-44fc-8951-57ead6a128ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eduidZSSuhrnZiadost</value>
      <webElementGuid>3deba4b0-008c-49a1-9ae2-eb286dc64182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>910020024</value>
      <webElementGuid>d2f76e99-acea-4951-a036-8e9d00c6dcab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eduidZSSuhrnZiadost&quot;)</value>
      <webElementGuid>e05cb79b-3160-422f-9ca5-1bd6d0f224c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='eduidZSSuhrnZiadost']</value>
      <webElementGuid>18488f15-3894-40bc-baae-1ff3c5bf9681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='info-o-zs']/div[2]/div[2]/div[2]</value>
      <webElementGuid>ce8a91d2-87bd-4c93-b3dd-4346efb2379e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EDUID základnej školy'])[3]/following::div[1]</value>
      <webElementGuid>821498f4-e0ca-4914-baca-fc39f2a7687e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zo ZŠ na Slovensku'])[2]/following::div[3]</value>
      <webElementGuid>1fcbccc1-0154-4aba-a25b-142aade9c15b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov základnej školy'])[3]/preceding::div[1]</value>
      <webElementGuid>81cb19d4-e0b5-409f-9bc0-2c152c5df899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Základná škola s materskou školou, Soblahov 404'])[1]/preceding::div[2]</value>
      <webElementGuid>a0f3863c-fb48-4951-882b-5d334a43857e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='910020024']/parent::*</value>
      <webElementGuid>6e009fb0-6773-4557-ae4b-b8d27034a7bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div[2]/div[2]</value>
      <webElementGuid>9b7391e7-c12c-433c-b0ab-eca7e562ae69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'eduidZSSuhrnZiadost' and (text() = '910020024' or . = '910020024')]</value>
      <webElementGuid>eff2b963-9424-4836-80c7-7db39a7324d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
