<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hada poda nzvu koly_hladat-podla-nazvu-skoly</name>
   <tag></tag>
   <elementGuidId>8684083f-7875-4671-a5e3-e222004d38d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hladat-podla-nazvu-skoly</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hladat-podla-nazvu-skoly']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92286268-9f9e-4ea8-bbbb-753a5420717e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hladat-podla-nazvu-skoly</value>
      <webElementGuid>46b6464b-bc89-4baf-8fa9-9c45cfecdda1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a2ed16f7-997d-49d4-9751-31318792c06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>4b795c92-cb62-42b7-a94b-a7467a43e877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hladat-podla-nazvu-skoly&quot;)</value>
      <webElementGuid>a6bc4003-df2a-4577-896f-f22fd2d6c643</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hladat-podla-nazvu-skoly']</value>
      <webElementGuid>fc79bd0a-f110-4361-a28b-cabd37a74a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hladat-podla-nazvu-skoly-wrapper']/div/input</value>
      <webElementGuid>ad696be0-1a2d-4aa9-aadd-6a0302e1d04c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/div/input</value>
      <webElementGuid>e05f2971-f577-44ec-b250-6408b27d8aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'hladat-podla-nazvu-skoly' and @type = 'text']</value>
      <webElementGuid>e8f12bf9-25cf-483c-9315-d8ced0bd1eea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
