<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-datumPodaniaPrihlaskyRok</name>
   <tag></tag>
   <elementGuidId>45db7d55-5309-4f3f-a2f6-b304bcf5054c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-datumPodaniaPrihlaskyRok</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-datumPodaniaPrihlaskyRok']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7d2ab67-8cc4-4f66-9168-9b704b421aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>554b7ea6-7598-4fd8-abf9-2b70ee443686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4cbf2af6-1464-4177-b9af-98dec670c258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-datumPodaniaPrihlaskyRok</value>
      <webElementGuid>addac6f8-8b47-4ed7-9b87-b2f91ffa4936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>c00754ba-1a33-4e1b-959c-c4b8d96ec244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>7b03a6f3-a181-442a-9e28-1a940532971c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>YYYY</value>
      <webElementGuid>5a4070b0-881d-415c-984e-4e348d70de59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-datumPodaniaPrihlaskyRok&quot;)</value>
      <webElementGuid>b5bd58fe-7e90-4bd9-9308-d51375c0f4e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-datumPodaniaPrihlaskyRok']</value>
      <webElementGuid>06289280-8f8e-406c-9802-97962ba7bb18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datumPodaniaPrihlaskyRok']/div/div[2]/input</value>
      <webElementGuid>e621d063-e4f5-469c-8f21-ee6bc73606bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/div/div[2]/input</value>
      <webElementGuid>1f1b7622-68d3-41e3-bcb7-1cec1972d665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-datumPodaniaPrihlaskyRok' and @placeholder = 'YYYY']</value>
      <webElementGuid>e376f009-0cde-44cd-b81c-27738e9c7e96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
