<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Uvete ronk, ktor iak tuduje_select-r_31771c</name>
   <tag></tag>
   <elementGuidId>4c4647a9-5536-4ae8-a8d9-9931e4d30b19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-rocnikSKSelect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select-rocnikSKSelect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>15fce52a-1432-46a7-89eb-c87d37bc20c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select</value>
      <webElementGuid>ad81f127-77ef-4d11-a8df-22aa7149d4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d4fb0fe6-92bf-4334-9373-3ace23cc1df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-rocnikSKSelect</value>
      <webElementGuid>d976f8e5-62e8-4e93-a59e-38bf4611942a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4.5.6.7.8.9.10.</value>
      <webElementGuid>383c25d7-534a-45c7-8137-0bc473521d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-rocnikSKSelect&quot;)</value>
      <webElementGuid>22031b62-de05-4da7-8f39-002631957a36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select-rocnikSKSelect']</value>
      <webElementGuid>c4010e61-cfb6-4250-bd00-5eb6b13c01ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rocnikSKSelect']/div/div[2]/select</value>
      <webElementGuid>d025283b-00c0-4f3f-b5d7-44f0c83c16dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uveďte ročník, ktorý žiak študuje.'])[1]/following::select[1]</value>
      <webElementGuid>9d039ac7-2bfc-4830-8f1f-acfc5addc853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(nepovinné)'])[118]/following::select[1]</value>
      <webElementGuid>37b5d7dd-bef8-4cca-9f45-c3a0f5e7dbf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[24]/preceding::select[1]</value>
      <webElementGuid>ddb68285-d6f5-4343-ae8a-275227161d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtre:'])[57]/preceding::select[1]</value>
      <webElementGuid>ddd515f6-247e-45a0-8ee0-c3f687c09ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[3]/div/div[2]/select</value>
      <webElementGuid>56d1cbf8-fd6a-42fe-b7fe-96d9e418438f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @id = 'select-rocnikSKSelect' and (text() = '4.5.6.7.8.9.10.' or . = '4.5.6.7.8.9.10.')]</value>
      <webElementGuid>ffc674a1-0beb-41a7-9253-1820890927cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
