<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Odhlsi</name>
   <tag></tag>
   <elementGuidId>2e9dfe48-8d53-4f06-86c9-3403d3268b30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logoutBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='logoutBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ce620442-22c3-4f72-8974-58a581abe27f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logoutBtn</value>
      <webElementGuid>4f211793-79ca-4c35-b7c2-b3f35bb3b441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/logout?returnurl=%2F</value>
      <webElementGuid>4141f640-0e14-44b4-9c2f-398a3178a42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Odhlásiť</value>
      <webElementGuid>e50b2614-0950-48f4-9486-16e6c59f4efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logoutBtn&quot;)</value>
      <webElementGuid>e1bb9731-65f3-4c3c-97a7-b56c8f68e654</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='logoutBtn']</value>
      <webElementGuid>27596988-4d20-4d28-9cd2-5f4069a24b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Odhlásiť')]</value>
      <webElementGuid>804820dd-d304-4ed3-a954-c793c6773adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oznámenia'])[1]/following::a[1]</value>
      <webElementGuid>49213aff-7007-44a8-bb6f-6cd8fda66a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Môj profil'])[1]/following::a[2]</value>
      <webElementGuid>01934c46-5348-427d-9f16-95c461a5bc44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[2]/preceding::a[1]</value>
      <webElementGuid>5a8dd979-1c21-46c3-b2c6-662c5a27a30d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prihlášky a rozhodnutia'])[1]/preceding::a[1]</value>
      <webElementGuid>28607418-f982-4908-90ec-030ec9046f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Odhlásiť']/parent::*</value>
      <webElementGuid>37577c55-1843-4e57-9bf7-b4d88014dc6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/logout?returnurl=%2F')]</value>
      <webElementGuid>8585b166-5066-4b54-8ec2-84b3357862f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>0a09892e-abb2-4cb1-b550-13df88e5bd32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'logoutBtn' and @href = '/logout?returnurl=%2F' and (text() = 'Odhlásiť' or . = 'Odhlásiť')]</value>
      <webElementGuid>6f7bf2c9-0eba-47ae-ad62-acaeef1bd05a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
