<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pretan</name>
   <tag></tag>
   <elementGuidId>f8421478-4dd6-4b1f-a8e6-61b5df389808</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.oznamenie-stav</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='riaditel-oznamenia']/div[2]/div[3]/div[2]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7db6ec3e-d563-4928-bf5e-746354cd2373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oznamenie-stav</value>
      <webElementGuid>2b8f5e4e-09ff-4e2e-9073-72ef1f260c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Prečítaná</value>
      <webElementGuid>35680539-f0c7-4532-b2d3-aa81224909f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;riaditel-oznamenia&quot;)/div[@class=&quot;sub-container&quot;]/div[@class=&quot;riaditel-oznamenia-list&quot;]/div[@class=&quot;oznamenie-item&quot;]/div[@class=&quot;oznamenie-col2&quot;]/div[@class=&quot;oznamenie-stav&quot;]</value>
      <webElementGuid>4eba00be-6977-48e8-9537-af2b31fc9e6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='riaditel-oznamenia']/div[2]/div[3]/div[2]/div[2]/div[2]</value>
      <webElementGuid>771e5a64-4220-4fa0-aa64-983bf2b7a690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prejsť na prihlášku'])[1]/following::div[3]</value>
      <webElementGuid>ff43e2ab-fde1-443e-be1e-ed906940d871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Úspešne ste odstránili používateľovi jeho rolu'])[2]/preceding::div[1]</value>
      <webElementGuid>17d7a764-34c8-403c-a017-ab6cbe9e074d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Prečítaná']/parent::*</value>
      <webElementGuid>0c6c440a-e693-4207-a71d-522f47ee1171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div[2]</value>
      <webElementGuid>6104455d-ee75-42f5-a1da-f58492f32488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Prečítaná' or . = 'Prečítaná')]</value>
      <webElementGuid>c028f7d1-f6e1-4a07-a30f-71a2b2580317</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
