<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nepretan (1)</name>
   <tag></tag>
   <elementGuidId>457cd476-1a9f-44fe-b5d5-399a6eae0635</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='riaditel-oznamenia']/div[2]/div[3]/div[2]/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.oznamenie-stav</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f2d1297a-4b53-478a-8dc3-59402c5f451d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oznamenie-stav</value>
      <webElementGuid>bd285531-230b-499c-8bfc-c448131f863c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Neprečítaná</value>
      <webElementGuid>d8b6e936-f240-4789-a099-2a4422f045ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;riaditel-oznamenia&quot;)/div[@class=&quot;sub-container&quot;]/div[@class=&quot;riaditel-oznamenia-list&quot;]/div[@class=&quot;oznamenie-item&quot;]/div[@class=&quot;oznamenie-col2&quot;]/div[@class=&quot;oznamenie-stav&quot;]</value>
      <webElementGuid>28ed0082-9f28-416e-882d-33e479cc702c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='riaditel-oznamenia']/div[2]/div[3]/div[2]/div[2]/div[2]</value>
      <webElementGuid>7799bd71-b2cf-44ad-8386-b7da395f6f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prejsť na prihlášku'])[1]/following::div[3]</value>
      <webElementGuid>7e5bda7c-b273-4c71-94fc-e89f1903bc51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Výsledok vygenerovania rozhodnutí'])[1]/following::div[4]</value>
      <webElementGuid>d52b4676-5373-42b4-9043-235f0f13398b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Výsledok vygenerovania rozhodnutí'])[2]/preceding::div[1]</value>
      <webElementGuid>e9e8ebde-6dde-4c65-b888-2bd78d8ad5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prejsť na prihlášku'])[2]/preceding::div[3]</value>
      <webElementGuid>0b1efa89-9af3-44e5-8408-ed1babac21b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Neprečítaná']/parent::*</value>
      <webElementGuid>3e92f01b-ae5d-42e6-bdbc-7ef5558fba82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div[2]</value>
      <webElementGuid>6966b395-8a24-48ba-b7b4-8e4b3498d485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Neprečítaná' or . = 'Neprečítaná')]</value>
      <webElementGuid>556c83e5-9233-4319-9052-7ff0cb9960d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
