<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Menu_inicialy-osoby-header</name>
   <tag></tag>
   <elementGuidId>aabca505-11cc-49ab-9a4b-36d87b5a4a9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inicialy-osoby-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='inicialy-osoby-header']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f6f01053-2c50-476d-9b52-a2632a6a5c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inicialy-osoby-header</value>
      <webElementGuid>376dc280-b6f9-4f60-a3b3-e158e0180ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KK</value>
      <webElementGuid>28874d34-62ef-4ae1-acb0-2e3986007421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inicialy-osoby-header&quot;)</value>
      <webElementGuid>94b9cab1-74e9-4538-9e09-e66a8bc1b267</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='inicialy-osoby-header']</value>
      <webElementGuid>711659e8-bedd-4434-87df-e0ccb07750e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/following::span[4]</value>
      <webElementGuid>eb0f7c01-fc7c-4a02-b630-5cab6a95d94e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elektronické prihlášky do škôl'])[1]/following::span[5]</value>
      <webElementGuid>694da3df-2c7d-4412-a3d3-4a82eb00a40d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Môj profil'])[1]/preceding::span[1]</value>
      <webElementGuid>95d4aa8f-dd92-461d-a25d-ff30e333367a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oznámenia'])[1]/preceding::span[1]</value>
      <webElementGuid>bfcb8b46-fa91-487b-b183-c1459ddba378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KK']/parent::*</value>
      <webElementGuid>dac2e44c-70e4-450d-bdef-379bd7db4ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/span</value>
      <webElementGuid>55f6ae77-4c47-4a48-9960-1ad99bb1a100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'inicialy-osoby-header' and (text() = 'KK' or . = 'KK')]</value>
      <webElementGuid>68707beb-95d7-4d6c-9e05-81e2b719ad47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
