<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Slovensk republika</name>
   <tag></tag>
   <elementGuidId>2e63eae2-f3a7-4290-9f6a-c88c451a4184</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.autocomplete-item.flex-center-ver</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Slovenská republika' or . = 'Slovenská republika')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ccfe85dd-f9d1-4320-b782-46db1facfc9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autocomplete-item flex-center-ver</value>
      <webElementGuid>05b5088f-4237-47d2-99a2-391eff4af3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>211</value>
      <webElementGuid>e297674a-3c65-402a-bf9e-9fb4887dd189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>976114e1-f480-44f8-8ad5-eb172175682e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Slovenská republika</value>
      <webElementGuid>ef539b13-77c9-43ca-b015-b15a1d23eb91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adresaTPKrajina&quot;)/div[@class=&quot;govuk-form-group autocomplete-control static-select required&quot;]/div[@class=&quot;autocomplete-dropdown&quot;]/div[@class=&quot;autocomplete-item flex-center-ver&quot;]</value>
      <webElementGuid>55b8b69f-9534-4686-8dfc-f8df028c790d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adresaTPKrajina']/div/div[3]/div</value>
      <webElementGuid>cdd71c7d-2d27-497f-9243-ed82c3382220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[1]/following::div[2]</value>
      <webElementGuid>52692718-7efd-4a66-b281-1a13a90fa71a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slovenská republika'])[1]/following::div[2]</value>
      <webElementGuid>5d21cf92-4249-408c-8b30-c02b5e13962c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slovinská republika'])[1]/preceding::div[1]</value>
      <webElementGuid>770fd78f-1485-4df9-a23e-03f42f109bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slovenská republika'])[3]/preceding::div[2]</value>
      <webElementGuid>69021e2b-8b9a-4e43-9380-d95466658523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[3]/div</value>
      <webElementGuid>7de0cb04-2f45-4f75-921a-a9d789e6c669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Slovenská republika' or . = 'Slovenská republika')]</value>
      <webElementGuid>9f8ecef4-5260-484e-872e-8ff742261396</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
