<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Severn 874874, 85214, Krpeany, Sloven_e36fcc</name>
   <tag></tag>
   <elementGuidId>7c7c442b-b099-4db9-846a-1701bf97fa3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#trvalyPobytRadio_option_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='trvalyPobytRadio_option_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2aedbd5f-0107-42f6-8fa3-a4ea9e18a79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>13dc4c0c-9257-4031-8951-3869dfa1fa0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trvalyPobytRadio_option_1</value>
      <webElementGuid>8af3e1d9-d438-4e21-b7d9-998f92217fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>trvalyPobytRadio</value>
      <webElementGuid>6b4a5dc1-6f90-4e0a-a896-b6d12b484516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9cccc1d4-6738-45d4-8089-981f701f023f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>8e0b642f-9c14-446b-b045-4f5b859143d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trvalyPobytRadio_option_1&quot;)</value>
      <webElementGuid>0c2bdb32-5976-430b-829a-1b4da1f79988</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='trvalyPobytRadio_option_1']</value>
      <webElementGuid>19bd1964-d0d7-44bf-9b07-0d2841a7150f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trvalyPobytRadio']/div/fieldset/div[3]/div[2]/input</value>
      <webElementGuid>22b81f22-79b7-4b64-93da-485012488774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>eaab01b6-ccf7-4a51-8494-a626975ffbac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'trvalyPobytRadio_option_1' and @name = 'trvalyPobytRadio' and @type = 'radio']</value>
      <webElementGuid>82249e7c-8356-4905-a69b-7d7e468b3831</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
