<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Prida existujcu prihlku_btn-vytvorit-prihlasku</name>
   <tag></tag>
   <elementGuidId>d0bf4eae-d27e-4b7c-ad13-c1853c7fb81a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-vytvorit-prihlasku</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn-vytvorit-prihlasku']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d978a2fd-0fef-40a9-9b6d-6e424a56ed8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-vytvorit-prihlasku</value>
      <webElementGuid>2bf2525c-4d50-4731-a012-5487c9914895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Vytvoriť prihlášku</value>
      <webElementGuid>cd884281-f4a6-4676-9401-f9ce69129f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button govuk-button__large</value>
      <webElementGuid>02958852-f022-464c-bc09-1b7b4a769475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-module</name>
      <type>Main</type>
      <value>govuk-button</value>
      <webElementGuid>c4d24406-5e62-4c70-be9f-ea58e00fcc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vytvoriť prihlášku</value>
      <webElementGuid>70bcfbc2-c969-440c-b522-bc8d07ce538d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;moje-prihlasky&quot;)/div[@class=&quot;prihlaska-heading-container&quot;]/div[@class=&quot;buttons&quot;]/a[@id=&quot;btn-vytvorit-prihlasku&quot;]</value>
      <webElementGuid>d9cff5cc-c355-4d6f-b14a-c290e6428da3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn-vytvorit-prihlasku']</value>
      <webElementGuid>d0e5b827-3fc4-47b4-8cd0-736948cc4a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='moje-prihlasky']/div[2]/div[2]/a[2]</value>
      <webElementGuid>2e0e2126-df63-405e-8084-052be4f516c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Vytvoriť prihlášku')]</value>
      <webElementGuid>517b553c-2899-4082-ab5e-ce12d6abcee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pridať existujúcu prihlášku'])[1]/following::a[1]</value>
      <webElementGuid>a744fdd9-17f3-4f4c-b586-8a52bd756888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identifikátor prihlášky:'])[1]/preceding::a[1]</value>
      <webElementGuid>f9eadd67-90a5-4f3b-bc36-0b34b7806554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vytvoriť prihlášku']/parent::*</value>
      <webElementGuid>bf97d657-ee75-49b0-8f7d-5f8ff2839350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]/div[2]/a[2]</value>
      <webElementGuid>80323728-9773-4704-a185-7ec02cf4aa34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn-vytvorit-prihlasku' and @name = 'Vytvoriť prihlášku' and (text() = 'Vytvoriť prihlášku' or . = 'Vytvoriť prihlášku')]</value>
      <webElementGuid>8a3e4d90-f5d8-465d-841e-161b1e465a68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
