<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hada poda mojej adresy_hladat-podla-r_df1d5a</name>
   <tag></tag>
   <elementGuidId>feecd8e8-cf94-45fa-8416-f801f53ac6b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hladat-podla-radio-wrapper-ZS_option_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hladat-podla-radio-wrapper-ZS_option_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56fef9c6-9ea4-41a5-a8b1-906abe3270df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>ed9d93a3-9233-426d-9e19-387ad54d4faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hladat-podla-radio-wrapper-ZS_option_1</value>
      <webElementGuid>069ba10d-1a82-4701-932d-181a328dab06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hladat-podla-radio-wrapper-ZS</value>
      <webElementGuid>c3068811-9650-404e-918f-ae43b2464249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0d80fb7a-53a6-4b79-841a-a1c1be86790a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>podla-nazvu-skoly-alebo-jej-adresy</value>
      <webElementGuid>79b9a1d0-dae1-4c90-afb4-d31b9626d1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hladat-podla-radio-wrapper-ZS_option_1&quot;)</value>
      <webElementGuid>8bf9ce5e-2c71-45ae-986d-8e3f1aa293c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hladat-podla-radio-wrapper-ZS_option_1']</value>
      <webElementGuid>99a75a4f-09a4-47ab-badf-f6f1ab98fe36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hladat-podla-radio-wrapper-ZS']/div/fieldset/div[3]/div[2]/input</value>
      <webElementGuid>2d678e09-6df5-4a77-a54f-46c7cf038e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/fieldset/div[3]/div[2]/input</value>
      <webElementGuid>0b04db58-408d-4243-bbe8-5d24c0247363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'hladat-podla-radio-wrapper-ZS_option_1' and @name = 'hladat-podla-radio-wrapper-ZS' and @type = 'radio']</value>
      <webElementGuid>b4b905b9-30b0-4624-b8b9-8153bc978c77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
