<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nzov koly alebo jej adresa_nazov-skol_cbc5a9</name>
   <tag></tag>
   <elementGuidId>d7037a91-f24c-4557-b07f-d73d3c7902c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nazov-skoly-alebo-adresa-input-MS']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nazov-skoly-alebo-adresa-input-MS</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a82e59f-af28-40f4-be0f-e67925d3ae5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nazov-skoly-alebo-adresa-input-MS</value>
      <webElementGuid>2fe32557-e088-4f1c-bed0-9cde8b4eb870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6cc5b7b7-5f44-4871-88ba-8c5944739c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>2deaee7b-bef6-4880-af26-ee31fee80475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nazov-skoly-alebo-adresa-input-MS&quot;)</value>
      <webElementGuid>6b87b180-0150-4534-be47-23682635dd78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nazov-skoly-alebo-adresa-input-MS']</value>
      <webElementGuid>5ad6da98-cef9-4580-8933-064d32d834c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nazov-skoly-alebo-adresa-input-wrapper-MS']/div/input</value>
      <webElementGuid>9497b2c0-d8dd-4e09-a5b2-62a390d20754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>8aba872f-2583-4b9c-b5a2-bcf6440a368d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nazov-skoly-alebo-adresa-input-MS' and @type = 'text']</value>
      <webElementGuid>5a7ecfee-a3a5-48b4-bb58-40c23db350bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
