<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Nzov koly alebo jej adresa_fulltext-_b34249</name>
   <tag></tag>
   <elementGuidId>497eda5a-a538-4e12-9a3a-a8e63da6e718</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fulltext-input-SS-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fulltext-input-SS-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a7364f94-9b59-44ae-aea9-36fc3be92b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fulltext-input-SS-button</value>
      <webElementGuid>12fe05e8-ec6d-448e-9e9c-72eb1d753f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button govuk-button__basic fulltext-input-button</value>
      <webElementGuid>8844c32c-f22e-42f0-897f-b7fb994a6043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Hľadať</value>
      <webElementGuid>51351863-0248-4c71-8f05-a0f1bf8ee98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    search
                                </value>
      <webElementGuid>9e417cbe-d85d-4271-8e87-98bfd2c8c143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fulltext-input-SS-button&quot;)</value>
      <webElementGuid>1dec3581-a240-489d-83e0-94776bd81daf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='fulltext-input-SS-button']</value>
      <webElementGuid>850a5050-1539-4640-a50d-603e5368158c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fulltext-input-wrapper-SS']/div/button</value>
      <webElementGuid>ddff94e5-10be-4ae7-b492-c4c276971bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov školy alebo jej adresa'])[1]/following::button[1]</value>
      <webElementGuid>bab021df-3d0c-40bd-9b89-98e267a6aa53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtre:'])[7]/following::button[1]</value>
      <webElementGuid>559327a7-45d1-46d9-93e2-e6a3dcc0a1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voľná kapacita na prijatie'])[1]/preceding::button[1]</value>
      <webElementGuid>2806abfd-af38-488e-8733-96adf63c6eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(nepovinné)'])[24]/preceding::button[1]</value>
      <webElementGuid>75f937ac-6a00-49a2-b576-a8974253b7d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/button</value>
      <webElementGuid>2ccc0da7-5934-40a1-b206-e5f28dd24e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'fulltext-input-SS-button' and (text() = '
                                    search
                                ' or . = '
                                    search
                                ')]</value>
      <webElementGuid>01b06061-a49a-4a74-a1f3-1d45386a9c38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
