<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kontaktn e-mail_zastupca1Email</name>
   <tag></tag>
   <elementGuidId>fffd2292-785a-42c7-a5f0-df36fcec034b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zastupca1Email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zastupca1Email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>18da12a5-af9f-4fab-b853-ee850243d04b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zastupca1Email</value>
      <webElementGuid>06994775-21c8-4cbe-b4d8-fe5037c26f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>barcik@ditec.sk</value>
      <webElementGuid>157ee45d-2845-4b52-9958-5588492992a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zastupca1Email&quot;)</value>
      <webElementGuid>20224463-9395-4f96-ba89-13eb4264ce8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zastupca1Email']</value>
      <webElementGuid>96e32b44-0353-4926-baa3-9a7f71d82dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='osobne-udaje-zz1']/div[2]/div[2]/div[6]/div[2]</value>
      <webElementGuid>077a54b3-513c-4c93-9f7f-f39f5edef79d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kontaktný e-mail'])[1]/following::div[1]</value>
      <webElementGuid>9798fef9-ece6-4424-81de-e6d643442e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum narodenia'])[2]/following::div[4]</value>
      <webElementGuid>8496448b-8adb-471b-b75f-6953b77fac34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodné priezvisko'])[3]/preceding::div[1]</value>
      <webElementGuid>2f78ea30-7d2c-4ef8-b203-34380d351ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(nepovinné)'])[31]/preceding::div[1]</value>
      <webElementGuid>9d272e39-8614-4841-9d54-337772956912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='barcik@ditec.sk']/parent::*</value>
      <webElementGuid>3b9eedcd-9672-494e-b22e-7b0fa590acd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[6]/div[2]</value>
      <webElementGuid>6ace5b7d-ad8d-4281-bace-f6c2a91733ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zastupca1Email' and (text() = 'barcik@ditec.sk' or . = 'barcik@ditec.sk')]</value>
      <webElementGuid>fce6d381-18a7-4304-b923-7de7fd675c9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
