<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rodn slo_dietaRodneCislo</name>
   <tag></tag>
   <elementGuidId>1f37f6a1-b583-4760-b285-205a0c55424e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dietaRodneCislo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='suhrnny-prehlad']/div[4]/div[2]/div[4]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>405416ac-a961-4bf9-ab51-c193408f4c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dietaRodneCislo</value>
      <webElementGuid>6d2d5713-9413-4667-8982-0607360e27de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>091127/1130</value>
      <webElementGuid>d7418634-4f48-4145-aa66-9eb3b7b35b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suhrnny-prehlad&quot;)/div[@class=&quot;panel-with-header&quot;]/div[@class=&quot;panel-content info-layout&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;dietaRodneCislo&quot;]</value>
      <webElementGuid>b32e93a0-55f4-436a-9a01-5c2318b912d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suhrnny-prehlad']/div[4]/div[2]/div[4]/div[2]</value>
      <webElementGuid>12560259-645d-42d5-b7d9-479176cfe7e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodné číslo'])[5]/following::div[1]</value>
      <webElementGuid>0fd66c57-b9d9-4367-8964-af1085caf8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[8]/following::div[3]</value>
      <webElementGuid>e20f2c76-68ce-4074-9d22-6c23fef91446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum narodenia'])[5]/preceding::div[1]</value>
      <webElementGuid>8fbd3312-57a4-4595-8494-48a2d037d32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pohlavie'])[2]/preceding::div[4]</value>
      <webElementGuid>fe1c9673-1050-4553-b168-f25e3932baa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[4]/div[2]</value>
      <webElementGuid>30b7b9e5-c924-4ef6-b86e-3e060d37df89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '091127/1130' or . = '091127/1130')]</value>
      <webElementGuid>a6090201-53b1-4b54-862e-d0b9681a1baa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
