<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Priezvisko_profil-priezvisko</name>
   <tag></tag>
   <elementGuidId>5cfbe2da-a06d-41d5-a0c1-beaa3b0eb0da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profil-priezvisko</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='profil-priezvisko']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b5b8e0dc-2c88-4afc-906f-823d92384a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profil-priezvisko</value>
      <webElementGuid>0290d782-e5bf-42ae-af24-931c43c5dc5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bystrá</value>
      <webElementGuid>a24a4908-c041-435a-96d5-03c690217db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profil-priezvisko&quot;)</value>
      <webElementGuid>2dd66b8f-057a-42b5-9b06-514c48f821a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='profil-priezvisko']</value>
      <webElementGuid>b8df9f42-44d4-4fc6-9634-2c22400e1db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='podrobnosti-o-dietati']/div/div[2]/div[2]/div[2]</value>
      <webElementGuid>32b91737-4321-4845-95aa-802812edced4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priezvisko'])[1]/following::div[1]</value>
      <webElementGuid>ec4d0903-6daf-4130-970d-b9eb24901acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lívia'])[1]/following::div[3]</value>
      <webElementGuid>7eb8cb9a-dec9-4a0c-b7df-53d24b727f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodné priezvisko'])[1]/preceding::div[1]</value>
      <webElementGuid>d95798d1-d003-44a1-a7e4-2ed9d15045f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::div[2]</value>
      <webElementGuid>4677304f-e2a5-4b57-bd55-8fa64220ae91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bystrá']/parent::*</value>
      <webElementGuid>a75d1e4e-83be-4e1c-9d95-5af62765829f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div[2]</value>
      <webElementGuid>f9728302-ad3e-408e-9298-dff0f3abc9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'profil-priezvisko' and (text() = 'Bystrá' or . = 'Bystrá')]</value>
      <webElementGuid>6b26477d-17a7-4d01-a29b-c3cd3f749240</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
