<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Meno_zakonnyZastupcaMeno</name>
   <tag></tag>
   <elementGuidId>79d42b5d-d031-446b-ad4d-5c19aa20b3ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.zakonnyZastupcaMeno</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zastupcovia']/div[2]/div[2]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>39d3e4c0-5d73-4a92-b4a3-6a127bf8cba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zakonnyZastupcaMeno</value>
      <webElementGuid>bd129fe2-9510-4dfb-84fb-dade81772d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stanislav</value>
      <webElementGuid>e2f9314d-ef92-4f82-9eb7-9e2a277f6ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zastupcovia&quot;)/div[@class=&quot;panel-content&quot;]/div[@class=&quot;zz1&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;zakonnyZastupcaMeno&quot;]</value>
      <webElementGuid>5b6ad695-2d03-4afc-a751-425e850633c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zastupcovia']/div[2]/div[2]/div/div[2]</value>
      <webElementGuid>b0e88526-32a6-48a7-b944-c07b6c67ab17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meno'])[6]/following::div[1]</value>
      <webElementGuid>9e5cf95f-24ee-4481-8f00-58e1a607c257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Osobné údaje zákonného zástupcu č. 1'])[1]/following::div[4]</value>
      <webElementGuid>d90ef22e-327f-4053-aa94-8a2734243fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priezvisko'])[6]/preceding::div[1]</value>
      <webElementGuid>cb7e09e4-f45c-4059-9836-f32f48ce4200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Štefánek'])[2]/preceding::div[2]</value>
      <webElementGuid>d89309a3-1c1b-4de1-ad90-270bbfa50e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div[2]/div/div[2]</value>
      <webElementGuid>771e8481-45a8-456d-9b0e-5338768bc20e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Stanislav' or . = 'Stanislav')]</value>
      <webElementGuid>d72d6659-82bd-424d-a930-26253f227647</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
