<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Meno_zastupca1Meno</name>
   <tag></tag>
   <elementGuidId>2e5b8cec-c694-48de-9362-2bee7233b2aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zastupca1Meno</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zastupca1Meno']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ad5492c0-a67d-446a-be3f-7e856b4ba680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zastupca1Meno</value>
      <webElementGuid>261e6b6e-05ab-4945-915e-238274d5468f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stanislav</value>
      <webElementGuid>7be0055c-ca22-45dc-906f-8672862b9020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zastupca1Meno&quot;)</value>
      <webElementGuid>63ca8380-f56c-47dc-8da2-9cad05b6b1a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zastupca1Meno']</value>
      <webElementGuid>5ee6dd3b-01b6-49e0-bcca-a2ef538db816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='osobne-udaje-zz1']/div[2]/div[2]/div/div[2]</value>
      <webElementGuid>1459c080-a43c-4cb9-b87a-0f705cbee9db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meno'])[2]/following::div[1]</value>
      <webElementGuid>a4904fdd-ed69-4627-a6f0-9dd618c071cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Údaje z vášho profilu'])[1]/following::div[4]</value>
      <webElementGuid>6455b8cd-a2c4-48a9-870e-e0aada672089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priezvisko'])[2]/preceding::div[1]</value>
      <webElementGuid>9b11ec80-adad-4e05-a0ab-0fbead55e90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Štefánek'])[1]/preceding::div[2]</value>
      <webElementGuid>6a2b4a5c-bb20-417c-9d28-01c8a841bdc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Stanislav']/parent::*</value>
      <webElementGuid>de02021c-00a5-4b04-ba5b-86a3d78587e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div[2]/div[2]/div/div[2]</value>
      <webElementGuid>e8f97efb-e3dc-4780-8237-95932959970d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zastupca1Meno' and (text() = 'Stanislav' or . = 'Stanislav')]</value>
      <webElementGuid>bd7146a5-d1bd-4f98-88a2-bc07ffff5e21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
