<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rodn slo_zastupca1RodneCislo</name>
   <tag></tag>
   <elementGuidId>8afe922f-192e-4bde-b69e-449d29c225c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zastupca1RodneCislo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zastupca1RodneCislo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5823e98c-dc3f-4904-8246-349ba15f689f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zastupca1RodneCislo</value>
      <webElementGuid>c4f567c2-eb2b-4602-ba22-41f170f90152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>030724/6027</value>
      <webElementGuid>d53b6b20-0347-4676-b0bf-7e91e00a984f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zastupca1RodneCislo&quot;)</value>
      <webElementGuid>084c583f-8fdb-4177-99c9-4399cb7793e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zastupca1RodneCislo']</value>
      <webElementGuid>7030797c-1fbd-4d28-8f96-2bba77f29d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='osobne-udaje-zz1']/div[2]/div[2]/div[4]/div[2]</value>
      <webElementGuid>808eb84b-cc93-404e-8d29-531e47a3bb65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodné číslo'])[2]/following::div[1]</value>
      <webElementGuid>3aaa1f5f-acd1-4823-b593-067c57e2032a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[5]/following::div[3]</value>
      <webElementGuid>2f5c75b4-8574-4009-81fa-6c9332977802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum narodenia'])[2]/preceding::div[1]</value>
      <webElementGuid>79d20916-cd4c-4c23-85f6-ef55b42ca529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kontaktný e-mail'])[1]/preceding::div[4]</value>
      <webElementGuid>d079dc3e-1b7e-4ae3-b3c2-616f872f6d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='030724/6027']/parent::*</value>
      <webElementGuid>c44ff026-be19-4c80-b5c2-2ad82b0207e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div[4]/div[2]</value>
      <webElementGuid>f31bb468-2153-4896-8ae7-f6c6533564e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zastupca1RodneCislo' and (text() = '030724/6027' or . = '030724/6027')]</value>
      <webElementGuid>2a61e4f0-6268-4e7e-a307-5e643f2b7076</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
