<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Korepondenn adresa_zakonnyZastupcaAdres_9d2f75</name>
   <tag></tag>
   <elementGuidId>98ed1cbb-e239-436a-8895-ec39a9b107c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.zakonnyZastupcaAdresaBydliska</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zastupcovia']/div[2]/div[2]/div[6]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5a491f74-bc7f-41bc-a694-58fc4a1cf14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zakonnyZastupcaAdresaBydliska</value>
      <webElementGuid>911a1736-4b20-4d6c-ba2d-62a748634d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kladnianska 58/98, 01508, Kriváň (Detva), Slovenská republika</value>
      <webElementGuid>89e5ee1b-9c39-46d7-8890-7fdf91d9e34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zastupcovia&quot;)/div[@class=&quot;panel-content&quot;]/div[@class=&quot;zz1&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;zakonnyZastupcaAdresaBydliska&quot;]</value>
      <webElementGuid>f70c869d-484b-4e69-8245-f32e31c1527e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zastupcovia']/div[2]/div[2]/div[6]/div[2]</value>
      <webElementGuid>d5043a20-0fba-4091-bbbd-084af6b1e734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Korešpondenčná adresa'])[4]/following::div[1]</value>
      <webElementGuid>bf5219ff-d814-4f18-b765-7e8d1b8ca365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum narodenia'])[6]/following::div[4]</value>
      <webElementGuid>7c307909-04fd-4f34-ba4b-88f31278a445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail'])[3]/preceding::div[1]</value>
      <webElementGuid>466b687a-8ade-4c5d-85ad-bd9451ca181a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='barcik@ditec.sk'])[2]/preceding::div[2]</value>
      <webElementGuid>c78118e4-e742-4f27-8415-453296b21557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div[2]/div[6]/div[2]</value>
      <webElementGuid>aba1f5ba-a4fb-461b-8c7e-55e0d8f0a982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Kladnianska 58/98, 01508, Kriváň (Detva), Slovenská republika' or . = 'Kladnianska 58/98, 01508, Kriváň (Detva), Slovenská republika')]</value>
      <webElementGuid>a04e2ffa-2fce-4626-a18f-c46b37040ef5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
