<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ttna prslunos_dietaStatnaPrislusnost</name>
   <tag></tag>
   <elementGuidId>8a33abb4-0bde-42a9-80f1-369f2694b465</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dietaStatnaPrislusnost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='suhrnny-prehlad']/div[4]/div[2]/div[9]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9eb271a8-994e-4534-be0b-b450669e71d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dietaStatnaPrislusnost</value>
      <webElementGuid>a15d9861-c079-4c37-a5aa-5199de6a6bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Slovenská republika</value>
      <webElementGuid>02638689-6f65-4017-898e-a242465a5c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suhrnny-prehlad&quot;)/div[@class=&quot;panel-with-header&quot;]/div[@class=&quot;panel-content info-layout&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;dietaStatnaPrislusnost&quot;]</value>
      <webElementGuid>06ddab24-da27-4019-bd66-53e9ca256660</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suhrnny-prehlad']/div[4]/div[2]/div[9]/div[2]</value>
      <webElementGuid>38a16008-0d8c-48c3-917f-3e6f7db14912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Štátna príslušnosť'])[2]/following::div[1]</value>
      <webElementGuid>36f60ab6-70ec-4bb4-ac2d-43576544c59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='slovenská'])[2]/following::div[3]</value>
      <webElementGuid>c0f59e56-f3df-4c4c-8121-f8202a45e974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Materinský jazyk'])[2]/preceding::div[1]</value>
      <webElementGuid>5294c8fe-1771-41ba-a1cd-adc4dfba5f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='slovenský'])[6]/preceding::div[2]</value>
      <webElementGuid>f1a5b73c-592f-4dc7-874a-06e713529f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[9]/div[2]</value>
      <webElementGuid>57758052-e5b2-4584-94f0-db766034d16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Slovenská republika' or . = 'Slovenská republika')]</value>
      <webElementGuid>68196056-34ed-4d6a-8d91-f96857a95769</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
