<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nzov koly alebo jej adresa_fulltext-input-SS</name>
   <tag></tag>
   <elementGuidId>340b4336-aa94-49a9-83c5-2ae5528b3175</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fulltext-input-SS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fulltext-input-SS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c0904ff-0ea0-4fcf-bf25-bed259fa05ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fulltext-input-SS</value>
      <webElementGuid>52b57029-af3b-4975-ae27-78c6496a9af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a68b9eb0-8e82-4414-a8b7-860fe06da2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>04b7300f-c9dc-4d7a-b3c7-ee643c47f331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fulltext-input-SS&quot;)</value>
      <webElementGuid>9d37bd87-3942-4d1f-9b29-f131d11a7b3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fulltext-input-SS']</value>
      <webElementGuid>f8968fa9-18c0-4428-8287-7c461a872dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fulltext-input-wrapper-SS']/div/input</value>
      <webElementGuid>e2ca21f9-8a4d-441c-8a27-5bbaa713f963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/input</value>
      <webElementGuid>ea26d6d3-e0b1-4fb9-924d-b30d27de625d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fulltext-input-SS' and @type = 'text']</value>
      <webElementGuid>bc6a3f13-af19-457b-8ca0-312f4e4a74b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
