<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_modalTypUmiestneniaRadio_option_2</name>
   <tag></tag>
   <elementGuidId>6443efb9-1033-4612-a2a4-59ccb0e8eb7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modalTypUmiestneniaRadio_option_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='modalTypUmiestneniaRadio_option_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82baed63-cb18-466d-9b43-45056e9faee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>819fd41c-49f3-4fc7-b10a-e2f21bddd9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modalTypUmiestneniaRadio_option_2</value>
      <webElementGuid>036df724-8614-471a-a391-b06f446fd596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>modalTypUmiestneniaRadio</value>
      <webElementGuid>34859fc0-060b-4f1a-bb4e-756b86e8d284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>60309507-c71a-408e-bbf7-ba1460a241c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>2d671254-1098-4af4-a254-a9e081edba56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalTypUmiestneniaRadio_option_2&quot;)</value>
      <webElementGuid>6dd24340-54b7-40b7-b186-9fb11512389d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='modalTypUmiestneniaRadio_option_2']</value>
      <webElementGuid>5dfe18da-0ffa-46e0-a8cd-4d4f1cb3a161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalTypUmiestneniaRadio']/div/fieldset/div[3]/div[3]/input</value>
      <webElementGuid>23b4a930-416b-413a-be5e-b24c0cf37b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/fieldset/div[3]/div[3]/input</value>
      <webElementGuid>07b9b805-df0b-43f7-adcd-c4f76a013855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'modalTypUmiestneniaRadio_option_2' and @name = 'modalTypUmiestneniaRadio' and @type = 'radio']</value>
      <webElementGuid>996d5d58-8a6e-427d-afd3-a7579bfcd114</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
