<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Uvete posledn ukonen ronk zkladnej k_a84d95</name>
   <tag></tag>
   <elementGuidId>9750c504-f659-419e-aeb7-c9411533f385</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-rocnikSelect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select-rocnikSelect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8bbdc581-a0a0-4774-b40e-0d50da7157cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select</value>
      <webElementGuid>e063b3d4-67da-4a03-9385-8eba97040374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f5e08b1-089e-4298-aa00-6d535e86f087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-rocnikSelect</value>
      <webElementGuid>3f97d3b8-7a5a-4a4d-a97b-2bd53ecaa01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4.5.6.7.8.9.10.</value>
      <webElementGuid>60c9478a-4db3-4c8b-a9b5-5878d2ea6e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-rocnikSelect&quot;)</value>
      <webElementGuid>d3ceffd7-013e-4776-bed0-7457e52b52be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select-rocnikSelect']</value>
      <webElementGuid>812d6d8b-39da-4544-a7cf-a2f33c1d56e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rocnikSelect']/div/div[2]/select</value>
      <webElementGuid>99362aa8-549c-4ab3-bd6c-bd4d15c8e2a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uveďte posledný ukončený ročník základnej školy.'])[2]/following::select[1]</value>
      <webElementGuid>05d3d312-80f7-46d2-ab63-4329727c66ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(nepovinné)'])[84]/following::select[1]</value>
      <webElementGuid>e7a38cb1-1c8d-4c1e-800b-8f03e3827bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[195]/preceding::select[1]</value>
      <webElementGuid>c66105e0-07b8-4e4c-baf6-3a42b09f36fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtre:'])[55]/preceding::select[1]</value>
      <webElementGuid>bc272053-d79f-469c-a4b5-02291abc44fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div[3]/div[2]/div/div/div[2]/select</value>
      <webElementGuid>374cda1f-fbc6-4a88-8766-839a093e0ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @id = 'select-rocnikSelect' and (text() = '4.5.6.7.8.9.10.' or . = '4.5.6.7.8.9.10.')]</value>
      <webElementGuid>5de9d900-cafe-40ee-98fc-65087b674c20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
