<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(nepovinn)_select-modalUrovenSutazeSelect</name>
   <tag></tag>
   <elementGuidId>d2b2cbcd-c921-4d4b-8296-c5b815094879</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-modalUrovenSutazeSelect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select-modalUrovenSutazeSelect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>361f793a-380d-4b12-b20c-82dfa4db21fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select</value>
      <webElementGuid>fd9bad7e-401b-4a06-b9dc-1c77902dd94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>052892c6-e5f0-4e86-9a39-ee5b80996bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-modalUrovenSutazeSelect</value>
      <webElementGuid>c7404539-73b3-4a2a-aa9d-a4c1f0ed6173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>krajskámedzinárodnámestskánárodnáokresnáškolská</value>
      <webElementGuid>78030d90-4660-45b7-a11a-4f71eaf261ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-modalUrovenSutazeSelect&quot;)</value>
      <webElementGuid>7e28cb4e-5f60-4a2d-a589-b462103ce46b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select-modalUrovenSutazeSelect']</value>
      <webElementGuid>458b855b-0d40-48a6-ac25-3fab2c99c19f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalUrovenSutazeSelect']/div/div[2]/select</value>
      <webElementGuid>989f6470-ac82-402c-b260-a3f23b10e136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(nepovinné)'])[94]/following::select[1]</value>
      <webElementGuid>4fa06c05-03de-4941-805f-fd5b1bdd1d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Úroveň súťaže'])[1]/following::select[1]</value>
      <webElementGuid>0893c852-fb28-44e1-b2ba-2362a9cc6d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[207]/preceding::select[1]</value>
      <webElementGuid>8d0b8320-b540-4a48-8496-1c0a04f6e61b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtre:'])[67]/preceding::select[1]</value>
      <webElementGuid>55610ec3-67f2-443e-a79e-50d71e15317c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[5]/div/div[2]/select</value>
      <webElementGuid>b6063ff7-12fe-4fd1-ba62-605a6f62d0b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @id = 'select-modalUrovenSutazeSelect' and (text() = 'krajskámedzinárodnámestskánárodnáokresnáškolská' or . = 'krajskámedzinárodnámestskánárodnáokresnáškolská')]</value>
      <webElementGuid>f180bed5-d2a5-4375-92e4-fbf7f11f2ccd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
