<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nahran_govuk-accordion__section-desc-te_b9349f</name>
   <tag></tag>
   <elementGuidId>4ff52e95-79e6-402a-8e7a-e577c6302098</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='acc-heading-']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.govuk-accordion__section-desc-text-focus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0e0ecfee-cd4f-4faf-a2dd-3bbb31509dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-accordion__section-desc-text-focus</value>
      <webElementGuid>dcd1db3e-902b-414c-8a9d-27e2ba2355cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Čestné vyhlásenie zákonného zástupcu — ak získanie podpisu druhého zákonného zástupcu je spojené s ťažko prekonateľnou prekážkou a je to v najlepšom záujme dieťaťa.  [ Uložiť vzor ]</value>
      <webElementGuid>a2492efa-000e-4b0f-bda4-37650e4c8482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acc-heading-&quot;)/div[@class=&quot;govuk-accordion__section-desc-text-focus&quot;]</value>
      <webElementGuid>159d651d-3a14-4015-93ab-34c3ae63fa11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='acc-heading-']/div[2]</value>
      <webElementGuid>bc68bb46-2734-484a-8e39-3726b204bc96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nahrané'])[1]/following::div[1]</value>
      <webElementGuid>15b64c17-f9f6-44c0-abd9-84129893c8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nenahrané'])[2]/following::div[2]</value>
      <webElementGuid>0bbecf2e-68dc-4489-8510-40bd9f8590d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add'])[1]/preceding::div[1]</value>
      <webElementGuid>ea111977-02ba-4da4-ab53-0ab6d8427894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Čestné vyhlásenie zákonného zástupcu — ak získanie podpisu druhého zákonného zástupcu je spojené s ťažko prekonateľnou prekážkou a je to v najlepšom záujme dieťaťa.']/parent::*</value>
      <webElementGuid>1f85ee49-34ac-4d7e-8ed4-13c8e3027f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>ef4d4a97-ae61-4b99-9923-59148b9fb960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Čestné vyhlásenie zákonného zástupcu — ak získanie podpisu druhého zákonného zástupcu je spojené s ťažko prekonateľnou prekážkou a je to v najlepšom záujme dieťaťa.  [ Uložiť vzor ]' or . = 'Čestné vyhlásenie zákonného zástupcu — ak získanie podpisu druhého zákonného zástupcu je spojené s ťažko prekonateľnou prekážkou a je to v najlepšom záujme dieťaťa.  [ Uložiť vzor ]')]</value>
      <webElementGuid>f9a2acfa-81cc-4366-aacb-03625a627f45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
