<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Menu_inicialy-osoby-header</name>
   <tag></tag>
   <elementGuidId>012bd4b0-18d7-4283-bfb6-ebc38dcf3594</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='inicialy-osoby-header']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inicialy-osoby-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f919ad29-56d9-408e-a432-02f7e1860b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inicialy-osoby-header</value>
      <webElementGuid>97c45ce1-ab83-4633-8f58-eb6e96b95220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MM</value>
      <webElementGuid>6379a840-c12b-4bec-b1aa-6e18ca61e496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inicialy-osoby-header&quot;)</value>
      <webElementGuid>5fe53383-ffb0-46b2-a9a9-64248f72b199</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='inicialy-osoby-header']</value>
      <webElementGuid>e1d40422-6233-4c7f-8e5c-f89e1e76392e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/following::span[4]</value>
      <webElementGuid>0cafb864-bc1d-4c14-9ac0-0e1b1b96d418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elektronické prihlášky do škôl'])[1]/following::span[5]</value>
      <webElementGuid>e64345fb-55e6-40ac-a474-701b7d1999a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Môj profil'])[1]/preceding::span[1]</value>
      <webElementGuid>09b9aeaf-ef0a-4cf8-95ff-aafff70d7f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oznámenia'])[1]/preceding::span[1]</value>
      <webElementGuid>af3da778-dd95-4871-a055-4b19d7fcfd23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MM']/parent::*</value>
      <webElementGuid>330075f7-0861-43f0-ba41-56b51571f070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/span</value>
      <webElementGuid>7c39aab7-eb74-4793-912b-721a1cfaada2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'inicialy-osoby-header' and (text() = 'MM' or . = 'MM')]</value>
      <webElementGuid>52d16479-9685-409a-b451-ec2fa9ea6ad3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
