<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(nepovinn)_select-skola</name>
   <tag></tag>
   <elementGuidId>05490edd-6172-43fd-9635-827962462b9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//fieldset/div[1]/div[1]/div[2]/input[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select-skola</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c81f9174-4b1e-442c-9fbb-8e939eb69cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select</value>
      <webElementGuid>afb29983-a54d-4437-9cb4-760a51375ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bbbe3397-18ef-4345-a7df-7ea22d3b2394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-skola</value>
      <webElementGuid>ccf9a94f-e9e1-4655-b95c-13018475f509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VybranaSaszEduId</value>
      <webElementGuid>8db31101-78d9-4a1d-b6d0-de6f2ad5d810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Materská škola Košice SeverElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyGymnázium MetodovaGymnázium v BudimíreMaterská škola Košice KVPStredná odborná škola strojníckaSúkromná stredná odborná školaSúkromná stredná umelecká škola scénického výtvarníctva</value>
      <webElementGuid>03aad654-7b26-485f-93f2-a0443e74268a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-skola&quot;)</value>
      <webElementGuid>042ffb83-3036-49ac-b5c6-829263cedefc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select-skola']</value>
      <webElementGuid>28b94aec-6e87-4117-bd31-b96ab349fef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='skola']/div/div[2]/select</value>
      <webElementGuid>6d35a075-4839-486f-8183-d89421c45053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(nepovinné)'])[1]/following::select[1]</value>
      <webElementGuid>a138861b-c121-44aa-acb9-ea3842541ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vybrať školu'])[1]/following::select[1]</value>
      <webElementGuid>36bc9f26-22f3-4b54-8abb-b6390d14ddb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[1]/preceding::select[1]</value>
      <webElementGuid>9a258ac8-94ab-4dae-811f-3915efbcc635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokračovať'])[1]/preceding::select[1]</value>
      <webElementGuid>e8beb47e-fd11-440e-a127-3042fa10bc3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>34c12083-3ac4-4cd1-a9b6-552f71ec4205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @id = 'select-skola' and @name = 'VybranaSaszEduId' and (text() = 'Materská škola Košice SeverElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyGymnázium MetodovaGymnázium v BudimíreMaterská škola Košice KVPStredná odborná škola strojníckaSúkromná stredná odborná školaSúkromná stredná umelecká škola scénického výtvarníctva' or . = 'Materská škola Košice SeverElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyElokované pracovisko ako súčasť Súkromnej strednej odbornej školyGymnázium MetodovaGymnázium v BudimíreMaterská škola Košice KVPStredná odborná škola strojníckaSúkromná stredná odborná školaSúkromná stredná umelecká škola scénického výtvarníctva')]</value>
      <webElementGuid>5076cb83-c276-4e1b-8f82-6a1d556acd8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
