<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Akcia_govuk-button govuk-button--sec_dea96d</name>
   <tag></tag>
   <elementGuidId>e76068d6-8849-49c6-a95e-c7172f8570e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='riaditel-prihlasky-na-strednu-skolu']/div[3]/div[5]/div[2]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.govuk-button.govuk-button--sec.btn-zobrazit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bef734a7-467c-4b21-ac38-e4c017235168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button govuk-button--sec btn-zobrazit</value>
      <webElementGuid>d0bbcec5-526f-4282-9f89-05f9a55931b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Zobraziť</value>
      <webElementGuid>728184bf-2a8f-47bd-90cc-cd82492b0f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;riaditel-prihlasky-na-strednu-skolu&quot;)/div[@class=&quot;riaditel-prihlasky-nasich-ziakov-container&quot;]/div[@class=&quot;fixed-right-column&quot;]/div[@class=&quot;riaditel-prihlasky-cell akcia-cell&quot;]/div[@class=&quot;akcia-buttons&quot;]/button[@class=&quot;govuk-button govuk-button--sec btn-zobrazit&quot;]</value>
      <webElementGuid>5f6d89d7-4ea2-438e-bbe6-5db596ed57e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='riaditel-prihlasky-na-strednu-skolu']/div[3]/div[5]/div[2]/div/button</value>
      <webElementGuid>7575cec6-7b29-4426-aa3c-8142c5809cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akcia'])[1]/following::button[1]</value>
      <webElementGuid>2618c8d3-d8c3-4c36-adc1-de77818513df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Talent / Netalent'])[3]/following::button[1]</value>
      <webElementGuid>a623bce6-f7c0-4568-97e3-50b66791b512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zobraziť'])[2]/preceding::button[2]</value>
      <webElementGuid>05899d99-f363-4d47-8012-b0156cf90927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zobraziť'])[3]/preceding::button[4]</value>
      <webElementGuid>2cea6a1c-6988-4a1f-af74-0ce74d29fa0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Zobraziť']/parent::*</value>
      <webElementGuid>8eb95a04-4c75-4c6c-a051-4fc92d94d475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/button</value>
      <webElementGuid>b94ee31d-6308-4750-b5d7-16c7b1df784e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Zobraziť' or . = 'Zobraziť')]</value>
      <webElementGuid>c7bc540f-dfb8-4a25-a3c7-fdb55a8f0c09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
