<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sp</name>
   <tag></tag>
   <elementGuidId>c7ca5790-d7ac-40b4-bc8b-50a713a3fd67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='prihlaska']/div/div[2]/div/div/div[11]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn-spat.govuk-button.govuk-button--sec.left-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8836ab6e-9d58-4df2-a9e2-2e0f136f36e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-spat govuk-button govuk-button--sec left-button</value>
      <webElementGuid>430615ae-840f-4de2-9656-e9855632c9c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Späť</value>
      <webElementGuid>6ea71258-5156-4cd0-847b-3c58c2fb93b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prihlaska&quot;)/div[@class=&quot;menu-layout&quot;]/div[@class=&quot;privatna-zona-content&quot;]/div[@class=&quot;govuk-form-group&quot;]/div[@class=&quot;govuk-wizard-steps&quot;]/div[@class=&quot;buttons-container&quot;]/button[@class=&quot;btn-spat govuk-button govuk-button--sec left-button&quot;]</value>
      <webElementGuid>f8fb6a54-f8e0-4118-87d6-1b35de90c6cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prihlaska']/div/div[2]/div/div/div[11]/button</value>
      <webElementGuid>dc1c067f-4766-473e-bb16-cdf700f724ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Viac informácií nájdete tu.'])[1]/following::button[1]</value>
      <webElementGuid>4a6ca874-6dbc-4201-8fa6-0aaf47c74ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uložiť a odísť'])[1]/preceding::button[1]</value>
      <webElementGuid>4816f04a-7d26-46af-9bac-e60c6a16470f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ďalej'])[3]/preceding::button[2]</value>
      <webElementGuid>d3f16b73-be43-491b-bdab-082ba7d8d5ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Späť']/parent::*</value>
      <webElementGuid>23f82d15-2f05-4bfa-875e-d1920603d8c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/button</value>
      <webElementGuid>d2d7cba8-3c06-422d-b894-4a2f13a266a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Späť' or . = 'Späť')]</value>
      <webElementGuid>b12dc097-6a74-446f-9e08-8dfe102c022c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
