<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>086801aa-1a58-45bf-9903-7c024efc971d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.navigation-container.govuk-wizard > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ziadost']/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>528cb486-e1ac-49a9-a89d-8aef9b7945c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ziadost&quot;)/div[@class=&quot;menu-layout&quot;]/div[@class=&quot;navigation-container govuk-wizard&quot;]/div[1]</value>
      <webElementGuid>fe4be8de-dfb9-4835-a67c-6f0c12ca8608</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ziadost']/div/div/div</value>
      <webElementGuid>b42dee82-b811-4e8d-8c00-d4b44354ae15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>fcf3fa29-4e60-449a-a6f6-b9851e55ab31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prihlaska']/div/div/div</value>
      <webElementGuid>8e86e282-d0d9-4059-9394-5caf6676681d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
