<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nmestie Svtho Egdia 45, Poprad (Poprad)_ba3ebb - Copy</name>
   <tag></tag>
   <elementGuidId>ca9dac9c-854e-4aa3-a362-e7e43aa31a8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zakonnyZastupcaAdresaBydliska']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zakonnyZastupca2AdresaBydliska</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>639c00f3-7b49-41de-9772-44bf2d025b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zakonnyZastupca2AdresaBydliska</value>
      <webElementGuid>7df30ac3-52f2-4548-a409-ee2511775e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Námestie Svätého Egídia 45, Poprad (Poprad), Slovenská republika</value>
      <webElementGuid>30a9f9cf-26bf-40ba-9150-25d76c36d651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zakonnyZastupca2AdresaBydliska&quot;)</value>
      <webElementGuid>8cc58c32-f040-4b51-b2fe-0ff4ecda7e5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zakonnyZastupca2AdresaBydliska']</value>
      <webElementGuid>658dea03-6768-4206-8477-42b263510165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz2']/div[4]/div[2]</value>
      <webElementGuid>62805fe7-6b0a-4175-b3e2-07bed559584c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adresa bydliska'])[4]/following::div[1]</value>
      <webElementGuid>cabe28ed-7134-46a0-9060-8b1e7e64a3fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[10]/following::div[3]</value>
      <webElementGuid>00c4dbe5-f31f-4fb2-9ab8-610683b982ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[4]/preceding::div[1]</value>
      <webElementGuid>c3edf185-0e74-4062-9076-d88b99824802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[11]/preceding::div[2]</value>
      <webElementGuid>72f6cd42-20ca-4cf0-ad4c-dd63f2103e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[4]/div[2]</value>
      <webElementGuid>759e913f-f906-4d95-b578-1b7cd13ba1d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zakonnyZastupca2AdresaBydliska' and (text() = 'Námestie Svätého Egídia 45, Poprad (Poprad), Slovenská republika' or . = 'Námestie Svätého Egídia 45, Poprad (Poprad), Slovenská republika')]</value>
      <webElementGuid>be1412fd-6248-4657-a9f4-37847bdfce53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zakonnyZastupcaAdresaBydliska']</value>
      <webElementGuid>0b1bef74-9098-45ab-bfa8-a58b4130a82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz1']/div[4]/div[2]</value>
      <webElementGuid>2a7bbd5c-e553-4751-8805-528a523260e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adresa bydliska'])[3]/following::div[1]</value>
      <webElementGuid>c54e6274-ae42-4a38-9a24-f688f152aa3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E1945657890'])[1]/following::div[3]</value>
      <webElementGuid>02605004-6dbe-4b57-8e04-537945f541c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[3]/preceding::div[1]</value>
      <webElementGuid>ad0ad766-37c7-49d2-9cb4-783f9c301f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[4]/preceding::div[2]</value>
      <webElementGuid>24b92887-122f-4754-9a22-34b278f7dbf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[2]/div[4]/div[2]</value>
      <webElementGuid>c7fb477e-4028-40a4-87eb-ca8611a76870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zakonnyZastupcaAdresaBydliska' and (text() = 'Námestie Svätého Egídia 45, Poprad (Poprad), Slovenská republika' or . = 'Námestie Svätého Egídia 45, Poprad (Poprad), Slovenská republika')]</value>
      <webElementGuid>f3cb9978-6c6f-4cfd-86ad-859c94387f65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
