<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Gemersk cesta 18, Luenec (Luenec), Slov_ef22e0 - Copy</name>
   <tag></tag>
   <elementGuidId>9807b600-774a-4c84-9683-d693630f1247</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zakonnyZastupca2AdresaBydliska']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zakonnyZastupcaAdresaBydliska</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>180b181a-8314-4580-82b1-5c4fcecf99df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zakonnyZastupcaAdresaBydliska</value>
      <webElementGuid>d864101a-93ab-43ee-ba01-ace4cc4817c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gemerská cesta 18, Lučenec (Lučenec), Slovenská republika</value>
      <webElementGuid>680243cf-04d2-42e8-8813-c0486daedbf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zakonnyZastupcaAdresaBydliska&quot;)</value>
      <webElementGuid>73e86818-94d2-4922-a114-fd64038ec6f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zakonnyZastupcaAdresaBydliska']</value>
      <webElementGuid>10cded91-f33c-48b5-986c-2113fd69ce47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz1']/div[4]/div[2]</value>
      <webElementGuid>d467ac36-6278-4858-a565-f18221fd324f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adresa bydliska'])[3]/following::div[1]</value>
      <webElementGuid>ff22a331-ead2-4b71-bc45-d46ae9ffdfa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E2125898753'])[1]/following::div[3]</value>
      <webElementGuid>90bbce7a-b125-42bc-a2c9-08dbdf0666d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[3]/preceding::div[1]</value>
      <webElementGuid>7018c0da-0475-43f2-8894-65e380d432ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[6]/preceding::div[2]</value>
      <webElementGuid>2c1e157a-a3b2-4cf8-abdb-d4df75b0c786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[2]/div[4]/div[2]</value>
      <webElementGuid>5c976f59-071e-4bdc-b8a7-2c3fa72b896b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zakonnyZastupcaAdresaBydliska' and (text() = 'Gemerská cesta 18, Lučenec (Lučenec), Slovenská republika' or . = 'Gemerská cesta 18, Lučenec (Lučenec), Slovenská republika')]</value>
      <webElementGuid>22f39581-d976-49a8-8619-b1b5c7a708a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zakonnyZastupca2AdresaBydliska']</value>
      <webElementGuid>b980f8b3-59eb-44a3-8849-6eecb341a12f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz2']/div[4]/div[2]</value>
      <webElementGuid>d2186b68-1b5e-493e-8338-4053b7bcfe46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adresa bydliska'])[4]/following::div[1]</value>
      <webElementGuid>91c8367f-6251-46ed-a63a-14b37d28d161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[6]/following::div[3]</value>
      <webElementGuid>ff0db380-c82a-43cd-bae3-bf9d215cf62e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[4]/preceding::div[1]</value>
      <webElementGuid>53479887-8c42-4d7b-abd9-aa5bf3a1efbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[7]/preceding::div[2]</value>
      <webElementGuid>2d7b5125-b264-4bb7-ad2c-d8b370a31db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[4]/div[2]</value>
      <webElementGuid>5d034c35-a9e3-40c8-8d51-f75b2a138a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zakonnyZastupca2AdresaBydliska' and (text() = 'Gemerská cesta 18, Lučenec (Lučenec), Slovenská republika' or . = 'Gemerská cesta 18, Lučenec (Lučenec), Slovenská republika')]</value>
      <webElementGuid>b4d2033b-7794-4547-bf18-6811d4941017</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
