<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_22.09.1980</name>
   <tag></tag>
   <elementGuidId>c1df4941-698a-443d-8a90-d4669616513c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zakonnyZastupcaDatumNarodenia</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zakonnyZastupcaDatumNarodenia']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>80bb9b8f-36bc-438e-988d-bb72d7826b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zakonnyZastupcaDatumNarodenia</value>
      <webElementGuid>8de6c48f-afd1-4996-8b2c-3a52e3db012f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>22.09.1980</value>
      <webElementGuid>4bc23239-2eed-4a6d-8e1a-9efbde703c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zakonnyZastupcaDatumNarodenia&quot;)</value>
      <webElementGuid>0501480b-871f-44ff-a3a2-ea6555719924</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zakonnyZastupcaDatumNarodenia']</value>
      <webElementGuid>22a0d8a5-d704-498b-9a73-7872b74e988c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz1']/div[2]/div[2]</value>
      <webElementGuid>2f08a483-403c-487b-916d-a027eb12358d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum narodenia'])[5]/following::div[1]</value>
      <webElementGuid>c5fd6630-97be-4655-8d28-e97853fa4533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emanuel Zelený'])[1]/following::div[3]</value>
      <webElementGuid>cddf6555-c52e-462e-9172-5d845049213d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Číslo elektronickej schránky'])[3]/preceding::div[1]</value>
      <webElementGuid>e300bdfe-bffa-46f3-910c-2c876468a4b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E2125898753'])[1]/preceding::div[2]</value>
      <webElementGuid>0a1421e8-4c88-4304-906b-8149bb173dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='22.09.1980']/parent::*</value>
      <webElementGuid>7a8644b1-faba-49de-bf1b-d476be8636a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[2]/div[2]/div[2]</value>
      <webElementGuid>6be87494-71c6-4e25-adc4-1d301aeabae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zakonnyZastupcaDatumNarodenia' and (text() = '22.09.1980' or . = '22.09.1980')]</value>
      <webElementGuid>eb1eb7e1-993b-44d0-8717-ab63d662d08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zakonnyZastupca2DatumNarodenia']</value>
      <webElementGuid>646c5b1c-cec4-4b11-afa5-35ab4c1346f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz2']/div[2]/div[2]</value>
      <webElementGuid>fdbde629-3bdc-42fd-9b63-98b05150eaf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum narodenia'])[6]/following::div[1]</value>
      <webElementGuid>18d5828d-0e38-4f0a-bd29-75cd88b3bdcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Číslo elektronickej schránky'])[4]/preceding::div[1]</value>
      <webElementGuid>900b4f74-977e-418f-89c1-97768d3fc234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[6]/preceding::div[2]</value>
      <webElementGuid>e2892c3c-136d-4eb8-b980-44dee362dacb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div[2]/div[2]</value>
      <webElementGuid>8903520c-e292-48f0-8daa-d9843c60cb59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zakonnyZastupca2DatumNarodenia' and (text() = '22.09.1980' or . = '22.09.1980')]</value>
      <webElementGuid>341c67c2-9436-46aa-a283-f6348cb26f7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
