<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Luenec</name>
   <tag></tag>
   <elementGuidId>8af56ed4-b5fc-4060-9e39-dc01c5b43a05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dietaMiestonarodenia</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dietaMiestonarodenia']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0224237f-8b63-4b0a-a768-6f6c14ed5170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dietaMiestonarodenia</value>
      <webElementGuid>1dfe7a26-ab81-4269-a0bf-d03729808b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lučenec</value>
      <webElementGuid>ccf26031-3aac-42d8-b90a-392445c9f982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dietaMiestonarodenia&quot;)</value>
      <webElementGuid>6c52ba1e-1ba0-4360-a11d-de9d35624bb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dietaMiestonarodenia']</value>
      <webElementGuid>44a2a7c6-4838-464c-ab9c-ea6d3f32bc46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suhrnny-prehlad']/div[3]/div[2]/div[6]/div[2]</value>
      <webElementGuid>17f26c34-07fa-443f-ace2-61c313397c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Miesto narodenia'])[2]/following::div[1]</value>
      <webElementGuid>b0e4df08-7789-4d35-983a-32b92cd1f235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mužské'])[1]/following::div[3]</value>
      <webElementGuid>89a92eb3-df6d-4f10-81ef-0997ae6b1c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Národnosť'])[2]/preceding::div[1]</value>
      <webElementGuid>007a2768-5835-445f-900b-6c6d2bba5fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='slovenská'])[3]/preceding::div[2]</value>
      <webElementGuid>82b0b9b3-d5d9-413c-9f12-e0eddf6ecfb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lučenec']/parent::*</value>
      <webElementGuid>f99b3840-1e4e-42ad-8ad2-a6db63e6605c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[6]/div[2]</value>
      <webElementGuid>d4705904-dc36-40d8-a62d-f21d0fd19e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dietaMiestonarodenia' and (text() = 'Lučenec' or . = 'Lučenec')]</value>
      <webElementGuid>f0f1af3b-750c-4005-973e-8c9041228f05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
