<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hronov</name>
   <tag></tag>
   <elementGuidId>553cbdd5-8755-4e79-81b8-5ea6b58b6215</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dietaRodnePriezvisko</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dietaRodnePriezvisko']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bede72fd-2086-49a9-97cf-8c726c107518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dietaRodnePriezvisko</value>
      <webElementGuid>05e2f58d-b42b-4b25-9bfd-69ea68fb5aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hronová</value>
      <webElementGuid>2d46ccc4-06bb-4c7a-aed6-e0a5c9ad9c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dietaRodnePriezvisko&quot;)</value>
      <webElementGuid>4095f3ff-e269-4bb8-b7c9-8e9236096f8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dietaRodnePriezvisko']</value>
      <webElementGuid>00b09641-510e-4095-9a70-409b8bac132a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suhrnny-prehlad']/div[3]/div[2]/div[2]/div[2]</value>
      <webElementGuid>e423e612-1788-4bf6-a085-e75b54dd16c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodné priezvisko'])[2]/following::div[1]</value>
      <webElementGuid>a34ac801-e743-4228-8df0-716c4aa380d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alžbeta Hronová'])[1]/following::div[3]</value>
      <webElementGuid>2f86a400-3071-4eda-af65-ab2f164d7a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodné číslo'])[3]/preceding::div[1]</value>
      <webElementGuid>f671371b-22e5-47d4-a565-54828d062eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum narodenia'])[4]/preceding::div[4]</value>
      <webElementGuid>dae70794-ce63-4d9f-b20d-e294f6efa140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hronová']/parent::*</value>
      <webElementGuid>0a0e186b-7028-4eae-9bbe-f2fd5093eba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div[2]</value>
      <webElementGuid>a4714bcb-5e88-4d0d-8a70-4717fd0c6bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dietaRodnePriezvisko' and (text() = 'Hronová' or . = 'Hronová')]</value>
      <webElementGuid>6ca86dba-3e75-406b-9b6c-4c3579658430</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
