<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_-_1_2_3_4_5_6_7_8_9_10</name>
   <tag></tag>
   <elementGuidId>2c6d88cc-04f4-477a-b260-29eefa686a72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dpDietataPoznamka</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dpDietataPoznamka']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf511d37-307a-4ebb-ac79-2b6895540dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dpDietataPoznamka</value>
      <webElementGuid>914912fd-7742-4f75-8c87-57ce94f277d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>dd4b708d-a84b-4495-bde1-e51d3b5b879a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dpDietataPoznamka&quot;)</value>
      <webElementGuid>4db97264-8190-40a4-8592-d130a0620005</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dpDietataPoznamka']</value>
      <webElementGuid>47b4d117-1ba3-4dfe-9073-92fe1c6ec0b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdpDietata']/div[2]/div[5]/div[7]/div[2]</value>
      <webElementGuid>f7220d5b-fd3b-47f4-814b-4bbb345720ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Poznámka'])[1]/following::div[1]</value>
      <webElementGuid>eb92686b-6b1c-406d-96ba-35c05cf519b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testovací popis'])[1]/following::div[3]</value>
      <webElementGuid>2c755e2d-b550-4762-94f7-9c481f57d74c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Späť'])[1]/preceding::div[1]</value>
      <webElementGuid>8c4429ac-1aec-4bf1-a5d4-88d15e82fd4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ďalej'])[1]/preceding::div[1]</value>
      <webElementGuid>350ead85-5ae6-4766-9adc-519e24ba4bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div[5]/div[7]/div[2]</value>
      <webElementGuid>505812d7-c0c0-4798-a3cf-5cf25c0ba21e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dpDietataPoznamka' and (text() = '-' or . = '-')]</value>
      <webElementGuid>222e9463-31a8-4a91-a8f6-290e60f1b03a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
