<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_15.04.1985</name>
   <tag></tag>
   <elementGuidId>6781a552-95ae-4dcb-957e-2198b2d00cf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zakonnyZastupca2DatumNarodenia</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zakonnyZastupca2DatumNarodenia']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>70f8fdc3-c358-4703-b5e2-a4f734239aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zakonnyZastupca2DatumNarodenia</value>
      <webElementGuid>2d555085-58cb-4256-8862-c0de26d02707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>15.04.1985</value>
      <webElementGuid>068ceeee-a7ad-409f-9b52-19439e5b331b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zakonnyZastupca2DatumNarodenia&quot;)</value>
      <webElementGuid>35395935-288f-46a2-a9a2-97d9e1cb4bb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zakonnyZastupca2DatumNarodenia']</value>
      <webElementGuid>b2f67a3c-f2cc-41f9-8200-6712b20f6d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz2']/div[2]/div[2]</value>
      <webElementGuid>cf8b4e57-198a-40b0-bd6b-aa29ae0ddd85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum narodenia'])[6]/following::div[1]</value>
      <webElementGuid>104dddc6-55ed-498c-9c9a-3ac616a635c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elena Hronová'])[1]/following::div[3]</value>
      <webElementGuid>e1c412bf-9c13-448a-bced-7dfabab80c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Číslo elektronickej schránky'])[4]/preceding::div[1]</value>
      <webElementGuid>110b054b-2b17-4b87-bfbd-8bf14df8c215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[10]/preceding::div[2]</value>
      <webElementGuid>4b66eb8e-cc5d-4c72-9d61-a62675f7abcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='15.04.1985']/parent::*</value>
      <webElementGuid>cdcd1f5c-74d4-4fc7-b6f5-4129314c0508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div[2]/div[2]</value>
      <webElementGuid>b75b7d89-fdcb-4f5e-ae13-94b88417d4be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zakonnyZastupca2DatumNarodenia' and (text() = '15.04.1985' or . = '15.04.1985')]</value>
      <webElementGuid>a7b74d12-1990-44e8-b9ed-7eeb49ac798b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zakonnyZastupcaDatumNarodenia']</value>
      <webElementGuid>dad1232b-726a-4f6a-b02d-3fc4289a735b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz1']/div[2]/div[2]</value>
      <webElementGuid>d73d3651-7797-4de9-96ef-9619baee01e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum narodenia'])[5]/following::div[1]</value>
      <webElementGuid>1b55ba40-9768-443b-8db0-c5263dedf48b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Číslo elektronickej schránky'])[3]/preceding::div[1]</value>
      <webElementGuid>f11cb9f7-398a-47d9-8477-aab64cb0c9ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E1945657890'])[1]/preceding::div[2]</value>
      <webElementGuid>f33d4a13-b152-40c2-aa26-60008f1eb01e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[2]/div[2]/div[2]</value>
      <webElementGuid>e9967874-01a2-47fc-86cb-346364244a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zakonnyZastupcaDatumNarodenia' and (text() = '15.04.1985' or . = '15.04.1985')]</value>
      <webElementGuid>8a2ed12c-d85c-4de3-bb65-3dd33b17bda1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
