<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Albeta Hronov</name>
   <tag></tag>
   <elementGuidId>446e66d5-0617-46b5-a5c9-a780b59efc0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dietaMenoAPriezvisko</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dietaMenoAPriezvisko']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b4b4756f-d5ec-408f-98de-25d54fefc501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dietaMenoAPriezvisko</value>
      <webElementGuid>500921b2-1c82-49ec-a479-b58798d22f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alžbeta Hronová</value>
      <webElementGuid>e98a11b9-8de5-4b40-8030-527b6442d27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dietaMenoAPriezvisko&quot;)</value>
      <webElementGuid>e48f78ee-34af-4838-9168-8e401f8b2e35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dietaMenoAPriezvisko']</value>
      <webElementGuid>4882016a-1ba0-4083-8a21-7f4d58f1e8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suhrnny-prehlad']/div[3]/div[2]/div/div[2]</value>
      <webElementGuid>dbeab186-ec75-4a77-aa3d-7e1ec6c70b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meno a priezvisko dieťaťa'])[1]/following::div[1]</value>
      <webElementGuid>928194f9-7945-4ccb-83dd-45a6310ab143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podrobnosti o dieťati'])[1]/following::div[4]</value>
      <webElementGuid>9d237a44-eb02-42df-a885-3db182894060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodné priezvisko'])[2]/preceding::div[1]</value>
      <webElementGuid>4deeaf96-0a2b-4f40-92e7-395c3493988f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hronová'])[1]/preceding::div[2]</value>
      <webElementGuid>fdaee031-bcf3-4bee-9093-b434ef6c1f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alžbeta Hronová']/parent::*</value>
      <webElementGuid>d08dcdac-348c-401c-a005-b8b8d0929f51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[3]/div[2]/div/div[2]</value>
      <webElementGuid>d2c4298b-f611-4739-bdc5-484af5157124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dietaMenoAPriezvisko' and (text() = 'Alžbeta Hronová' or . = 'Alžbeta Hronová')]</value>
      <webElementGuid>b9679df7-4ee1-45db-a19e-ff7743e26405</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
