<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_06.12.2020</name>
   <tag></tag>
   <elementGuidId>d81f4973-e844-48b8-9169-68a5cf90229d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dietaDatumNarodenia</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dietaDatumNarodenia']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2bd15edd-91bd-4f7c-bcef-dbb8c1c156f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dietaDatumNarodenia</value>
      <webElementGuid>1f81dbed-f16c-4e83-868c-a40cbee0c99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>06.12.2020</value>
      <webElementGuid>b329e6a4-5179-47e9-b8c7-853c765451ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dietaDatumNarodenia&quot;)</value>
      <webElementGuid>7cd5fa98-6629-4b3d-888c-fb4b5868b4ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dietaDatumNarodenia']</value>
      <webElementGuid>65347b6d-b6a3-450f-b9ef-bfb29fd7c005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suhrnny-prehlad']/div[3]/div[2]/div[4]/div[2]</value>
      <webElementGuid>7352269f-80c0-4d59-b31b-40fce4bfe465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum narodenia'])[4]/following::div[1]</value>
      <webElementGuid>f2c3b653-680a-4c42-a05b-08ed33e287f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodné číslo'])[3]/following::div[4]</value>
      <webElementGuid>6477099d-da81-4027-8e1b-5c3c214e7aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pohlavie'])[2]/preceding::div[1]</value>
      <webElementGuid>7cc80b9b-3ac3-49f6-bcc5-bb11ba70c222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mužské'])[1]/preceding::div[2]</value>
      <webElementGuid>38525444-ddb3-4485-93c5-ea1838f409f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='06.12.2020']/parent::*</value>
      <webElementGuid>d7de10a9-6b6a-400f-a7be-72c7309f6109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[3]/div[2]/div[4]/div[2]</value>
      <webElementGuid>e2f083c3-1963-4be8-baf0-eb8a6862c823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dietaDatumNarodenia' and (text() = '06.12.2020' or . = '06.12.2020')]</value>
      <webElementGuid>d04e0068-3426-4bc1-b856-dbc61ed8bc5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
