<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Informcie o zkonnom zstupcovi .2</name>
   <tag></tag>
   <elementGuidId>c334de5e-dc3e-4950-bf70-e0bb463ee8b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zastupcovia']/div[2]/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e821d2d7-6ed6-47b5-87ff-fdd6759bc89d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sectionHeader</value>
      <webElementGuid>d03b0192-41e5-4b63-9ab2-f66715fe0568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Informácie o zákonnom zástupcovi č.2:</value>
      <webElementGuid>270f6f68-c928-4f73-8022-b206918b9fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zastupcovia&quot;)/div[@class=&quot;panel-content&quot;]/div[@class=&quot;sectionHeader&quot;]</value>
      <webElementGuid>0419c02a-b527-4e54-a76f-485493a91d2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zastupcovia']/div[2]/div[4]</value>
      <webElementGuid>84237efa-f22c-4278-85aa-b1118f7a2f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IČO zariadenia'])[2]/following::div[3]</value>
      <webElementGuid>a35007a8-31d2-4687-9996-58daef90a28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='zariadenie #1'])[1]/following::div[5]</value>
      <webElementGuid>5360c56a-18d3-4219-9c09-d9b8899f7cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meno a priezvisko'])[2]/preceding::div[1]</value>
      <webElementGuid>92c1399f-bfb4-4941-991c-08327743246a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emanuel Zelený'])[1]/preceding::div[2]</value>
      <webElementGuid>760d213f-836c-4d37-876d-bf39553a8faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Informácie o zákonnom zástupcovi č.2:']/parent::*</value>
      <webElementGuid>4a57f084-e641-43d4-bd6a-5270070fe5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[4]</value>
      <webElementGuid>102bf657-20b0-4b5f-bdcb-e5daf6ed89ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Informácie o zákonnom zástupcovi č.2:' or . = 'Informácie o zákonnom zástupcovi č.2:')]</value>
      <webElementGuid>c2323037-95b1-4e6b-9ddc-306cbd9d5ec9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
