<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nie - Copy</name>
   <tag></tag>
   <elementGuidId>eeac9ba1-0526-4a30-9862-e98ef380f883</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dpDietataStravovanie']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#suhlasDruhehoZZ</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>175cac6e-aa8f-41ef-8641-4b582d608b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suhlasDruhehoZZ</value>
      <webElementGuid>f3eec577-543c-4d71-acd1-b78a4c3daeeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nie</value>
      <webElementGuid>3e5be747-8865-41b5-b046-c2b2ee989058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suhlasDruhehoZZ&quot;)</value>
      <webElementGuid>2ec2e61e-46a7-4f20-a4ea-bf263e8a2153</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='suhlasDruhehoZZ']</value>
      <webElementGuid>67d21290-78fa-4378-bf11-400fa58e886a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz2']/div[7]/div[2]</value>
      <webElementGuid>19687979-8a1a-457d-916a-fbd538f3fcde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Súhlas druhého zákonného zástupcu'])[2]/following::div[1]</value>
      <webElementGuid>e9ecdbb3-6d84-4bf5-a6c5-bb89066170e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[12]/following::div[3]</value>
      <webElementGuid>289f2994-f8d5-428e-bb44-31421813ee1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dôvod nezabezpečenia súhlasu'])[2]/preceding::div[1]</value>
      <webElementGuid>bb5d1580-2aee-447c-a7c3-1615c42c1e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zdravotný - nevie sa podpísať'])[3]/preceding::div[2]</value>
      <webElementGuid>f1ee5200-1784-423b-a722-573d53670a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[7]/div[2]</value>
      <webElementGuid>12b48bf8-7f22-482b-906f-e5de6374569e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'suhlasDruhehoZZ' and (text() = 'Nie' or . = 'Nie')]</value>
      <webElementGuid>1c888591-b2b0-4fef-bf58-53195bcb1264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dpDietataStravovanie']</value>
      <webElementGuid>2cf08edf-ce56-4d43-91e0-55c4d07c9ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdpDietata']/div[2]/div[5]/div[3]/div[2]</value>
      <webElementGuid>6bb0f903-aa69-410a-a4bc-05e447c14905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Záujem o stravovanie v jedálni'])[2]/following::div[1]</value>
      <webElementGuid>bdf9e194-3642-44ea-b524-359b8d658f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Náboženská'])[2]/following::div[3]</value>
      <webElementGuid>f5a7786f-95ab-4f3b-a5e8-4dcb4a959726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Záujem o Školský klub detí'])[2]/preceding::div[1]</value>
      <webElementGuid>f5678fda-9bd8-465a-91e1-7e513f649d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nie'])[6]/preceding::div[2]</value>
      <webElementGuid>8a46c968-4b1b-455d-b58d-45d6a7f33e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div[5]/div[3]/div[2]</value>
      <webElementGuid>d9b7f2e4-3bdb-4dad-b893-279570987c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dpDietataStravovanie' and (text() = 'Nie' or . = 'Nie')]</value>
      <webElementGuid>b5ad5398-746d-4f49-9347-a37cca9f388e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
