<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nie</name>
   <tag></tag>
   <elementGuidId>f444d071-6960-4b89-9e73-16dc66a51e44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#suhlasDruhehoZZ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='suhlasDruhehoZZ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>06a657c3-7a08-4050-a61c-b5281720e60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suhlasDruhehoZZ</value>
      <webElementGuid>89562265-991a-4111-aaea-be0a181f85fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nie</value>
      <webElementGuid>9bc1eb73-c50b-4a07-858d-20dd4b8f20db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suhlasDruhehoZZ&quot;)</value>
      <webElementGuid>0de0bb42-c383-4bbb-a401-5d6450c8bf1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='suhlasDruhehoZZ']</value>
      <webElementGuid>cb6c8b51-8846-4cdf-8a9f-855f0d7e2ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz2']/div[7]/div[2]</value>
      <webElementGuid>fff7398e-7a97-478e-aefc-5883cf19c913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Súhlas druhého zákonného zástupcu'])[2]/following::div[1]</value>
      <webElementGuid>f25c14e4-3f51-477c-a370-ad14276743d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[12]/following::div[3]</value>
      <webElementGuid>099c7f59-4326-4788-8cf4-4d1b6ce10a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dôvod nezabezpečenia súhlasu'])[2]/preceding::div[1]</value>
      <webElementGuid>26bc6b98-989e-4be1-bf5d-ba32413bde0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zdravotný - nevie sa podpísať'])[3]/preceding::div[2]</value>
      <webElementGuid>9b896ad5-7fa3-4bed-b0d2-b5f7aeadee3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[7]/div[2]</value>
      <webElementGuid>c09090f1-9c7e-41ee-9454-69d37c272d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'suhlasDruhehoZZ' and (text() = 'Nie' or . = 'Nie')]</value>
      <webElementGuid>54adcab5-68cd-4e91-9667-9a45ea45bcf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dpDietataStravovanie']</value>
      <webElementGuid>875b1499-6978-466e-8314-abcda8518ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdpDietata']/div[2]/div[5]/div[3]/div[2]</value>
      <webElementGuid>0731a5ce-799b-465d-9264-bf0dc296b9f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Záujem o stravovanie v jedálni'])[2]/following::div[1]</value>
      <webElementGuid>ebac290b-5c93-49b3-941a-9f3d08acf6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Náboženská'])[2]/following::div[3]</value>
      <webElementGuid>03c51700-533b-45e8-a0fb-d7f407f7f87b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Záujem o Školský klub detí'])[2]/preceding::div[1]</value>
      <webElementGuid>325a1080-f4af-4a23-aba5-39b4dc0f3ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nie'])[6]/preceding::div[2]</value>
      <webElementGuid>7200c58f-550b-4f15-b7b5-cac503d0d713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div[5]/div[3]/div[2]</value>
      <webElementGuid>829a07f7-79d6-4544-9bc9-4fb787ca00fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dpDietataStravovanie' and (text() = 'Nie' or . = 'Nie')]</value>
      <webElementGuid>838dd9b2-7c5f-44e8-a355-d0528e504b98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
