<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_20.05.2025</name>
   <tag></tag>
   <elementGuidId>0ca5a69e-cce4-47a1-9f07-aa1e51b18ef8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ziadostDatumPodania</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ziadostDatumPodania']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c9d727f9-3b03-4e9c-9293-23934229990a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ziadostDatumPodania</value>
      <webElementGuid>0c29f5cd-e50d-4b8a-a034-f4545a90ae5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20.05.2025</value>
      <webElementGuid>93a1e2c6-e4cc-47fb-a5c8-e94209a49ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ziadostDatumPodania&quot;)</value>
      <webElementGuid>0e43e5e5-37ef-4ab4-9d16-b04a5f0020c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ziadostDatumPodania']</value>
      <webElementGuid>b30578ad-cfcb-4616-b85f-cf9ee6281d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suhrnny-prehlad']/div[2]/div[2]/div[3]/div[2]</value>
      <webElementGuid>2657adf6-c2ea-4e5f-843f-e10dffaea72e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum podania'])[1]/following::div[1]</value>
      <webElementGuid>898cc7cd-745a-40bd-a933-eb47b48d5171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Školský rok'])[1]/following::div[4]</value>
      <webElementGuid>39dee3c5-e4b3-4371-890d-90e663d856a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Poznámka školy'])[1]/preceding::div[1]</value>
      <webElementGuid>918db724-b400-4db5-a415-6ee5fa3969de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[3]/preceding::div[2]</value>
      <webElementGuid>5459dc79-8255-4295-acf6-9158f2456a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='20.05.2025']/parent::*</value>
      <webElementGuid>cbc3b7ab-f504-472b-b48d-3ef31a385c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/div[2]</value>
      <webElementGuid>6e935d18-0c78-4194-8cae-3b44eb9890c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ziadostDatumPodania' and (text() = '20.05.2025' or . = '20.05.2025')]</value>
      <webElementGuid>5583ba64-a40e-4767-86d1-2217343a25cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
