<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_12345678</name>
   <tag></tag>
   <elementGuidId>4cea08cb-ed94-40e6-ae22-c4066e3759ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.panel-item > #icoZariadenia</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='icoZariadenia'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9240fe24-e6f6-438f-b7f6-5e36068f8c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icoZariadenia</value>
      <webElementGuid>06417818-40fb-47c1-a4e4-382f21bbdcef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12345678</value>
      <webElementGuid>b8c69d88-85d4-4421-93c2-3dbb079967e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zz1&quot;)/div[@class=&quot;panel-item&quot;]/div[@id=&quot;icoZariadenia&quot;]</value>
      <webElementGuid>5f58fd03-90ce-478b-8039-8104b95d539a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='icoZariadenia'])[2]</value>
      <webElementGuid>a46e74dd-6c97-423a-b749-d1cd28c66f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz1']/div[8]/div[2]</value>
      <webElementGuid>7b4b33cb-b989-4fa6-9bde-54fe78347e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IČO zariadenia'])[2]/following::div[1]</value>
      <webElementGuid>288463e9-5c5a-46e0-8d43-e138947cb256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='zariadenie #1'])[1]/following::div[3]</value>
      <webElementGuid>c14e3a05-2393-408a-b6b9-b9a13cdf5d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informácie o zákonnom zástupcovi č.2:'])[1]/preceding::div[2]</value>
      <webElementGuid>22772943-e6d8-4228-866a-1d9267b2c44c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meno a priezvisko'])[2]/preceding::div[3]</value>
      <webElementGuid>ed663cb1-b008-4e9f-9ca6-5e609693a351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='12345678']/parent::*</value>
      <webElementGuid>796fb547-51a9-4d03-bc97-b59c14e29018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[8]/div[2]</value>
      <webElementGuid>a9c53c38-7b7f-427a-a295-f1611577ebf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'icoZariadenia' and (text() = '12345678' or . = '12345678')]</value>
      <webElementGuid>3fdc262d-784d-4cd7-b031-dc032b96c398</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
