<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-adresaTPPSC</name>
   <tag></tag>
   <elementGuidId>decab244-794b-4cca-8360-59fe30578928</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-adresaTPPSC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-adresaTPPSC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d646f3d-baa2-4bc3-aeae-23d8e6ef4f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>f1bd37e6-c94b-49d6-a287-224b80b9c739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b13312c-8b83-4fa1-9e89-f7784a19c8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-adresaTPPSC</value>
      <webElementGuid>3f7803f6-7ea4-4447-a9c6-bf08bd1551fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>1825a27a-347b-44f4-8c65-7e580eae6c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-adresaTPPSC&quot;)</value>
      <webElementGuid>a3dcfc31-72f3-4f12-be10-579da0a698b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-adresaTPPSC']</value>
      <webElementGuid>b97aee5c-9160-4c26-bd28-8296afac5dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adresaTPPSC']/div/div[2]/input</value>
      <webElementGuid>57aa8858-48b5-4fb4-af43-c1abe48db783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[5]/div/div[2]/input</value>
      <webElementGuid>c31c323d-2397-4f9e-a6ff-ceef4713fce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-adresaTPPSC']</value>
      <webElementGuid>1abe336d-c8e3-4fb4-9f0d-7d49627cd436</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
