<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Etick_zsDPDVychovaRadio</name>
   <tag></tag>
   <elementGuidId>98500957-1798-48cc-b50d-38eb88fb33f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zsDPDVychovaRadio_option_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='zsDPDVychovaRadio_option_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6cad41b9-31c7-4c63-ba72-e4b5862b3f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>06c6da74-1bca-4ec7-8f4d-4e426c1beb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zsDPDVychovaRadio_option_1</value>
      <webElementGuid>49bc4c0d-5042-4e4d-86f4-1a00429f4bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zsDPDVychovaRadio</value>
      <webElementGuid>9ad7ac05-27ab-4756-8001-10534cc94582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>054a9f5e-4a8b-49a5-bc9b-e005694ea347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>961961dc-9dbe-45e6-be05-e9a71715d6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zsDPDVychovaRadio_option_1&quot;)</value>
      <webElementGuid>55530c44-75b8-4c6f-932e-5b592b87f4c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zsDPDVychovaRadio_option_1']</value>
      <webElementGuid>959703fd-d46d-4563-bcb4-00be9c207db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zsDPDVychovaRadio']/div/fieldset/div[3]/div[2]/input</value>
      <webElementGuid>981c6818-382d-48ff-b641-004d1b18b6ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/fieldset/div[3]/div[2]/input</value>
      <webElementGuid>973f0527-3a95-4823-b56e-cc6a366061d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'zsDPDVychovaRadio_option_1' and @name = 'zsDPDVychovaRadio' and @type = 'radio']</value>
      <webElementGuid>5d57c622-1cb8-481b-aa9e-23ae7df89c39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
