<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_pohlavieRadio</name>
   <tag></tag>
   <elementGuidId>68a58107-1ef1-485f-8945-03f5d0d1b448</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pohlavieRadio_option_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pohlavieRadio_option_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb28ac05-129d-46e6-8c25-d6b8198e138b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>53d393d8-6104-46d6-860e-079a6c215bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pohlavieRadio_option_0</value>
      <webElementGuid>f914965e-7928-41cf-b245-cb4236862327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pohlavieRadio</value>
      <webElementGuid>7b208a17-2741-4fda-a228-c40cb887e8a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>05f52ce9-275c-4459-91d4-80df4c7dff8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>141ca89d-9704-4ad7-a5cb-0914889e5a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pohlavieRadio_option_0&quot;)</value>
      <webElementGuid>b7a7671c-ff42-4639-9e3f-91f16fa725dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pohlavieRadio_option_0']</value>
      <webElementGuid>e7277405-c8ec-4e35-8e35-d38d58f1d89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pohlavieRadio']/div/fieldset/div[3]/div/input</value>
      <webElementGuid>e07e30cd-fdc5-45ff-a9b2-29bf156d35ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/fieldset/div[3]/div/input</value>
      <webElementGuid>5d15c033-3a4f-4272-810b-cc2d41993628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pohlavieRadio_option_0' and @name = 'pohlavieRadio' and @type = 'radio']</value>
      <webElementGuid>76dbc74d-13da-4f87-bc2c-a03f64c23c35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
