<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-miestoNarodenia</name>
   <tag></tag>
   <elementGuidId>c3d3d9ff-35d5-4549-b7b5-4101c407a098</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-miestoNarodenia</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-miestoNarodenia']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a090f6c-6c8c-4b05-9da2-be775f8e596a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>be0f27a5-aeae-4e1c-b5c6-2dfef29b9f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e23b96ff-d4eb-4c73-ae6f-c52f18f28186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-miestoNarodenia</value>
      <webElementGuid>46b401e2-3d49-41d9-9626-c966160deda7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>4ce7ba43-5f5e-4474-aea1-c864fe0e9033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-miestoNarodenia&quot;)</value>
      <webElementGuid>ad85f19c-a8e8-480a-8411-645e888e3a2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-miestoNarodenia']</value>
      <webElementGuid>aa7ca8b8-fdcb-4462-8217-54bcfd0d866b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='miestoNarodenia']/div/div[2]/input</value>
      <webElementGuid>2c8c81a8-0d1f-4203-8e10-b88b7eab1085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>23caa377-5942-4c75-9496-b809c0c9782c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-miestoNarodenia']</value>
      <webElementGuid>932a0988-3421-4f66-bb71-56f8950ac3a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
