<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_radioGroup-typ-skoly</name>
   <tag></tag>
   <elementGuidId>fbb9e244-5b0e-43eb-abf7-07f0a39feef9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radioGroup-typ-skoly_option_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radioGroup-typ-skoly_option_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cfb502f8-0ffc-4aeb-a751-54c992af2893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>84edeb5c-b8ab-4cb6-a250-e386b1780e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radioGroup-typ-skoly_option_0</value>
      <webElementGuid>2a316f25-3adc-4e17-8f6a-f4bb1751059d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radioGroup-typ-skoly</value>
      <webElementGuid>372ae337-b601-4016-8cbb-5d8d0bf342d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3c39cac6-ed0d-495b-8d16-b1764a2a2525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ZŠ</value>
      <webElementGuid>d4451b47-103a-4038-84a5-e1cb322dae43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radioGroup-typ-skoly_option_0&quot;)</value>
      <webElementGuid>74676357-dd50-445b-8d02-f7948090e2b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radioGroup-typ-skoly_option_0']</value>
      <webElementGuid>a6fad488-3a7f-4cd7-b84d-12abc9d4a8ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radioGroup-typ-skoly']/div/fieldset/div[3]/div/input</value>
      <webElementGuid>f4aacada-e6c9-4169-81b1-ed700d87afa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/fieldset/div[3]/div/input</value>
      <webElementGuid>6ebb99e4-6e70-43d7-8c9b-2bfb3878dfea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'radioGroup-typ-skoly_option_0' and @name = 'radioGroup-typ-skoly' and @type = 'radio']</value>
      <webElementGuid>7a4b3b25-e0a8-4866-8d82-8836e298803f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
