<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-zastupca1CisloSchranky</name>
   <tag></tag>
   <elementGuidId>6b68ef62-15c3-4761-8d14-c93734151c80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-zastupca1CisloSchranky</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-zastupca1CisloSchranky']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3b3de90-3b96-4170-a873-9361506e7b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>7a377177-7589-4d7e-85a1-bf0dc1fd43b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f64ac17a-e53e-4880-a0ca-34e5a0e9419c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-zastupca1CisloSchranky</value>
      <webElementGuid>2fd670bd-0598-4199-9d5f-b00954ffeb5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>1d4f8cd3-bfae-4dc6-bccc-1d1df32f4be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-zastupca1CisloSchranky&quot;)</value>
      <webElementGuid>57df7525-7ae9-421a-b6cb-4826c60b3bca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-zastupca1CisloSchranky']</value>
      <webElementGuid>cfb07254-ba85-4e91-b2fe-45c3e414af0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zastupca1CisloSchranky']/div/div[2]/input</value>
      <webElementGuid>2663051e-8909-4c20-8214-ca98bf71a3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/div/div[2]/input</value>
      <webElementGuid>456c6a74-6415-42a0-b67a-116482dbd7b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-zastupca1CisloSchranky']</value>
      <webElementGuid>112e1b77-76d8-49b1-ae36-fe0c451a521b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
