<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Martin Tlaienka_radioGroup-deti</name>
   <tag></tag>
   <elementGuidId>a83f566b-1f77-490b-b1b5-341769f83025</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radioGroup-deti_option_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radioGroup-deti_option_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f4c3c00-7059-4cc6-9701-81fd5924975d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>8de29ca4-2013-407b-94e6-c30446e275c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radioGroup-deti_option_2</value>
      <webElementGuid>a57f611d-c722-4837-a2fb-9a837bf2939a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radioGroup-deti</value>
      <webElementGuid>6606e1ff-b2f6-4e26-933a-560372d53e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>da3ac3b6-f4ba-42d2-8faa-f0f6f9cd945a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3b692e6d-4f56-4c31-b420-f0faa89a7324</value>
      <webElementGuid>155c2d59-7c15-4e3b-a265-db65f5750178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radioGroup-deti_option_2&quot;)</value>
      <webElementGuid>b65b9129-df5d-473b-8c4c-f41364669367</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radioGroup-deti_option_2']</value>
      <webElementGuid>fb41673a-76eb-4a64-91d0-36e11ab784fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radioGroup-deti']/div/fieldset/div[3]/div[3]/input</value>
      <webElementGuid>22c4ecb7-2064-4949-9b66-14e92455eb47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>b09e66d2-4719-4ae1-b87b-f8f0f6fb733e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'radioGroup-deti_option_2' and @name = 'radioGroup-deti' and @type = 'radio']</value>
      <webElementGuid>a9d51f92-2528-4418-a809-8bffe15d5731</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
