<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Eleonra Schwarzwaldsk_radioGroup-deti</name>
   <tag></tag>
   <elementGuidId>ebfd5ff0-9df5-4256-b97a-c4a5ec631ec6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radioGroup-deti_option_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radioGroup-deti_option_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2334059f-1b91-4551-af84-c9866f7b935e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>c7643bbd-acd6-456e-9a3e-69ecd386c710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radioGroup-deti_option_2</value>
      <webElementGuid>96b23108-9c0c-4a23-920e-09b1f471e0b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radioGroup-deti</value>
      <webElementGuid>cecf2dc0-1483-4d8b-afc6-cc95c5f8f798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>54fa6a67-4589-4278-a0f3-8c0de592ed0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>eeeba84a-75ed-4805-bf8e-e5ca538379f3</value>
      <webElementGuid>1165ac2d-3f3d-4c91-9bfd-dcd481232d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radioGroup-deti_option_2&quot;)</value>
      <webElementGuid>07d30c5d-b5f7-4486-be99-e5559224515d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radioGroup-deti_option_2']</value>
      <webElementGuid>6b4a3f98-0b5d-4b7d-87d3-d4b8b711c17a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radioGroup-deti']/div/fieldset/div[3]/div[3]/input</value>
      <webElementGuid>831bca77-53f5-4c1b-ae19-2087052aa336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>9ba4c4af-5df2-4495-b159-1dc0773fd98a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'radioGroup-deti_option_2' and @name = 'radioGroup-deti' and @type = 'radio']</value>
      <webElementGuid>89c4ead6-4de7-48f2-9802-998c5f41fb69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
