<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-priezvisko</name>
   <tag></tag>
   <elementGuidId>1a397b31-be2d-47fa-bb67-ee31034b7ceb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-priezvisko</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-priezvisko']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>febebcb6-61e1-4eaf-828e-ac71416001bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>1290af44-ddfd-41e3-8772-9ca646ae4952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9d299151-fa5e-4575-876e-f8c63efe9fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-priezvisko</value>
      <webElementGuid>cbc112d0-d39d-4e0a-ba6a-e6d862eac8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>8ed5f48a-1ccf-4637-963b-bcb1b4ca50f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-priezvisko&quot;)</value>
      <webElementGuid>8cd81aa1-ccc6-4738-a3d7-b6122bbf85c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-priezvisko']</value>
      <webElementGuid>79b88ed2-57a1-47c2-adec-aae8cb79d5b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='priezvisko']/div/div[2]/input</value>
      <webElementGuid>c0dd6523-89a2-4d75-a753-d895f766db5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/input</value>
      <webElementGuid>4c80396d-242c-4f02-b56d-3c0a1cf2c463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-priezvisko']</value>
      <webElementGuid>445f3544-12e7-4971-ad0a-7b6da12aeb79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
