<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-adresaTPOrientacneCislo</name>
   <tag></tag>
   <elementGuidId>b1a406f7-9fc7-4e5f-a386-855a5e8597c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-adresaTPOrientacneCislo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-adresaTPOrientacneCislo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b520331-7668-479b-81fd-893f6e37cb91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>b69cbd75-cf4f-4239-b757-00290b91e81d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3a2e2104-3296-4891-97ce-020abf443385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-adresaTPOrientacneCislo</value>
      <webElementGuid>dc56f1d0-2f54-468b-9011-3cea60aa8edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>341939a6-a384-42dc-be00-a7eb43bd9d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-adresaTPOrientacneCislo&quot;)</value>
      <webElementGuid>43c3617a-ff00-4fe3-b435-ae61ee35d2bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-adresaTPOrientacneCislo']</value>
      <webElementGuid>713297c0-8194-4ee4-b652-59a86b15fe0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adresaTPOrientacneCislo']/div/div[2]/input</value>
      <webElementGuid>a43f97ec-9335-4ae5-9cab-faea16b11ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div[2]/input</value>
      <webElementGuid>268fba8f-8ce9-4b87-858e-96133ed0ea90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-adresaTPOrientacneCislo']</value>
      <webElementGuid>5338934c-bbe0-4f3e-8278-1d9b54cbaa42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
