<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-zastupca1InaAdresaPSC</name>
   <tag></tag>
   <elementGuidId>c4a25e0d-6604-4464-a681-85a1cbd2ab02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-zastupca1InaAdresaPSC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-zastupca1InaAdresaPSC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ecb48512-3fcf-42b3-a908-acd1a0723489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>d0d0a75f-1f87-4b41-a60e-ba900d36a7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1616e4b4-b015-4136-9404-7213e6b13881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-zastupca1InaAdresaPSC</value>
      <webElementGuid>51c8e0c3-48f4-4387-934a-e89f78de04c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>5e2430f9-570a-4eb8-944c-4dddbf3c3414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-zastupca1InaAdresaPSC&quot;)</value>
      <webElementGuid>effac5dd-64df-4e14-a7e8-c0a406d83757</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-zastupca1InaAdresaPSC']</value>
      <webElementGuid>2071a4cf-a330-40e9-9f79-235688b23b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zastupca1InaAdresaPSC']/div/div[2]/input</value>
      <webElementGuid>b1c544f9-0a25-41c6-8617-5ddb04364eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/input</value>
      <webElementGuid>e008a5e5-01ce-4dae-87b6-b1b2c9a58a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-zastupca1InaAdresaPSC']</value>
      <webElementGuid>9cdc03c3-5519-46d1-8b76-10c24a4b764d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
