<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_maDietaRCRadio</name>
   <tag></tag>
   <elementGuidId>be820c8b-aca9-41da-aecb-3fe2e2f27a9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#maDietaRCRadio_option_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='maDietaRCRadio_option_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e2d9934-c565-4c53-b314-f7b4ed277d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>34a92b72-bdc7-4961-a78a-3c24b61b1a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maDietaRCRadio_option_0</value>
      <webElementGuid>11311cc0-2286-4b1a-8f18-82ef6dc2cc5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>maDietaRCRadio</value>
      <webElementGuid>d0db18f6-b1aa-4bc4-a3ff-e3e385f20d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4500c6ff-99ca-4419-b717-c82b9f762bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2a0e43c8-f540-46fc-962f-49599e936019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maDietaRCRadio_option_0&quot;)</value>
      <webElementGuid>d66488e5-da0f-4214-b898-823e66ee64fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='maDietaRCRadio_option_0']</value>
      <webElementGuid>e290dc91-a03b-41c3-9a1f-cfe8c4cd45b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maDietaRCRadio']/div/fieldset/div[3]/div/input</value>
      <webElementGuid>53fdddc1-8df6-4ee1-8f60-c022a1004bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>b58bbdab-a5f3-436c-87d8-92ccdecef2c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'maDietaRCRadio_option_0' and @name = 'maDietaRCRadio' and @type = 'radio']</value>
      <webElementGuid>edf621ab-2bf8-4bcd-a017-8449e22e7a49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
