<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Odporuanie veobecnho lekra pre deti _5e1967</name>
   <tag></tag>
   <elementGuidId>7e2ab11c-1d37-435c-8592-af53b882ea3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select-TypPrilohySelect']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select-TypPrilohySelect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c3cd9baf-f549-4137-b359-baa90ce75ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select</value>
      <webElementGuid>e1ce9a48-74ff-435b-acd5-02dd3ad6c4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>259c1af1-c90a-4056-a36c-06e5869e6c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-TypPrilohySelect</value>
      <webElementGuid>1823f4e6-fc0f-4d6f-b001-2442568d0e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Odporučanie všeobecného lekára pre deti a dorastPotvrdenie o zdravotnej spôsobilostiSúhlasné vyjadrenie všeobecného lekára pre deti a dorastVyjadrenie zariadenia poradenstva a prevencie - zdravotné znevýhodnenie</value>
      <webElementGuid>e7667992-6880-4921-b359-0004a9c3ea29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-TypPrilohySelect&quot;)</value>
      <webElementGuid>99279f62-78ce-463a-9777-e6aa1c9b8bfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select-TypPrilohySelect']</value>
      <webElementGuid>f6032cf3-813c-4b61-9280-b750b08fcb51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TypPrilohySelect']/div/div[2]/select</value>
      <webElementGuid>290ec6a5-df2b-4f67-9b71-09607fdca99f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(nepovinné)'])[47]/following::select[1]</value>
      <webElementGuid>f5509cdd-305d-4ae8-b1dd-44bd259c5888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vyberte typ prílohy'])[1]/following::select[1]</value>
      <webElementGuid>7c5b2079-039d-4fb1-9f4c-ae12c7923a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zvoľte, ako chcete nahrať súbor:'])[1]/preceding::select[1]</value>
      <webElementGuid>a4a174f0-f8f4-41b3-a15e-2a84194a173f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Súbory'])[1]/preceding::select[1]</value>
      <webElementGuid>b86e9b30-2b7e-4b37-9a7e-1d871fd931b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>262dfc03-a7fb-422b-adf6-0c79dc784c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @id = 'select-TypPrilohySelect' and (text() = 'Odporučanie všeobecného lekára pre deti a dorastPotvrdenie o zdravotnej spôsobilostiSúhlasné vyjadrenie všeobecného lekára pre deti a dorastVyjadrenie zariadenia poradenstva a prevencie - zdravotné znevýhodnenie' or . = 'Odporučanie všeobecného lekára pre deti a dorastPotvrdenie o zdravotnej spôsobilostiSúhlasné vyjadrenie všeobecného lekára pre deti a dorastVyjadrenie zariadenia poradenstva a prevencie - zdravotné znevýhodnenie')]</value>
      <webElementGuid>7b8df188-81d7-4712-bc31-b3c708c60713</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
