<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_(nepovinn)_textarea-OUPoznamkaText</name>
   <tag></tag>
   <elementGuidId>076b6fd1-2f56-4320-b29c-7ed5ac694dd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textarea-OUPoznamkaText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='textarea-OUPoznamkaText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8fc30f3f-ed6d-41f2-86ee-2c3fe00b84bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-textarea</value>
      <webElementGuid>b8550661-2aa7-4cef-b09f-fd7d3e0441f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>2b30b53a-9706-442d-bdd0-170e5f01f779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textarea-OUPoznamkaText</value>
      <webElementGuid>c8c14b0a-9518-4a4a-a0fb-424c6827429e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>af797ce4-2011-4051-9c7b-282472b5f673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textarea-OUPoznamkaText&quot;)</value>
      <webElementGuid>740cd564-e8d3-4439-a2b0-ba0acfda6e37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textarea-OUPoznamkaText']</value>
      <webElementGuid>c20ec29f-db37-4f85-bfe3-34879d00f0f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OUPoznamkaText']/div/div[2]/textarea</value>
      <webElementGuid>d59240b5-ada0-40b0-8c79-e965b1856b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/textarea</value>
      <webElementGuid>43e4c146-eff4-48f2-b049-af92ebdfc245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'textarea-OUPoznamkaText']</value>
      <webElementGuid>e37089d9-c69b-44ca-ba45-110b05d83abc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
