<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Exportova PDF_btn-oznacit-ako-skontrolovana</name>
   <tag></tag>
   <elementGuidId>35edf999-f2ee-43b1-9262-1594df90f9e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-oznacit-ako-skontrolovana']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-oznacit-ako-skontrolovana</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>07708400-a5a0-4398-9878-de2773825b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-oznacit-ako-skontrolovana</value>
      <webElementGuid>f6f1b5f3-f1d5-4967-ad14-28a7520b56aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button govuk-button--sec red green</value>
      <webElementGuid>3b26f738-c5eb-48fa-b084-b479ef6a31cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fce1670c-5f1e-4ada-9bcf-9c32462cac92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-module</name>
      <type>Main</type>
      <value>govuk-button</value>
      <webElementGuid>6a0f7ab4-21e6-40f8-9014-58bead3a1ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Označiť ako skontrolovaná</value>
      <webElementGuid>c7809845-b76d-49d1-a3ba-35a8b2fbebd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-oznacit-ako-skontrolovana&quot;)</value>
      <webElementGuid>f80d9f0c-b5f5-43f2-b7d9-1ca300fc7d40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-oznacit-ako-skontrolovana']</value>
      <webElementGuid>1493fa2b-a47d-4b36-8dcf-8c3c3040106a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='detail-prihlasky-riad-SS-content']/div[2]/button</value>
      <webElementGuid>b76e196d-18b8-4ce6-9a46-655341470a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exportovať PDF'])[1]/following::button[1]</value>
      <webElementGuid>8cadf174-5c44-4d12-8d32-0d05940573af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pridávajte dokumenty a upravujte informácie podľa potreby.'])[1]/following::button[1]</value>
      <webElementGuid>e36abec5-ad53-42d0-bec7-28fd4b0c0378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vyzvať na riešenie konfliktu'])[1]/preceding::button[1]</value>
      <webElementGuid>aa2e0ec8-96dd-4ce5-a52a-fbec4d444f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vyriešiť konflikt'])[1]/preceding::button[2]</value>
      <webElementGuid>4d269200-e9c2-422d-b48c-5efb6814cd5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Označiť ako skontrolovaná']/parent::*</value>
      <webElementGuid>fb3a2d35-434c-4f53-be88-a64a46e19edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div[2]/button</value>
      <webElementGuid>653faf2d-907d-4618-a7c5-9f9982549b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-oznacit-ako-skontrolovana' and @type = 'submit' and (text() = 'Označiť ako skontrolovaná' or . = 'Označiť ako skontrolovaná')]</value>
      <webElementGuid>d2f5c122-ad01-4fd8-8028-52d84b5fcff8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
