<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Stav kontroly_stavKontroly badge red</name>
   <tag></tag>
   <elementGuidId>13c345f7-7dc9-4208-b098-f33196680dc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='stavKontroly badge']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.stavKontroly.badge.red</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a2e69639-cefe-40bd-bdfb-fa96ce671e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>stavKontroly badge red</value>
      <webElementGuid>bc3b2011-41f5-4f5e-82a7-6403d00832ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Neskontrolovaná</value>
      <webElementGuid>a7a36aae-efe8-41fb-9f1c-cd0016592c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detail-prihlasky-riad-SS-content&quot;)/div[@class=&quot;panel-with-header&quot;]/div[@class=&quot;panel-content info-layout vseobecne-body&quot;]/div[@class=&quot;panel-item column&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;stavKontroly badge red&quot;]</value>
      <webElementGuid>4de76db7-2666-4605-9b8e-c979b5ec4950</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='detail-prihlasky-riad-SS-content']/div[4]/div[2]/div[10]/div[3]/div[2]</value>
      <webElementGuid>f1224b28-0bd0-4200-b4ff-183f3d6a65cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stav kontroly'])[1]/following::div[1]</value>
      <webElementGuid>b08381f2-1136-4037-ba34-6ad6e3ecf63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vyberte'])[2]/following::div[3]</value>
      <webElementGuid>69fc2255-0987-48f7-a2be-2cc647d8aef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Poznámka školy'])[1]/preceding::div[1]</value>
      <webElementGuid>7ff90424-2252-4e08-926e-e30210f0d6cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upraviť'])[3]/preceding::div[2]</value>
      <webElementGuid>8bfb85c7-4515-4052-8dd9-df323ffd48c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Neskontrolovaná']/parent::*</value>
      <webElementGuid>3c3b8e6e-e58d-4df3-868c-546cd92ba2e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[3]/div[2]</value>
      <webElementGuid>0346287b-cae2-423b-b5b2-86f0e4328516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Neskontrolovaná' or . = 'Neskontrolovaná')]</value>
      <webElementGuid>e9eb9497-fc26-4019-a744-ed91ca7383d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
