<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nzov zkladnej koly_nazovZSSuhrn</name>
   <tag></tag>
   <elementGuidId>2464c7b3-ed06-4a34-a945-bb51f83fac49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='info-o-zs']/div[2]/div[3]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.nazovZSSuhrn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3180f1a0-12d5-48cb-a5a8-9fc61a41691f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nazovZSSuhrn</value>
      <webElementGuid>8b623d63-9055-4cda-b8f8-981d55f128cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Základná škola s materskou školou, Soblahov 404</value>
      <webElementGuid>8255d2f0-a03e-451e-91bf-8693a6a3bfe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;info-o-zs&quot;)/div[@class=&quot;panel-content info-layout&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;nazovZSSuhrn&quot;]</value>
      <webElementGuid>8e095db9-3ab4-4dc0-a7e7-538a69b169bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='info-o-zs']/div[2]/div[3]/div[2]</value>
      <webElementGuid>1b33663d-4797-47c3-bf15-46fa00fcce44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov základnej školy'])[1]/following::div[1]</value>
      <webElementGuid>b9a0159d-3cd6-47bb-bb03-08c0c214f85c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EDUID základnej školy'])[1]/following::div[4]</value>
      <webElementGuid>a60ad764-9f33-42dc-8a77-7b8718b86dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ročník'])[1]/preceding::div[1]</value>
      <webElementGuid>07c92519-6c09-43a3-97e2-531bbf27be91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trieda'])[1]/preceding::div[4]</value>
      <webElementGuid>d64f0a47-fe21-461e-8f1b-46eec692e0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Základná škola s materskou školou, Soblahov 404']/parent::*</value>
      <webElementGuid>289a3378-dc85-4474-ba50-0450081fa872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div[3]/div[2]</value>
      <webElementGuid>d40449b0-231a-49cf-8535-d1cf536532f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Základná škola s materskou školou, Soblahov 404' or . = 'Základná škola s materskou školou, Soblahov 404')]</value>
      <webElementGuid>d7b7ec04-5dfd-46db-8e48-a4825bfe7096</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
