<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sprvanie_red-span_1</name>
   <tag></tag>
   <elementGuidId>d6cbdc3a-c54d-426f-adeb-7ffa206c53bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vysledky-vzdelavania']/div[2]/div[5]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bbef9b1a-b149-4e51-9372-aab22deedc17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>red-span</value>
      <webElementGuid>3102e5ad-ab11-484f-ae34-a47f7971c1f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>veľmi dobré</value>
      <webElementGuid>5fcb3bc5-f49e-4ed9-acef-fd5f1ca5d347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vysledky-vzdelavania&quot;)/div[@class=&quot;panel-content&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;red-span&quot;]</value>
      <webElementGuid>257d07fb-df5a-45e7-91bd-f349ec9bb3a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vysledky-vzdelavania']/div[2]/div[5]/div[2]</value>
      <webElementGuid>90e7ef23-681a-46be-b599-02f0a6e5ad7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Správanie'])[2]/following::div[1]</value>
      <webElementGuid>ba1c551a-cf5d-4078-89b5-817552fc3fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='veľmi dobré'])[1]/following::div[5]</value>
      <webElementGuid>181c82ab-c2cd-4082-b844-e74fe0816f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Správanie'])[3]/preceding::div[3]</value>
      <webElementGuid>8acd6930-9f8f-4e0b-822f-ef5a41cc5cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='veľmi dobré'])[3]/preceding::div[4]</value>
      <webElementGuid>24b54494-e91d-4e0e-be61-d25705b4094a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div[5]/div[2]</value>
      <webElementGuid>8a672633-7220-4a4f-b6f3-ab1f02d4260f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'veľmi dobré' or . = 'veľmi dobré')]</value>
      <webElementGuid>5aeed77e-faf0-4242-b011-97e9c6f1d2a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
