<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Stav kontroly_stavKontroly badge red - Copy</name>
   <tag></tag>
   <elementGuidId>0939a13c-9904-4944-8eaf-94f904383e9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='stavKontroly badge red']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.stavKontroly.badge.red</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>64897919-11fb-48ed-af56-9eff367f29df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>stavKontroly badge red</value>
      <webElementGuid>0431808b-18fb-427a-9f6b-d00502e95779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Neskontrolovaná</value>
      <webElementGuid>8e2f1109-d8e6-4368-b607-b0785af5b556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detail-prihlasky-riad-SS-content&quot;)/div[@class=&quot;panel-with-header&quot;]/div[@class=&quot;panel-content info-layout vseobecne-body&quot;]/div[@class=&quot;panel-item column&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;stavKontroly badge red&quot;]</value>
      <webElementGuid>d81f2663-5b03-498d-9bf3-5752b98b8eb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='detail-prihlasky-riad-SS-content']/div[4]/div[2]/div[10]/div[3]/div[2]</value>
      <webElementGuid>17abb563-8320-4a1f-8a51-07186484b001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stav kontroly'])[1]/following::div[1]</value>
      <webElementGuid>cbad32cc-53f8-4ff5-a667-2820a5066dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vyberte'])[2]/following::div[3]</value>
      <webElementGuid>fcc5cad7-9766-4389-b482-2a9c78763570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Poznámka školy'])[1]/preceding::div[1]</value>
      <webElementGuid>8ab1632e-3f7c-455f-88c4-3c2b48a3ad05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upraviť'])[3]/preceding::div[2]</value>
      <webElementGuid>b13cc673-1283-4ff5-9224-41a55d997db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Neskontrolovaná']/parent::*</value>
      <webElementGuid>e6146dc8-a35c-4ecc-a566-7b7657db1019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[3]/div[2]</value>
      <webElementGuid>d8689ae4-67e0-4dfa-af17-860d43f0d25f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Neskontrolovaná' or . = 'Neskontrolovaná')]</value>
      <webElementGuid>4164c83d-e130-45ee-8b4e-28abc8a58e8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
