<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sprvanie_red-span_2</name>
   <tag></tag>
   <elementGuidId>7e360694-128e-422d-be0e-3b9e4d83776c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vysledky-vzdelavania']/div[2]/div[8]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1ee92b89-5d5f-4d7b-b1c9-3c6ecc7d235c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>red-span</value>
      <webElementGuid>aeec4898-a75e-43da-8e6b-aad130bc7957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>veľmi dobré</value>
      <webElementGuid>59e03465-c938-4786-859c-a5e6feeec7d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vysledky-vzdelavania&quot;)/div[@class=&quot;panel-content&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;red-span&quot;]</value>
      <webElementGuid>9845906e-073b-4ec3-8ca6-1cc0946c5cef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vysledky-vzdelavania']/div[2]/div[8]/div[2]</value>
      <webElementGuid>10967443-004d-495d-9e91-ff544a11321c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Správanie'])[3]/following::div[1]</value>
      <webElementGuid>b0286a52-0d1b-4912-88e3-22111a6c17f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='veľmi dobré'])[2]/following::div[5]</value>
      <webElementGuid>af8daf26-52d0-49e5-9442-7dce2b03245f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Správanie'])[4]/preceding::div[3]</value>
      <webElementGuid>d4c2fa3e-1b75-4249-9350-391646d40e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='veľmi dobré'])[4]/preceding::div[4]</value>
      <webElementGuid>1ae1bdc8-d725-4c75-ab82-3b8f952eeb2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div[8]/div[2]</value>
      <webElementGuid>d48cde09-9e00-4351-9c6b-588340d0ebb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'veľmi dobré' or . = 'veľmi dobré')]</value>
      <webElementGuid>29157ecc-14ec-428b-b02c-06014615efc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
