<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sprvanie_red-span_3</name>
   <tag></tag>
   <elementGuidId>b32f34bf-ffec-40ed-b28a-d84ca797dd09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vysledky-vzdelavania']/div[2]/div[11]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eb1c98ff-80a3-48be-9004-36dc5e3658a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>red-span</value>
      <webElementGuid>be73887e-eb27-4265-901b-eb0aea3c4dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>veľmi dobré</value>
      <webElementGuid>758ce961-4f1b-4def-8424-29e100f06258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vysledky-vzdelavania&quot;)/div[@class=&quot;panel-content&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;red-span&quot;]</value>
      <webElementGuid>a2feba01-a052-4d70-85cf-179ca636b37a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vysledky-vzdelavania']/div[2]/div[11]/div[2]</value>
      <webElementGuid>62b04349-dbbd-4598-b511-3d112f6b407a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Správanie'])[4]/following::div[1]</value>
      <webElementGuid>e4f18bd0-0dad-47e4-80c0-067dd2eea629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='veľmi dobré'])[3]/following::div[5]</value>
      <webElementGuid>09f5fe59-a76d-4765-bc46-c76bdd85b66a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Výsledky testovania 9'])[1]/preceding::div[1]</value>
      <webElementGuid>00f72af6-a3dc-469d-a462-b98b89f4e085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add'])[8]/preceding::div[2]</value>
      <webElementGuid>c90ae020-a1e3-4208-8e73-fb8c485056de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div[11]/div[2]</value>
      <webElementGuid>bd9c08d9-0ca5-4cba-9267-7ac8c7d45d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'veľmi dobré' or . = 'veľmi dobré')]</value>
      <webElementGuid>40d90070-6049-4744-bf43-9034ffd8d73a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
