<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Dtum podania_vseobecne-datum-podania</name>
   <tag></tag>
   <elementGuidId>4f5f3c81-6a1f-42bc-bb14-674e5982b95f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='vseobecne-datum-podania']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vseobecne-datum-podania</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e6a9df54-ad15-4e8e-bfb3-22d63cbf2f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vseobecne-datum-podania</value>
      <webElementGuid>86eed85b-eef0-4576-b85a-6d34534e9743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>24.02.2026</value>
      <webElementGuid>c50fef39-0d6d-47c0-acd0-f1e32ce78d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vseobecne-datum-podania&quot;)</value>
      <webElementGuid>558b149b-eb1e-478c-b5ab-7cac1da7956a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='vseobecne-datum-podania']</value>
      <webElementGuid>2c80cd74-00af-47db-8bed-bd895604a8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vseobecne-datum-podania-read']/span</value>
      <webElementGuid>60d35175-4136-47ad-ba07-3427787d803f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum podania'])[1]/following::span[1]</value>
      <webElementGuid>30bda816-3830-4da0-9823-7bf3b7041cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Školský rok'])[1]/following::span[1]</value>
      <webElementGuid>6ff26cf4-a9e9-4e8b-9a67-b4e2152b4dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upraviť'])[2]/preceding::span[1]</value>
      <webElementGuid>b9ef51cf-982d-44b8-a5e3-be4a00d632c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spôsob podania'])[1]/preceding::span[1]</value>
      <webElementGuid>04a8d043-c2f7-423f-afff-65e78f40e003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='24.02.2026']/parent::*</value>
      <webElementGuid>0ee979b7-3083-4bd1-a3fe-f42610df034d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/span</value>
      <webElementGuid>62b909bf-648f-4eb3-970e-68b4913222cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'vseobecne-datum-podania' and (text() = '24.02.2026' or . = '24.02.2026')]</value>
      <webElementGuid>7eb1784a-cb12-4552-b8fc-8fa776582cdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
