<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nahran_govuk-accordion__section-desc-te_b9349f</name>
   <tag></tag>
   <elementGuidId>32186881-25c7-4453-bfb9-9088d638f72c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.govuk-accordion__section-desc-text-focus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='acc-heading-']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b22dfbde-9bd0-499a-8b74-020c0f52888e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-accordion__section-desc-text-focus</value>
      <webElementGuid>1f22c92a-5671-4106-bfaf-23650a02aab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Čestné vyhlásenie zákonného zástupcu — ak získanie podpisu druhého zákonného zástupcu je spojené s ťažko prekonateľnou prekážkou a je to v najlepšom záujme dieťaťa.  [ Uložiť vzor ]</value>
      <webElementGuid>10ec15a8-02de-456a-b8f8-5fc1ff34dd71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acc-heading-&quot;)/div[@class=&quot;govuk-accordion__section-desc-text-focus&quot;]</value>
      <webElementGuid>0d0c5f5e-606f-4285-bc9a-8b11fcf2c920</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='acc-heading-']/div[2]</value>
      <webElementGuid>2fae7a0e-73ae-401f-aea3-407bc895e5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nahrané'])[1]/following::div[1]</value>
      <webElementGuid>08764ecf-c0f6-4da6-af89-53e068e114e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nenahrané'])[2]/following::div[2]</value>
      <webElementGuid>c1cd0cda-be62-4cd8-a9fd-e20fe31f9c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add'])[1]/preceding::div[1]</value>
      <webElementGuid>bb2f7dbd-a4a2-4c80-87de-23e572498911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Čestné vyhlásenie zákonného zástupcu — ak získanie podpisu druhého zákonného zástupcu je spojené s ťažko prekonateľnou prekážkou a je to v najlepšom záujme dieťaťa.']/parent::*</value>
      <webElementGuid>36e47022-23ae-49b5-9e24-ab41dd159f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>1ca60f14-3f9e-464f-9d94-79c790773d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Čestné vyhlásenie zákonného zástupcu — ak získanie podpisu druhého zákonného zástupcu je spojené s ťažko prekonateľnou prekážkou a je to v najlepšom záujme dieťaťa.  [ Uložiť vzor ]' or . = 'Čestné vyhlásenie zákonného zástupcu — ak získanie podpisu druhého zákonného zástupcu je spojené s ťažko prekonateľnou prekážkou a je to v najlepšom záujme dieťaťa.  [ Uložiť vzor ]')]</value>
      <webElementGuid>abddf5c8-57a8-4fcb-b910-8251b2546783</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
