<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-prij__edit_datumDen</name>
   <tag></tag>
   <elementGuidId>82d930b6-7264-4c80-a9d8-db06e6b99d68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-prij__edit_datumDen']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-prij__edit_datumDen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4fe2dae3-0417-4fd2-8e6e-b0d0a29acb60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>9c51d471-9985-49f2-b9d3-6d1589c13051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3d43c187-888c-4002-9495-513b0c415632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-prij__edit_datumDen</value>
      <webElementGuid>1b5bdeea-c901-41ac-a5a2-dc520e4095d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7928b826-0587-4df8-ae6a-fc07baa3dee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD</value>
      <webElementGuid>fca84b0f-f0fb-4ad6-b9d9-07958af04cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-prij__edit_datumDen&quot;)</value>
      <webElementGuid>38e59f99-e0ca-40ee-965f-479875640514</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-prij__edit_datumDen']</value>
      <webElementGuid>daf81621-76cf-4608-a132-7f5d831373a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prij__edit_datumDen']/div/div[2]/input</value>
      <webElementGuid>59102dab-0774-47d2-85b7-2fc22965a9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/div/div[2]/input</value>
      <webElementGuid>8a80f108-b528-4531-8806-dba28e92d511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-prij__edit_datumDen' and @placeholder = 'DD']</value>
      <webElementGuid>3dad0452-d915-4602-b27d-9b1d45a5d994</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
