<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-prij__edit_casHodina</name>
   <tag></tag>
   <elementGuidId>60565c08-8fb3-4aea-a0d1-6d04c222c246</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-prij__edit_casHodina']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-prij__edit_casHodina</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e296da91-fc88-4f28-9485-1d333a205dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>102f8cb1-b402-4cd8-95f9-a86e7a1b0860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d7035064-628f-4b67-b734-647f7612a0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-prij__edit_casHodina</value>
      <webElementGuid>83ae945c-0c68-4d12-896d-f9814f085de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1ddaba5a-feab-42fb-8716-b2c510595220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>HH</value>
      <webElementGuid>3375bee7-d681-4e81-a553-ccda3cc1e65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-prij__edit_casHodina&quot;)</value>
      <webElementGuid>2aa4c5dc-8b78-4449-a07a-65769691f853</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-prij__edit_casHodina']</value>
      <webElementGuid>f00d8595-0526-448e-a57d-0b3c83f57c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prij__edit_casHodina']/div/div[2]/input</value>
      <webElementGuid>fe29663a-21fb-4c22-b5e7-b62ac617d265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>39d7c8db-4d86-4b72-94b9-af182134f2a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-prij__edit_casHodina' and @placeholder = 'HH']</value>
      <webElementGuid>b0a8e028-4506-48be-be0d-8f693db9778a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
