<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dlh</name>
   <tag></tag>
   <elementGuidId>0c4f16e0-8e46-4fe0-a724-e4980dc565a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dietaRodnePriezvisko']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dietaRodnePriezvisko</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b16d78bd-bbb1-46df-9e7d-eaca9d5e5fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dietaRodnePriezvisko</value>
      <webElementGuid>d76d45b1-a7d3-4c97-8e0b-a6ace5032846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dlhá</value>
      <webElementGuid>0f5bf30e-bdce-46b8-962f-9229ad895ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dietaRodnePriezvisko&quot;)</value>
      <webElementGuid>66253ffd-7fcc-4b35-821e-079850c48d76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dietaRodnePriezvisko']</value>
      <webElementGuid>fd12590d-2143-4de4-837f-e1693359209a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suhrnny-prehlad']/div[3]/div[2]/div[2]/div[2]</value>
      <webElementGuid>32b10bd4-2258-47a9-84cd-2a9619060ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodné priezvisko'])[2]/following::div[1]</value>
      <webElementGuid>c0961407-5603-45c3-8946-de2391282466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Petra Dlhá'])[1]/following::div[3]</value>
      <webElementGuid>5020d933-ca9c-435b-bfa8-ec570c2e5bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodné číslo'])[3]/preceding::div[1]</value>
      <webElementGuid>9eeaf1ca-0d25-4351-9f61-05b96bdc528c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[4]/preceding::div[2]</value>
      <webElementGuid>8e74fb6e-2098-4c21-a628-18c281f05fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div[2]</value>
      <webElementGuid>053ee62f-b893-475a-a967-55babd3a6342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dietaRodnePriezvisko' and (text() = 'Dlhá' or . = 'Dlhá')]</value>
      <webElementGuid>aa50de5f-ce9a-42c2-8c8f-622183885564</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
