<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-zastupca1DatumNarodenia</name>
   <tag></tag>
   <elementGuidId>67d016c0-9acf-4f13-9d43-723d427e0bee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-zastupca1DatumNarodenia']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-zastupca1DatumNarodenia</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>582bcf7b-08be-4120-8226-acc44c492f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>2d867dc2-9507-46e4-bc2e-33953d9f3aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6cdf76d4-46ee-4ad5-85e7-d658d4aae937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-zastupca1DatumNarodenia</value>
      <webElementGuid>a58d3b8d-a970-493c-aacf-439f99eed018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD.MM.YYYY</value>
      <webElementGuid>23dde283-e1d0-4f02-8f8c-b43334c1923a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>3e58a843-792c-4005-9e2a-ccc4b974b48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-zastupca1DatumNarodenia&quot;)</value>
      <webElementGuid>123c466e-66d1-4440-9c4c-954b3b97eb0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-zastupca1DatumNarodenia']</value>
      <webElementGuid>08f4f1cd-5934-4a4d-851f-7f788e97a761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zastupca1DatumNarodenia']/div/div[2]/span/input</value>
      <webElementGuid>3268346f-2170-42bc-9044-90e8e4f36cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/span/input</value>
      <webElementGuid>6ebcbfca-d7c6-4176-a5f6-f77e76c6ac55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-zastupca1DatumNarodenia' and @placeholder = 'DD.MM.YYYY']</value>
      <webElementGuid>da63b29c-0617-4c74-9865-0e059f519000</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
