<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_no_maDietaRCRadio</name>
   <tag></tag>
   <elementGuidId>500681e1-547a-4390-92d6-12787ac4b733</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='maDietaRCRadio_option_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#maDietaRCRadio_option_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1280b5b3-8268-4cac-b57a-775f7dc2a0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>21ce5a94-d52b-4e91-9248-c973538da811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maDietaRCRadio_option_1</value>
      <webElementGuid>1b3b02ec-831e-4e40-b347-812cbad6ff8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>maDietaRCRadio</value>
      <webElementGuid>5b87f575-9948-407e-8461-a6d131606862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>57bcca65-c7a8-4fca-a1c2-8f46bc249f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>07f3ae8a-aea0-4ff0-af79-10a918152fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maDietaRCRadio_option_1&quot;)</value>
      <webElementGuid>04f3bee2-5057-4b59-a7c2-76706d95331e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='maDietaRCRadio_option_1']</value>
      <webElementGuid>3ef551be-cbc9-40dc-909b-d9c023bd022c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maDietaRCRadio']/div/fieldset/div[3]/div[2]/input</value>
      <webElementGuid>13992421-6698-46bc-954b-d2ae0f4ada52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>725adb16-bb01-466e-8726-4ae71bd2ca7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'maDietaRCRadio_option_1' and @name = 'maDietaRCRadio' and @type = 'radio']</value>
      <webElementGuid>eec5dbf1-5e1a-4490-8847-b1898d1d13f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
