<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Rozhodnutie sduPotvrdenie od veobecn_b7915e</name>
   <tag></tag>
   <elementGuidId>66c60054-4c1d-4dd4-b362-8dd2aabdbf7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select-TypPrilohySelect']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select-TypPrilohySelect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7ed897fc-9127-4758-b6e7-c146327a8094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select</value>
      <webElementGuid>bdfd4e7f-d711-4fac-a1f3-0d3cc6aaa2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e09702b1-9aac-45c7-9a05-680cd88068dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-TypPrilohySelect</value>
      <webElementGuid>00d7c205-939b-4920-862b-d6735b60d4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rozhodnutie súduPotvrdenie od všeobecného lekára zákonného zástupcu (ktorý nie je schopný sa podpísať)Čestné vyhlásenie zákonného zástupcuPotvrdenie o zdravotnej spôsobilostiOdporúčanie všeobecného lekára pre deti a dorastVyjadrenie zariadenia poradenstva a prevencie - zdravotné znevýhodnenie/nadanieIná</value>
      <webElementGuid>d3dac367-b7fd-4b1f-8147-2a14d822264c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-TypPrilohySelect&quot;)</value>
      <webElementGuid>a3123764-dab8-48dc-af9e-c4f6056fc03e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select-TypPrilohySelect']</value>
      <webElementGuid>d977aa43-4eac-4181-b0a7-e664762b84f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TypPrilohySelect']/div/div[2]/select</value>
      <webElementGuid>26fc842d-46c3-414e-a60b-056b67ab02d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(nepovinné)'])[70]/following::select[1]</value>
      <webElementGuid>3e0cd8cd-42ac-474e-b2d6-82fe0baf0caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vyberte typ prílohy'])[1]/following::select[1]</value>
      <webElementGuid>30e2f522-69fc-4fc0-b090-d0638df43edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nahrajte súbor'])[1]/preceding::select[1]</value>
      <webElementGuid>710d0b1e-af19-4fc8-a195-fbbbdae9897c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='alebo ho sem potiahnite (max. 10 MB)'])[1]/preceding::select[1]</value>
      <webElementGuid>9e1ca7f1-1554-4584-98ab-50e1bd4298b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a86d4ebc-cc3f-45e6-8d1a-834e50c4a9ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @id = 'select-TypPrilohySelect' and (text() = 'Rozhodnutie súduPotvrdenie od všeobecného lekára zákonného zástupcu (ktorý nie je schopný sa podpísať)Čestné vyhlásenie zákonného zástupcuPotvrdenie o zdravotnej spôsobilostiOdporúčanie všeobecného lekára pre deti a dorastVyjadrenie zariadenia poradenstva a prevencie - zdravotné znevýhodnenie/nadanieIná' or . = 'Rozhodnutie súduPotvrdenie od všeobecného lekára zákonného zástupcu (ktorý nie je schopný sa podpísať)Čestné vyhlásenie zákonného zástupcuPotvrdenie o zdravotnej spôsobilostiOdporúčanie všeobecného lekára pre deti a dorastVyjadrenie zariadenia poradenstva a prevencie - zdravotné znevýhodnenie/nadanieIná')]</value>
      <webElementGuid>443d3fc1-1d20-4c03-b423-25b1ab13ab76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
