<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Overi</name>
   <tag></tag>
   <elementGuidId>e4d737d8-9832-4dce-acfc-51da048a6c20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;Overiť&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='Overiť']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>40e548cb-e0bf-4d17-9715-cfad7d074e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Overiť</value>
      <webElementGuid>384c7469-a3a9-4360-8bec-437a9d48e726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button govuk-button__large overenie-emailu-dalej</value>
      <webElementGuid>1ec302ee-b49d-4fb3-b508-4bf29bec6c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-module</name>
      <type>Main</type>
      <value>govuk-button</value>
      <webElementGuid>7099ec97-3291-491c-8869-a30be9f540c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Overiť
            </value>
      <webElementGuid>4534e1b2-9a85-495a-b59e-0460c7160e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;overenie-emailu&quot;)/div[@class=&quot;idsk-card__content&quot;]/div[@class=&quot;idsk-card__buttons&quot;]/button[@class=&quot;govuk-button govuk-button__large overenie-emailu-dalej&quot;]</value>
      <webElementGuid>dd1503ae-b29f-4357-9b92-2cb71c04ee46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='Overiť']</value>
      <webElementGuid>f5c3fe03-ca50-4bbb-bea2-ccd30066ec45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='overenie-emailu']/div/div[4]/button[2]</value>
      <webElementGuid>23b7673b-2774-49cb-93fa-fb03660d9e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Znova odoslať kód'])[1]/following::button[1]</value>
      <webElementGuid>dca46890-ef31-4115-a414-2a185489d757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(nepovinné)'])[5]/following::button[2]</value>
      <webElementGuid>5b4b4698-0b11-45e3-b2f7-ff3f5f0531e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items'])[1]/preceding::button[1]</value>
      <webElementGuid>560214ad-0a64-4128-b93c-c52fe73f6016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vyhlásenie o prístupnosti'])[1]/preceding::button[1]</value>
      <webElementGuid>4878baae-6b1c-4bd2-838d-b255fe03b16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Overiť']/parent::*</value>
      <webElementGuid>df888be1-b6c1-4156-8762-3c6dbfe6f9f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>4455e5a0-cc99-4860-8819-ea48263cba1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'Overiť' and (text() = '
                Overiť
            ' or . = '
                Overiť
            ')]</value>
      <webElementGuid>984c8992-b79b-45e6-bc9a-71fed0ae6136</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
