<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-overenie-input</name>
   <tag></tag>
   <elementGuidId>de3931ed-245b-449f-8900-4e6ec6ba4123</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-overenie-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-overenie-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86d82f5e-15ad-4ae7-8c86-42c6422ddbb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>73e0f3bc-8823-4b9c-91f8-c1aa582db1d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cae61b86-bd9f-47df-a071-f41738df990a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-overenie-input</value>
      <webElementGuid>4ef1804b-2ae1-446d-91e2-7803aed10ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>159f15ca-2754-4443-8177-0c5485515ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-overenie-input&quot;)</value>
      <webElementGuid>732d0051-046c-4814-9cd8-d7e4b2c4cbea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-overenie-input']</value>
      <webElementGuid>61178660-73d2-42d7-b8cd-53e57714da30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='overenie-input']/div/div[2]/input</value>
      <webElementGuid>2841694a-caf9-42cf-adef-0b4041c618c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/div[2]/input</value>
      <webElementGuid>6a87b6f0-920e-47e8-af2c-e7542bd24907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-overenie-input']</value>
      <webElementGuid>fbb132a0-c2e7-421d-9083-a5b2b0c9cae0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
