<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_pohlavieRadioZ</name>
   <tag></tag>
   <elementGuidId>0b7e2a51-e12a-444f-9546-25b0cec7aed5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pohlavieRadio_option_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pohlavieRadio_option_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd501f71-e27a-4ccc-9450-920d78312f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>e538b064-fc15-46fb-8eda-29f571379072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pohlavieRadio_option_0</value>
      <webElementGuid>89734e21-a71d-4525-9c46-c296d28c904b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pohlavieRadio</value>
      <webElementGuid>e479b0bd-cea2-419e-9bfd-012ce3b4046c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e71ec3a4-cad3-4c55-b584-7d39ee4161a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b51e389b-ac2b-47c4-9390-44082700ca88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pohlavieRadio_option_0&quot;)</value>
      <webElementGuid>18cf1cb8-86ce-4a22-9c47-4147dad359bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pohlavieRadio_option_0']</value>
      <webElementGuid>0a155df8-32ed-4503-b6b4-d49395f0cf65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pohlavieRadio']/div/fieldset/div[3]/div/input</value>
      <webElementGuid>6454d63d-4f4b-4481-858a-06d3536684b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/fieldset/div[3]/div/input</value>
      <webElementGuid>89e94fc6-6067-4ab2-aeb3-6e801e92dda2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pohlavieRadio_option_0' and @name = 'pohlavieRadio' and @type = 'radio']</value>
      <webElementGuid>d86e7929-6648-40c2-a1bf-97bfddacf7ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
