<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_zsDPDVychovaRadio</name>
   <tag></tag>
   <elementGuidId>ef368bd3-c413-4bae-9fbd-e47b22a8c669</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='zsDPDVychovaRadio_option_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zsDPDVychovaRadio_option_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1fadc50-535c-4c65-a6fa-e2b293cc8292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>8b2b886b-dc94-4e5b-a150-d9a6e51bc09f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zsDPDVychovaRadio_option_0</value>
      <webElementGuid>9e1bd37b-a122-4577-baef-6b63a33cb5be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zsDPDVychovaRadio</value>
      <webElementGuid>1dce6817-fbff-4dfd-90e9-fba328f90659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>96505b70-e087-4aee-86b6-efff39b6e2e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5d86ff90-ee45-427f-a774-ee7a75e2c8c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zsDPDVychovaRadio_option_0&quot;)</value>
      <webElementGuid>fbd29fdb-4e2a-4a5c-b3f3-67994dc749c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zsDPDVychovaRadio_option_0']</value>
      <webElementGuid>8272bdb5-a051-49e1-9059-e16878b1a822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zsDPDVychovaRadio']/div/fieldset/div[3]/div/input</value>
      <webElementGuid>064d891d-ac0a-40c0-91c2-4bd9fc0f2bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/fieldset/div[3]/div/input</value>
      <webElementGuid>cbb77426-9eea-4b45-802d-3c1f205ffe1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'zsDPDVychovaRadio_option_0' and @name = 'zsDPDVychovaRadio' and @type = 'radio']</value>
      <webElementGuid>92ea9194-47bc-453a-8783-598571ad8902</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
