<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_check_circle_panel-text</name>
   <tag></tag>
   <elementGuidId>e3667a6d-7326-4da4-9afa-8ffb46e45e7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='registration-page']/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.panel-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>de7074a8-8a14-4229-b79f-8960114dc5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-text</value>
      <webElementGuid>0554a4e7-bf83-402c-ad8c-14609e3e28cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vaša registrácia už bola dokončená a preto nie je potrebné klikať opätovne na daný link.</value>
      <webElementGuid>ad6277e5-d5c0-410c-b094-d5e7c8f07fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration-page&quot;)/div[@class=&quot;govuk-panel govuk-!-margin-bottom-8 govuk-panel--confirmation&quot;]/div[1]/div[@class=&quot;govuk-panel__body&quot;]/span[@class=&quot;panel-text&quot;]</value>
      <webElementGuid>fdbb8864-f229-4962-9376-63ee641e1a71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='registration-page']/div/div/div/span</value>
      <webElementGuid>f6016539-f87f-4e44-97dd-41839d83c836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='check_circle'])[1]/following::span[1]</value>
      <webElementGuid>04eca571-2c8d-470b-9435-9aba93f3de01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registrácia'])[2]/following::span[2]</value>
      <webElementGuid>23d2442f-d12d-480a-bb20-2dec77d944b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close'])[1]/preceding::span[1]</value>
      <webElementGuid>6ecd31e1-6d93-4bb2-85dc-073709649870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gratulujeme! Úspešne sme Vás zaregistrovali do systému.'])[1]/preceding::span[3]</value>
      <webElementGuid>e2464295-aa90-42f5-b5da-31ada28628e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vaša registrácia už bola dokončená a preto nie je potrebné klikať opätovne na daný link.']/parent::*</value>
      <webElementGuid>bbfcaa4b-25dc-4c42-9862-5c7828ee5215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/span</value>
      <webElementGuid>f6461f19-dbab-4b94-8541-736cb932561c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Vaša registrácia už bola dokončená a preto nie je potrebné klikať opätovne na daný link.' or . = 'Vaša registrácia už bola dokončená a preto nie je potrebné klikať opätovne na daný link.')]</value>
      <webElementGuid>717784f3-bfda-4b53-b46c-5fd1fe349b37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
