<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_M</name>
   <tag></tag>
   <elementGuidId>856bd0b6-aad8-4af8-95b8-5905f675017a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='inicialy-osoby-header']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inicialy-osoby-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e25d6432-4720-490b-b0b9-84fabcdbe777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inicialy-osoby-header</value>
      <webElementGuid>089c9106-fa62-4322-952d-dee14cf35dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MĎ</value>
      <webElementGuid>e95645bf-0a8a-4d13-a7df-54b53aa64d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inicialy-osoby-header&quot;)</value>
      <webElementGuid>3c898fc3-d857-437b-ba3d-c9af13c18818</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='inicialy-osoby-header']</value>
      <webElementGuid>4d522c7a-1e9c-4c05-807a-ebf48f309930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/following::span[2]</value>
      <webElementGuid>44d21232-39a1-4fdb-a18e-ac6eebd5da8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elektronické prihlášky do škôl'])[1]/following::span[3]</value>
      <webElementGuid>8d6e9817-209b-4c1c-8486-22c3001add5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Môj profil'])[1]/preceding::span[1]</value>
      <webElementGuid>82be8db6-075d-41c4-98b3-77a1f174ed91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odhlásiť'])[1]/preceding::span[1]</value>
      <webElementGuid>d0fe9c23-369d-4d24-9113-496067423e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MĎ']/parent::*</value>
      <webElementGuid>97e61a5d-6de0-4755-a408-9b57d589eef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/span</value>
      <webElementGuid>e3864c45-e9af-4a96-a211-bf6a881df96c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'inicialy-osoby-header' and (text() = 'MĎ' or . = 'MĎ')]</value>
      <webElementGuid>dc2e37df-80c7-40dd-ad87-283d3ccb84ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
