<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a</name>
   <tag></tag>
   <elementGuidId>460e68d0-76ae-43d5-92fb-ca700c9adeb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#popup-main > div.popup-content > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popup-main']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5ca62d72-c774-4e11-b449-8ad92a1121b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript: void(0);</value>
      <webElementGuid>64c3ba0e-9704-4ee2-bd59-d393344f2104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upraviť</value>
      <webElementGuid>9b18fcc1-1653-48d9-bb98-0ac7662d5de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popup-main&quot;)/div[@class=&quot;popup-content&quot;]/a[1]</value>
      <webElementGuid>ed0f684a-ea5a-4191-8df2-8a5159c560a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup-main']/div/a</value>
      <webElementGuid>1867ebcd-4d52-4df8-bc4d-d875056c42a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Upraviť')])[2]</value>
      <webElementGuid>0d734543-639c-44f8-81a7-d6bc4550219f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vydať rozhodnutia'])[1]/following::a[1]</value>
      <webElementGuid>2a79432c-770c-4c50-826f-6113e13924e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uložiť ePodací hárok XML'])[1]/following::a[2]</value>
      <webElementGuid>5ba900ea-1337-4ba9-9d66-250ea9129fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stiahnuť PDF - Pozvánka'])[2]/preceding::a[1]</value>
      <webElementGuid>8d364ae2-5c05-491d-b533-cfb457b74f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stiahnuť PDF - Správa o bodoch'])[2]/preceding::a[2]</value>
      <webElementGuid>2534da5c-bc05-44c4-9bf0-b2a2e125e177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript: void(0);')])[11]</value>
      <webElementGuid>9908a757-7845-459d-b136-a6ba0351fe47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/a</value>
      <webElementGuid>562cc5da-c216-4bc3-a5aa-b703782086e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript: void(0);' and (text() = 'Upraviť' or . = 'Upraviť')]</value>
      <webElementGuid>9e8a8f77-d870-4167-966c-f3b3b9f0aefc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
