<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Zrui_btn-odoslat govuk-button govuk-_541f94</name>
   <tag></tag>
   <elementGuidId>572efecb-3eda-421a-a808-c5d38663e1ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn-odoslat.govuk-button.govuk-button__basic.last-focusable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sub-riaditel-prijimacky']/div[14]/div/div[3]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6abbe1ff-813e-4829-b573-9cf2aad1bd1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-odoslat govuk-button govuk-button__basic last-focusable</value>
      <webElementGuid>39c9692a-2981-438d-8382-9f4de976a576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Odoslať</value>
      <webElementGuid>05a1fe75-8187-4d86-80bf-4fbc3862c096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub-riaditel-prijimacky&quot;)/div[@class=&quot;modal-wrapper vygenerovat-pozvanky-modal-wrapper&quot;]/div[@class=&quot;modal vygenerovat-pozvanky-modal&quot;]/div[@class=&quot;buttons-container&quot;]/div[@class=&quot;right-buttons&quot;]/button[@class=&quot;btn-odoslat govuk-button govuk-button__basic last-focusable&quot;]</value>
      <webElementGuid>bf31cea9-0b97-477d-9da7-ade2ea276194</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sub-riaditel-prijimacky']/div[14]/div/div[3]/div/button</value>
      <webElementGuid>fbe7281a-f07f-4888-8f34-ff4bc300aaca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zrušiť'])[3]/following::button[1]</value>
      <webElementGuid>02ce11cb-a726-428c-b933-082a6d55114c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='prihlaska1.pdf'])[1]/following::button[2]</value>
      <webElementGuid>f428830d-6af9-43d2-809d-08db48da2013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='žiakov vyhovelo'])[1]/preceding::button[1]</value>
      <webElementGuid>0862d7db-cf14-4f18-970e-03f2a57ad284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_forward'])[33]/preceding::button[1]</value>
      <webElementGuid>88f28c0b-9315-4cea-b40d-5682e2aa86dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Odoslať']/parent::*</value>
      <webElementGuid>74f6ec07-64bf-4f91-9081-918377c57686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[3]/div/button</value>
      <webElementGuid>468ee65e-16a0-4b5d-8069-1264602d6ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Odoslať' or . = 'Odoslať')]</value>
      <webElementGuid>2e085ed7-ee78-4cff-af6a-f63fa4708c83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
