<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_(nepovinn)_prijimacky-btn-zoradit-po_1f8ad8</name>
   <tag></tag>
   <elementGuidId>2c37d3b5-16ff-4bc9-926e-2868a160b8ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prijimacky-btn-zoradit-podla-predvolene</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='prijimacky-btn-zoradit-podla-predvolene']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>930f9bf4-ad9e-48d2-beed-e37b134bebf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prijimacky-btn-zoradit-podla-predvolene</value>
      <webElementGuid>85d5940d-4914-4b01-bccc-8fe5068ce82e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button govuk-button--sec riaditel-sprava-prihlasok-heading-button</value>
      <webElementGuid>a68de71c-cedf-406c-bfdd-03f14605eb6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-module</name>
      <type>Main</type>
      <value>govuk-button</value>
      <webElementGuid>55d6e505-ddc9-44af-a702-60c5390e8443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript: void(0);</value>
      <webElementGuid>cb2eee69-218c-45f6-a763-9eabb3d5a222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Zoradiť podľa: Predvolené</value>
      <webElementGuid>4390b66b-9b50-42ad-bb3e-c6134d2878a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prijimacky-btn-zoradit-podla-predvolene&quot;)</value>
      <webElementGuid>e8aee736-3f2b-4b0f-a45c-e3cd57541d0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='prijimacky-btn-zoradit-podla-predvolene']</value>
      <webElementGuid>23b79240-c814-426e-b9cf-541c7ca68752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sub-riaditel-prijimacky']/div[5]/div/div[3]/button</value>
      <webElementGuid>dd30f984-b032-47c8-8adf-3970d31fbdc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(nepovinné)'])[33]/following::button[1]</value>
      <webElementGuid>14920367-cfc4-40c4-96a7-ee4128d6e0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vybrať všetky'])[3]/following::button[1]</value>
      <webElementGuid>c6ba5537-0272-438c-8084-ae1dd059f75d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]/button</value>
      <webElementGuid>7ea4b104-aca8-4b2b-a1e5-0b17c52d825a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'prijimacky-btn-zoradit-podla-predvolene' and @href = 'javascript: void(0);' and (text() = 'Zoradiť podľa: Predvolené' or . = 'Zoradiť podľa: Predvolené')]</value>
      <webElementGuid>7d2ec5ca-3894-4d59-b63a-ba584028fedb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
