<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nhradn termn_grey-label_2</name>
   <tag></tag>
   <elementGuidId>5579cf68-7352-4602-bb19-a3c76e8d39da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.riaditel-prijimacky-cell.miestnost-cell > div.grey-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sub-riaditel-prijimacky']/div[5]/div[3]/div/div[2]/div[7]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d9827717-8720-4c4b-acc3-2737c7a800eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grey-label</value>
      <webElementGuid>c3ac1ca8-f382-425a-8f98-55971151c90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6.C</value>
      <webElementGuid>42b69971-b419-4ec3-ba52-cc754ac082ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub-riaditel-prijimacky&quot;)/div[@class=&quot;riaditel-prijimacky-container&quot;]/div[@class=&quot;scrollable-middle-area&quot;]/div[@class=&quot;scroll-content-wrapper&quot;]/div[@class=&quot;row data-row&quot;]/div[@class=&quot;riaditel-prijimacky-cell miestnost-cell&quot;]/div[@class=&quot;grey-label&quot;]</value>
      <webElementGuid>a4740014-5c8f-4de2-9821-b443329c2e7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sub-riaditel-prijimacky']/div[5]/div[3]/div/div[2]/div[7]/div</value>
      <webElementGuid>548829b3-d8de-453e-9170-5f7f4fa33d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Náhradný termín'])[1]/following::div[6]</value>
      <webElementGuid>0cb78b00-9a88-440e-ab05-6e706dc9d3ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Áno'])[1]/following::div[9]</value>
      <webElementGuid>b484cfa8-7b9c-40fd-b770-fd7218edb80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Náhradný termín'])[2]/preceding::div[1]</value>
      <webElementGuid>c4c1e407-e278-43cb-891c-e24abdd6b150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Neodoslaná'])[2]/preceding::div[2]</value>
      <webElementGuid>8181e96d-0b4e-4631-9c1e-b784ad3c6bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='6.C']/parent::*</value>
      <webElementGuid>cfa518bd-0b80-4e65-b27a-aeaeedaa8eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[7]/div</value>
      <webElementGuid>9108c4a1-c00f-4502-9886-8d444cb3a0b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '6.C' or . = '6.C')]</value>
      <webElementGuid>11295713-8486-42e6-bde5-ba63e584be7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
