<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-prij__edit_datumMesiac</name>
   <tag></tag>
   <elementGuidId>9ed0f994-af8e-458b-8e5c-3ea0ee228d9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-prij__edit_datumMesiac</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-prij__edit_datumMesiac']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31269e35-5238-4b37-94dc-4d00bdb32bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>aa765784-9dc1-4bb9-b7a7-49d2838261cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1c3b5dd9-70ba-4cdd-8615-1975a44b380f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-prij__edit_datumMesiac</value>
      <webElementGuid>b98412f4-b0e6-44cb-ab02-db6555dcc4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5ee43717-3f93-4314-b465-f33ee1a6dbc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM</value>
      <webElementGuid>15f07f01-5f32-4d75-930f-cf22cc2a52ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-prij__edit_datumMesiac&quot;)</value>
      <webElementGuid>64b3627b-6647-4979-b1b4-ab5d955af1c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-prij__edit_datumMesiac']</value>
      <webElementGuid>1de029e8-33e8-465f-a106-050b6d4a90b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prij__edit_datumMesiac']/div/div[2]/input</value>
      <webElementGuid>ee468f06-2021-4ee0-9a32-8f44f84dc055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>f9361ac6-40a9-4d63-968a-e66b757fa8a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-prij__edit_datumMesiac' and @placeholder = 'MM']</value>
      <webElementGuid>692af3f9-9e33-4890-a185-7cf7cc419704</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
