<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_(nepovinn)_textarea-prijimackyVoli_879f89</name>
   <tag></tag>
   <elementGuidId>ffe3af00-ae39-4ce5-b053-98f2e084b90d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textarea-prijimackyVolitelnyText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='textarea-prijimackyVolitelnyText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>00157c29-eb30-430e-8ad7-2711e06f918a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-textarea</value>
      <webElementGuid>52e9bdf1-8c05-4629-bda5-e2bbeeec7ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>1cc47de8-967d-4c8f-bb18-f9d0b56b9369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textarea-prijimackyVolitelnyText</value>
      <webElementGuid>f2a70589-d192-4892-85ac-e09b8aff7229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>74d57400-a3ad-491e-9bde-3ee86991dca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textarea-prijimackyVolitelnyText&quot;)</value>
      <webElementGuid>33d84d3a-eafd-4078-8d95-ba102122cf03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textarea-prijimackyVolitelnyText']</value>
      <webElementGuid>ce299e5d-2beb-4026-8efb-7b4b1f224bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prijimackyVolitelnyText']/div/div[2]/textarea</value>
      <webElementGuid>92e338ee-8ea1-4473-88bd-bd39aa699c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>9f16e7db-cb8c-44cb-ad26-8bb5c36d2521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'textarea-prijimackyVolitelnyText']</value>
      <webElementGuid>6b707be9-6742-4707-a09d-e7b4e98c9f37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
