<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Uloi</name>
   <tag></tag>
   <elementGuidId>bdeb3b59-b0b3-4169-9ca6-b45a514d9a19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vseobecne-datum-podania-edit']/div[2]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn-ulozit.govuk-button.govuk-button__basic</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc6fedc2-c929-4a13-9be7-25dc47ecd926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-ulozit govuk-button govuk-button__basic</value>
      <webElementGuid>d5ba96ba-623b-46f6-9a89-533b72e17181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Uložiť</value>
      <webElementGuid>ec6e7c85-9ef2-44c9-a528-6e593f7b34d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vseobecne-datum-podania-edit&quot;)/div[@class=&quot;buttons&quot;]/button[@class=&quot;btn-ulozit govuk-button govuk-button__basic&quot;]</value>
      <webElementGuid>9c0c99b2-d983-4512-b6d6-8487f803d9d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vseobecne-datum-podania-edit']/div[2]/button[2]</value>
      <webElementGuid>25c612e1-8e91-45ee-becb-321848804a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Späť'])[2]/following::button[1]</value>
      <webElementGuid>8b29196b-5eff-4b04-9208-6d2639ce031e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear date'])[1]/following::button[2]</value>
      <webElementGuid>636c290f-370d-4efe-8655-30e4d16f36f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Papierovo'])[1]/preceding::button[1]</value>
      <webElementGuid>2e9a7657-4b04-41e5-8e48-99022da8c4da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Uložiť']/parent::*</value>
      <webElementGuid>a61368af-7e7b-457b-b077-ddb720e714d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>73c824ce-d5de-4130-8a13-a7d5d4adf41e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Uložiť' or . = 'Uložiť')]</value>
      <webElementGuid>fd3d4f5b-8a67-49ff-9f27-dc179074e89e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
