<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_nie</name>
   <tag></tag>
   <elementGuidId>4dfa9dce-201a-44fd-bfa8-e970e1bb9263</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dpDietataMsCelodennaVychova']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dpDietataMsCelodennaVychova</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aaa92ad7-0612-4986-a5cd-a95acdf16f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dpDietataMsCelodennaVychova</value>
      <webElementGuid>97ef353c-5116-4f0e-bfe8-d90c6bd6ee5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>nie</value>
      <webElementGuid>0dc9075e-e512-4ae7-9c90-423fc7a534cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dpDietataMsCelodennaVychova&quot;)</value>
      <webElementGuid>1a799615-ac20-4588-84ee-395ea25b96cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dpDietataMsCelodennaVychova']</value>
      <webElementGuid>44f29f39-428a-4680-bd1d-228100e5aab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdpDietata']/div[2]/div[5]/div/div[2]</value>
      <webElementGuid>f0cf8919-094c-4aea-bf88-553a8ec776b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Celodenná výchova'])[1]/following::div[1]</value>
      <webElementGuid>9b3412b2-8e1a-44f4-91d1-79c4607c4e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doplňujúce informácie o dieťati'])[1]/following::div[4]</value>
      <webElementGuid>ed806167-f983-49a2-8de8-f386538b7694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Požadovaná výchova'])[1]/preceding::div[1]</value>
      <webElementGuid>a3d3c358-a548-4cbf-a025-0426c34eba69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[7]/preceding::div[2]</value>
      <webElementGuid>0e5850d5-731c-4966-9650-a8f7a47e8513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='nie']/parent::*</value>
      <webElementGuid>8aa6997d-b162-4342-9b6e-2abde75ce5c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div[5]/div/div[2]</value>
      <webElementGuid>d4a80324-824c-4122-bfaa-624f9bb654c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dpDietataMsCelodennaVychova' and (text() = 'nie' or . = 'nie')]</value>
      <webElementGuid>55f982fa-9f12-417f-9c0a-90713e79094e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
