<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_mailtest.sk</name>
   <tag></tag>
   <elementGuidId>047d21fb-432f-4485-abda-f6fdd1490985</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zakonnyZastupcaEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zakonnyZastupcaEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4996795e-f874-464c-bded-65e94d5c7ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zakonnyZastupcaEmail</value>
      <webElementGuid>96d5a998-b61d-4e6d-871d-0f067e2825b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mail@test.sk</value>
      <webElementGuid>3a53231d-a832-499e-92d5-cd68c51cab2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zakonnyZastupcaEmail&quot;)</value>
      <webElementGuid>3b0bb45b-70e3-4834-beb0-7f18c7cf0d0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zakonnyZastupcaEmail']</value>
      <webElementGuid>ffb1c3dc-f797-40c9-8565-24b2582d0c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz1']/div[5]/div[2]</value>
      <webElementGuid>ea9732a7-54d9-417a-b83b-925fea8c8953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::div[1]</value>
      <webElementGuid>04a815f2-85ab-492a-b9c3-2347c15ff346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gemerská cesta 18, 98745, Lučenec, Slovenská republika'])[1]/following::div[3]</value>
      <webElementGuid>861ae461-2110-47fc-9ebd-ae066f969c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telefónne číslo'])[1]/preceding::div[1]</value>
      <webElementGuid>2d214b23-5e49-4392-9614-bc5051bc3f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov zariadenia'])[1]/preceding::div[4]</value>
      <webElementGuid>07a37fed-dc7d-4c71-98b6-e3d6bea3cbe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='mail@test.sk']/parent::*</value>
      <webElementGuid>f1285878-659a-4820-86a1-c6df21c5f681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[5]/div[2]</value>
      <webElementGuid>23fe0ef5-9366-43ef-bf1b-082e39cd7e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zakonnyZastupcaEmail' and (text() = 'mail@test.sk' or . = 'mail@test.sk')]</value>
      <webElementGuid>55fc1b98-fb4f-4476-a7b4-cd0c4122b2a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
