<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_no</name>
   <tag></tag>
   <elementGuidId>55825fe3-7a83-4275-9525-58a86e59e455</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zakonnyZastupca2Suhlas']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zakonnyZastupca2Suhlas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a66e0cd4-769f-4104-bcb2-71c7c19d62ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zakonnyZastupca2Suhlas</value>
      <webElementGuid>638d66da-fe98-4d9c-8108-22523aeca341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>áno</value>
      <webElementGuid>2f2286f2-2bad-4693-a52d-d8348368f9e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zakonnyZastupca2Suhlas&quot;)</value>
      <webElementGuid>3895ccfe-5eb6-43c4-82fb-4e68649b6596</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zakonnyZastupca2Suhlas']</value>
      <webElementGuid>92a80fcd-6590-438d-a5c1-98f19408b0c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz2']/div[7]/div[2]</value>
      <webElementGuid>29669054-99ee-4462-b129-5fc37d382ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Súhlas druhého zákonného zástupcu'])[1]/following::div[1]</value>
      <webElementGuid>e7ed7afe-bd8a-4b27-94ef-184c5f8991c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telefónne číslo'])[2]/following::div[4]</value>
      <webElementGuid>b8cff3b2-d669-44a5-b7bd-02e03e58b8d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dôvod nezabezpečenia súhlasu'])[1]/preceding::div[1]</value>
      <webElementGuid>1f347d85-3031-4e4b-bd93-dc25dbc6521d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[6]/preceding::div[2]</value>
      <webElementGuid>f6f3054e-903c-401d-a978-61354434cef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='áno']/parent::*</value>
      <webElementGuid>0c28923a-ea58-432e-b132-ecdfc9cc4062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[7]/div[2]</value>
      <webElementGuid>7b36b7af-28e6-4646-9ec0-de3f4182ea91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zakonnyZastupca2Suhlas' and (text() = 'áno' or . = 'áno')]</value>
      <webElementGuid>a8df36c0-a482-45b2-a7db-33038322e800</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
