<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_launch_govuk-header__link</name>
   <tag></tag>
   <elementGuidId>ba403b34-da63-442a-b2c8-a57b74136562</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.govuk-header__navigation-item.govuk-header__navigation-item--active > a.govuk-header__link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='header-navigation']/div/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fe475885-763b-445c-93c9-b8d24a36b903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-header__link</value>
      <webElementGuid>82aeaf9d-5f6f-428f-a607-3a8172403c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Prihlasky</value>
      <webElementGuid>07b1c54d-0fdf-4fb2-8b36-e2e67bdc9321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Prihlášky
                                    </value>
      <webElementGuid>87506c2e-00d7-4b39-bb63-fb0be86c1b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-navigation&quot;)/div[@class=&quot;govuk-header__navigation-list&quot;]/ul[@class=&quot;govuk-width-container&quot;]/li[@class=&quot;govuk-header__navigation-item govuk-header__navigation-item--active&quot;]/a[@class=&quot;govuk-header__link&quot;]</value>
      <webElementGuid>5dbf588e-e634-4479-9f18-5be1b833b88c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='header-navigation']/div/ul/li[4]/a</value>
      <webElementGuid>bf4ac71a-859f-47f5-b8eb-eb2eb3a12b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Prihlášky')]</value>
      <webElementGuid>8a6b5966-01d0-4cf0-853b-0babc38fcd66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='launch'])[1]/following::a[1]</value>
      <webElementGuid>1a26781e-a412-4bc1-8c6d-38e44cf9765d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pomoc a podpora'])[1]/following::a[1]</value>
      <webElementGuid>2f50b5a2-534a-4e1f-b6fb-3921f2e6491e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Môj profil'])[2]/preceding::a[1]</value>
      <webElementGuid>b02bfd5c-bf76-484b-9aa1-10236d1e7ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odhlásiť'])[2]/preceding::a[2]</value>
      <webElementGuid>119cd9f4-af4e-44ef-a060-1e0370920670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Prihlášky']/parent::*</value>
      <webElementGuid>7ca307fa-b3ae-4aa0-b1ea-2e95416fa06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Prihlasky')]</value>
      <webElementGuid>27ac3f8d-21a0-437c-bc34-23e60e3b8cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>33c62630-f968-4a60-8517-4c6a7e1e4271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Prihlasky' and (text() = '
                                        Prihlášky
                                    ' or . = '
                                        Prihlášky
                                    ')]</value>
      <webElementGuid>26fc46a7-914f-450d-acad-f4d43689d253</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
