<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_EDUID zkladnej koly_eduidZSSuhrnZiadost</name>
   <tag></tag>
   <elementGuidId>63fc6979-2c4a-40a0-8014-500b42102111</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eduidZSSuhrnZiadost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='eduidZSSuhrnZiadost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>506293cf-eb6c-42a7-ba68-3bc50e9635be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eduidZSSuhrnZiadost</value>
      <webElementGuid>e014e521-0e41-482a-b1ef-b5113cca6bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>910020024</value>
      <webElementGuid>d733f576-b9aa-487b-9144-259f69c1a10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eduidZSSuhrnZiadost&quot;)</value>
      <webElementGuid>8483ede6-0acb-4488-8857-f4d15d2c5d78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='eduidZSSuhrnZiadost']</value>
      <webElementGuid>a5b3a857-e16d-489c-9a83-38edccec7f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='info-o-zs']/div[2]/div[2]/div[2]</value>
      <webElementGuid>63763358-bbf8-4025-a643-c3d137a89b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EDUID základnej školy'])[3]/following::div[1]</value>
      <webElementGuid>e36af855-b623-4f18-8886-98342aa03d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zo ZŠ na Slovensku'])[2]/following::div[3]</value>
      <webElementGuid>df13404c-4827-4937-a442-d652d0ab3be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov základnej školy'])[3]/preceding::div[1]</value>
      <webElementGuid>c116e2fe-e512-47cc-b226-d8bfde870b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Základná škola s materskou školou, Soblahov 404'])[1]/preceding::div[2]</value>
      <webElementGuid>8dcfdc8f-ffa9-4522-9158-eee2f8879a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='910020024']/parent::*</value>
      <webElementGuid>d5e91926-cf3a-4acf-9a7f-a81f57178992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div[2]/div[2]</value>
      <webElementGuid>23086310-e98c-4bfc-aa4b-8700c557a21c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'eduidZSSuhrnZiadost' and (text() = '910020024' or . = '910020024')]</value>
      <webElementGuid>d7c70957-749f-4774-9e9c-0a3c94cf7582</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
