<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dtum narodenia_dietaDatumNarodeniaSuhrn</name>
   <tag></tag>
   <elementGuidId>c4b42fd5-6942-442c-80a1-6d7071e68383</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dietaDatumNarodeniaSuhrn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dietaDatumNarodeniaSuhrn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>282977f6-4e5b-4f66-a901-dc30fd4bab01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dietaDatumNarodeniaSuhrn</value>
      <webElementGuid>83f42409-86e2-4ad5-a89a-40d43d54f46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>09.07.2009</value>
      <webElementGuid>17e0d5c9-f7a3-492c-8fdc-c6a6b09b54b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dietaDatumNarodeniaSuhrn&quot;)</value>
      <webElementGuid>4ae2c810-4b97-4617-9d83-6fc398e988d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dietaDatumNarodeniaSuhrn']</value>
      <webElementGuid>279111cc-8fe7-4dc5-aafb-7b1b964956ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suhrnny-prehlad']/div[3]/div[2]/div[5]/div[2]</value>
      <webElementGuid>1135a64b-0c94-49dd-8d3c-f42e8cab4076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum narodenia'])[5]/following::div[1]</value>
      <webElementGuid>488dd07d-2a5e-4e2e-a613-3aaf18ffbdfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodné číslo'])[6]/following::div[4]</value>
      <webElementGuid>313a089d-d5f7-45af-9f5e-67f7af1e20a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pohlavie'])[3]/preceding::div[1]</value>
      <webElementGuid>f4afe0f7-99b1-4853-9b0e-3fbb6b2283e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mužské'])[2]/preceding::div[2]</value>
      <webElementGuid>da0c9320-6cb1-411c-9eac-2525bb19104e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[3]/div[2]/div[5]/div[2]</value>
      <webElementGuid>9c800251-980a-4c9f-9c95-17946db1b123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dietaDatumNarodeniaSuhrn' and (text() = '09.07.2009' or . = '09.07.2009')]</value>
      <webElementGuid>fd7d3e57-f7ff-40c5-b187-4864f34d9aed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
