<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Zmenen pracovn schopnos_dpZmenenaPracov_8af9b9</name>
   <tag></tag>
   <elementGuidId>86756f86-df25-4bbc-b9de-b8309b66e99b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dpZmenenaPracovnaSchopnost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dpZmenenaPracovnaSchopnost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ce1e1193-a342-49d3-a5a7-450c7310d269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dpZmenenaPracovnaSchopnost</value>
      <webElementGuid>d371194d-6633-474b-bb89-096416b4e504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nie</value>
      <webElementGuid>c57e5438-50d3-454c-8301-4d61bec21684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dpZmenenaPracovnaSchopnost&quot;)</value>
      <webElementGuid>d352dad1-f049-4e74-a7a7-60d674d704af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dpZmenenaPracovnaSchopnost']</value>
      <webElementGuid>8b2295a8-b92e-4883-b3db-8313488dedd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdpDietata']/div[2]/div[2]/div/div/div[2]</value>
      <webElementGuid>bd57e6f1-faad-4f2c-b6e7-da9cd48478e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zmenená pracovná schopnosť'])[2]/following::div[1]</value>
      <webElementGuid>026fa9c3-ceec-4bdb-b1fe-fdf5129921ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Poznámka'])[1]/following::div[6]</value>
      <webElementGuid>eb632be3-a6d5-42b4-8dff-5b349f13836a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upravené podmienky prijímacieho konania (Špeciálne výchovno-vzdelávacie potreby)'])[2]/preceding::div[1]</value>
      <webElementGuid>cacb8c72-924b-445c-89b3-efaee1c6c284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nie'])[10]/preceding::div[2]</value>
      <webElementGuid>b7c30d89-4b8d-4817-bd90-61fd99a47448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/div/div/div[2]</value>
      <webElementGuid>158a8b99-57f4-4063-b868-f2f7d431a036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dpZmenenaPracovnaSchopnost' and (text() = 'Nie' or . = 'Nie')]</value>
      <webElementGuid>7450e4be-bb1c-4b17-80e1-44e6558a969c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
