<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dtum narodenia_zakonnyZastupcaDatumNarodenia</name>
   <tag></tag>
   <elementGuidId>68b9f59e-265a-4dfa-8302-a967e412f083</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zakonnyZastupcaDatumNarodenia</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zakonnyZastupcaDatumNarodenia']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fcf666d0-4e71-4119-a125-fbdd11d28dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zakonnyZastupcaDatumNarodenia</value>
      <webElementGuid>15fcbc5b-569c-4acf-b035-8289dba59b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>24.02.1985</value>
      <webElementGuid>ad360924-3074-4d36-b732-d040173e298c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zakonnyZastupcaDatumNarodenia&quot;)</value>
      <webElementGuid>48ca1aee-8825-44f6-aac3-1276adeb8939</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zakonnyZastupcaDatumNarodenia']</value>
      <webElementGuid>6135d2a9-976b-4508-b06c-13a010851bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz1']/div[6]/div[2]</value>
      <webElementGuid>337eaa12-f0f6-4d19-baf9-17f735933c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum narodenia'])[6]/following::div[1]</value>
      <webElementGuid>f177a0bb-d30e-4f23-8f19-ac5f74959b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[12]/following::div[3]</value>
      <webElementGuid>37cb1b21-1ef9-48ce-8484-d6b62676d072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Korešpondenčná adresa'])[3]/preceding::div[1]</value>
      <webElementGuid>779cad7e-85f7-4ede-a23c-498cd8cf8379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kráľová 654/23, 01514, Smižany (Spišská Nová Ves), Slovenská republika'])[3]/preceding::div[2]</value>
      <webElementGuid>2e2848fe-9cf8-4ba6-8085-abcc2a275741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='24.02.1985']/parent::*</value>
      <webElementGuid>eb3a0a4d-f602-4b7f-8a7e-32a8791811d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[6]/div[2]</value>
      <webElementGuid>f7812b4a-a88c-4726-a6b6-c17591bb1125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zakonnyZastupcaDatumNarodenia' and (text() = '24.02.1985' or . = '24.02.1985')]</value>
      <webElementGuid>10bfbbfe-1b5d-4e86-a0c0-f85f19fa8d19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
