<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_S nadanm_specialneVVP_option_1</name>
   <tag></tag>
   <elementGuidId>bbc9d9cf-4443-4dfc-8e94-65586a0c4552</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#specialneVVP_option_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='specialneVVP_option_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3067675f-9ce2-41b6-ab77-b7abf9d778eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>4047ea18-78f4-4ff3-bb7d-a8ac74be2781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>specialneVVP_option_1</value>
      <webElementGuid>98a6f4de-ef81-43cd-8e18-c38e7afd45a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>specialneVVP</value>
      <webElementGuid>4921603d-d3e3-46c7-9b77-c9c68f0599c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c43ecf45-4d76-4038-951b-1115ff27e51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>504565a6-32f6-40ff-b7a5-9afaa2bae4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;specialneVVP_option_1&quot;)</value>
      <webElementGuid>b0b5ce5d-0816-4148-bc67-386ff6cf77a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='specialneVVP_option_1']</value>
      <webElementGuid>e4e3edd2-83d8-4140-a8c9-abd7cf9acd2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='specialneVVP']/div/fieldset/div[3]/div[3]/input</value>
      <webElementGuid>ef0de6a3-a618-480f-8927-4a4d2cb7f3a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/fieldset/div[3]/div[3]/input</value>
      <webElementGuid>e56bc2e1-4b0e-48d3-8d16-b54f0edc3123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'specialneVVP_option_1' and @name = 'specialneVVP' and @type = 'radio']</value>
      <webElementGuid>f65ede6e-740d-40d3-804e-c525cbbf2c30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
