<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_govuk-input autocomplete-input_1</name>
   <tag></tag>
   <elementGuidId>30f8ca2c-1a40-4d18-8738-546e43cc4bba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#adresaTPObec > div.govuk-form-group.autocomplete-control.required > div.input-wrapper > input.govuk-input.autocomplete-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[15]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70430019-8532-4dc7-968b-d02852bed9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input autocomplete-input</value>
      <webElementGuid>02b3d878-957e-44ed-a9d5-c4c7f8dd9a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>652707d4-76af-4316-a101-afa7f83c01b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b961bab0-29f6-49c4-a1da-7231fbd31aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>800dce50-6332-4301-af9b-92021a47eafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>autocomplete-label-adresaTPObec</value>
      <webElementGuid>c6a7c5ce-ea28-4e04-b45e-5674e841bf53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>ed65d1e9-7a51-460b-b9a9-edfc31f9082c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adresaTPObec&quot;)/div[@class=&quot;govuk-form-group autocomplete-control required&quot;]/div[@class=&quot;input-wrapper&quot;]/input[@class=&quot;govuk-input autocomplete-input&quot;]</value>
      <webElementGuid>4f029810-e1fa-4e48-9787-c97964c36316</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[15]</value>
      <webElementGuid>4e8652d8-0afd-4506-90bc-1e580fd6ebe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adresaTPObec']/div/div[2]/input</value>
      <webElementGuid>f336e69a-cc01-4712-845a-4ab398d95412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div[2]/div/div[2]/input</value>
      <webElementGuid>5a146cff-dbfb-46d5-8f09-ce7d2321590e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>b519fcfb-d2b4-4dab-9285-66d7bd571633</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
