<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_no_zmenenaPracovnaSchopnostRadio_option_1</name>
   <tag></tag>
   <elementGuidId>17c8e94d-e140-4c41-b7fa-a47fdc4873e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zmenenaPracovnaSchopnostRadio_option_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='zmenenaPracovnaSchopnostRadio_option_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ccb1da0e-65cb-46fc-a485-132ced438ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>35563097-b4f1-4f60-b23a-ff9507591f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zmenenaPracovnaSchopnostRadio_option_1</value>
      <webElementGuid>8412e03d-2159-4709-a47e-8e79d49f1fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zmenenaPracovnaSchopnostRadio</value>
      <webElementGuid>41ead444-adb7-4419-a1fa-79350028b00b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5f865dfc-0cfd-4534-8225-70675c7ac3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7957c1ea-4d62-4bc8-b5a0-c5d87b72e9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zmenenaPracovnaSchopnostRadio_option_1&quot;)</value>
      <webElementGuid>40426100-783c-479b-b89f-b6895f2f9968</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zmenenaPracovnaSchopnostRadio_option_1']</value>
      <webElementGuid>d43e863c-920c-4ba8-bdf7-f89bde51cee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zmenenaPracovnaSchopnostRadio']/div/fieldset/div[3]/div[2]/input</value>
      <webElementGuid>ddcef7e4-780a-4787-bdfe-1919aa034ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/fieldset/div[3]/div[2]/input</value>
      <webElementGuid>6137d9f5-1161-4a53-bc20-34847c25eefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'zmenenaPracovnaSchopnostRadio_option_1' and @name = 'zmenenaPracovnaSchopnostRadio' and @type = 'radio']</value>
      <webElementGuid>9d59d877-cb67-40e6-be8a-8ad5e1aa65cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
