<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pozcia_profil-riaditel-typ_1</name>
   <tag></tag>
   <elementGuidId>971d5cfc-2359-426a-8525-6bc8e6646237</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profil-riaditel-typ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='profil-riaditel-typ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6b32d2ff-3a9b-4aa6-9a6e-9ce100f40436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profil-riaditel-typ</value>
      <webElementGuid>ce5cd580-da31-4eec-b492-ce2fe6198a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Administrátor</value>
      <webElementGuid>45291780-e64b-4012-b3c6-669195ba7867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profil-riaditel-typ&quot;)</value>
      <webElementGuid>f7a5b3da-edae-4fec-8ca8-207a1178495c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='profil-riaditel-typ']</value>
      <webElementGuid>a1c1562e-92ec-4674-8ecd-0a0dc69b5d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profil']/div[2]/div[2]/div[2]</value>
      <webElementGuid>ae8c0e87-75d3-49e3-a24c-bde30e9fbbd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pozícia'])[1]/following::div[1]</value>
      <webElementGuid>38013fe9-ff64-4ddf-9601-3f4d1cc7ed03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gymnázium Metodova'])[1]/following::div[3]</value>
      <webElementGuid>2e3eaa3d-bbea-471b-8a47-ed83daee3b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telefónne číslo'])[1]/preceding::div[1]</value>
      <webElementGuid>2e15c014-89d4-4891-b639-a2d0af4e4402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::div[2]</value>
      <webElementGuid>58d01f7b-2273-48b8-9cef-c3fcd83e02f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Administrátor']/parent::*</value>
      <webElementGuid>e781d9e2-2623-4a7b-8d9c-a153c15a5a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]</value>
      <webElementGuid>b42c24d7-a61f-468a-8f81-768145187512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'profil-riaditel-typ' and (text() = 'Administrátor' or . = 'Administrátor')]</value>
      <webElementGuid>b8bbd7e4-65ce-4ee2-89aa-72da597b42c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
