<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_kola_profil-riaditel-skola</name>
   <tag></tag>
   <elementGuidId>12edb6f9-a88d-4e9f-9eed-182d34d90595</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profil-riaditel-skola</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='profil-riaditel-skola']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fb955a4a-e4cd-4d6e-b3d0-b48f763d6f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profil-riaditel-skola</value>
      <webElementGuid>c23bd175-cab3-4306-9325-373c46e6336a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gymnázium Metodova</value>
      <webElementGuid>cefb6bcb-787a-4267-9a04-7c71bb325c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profil-riaditel-skola&quot;)</value>
      <webElementGuid>6a358128-9137-4fc0-8f8e-2f571fa87b61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='profil-riaditel-skola']</value>
      <webElementGuid>23a4bfb3-486a-4efb-82fc-5f6d945b8bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profil']/div[2]/div/div[2]</value>
      <webElementGuid>9d5a29b1-0b56-43a6-9b1d-e3ba0e06404c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Škola'])[1]/following::div[1]</value>
      <webElementGuid>7f97e3e6-3d9a-45f7-b887-99801ee48a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upraviť údaje'])[1]/following::div[4]</value>
      <webElementGuid>cafa3812-41d4-4d3a-b6dc-4661ac7348c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pozícia'])[1]/preceding::div[1]</value>
      <webElementGuid>a0908f37-37e7-4579-8a4b-582312d41f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spracovateľ'])[1]/preceding::div[2]</value>
      <webElementGuid>70adddea-793f-4545-9c6d-47645b791ff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gymnázium Metodova']/parent::*</value>
      <webElementGuid>ceebbe9f-6796-4435-bc50-a326a85159d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>2637a6e4-70f9-400c-a9e0-787172d61bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'profil-riaditel-skola' and (text() = 'Gymnázium Metodova' or . = 'Gymnázium Metodova')]</value>
      <webElementGuid>fe201a10-fb70-4e55-b4ec-2a750594d4dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
