<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nrodnos_dietaNarodnostSuhrn</name>
   <tag></tag>
   <elementGuidId>f565bd57-d432-4481-ae05-cca352989d63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dietaNarodnostSuhrn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dietaNarodnostSuhrn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5e08ed6b-e4dd-40db-a1a9-8cfd117d3761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dietaNarodnostSuhrn</value>
      <webElementGuid>753fbb2e-2c09-47e8-88ea-c2b90cd45641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>slovenská</value>
      <webElementGuid>591643bc-ebe5-4ed2-90d8-6be71818811a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dietaNarodnostSuhrn&quot;)</value>
      <webElementGuid>3f1f7ae1-9e85-4386-a3f4-3b4cc7b943ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dietaNarodnostSuhrn']</value>
      <webElementGuid>89aea170-0550-4cbc-9eee-01e13c3f96bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suhrnny-prehlad']/div[3]/div[2]/div[8]/div[2]</value>
      <webElementGuid>016cd861-59c8-4cd0-9a15-5ceffa8ae8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Národnosť'])[3]/following::div[1]</value>
      <webElementGuid>527e4ff6-162e-4a76-806d-f94d207298cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slovensko'])[2]/following::div[3]</value>
      <webElementGuid>f034f17b-e9df-46fe-bab9-bfed7757ad8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Štátna príslušnosť'])[3]/preceding::div[1]</value>
      <webElementGuid>c0e25374-a57f-4c00-8d12-8ac901ba275b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slovenská republika'])[5]/preceding::div[2]</value>
      <webElementGuid>6b659d8a-17f4-431d-b097-a7e309c69d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div[3]/div[2]/div[8]/div[2]</value>
      <webElementGuid>846d30ed-ca59-4177-99bf-cf6c5e261c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dietaNarodnostSuhrn' and (text() = 'slovenská' or . = 'slovenská')]</value>
      <webElementGuid>1729d97c-bd89-45e9-b0dc-1f4e6f428255</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
