<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dtum narodenia_zakonnyZastupcaDatumNarodenia</name>
   <tag></tag>
   <elementGuidId>33885944-2439-4826-a511-b35395a57fe0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zakonnyZastupcaDatumNarodenia']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zakonnyZastupcaDatumNarodenia</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>943c1920-92da-454b-8f63-29a6c81adca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zakonnyZastupcaDatumNarodenia</value>
      <webElementGuid>22e9376e-dea4-42c6-9be0-436639a1086d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>26.02.1966</value>
      <webElementGuid>bd7b1e5c-14a0-4992-b83a-352d8fc97d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zakonnyZastupcaDatumNarodenia&quot;)</value>
      <webElementGuid>582157d4-9e68-4b7e-9c46-4fb0076f57ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zakonnyZastupcaDatumNarodenia']</value>
      <webElementGuid>eceb5b4c-12ed-4c97-a575-821b759557fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz1']/div[6]/div[2]</value>
      <webElementGuid>d29b2879-557d-407f-8858-1f55e5d3984d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum narodenia'])[6]/following::div[1]</value>
      <webElementGuid>33b81d5c-442a-4c11-901c-521f1f0b9b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[18]/following::div[3]</value>
      <webElementGuid>f7969212-605b-42be-bf39-7ddb6be55f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Korešpondenčná adresa'])[3]/preceding::div[1]</value>
      <webElementGuid>5b1ab801-ea91-4249-9578-55ad9e0cffc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Egrešská 12/1, 01589, Predmier, Slovenská republika'])[3]/preceding::div[2]</value>
      <webElementGuid>8cb416f8-5e54-430e-bea8-657e0d1707c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='26.02.1966']/parent::*</value>
      <webElementGuid>4051b886-68f6-4a3f-b4d9-6f87d0b68e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[6]/div[2]</value>
      <webElementGuid>0175d25d-f29a-49ce-b1dc-6e41ad2aa945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zakonnyZastupcaDatumNarodenia' and (text() = '26.02.1966' or . = '26.02.1966')]</value>
      <webElementGuid>46c802dc-411f-44c4-8b81-6bebac7dbb31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
