<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rodn priezvisko_zakonnyZastupcaRodnePriezvisko</name>
   <tag></tag>
   <elementGuidId>e27a55f0-05f1-4c3e-988d-0add2703f1ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zakonnyZastupcaRodnePriezvisko']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zakonnyZastupcaRodnePriezvisko</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8a631efb-9ede-487d-865f-8c93f0b307b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zakonnyZastupcaRodnePriezvisko</value>
      <webElementGuid>f426261b-a537-4a26-af05-d812f2706d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>9fbf0ae1-28aa-4834-83fe-51f5f7016dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zakonnyZastupcaRodnePriezvisko&quot;)</value>
      <webElementGuid>ce64ea0b-8f4c-467c-b5d3-267fbaea0762</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zakonnyZastupcaRodnePriezvisko']</value>
      <webElementGuid>69f1ffae-103d-4e8d-a68d-aaebd0756089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz1']/div[3]/div[2]</value>
      <webElementGuid>e4dd2374-eeae-494b-a97e-023b8508cd44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodné priezvisko'])[6]/following::div[1]</value>
      <webElementGuid>136dcb3f-ac05-4c24-8a1e-94ed6e8aa8b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mrkva'])[1]/following::div[3]</value>
      <webElementGuid>edce9211-6207-4da0-b9e4-81dbcd62d63c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodné číslo'])[7]/preceding::div[1]</value>
      <webElementGuid>2b59c4ec-438c-46be-a5b5-1a79c50d182d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Číslo elektronickej schránky'])[4]/preceding::div[4]</value>
      <webElementGuid>b1138f9f-8948-430b-961d-c111d5bb04c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[3]/div[2]</value>
      <webElementGuid>c24b3cfa-5728-4fc1-9020-fc41d8eea278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zakonnyZastupcaRodnePriezvisko' and (text() = '-' or . = '-')]</value>
      <webElementGuid>210a6c7d-229e-4c30-8101-858090404375</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
