<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Korepondenn adresa_zakonnyZastupcaAdres_9d2f75</name>
   <tag></tag>
   <elementGuidId>eec5660a-6440-4b49-bec2-6470b60d11c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zakonnyZastupcaAdresaBydliska']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zakonnyZastupcaAdresaBydliska</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1ac4f62c-8fc3-4a14-acdc-19530ca90885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zakonnyZastupcaAdresaBydliska</value>
      <webElementGuid>7c161c56-492c-4db6-babb-d286148e0e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Egrešská 12/1, 01589, Predmier, Slovenská republika</value>
      <webElementGuid>4aebc94d-2f4c-460a-98ce-70f0a21774d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zakonnyZastupcaAdresaBydliska&quot;)</value>
      <webElementGuid>39fc6bf3-d275-431c-9677-cd2ab933943f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zakonnyZastupcaAdresaBydliska']</value>
      <webElementGuid>08f50e67-5959-4c3d-b097-0492bc329305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz1']/div[7]/div[2]</value>
      <webElementGuid>60a77aab-56bf-4a22-a524-92eadd8fe51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Korešpondenčná adresa'])[3]/following::div[1]</value>
      <webElementGuid>e7e12197-c6c0-4af3-a3a3-c85dea6131d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum narodenia'])[6]/following::div[4]</value>
      <webElementGuid>a664a546-ebdf-4d0f-84f2-8b795dcc7e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail'])[4]/preceding::div[1]</value>
      <webElementGuid>cae11d3c-8ccd-4200-891d-10ca6febb607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[19]/preceding::div[2]</value>
      <webElementGuid>01aa30ad-bec5-4cf1-9d2c-f273680c25e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[7]/div[2]</value>
      <webElementGuid>756f5106-98e2-4500-b05f-38b5e22d200d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zakonnyZastupcaAdresaBydliska' and (text() = 'Egrešská 12/1, 01589, Predmier, Slovenská republika' or . = 'Egrešská 12/1, 01589, Predmier, Slovenská republika')]</value>
      <webElementGuid>b14db9d4-0a11-472e-994c-a0535b62a6f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
