<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Meno_zakonnyZastupcaMeno</name>
   <tag></tag>
   <elementGuidId>277e0f99-c1b5-4874-894e-094d5a899064</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zakonnyZastupcaMeno']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zakonnyZastupcaMeno</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>642cd8ac-c7d7-409a-9a42-f24acde1c008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zakonnyZastupcaMeno</value>
      <webElementGuid>cae6ac5c-f603-4685-b26a-f900eb363e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jozef</value>
      <webElementGuid>f839d58f-66d8-407e-a120-e28c535879b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zakonnyZastupcaMeno&quot;)</value>
      <webElementGuid>955cf669-7dcb-49e8-a127-f6bfd2cc6190</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zakonnyZastupcaMeno']</value>
      <webElementGuid>1232ca4f-1dc9-454b-ac5e-e47f89c86bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz1']/div/div[2]</value>
      <webElementGuid>7d18d6c2-2554-459d-8131-7f53e8138f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meno'])[6]/following::div[1]</value>
      <webElementGuid>de0c2e1c-c24d-4e99-b541-d3b1a359acec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Osobné údaje zákonného zástupcu č. 1'])[2]/following::div[4]</value>
      <webElementGuid>8e2f0739-7eb5-4b63-b576-47a45e94b4b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priezvisko'])[6]/preceding::div[1]</value>
      <webElementGuid>1be723b3-aa2f-4808-9899-0aa04ec96409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mrkva'])[1]/preceding::div[2]</value>
      <webElementGuid>3a9c5b62-c3f5-471a-85bf-aa788d93459c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jozef']/parent::*</value>
      <webElementGuid>5f5b3f9f-5d83-4587-b9d5-d18426fd2ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/div/div[2]</value>
      <webElementGuid>8a5e6026-6e92-459a-9737-de60afb1ed54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zakonnyZastupcaMeno' and (text() = 'Jozef' or . = 'Jozef')]</value>
      <webElementGuid>76f43b7f-2492-497c-83de-b07e2aa3d15b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
