<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rodn slo_zakonnyZastupcaRodneCislo</name>
   <tag></tag>
   <elementGuidId>9682ee73-621c-4f95-9d84-299f13bf2688</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zakonnyZastupcaRodneCislo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zakonnyZastupcaRodneCislo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2e650848-1904-4350-9e13-a806bb48320f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zakonnyZastupcaRodneCislo</value>
      <webElementGuid>4fd4edb4-f54c-4f9a-9023-c8f640306440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>660226/9146</value>
      <webElementGuid>7acd2776-a672-448b-99cb-f7bd7a09ce4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zakonnyZastupcaRodneCislo&quot;)</value>
      <webElementGuid>5da6fc2f-87b7-4d4d-a220-be5c7a0443a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zakonnyZastupcaRodneCislo']</value>
      <webElementGuid>b3862294-2b81-4f23-b6c9-1dcf36950674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz1']/div[4]/div[2]</value>
      <webElementGuid>6453c6fd-43d8-4d0e-9c2a-b9e2ca6df7f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodné číslo'])[7]/following::div[1]</value>
      <webElementGuid>f4909407-54fa-49fc-b3f5-8f2ee0af3d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[17]/following::div[3]</value>
      <webElementGuid>6483b90e-edb8-439b-bb8e-fafa4c6f5925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Číslo elektronickej schránky'])[4]/preceding::div[1]</value>
      <webElementGuid>d91e2dc1-f932-4a30-b9f8-c9e6913d68a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[18]/preceding::div[2]</value>
      <webElementGuid>d4516c4d-30ec-47fd-8d86-cbe4cb7a62ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='660226/9146']/parent::*</value>
      <webElementGuid>189009b3-44bc-4163-8517-624861d9dc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/div[4]/div[2]</value>
      <webElementGuid>3599e74a-b38e-46c9-a22d-bebe48980260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zakonnyZastupcaRodneCislo' and (text() = '660226/9146' or . = '660226/9146')]</value>
      <webElementGuid>c1540797-c789-4263-878f-b002fcbb989a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
