<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Predprimrne vzdelvanie_povinnePredprima_f31d60</name>
   <tag></tag>
   <elementGuidId>0c04ec77-d43a-4525-852a-6eda2559b688</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='povinnePredprimarneVzdelavanie']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#povinnePredprimarneVzdelavanie</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1cb85c8d-2650-4e7b-9a99-21e94ae579b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>povinnePredprimarneVzdelavanie</value>
      <webElementGuid>b1fb847b-1e04-4a58-9c25-b13f0962ab86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>83aa9858-2a75-401f-a987-60f2933e4eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;povinnePredprimarneVzdelavanie&quot;)</value>
      <webElementGuid>3411334d-33b4-4286-8d24-db517421a382</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='povinnePredprimarneVzdelavanie']</value>
      <webElementGuid>12d6bd87-9ffa-4553-9607-49b25c10352d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pridanie-dietata-suhrn']/div[2]/div[15]/div[2]</value>
      <webElementGuid>e1f5e29d-994a-4b5b-83f0-38fa8968bf79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Predprimárne vzdelávanie'])[1]/following::div[1]</value>
      <webElementGuid>5819ae2d-aa33-46a4-a715-389cfdde776f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Egrešská 12/1, 01589, Predmier (Bytča), Slovenská republika'])[2]/following::div[3]</value>
      <webElementGuid>e598ae31-f0d8-49dd-9728-1df741736b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Osobné údaje dieťaťa'])[4]/preceding::div[1]</value>
      <webElementGuid>dc590408-e2a4-4acf-b1e2-620d33ed05fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodné číslo'])[3]/preceding::div[2]</value>
      <webElementGuid>29b366be-f20e-4b2d-8aa6-a119cf09f4f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div[2]</value>
      <webElementGuid>269003de-2dd4-47c4-8393-5d27c182183c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'povinnePredprimarneVzdelavanie' and (text() = '-' or . = '-')]</value>
      <webElementGuid>cd836d13-8827-4057-8f3a-dcee547ddc42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
