<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Adresa miesta, kde sa diea obvykle zdri_2f5e08</name>
   <tag></tag>
   <elementGuidId>5b5dd671-e316-43a0-9552-855bc0a13dc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dietaAdresaObvyklehoPobytuSuhrn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dietaAdresaObvyklehoPobytuSuhrn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>34b2e230-a499-42c2-b16e-30494001b0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dietaAdresaObvyklehoPobytuSuhrn</value>
      <webElementGuid>c84655f7-b73b-4f16-8656-5d42e8326ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Egrešská 12/1, 01589, Predmier, Slovenská republika</value>
      <webElementGuid>f1434123-c5b8-4446-8c4e-1e298966391b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dietaAdresaObvyklehoPobytuSuhrn&quot;)</value>
      <webElementGuid>b0641b9e-203e-42c5-9c64-ff1dce9421f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dietaAdresaObvyklehoPobytuSuhrn']</value>
      <webElementGuid>e8551696-ebe0-4973-a92f-8e0568854cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suhrnny-prehlad']/div[3]/div[2]/div[13]/div[2]</value>
      <webElementGuid>3c18b76b-59cb-4b94-bf1e-bfd40aaaedb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adresa miesta, kde sa dieťa obvykle zdržiava, ak je iná, než adresa trvalého pobytu.'])[2]/following::div[1]</value>
      <webElementGuid>497e2874-8f48-47fb-8849-1fec337cb031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Egrešská 12/1, 01589, Predmier, Slovenská republika'])[1]/following::div[3]</value>
      <webElementGuid>9caeb6d7-f359-4e5c-8158-c1525b166938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Povinné predprimárne vzdelávanie aktuálne v'])[2]/preceding::div[1]</value>
      <webElementGuid>91125813-6e1f-4789-abc3-01f10da62ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[10]/preceding::div[2]</value>
      <webElementGuid>38cfacb1-308b-4561-ad70-b5e22d0580ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div[3]/div[2]/div[13]/div[2]</value>
      <webElementGuid>37d11732-fb03-4ae4-ac2c-561ef929a942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dietaAdresaObvyklehoPobytuSuhrn' and (text() = 'Egrešská 12/1, 01589, Predmier, Slovenská republika' or . = 'Egrešská 12/1, 01589, Predmier, Slovenská republika')]</value>
      <webElementGuid>d123f225-2382-4442-8ae0-6f8041f5f223</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
