<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_In materinsk jazyk_dietaInyMaterinskyJa_0014a5</name>
   <tag></tag>
   <elementGuidId>f1b3213a-bddb-4977-b7c4-658019cadba6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dietaInyMaterinskyJazykSuhrn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dietaInyMaterinskyJazykSuhrn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3aa20fe4-3d55-41e5-a6f3-5b0ca9eff4a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dietaInyMaterinskyJazykSuhrn</value>
      <webElementGuid>f91dc858-181d-4a82-b658-f20bde235d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>093439fe-8057-4115-ab8e-45fcabee5c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dietaInyMaterinskyJazykSuhrn&quot;)</value>
      <webElementGuid>d9a3e2c8-9f28-4da2-a786-8dd89f56648e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dietaInyMaterinskyJazykSuhrn']</value>
      <webElementGuid>6282f0b2-8ddc-4703-ba55-4cb33128416f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suhrnny-prehlad']/div[3]/div[2]/div[11]/div[2]</value>
      <webElementGuid>31c507b1-55f4-4bcc-949b-fc48dfbb6795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iný materinský jazyk'])[3]/following::div[1]</value>
      <webElementGuid>70e774eb-1a67-474f-9aa6-d38a8ce958c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='slovenský'])[4]/following::div[3]</value>
      <webElementGuid>b94107dc-d2f2-4bc6-92c8-404f37bc8c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adresa trvalého pobytu'])[2]/preceding::div[1]</value>
      <webElementGuid>23732109-e782-4909-bad3-18456c8f6fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Egrešská 12/1, 01589, Predmier, Slovenská republika'])[1]/preceding::div[2]</value>
      <webElementGuid>7a44d021-9699-4f9b-81c7-af4c28625d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div[3]/div[2]/div[11]/div[2]</value>
      <webElementGuid>338410b8-8fae-4f3b-abf3-bf255f433994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dietaInyMaterinskyJazykSuhrn' and (text() = '-' or . = '-')]</value>
      <webElementGuid>d60cd9e1-2d8b-4b87-9d49-fdd49511b7cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
