<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1</name>
   <tag></tag>
   <elementGuidId>f7ff675f-dbba-4a80-a488-ac68fd7bff8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='skoly']/div[2]/div[3]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a20e3c8c-fdb2-44a0-95dd-2f092113e2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jalmová 266/19, 06534 Prešov</value>
      <webElementGuid>1bd80426-a91d-4ff7-8c99-c706bed115a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skoly&quot;)/div[@class=&quot;panel-content&quot;]/div[@class=&quot;panel-item&quot;]/div[2]</value>
      <webElementGuid>f321cb7b-1c49-44b4-b631-31ca37ccace7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='skoly']/div[2]/div[3]/div[2]</value>
      <webElementGuid>b5088d29-ecd1-405c-8a65-5afd318103f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sídlo základnej školy'])[1]/following::div[1]</value>
      <webElementGuid>c39ed444-d5b0-4c1e-b49b-e902b9757026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Základná škola pre AT'])[3]/following::div[3]</value>
      <webElementGuid>d4f713c9-a0ec-4aaf-901e-4cacbb938093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vzdelávanie dieťaťa žiadam poskytovať v jazyku'])[2]/preceding::div[1]</value>
      <webElementGuid>540fb4dd-8dee-42ff-b6b1-b326697b0ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='undefined'])[1]/preceding::div[2]</value>
      <webElementGuid>159cbd32-1b7c-4a03-afdd-1a7ba6681077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[3]/div[2]</value>
      <webElementGuid>d8c6dd02-d49c-48e9-ae05-ba179044a973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Jalmová 266/19, 06534 Prešov' or . = 'Jalmová 266/19, 06534 Prešov')]</value>
      <webElementGuid>1e3b9717-fe50-4183-8cca-a275a9ee24a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
