<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-zastupca1Priezvisko</name>
   <tag></tag>
   <elementGuidId>7f6afe72-88b0-47d8-a6eb-1bef82587460</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-zastupca1Priezvisko']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-zastupca1Priezvisko</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65ccde13-5c7f-4959-98f7-3a4f156f4152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>bec4ce75-fa64-4d13-a36c-0784e8e91c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7af51544-4a2d-4068-8ad3-43c2394f30fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-zastupca1Priezvisko</value>
      <webElementGuid>98b7a3a1-e19f-4736-8baf-8078b7bfe50d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>d38d174f-cccf-4a95-bd57-1770d610984c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-zastupca1Priezvisko&quot;)</value>
      <webElementGuid>1718b019-337c-4e19-b6d3-4cccf0506f06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-zastupca1Priezvisko']</value>
      <webElementGuid>cde507ab-d23c-4383-a798-76d5b4b148b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zastupca1Priezvisko']/div/div[2]/input</value>
      <webElementGuid>04919a15-2c02-40ca-b9e3-52a3ed9708ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]/div/div[2]/input</value>
      <webElementGuid>e9ded938-87aa-466c-8c35-d0bd1a1cd294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-zastupca1Priezvisko']</value>
      <webElementGuid>e4069cac-c781-44ff-b820-53bc2927d685</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
