<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_no_zsDPDSkolskyKlubRadio_option_1</name>
   <tag></tag>
   <elementGuidId>98cb57ad-fe64-491a-a6f9-f2bb6cab2414</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='zsDPDSkolskyKlubRadio_option_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zsDPDSkolskyKlubRadio_option_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6dbbb6cb-5aec-459d-a8fc-091cf22a23a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>0432c6a3-b3d4-442d-9a11-9188b52003ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zsDPDSkolskyKlubRadio_option_1</value>
      <webElementGuid>ad348b3e-84bc-444e-b0a9-34624a64d6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zsDPDSkolskyKlubRadio</value>
      <webElementGuid>4f93a76f-ed0b-4beb-b504-3ef8eb098562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ba03679c-d9c8-4b85-92a1-a56aed2e8958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d0fb124c-02b8-4f07-a9bf-0630d416ab7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zsDPDSkolskyKlubRadio_option_1&quot;)</value>
      <webElementGuid>69c350c4-7613-4037-adc8-a571183319ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zsDPDSkolskyKlubRadio_option_1']</value>
      <webElementGuid>c801daf1-4a21-41e6-820a-d88bc5af344b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zsDPDSkolskyKlubRadio']/div/fieldset/div[3]/div[2]/input</value>
      <webElementGuid>0b7f476c-8f5f-48e5-8cc9-2cc9bc02c885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/fieldset/div[3]/div[2]/input</value>
      <webElementGuid>276d5b09-2620-4ad1-a36d-35edb1960d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'zsDPDSkolskyKlubRadio_option_1' and @name = 'zsDPDSkolskyKlubRadio' and @type = 'radio']</value>
      <webElementGuid>ee15512f-fe4b-457d-b444-cc56a778ad1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
