<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-adresaTPPSC</name>
   <tag></tag>
   <elementGuidId>dd7a60c9-e440-4aa3-ac2e-54ae477a7c21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-adresaTPPSC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-adresaTPPSC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0817fd5a-a888-414d-9430-d63c381697d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>c99ceb72-b313-4e6c-bf02-d657b35a24ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9c03fa25-3aca-4ed2-b4f9-680003b2e420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-adresaTPPSC</value>
      <webElementGuid>627bd54d-eea3-4352-8b7c-e4f6e0ad4e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>75bc3aaf-d409-4ce0-99a9-6ea5ef4442d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-adresaTPPSC&quot;)</value>
      <webElementGuid>f3594ddd-6f30-4ab8-8f9c-2c3e0aa0a498</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-adresaTPPSC']</value>
      <webElementGuid>3158d34d-cc9b-4694-9ccb-757d41bf00df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adresaTPPSC']/div/div[2]/input</value>
      <webElementGuid>98fdbb64-67e2-4dfd-9d37-c37915e32a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[5]/div/div[2]/input</value>
      <webElementGuid>945f1c1e-9ef3-4d6f-b7d9-85bcaa17d6aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-adresaTPPSC']</value>
      <webElementGuid>ed893b4f-9118-49cc-90a8-9f0b02e6a822</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
