<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-datumPodaniaPrihlaskyDen</name>
   <tag></tag>
   <elementGuidId>13100569-7142-4005-97b6-904adf1f2d2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-datumPodaniaPrihlaskyDen']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-datumPodaniaPrihlaskyDen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92ca2acd-dc58-484e-8e09-0e4f3746d96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>ad8891ac-a2eb-4f04-baae-eb4ddc1054b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>73acb45b-a5fd-41b4-ae21-ad2f9b168c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-datumPodaniaPrihlaskyDen</value>
      <webElementGuid>c4edff73-43e0-49d9-aec8-e646d3fce17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>56422f5a-0a23-4127-be37-3e59b24626af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD</value>
      <webElementGuid>6ab3fe32-a4a4-43d1-9c3f-358a07e61d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-datumPodaniaPrihlaskyDen&quot;)</value>
      <webElementGuid>15bf78d3-b412-4dea-a431-8c43680f1aa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-datumPodaniaPrihlaskyDen']</value>
      <webElementGuid>d14d0723-0a18-4b90-bc27-b3047aabb805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datumPodaniaPrihlaskyDen']/div/div[2]/input</value>
      <webElementGuid>05f96ae2-1fea-432e-bb3b-a9916433856a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>f33e6e88-adac-46f5-b929-6b28ffce2a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-datumPodaniaPrihlaskyDen' and @placeholder = 'DD']</value>
      <webElementGuid>1b6c3c6f-fada-4bcb-b601-5f999000ffcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
