<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Etick_zsDPDVychovaRadio_option_1</name>
   <tag></tag>
   <elementGuidId>bf745f09-1a1d-45a9-aff6-a442a265d96b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='zsDPDVychovaRadio_option_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zsDPDVychovaRadio_option_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0eb05248-2794-4db9-9539-a73e7a6ae2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>92170f60-e4da-47af-9b6c-156e505f70dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zsDPDVychovaRadio_option_1</value>
      <webElementGuid>99c5c2bc-d489-4847-8846-a0d271c96982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zsDPDVychovaRadio</value>
      <webElementGuid>b329dbd6-b885-40f2-9644-00164133c454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>093b876a-e63c-48c8-906c-aa8da0ab429b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>dddc7eaa-daeb-43c4-90df-0a1827c83e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zsDPDVychovaRadio_option_1&quot;)</value>
      <webElementGuid>9ef09dec-6352-4508-9ec1-fcfcec0ced0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zsDPDVychovaRadio_option_1']</value>
      <webElementGuid>081faa7e-47ad-4890-af97-4f215af9d838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zsDPDVychovaRadio']/div/fieldset/div[3]/div[2]/input</value>
      <webElementGuid>f37ce838-1c66-4a52-9fe0-edff89edab31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/fieldset/div[3]/div[2]/input</value>
      <webElementGuid>8541da53-5f97-4d57-a1d4-33401a517f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'zsDPDVychovaRadio_option_1' and @name = 'zsDPDVychovaRadio' and @type = 'radio']</value>
      <webElementGuid>c6919c7a-6e3f-4c0b-9ae2-4f34feb79d95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
