<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_(nepovinn)_textarea-DPDPoznamkaText</name>
   <tag></tag>
   <elementGuidId>96900784-5642-4054-ad06-50e7527be283</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='textarea-DPDPoznamkaText']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#textarea-DPDPoznamkaText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b09b2ac9-23ae-4910-844f-eb8da52b36b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-textarea</value>
      <webElementGuid>2bc39d81-1baa-44ec-83c9-fad263cc41e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>0683acf1-a55f-4369-a94b-606fac39faa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textarea-DPDPoznamkaText</value>
      <webElementGuid>112116c7-c51c-45bd-b2fc-a241ccf8d77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>681a70b4-322e-4330-951a-90e8fb986e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textarea-DPDPoznamkaText&quot;)</value>
      <webElementGuid>3127add4-08e0-4e33-99e9-452345e0f399</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textarea-DPDPoznamkaText']</value>
      <webElementGuid>4dbe30ce-9dc1-4407-933b-51d1a111a888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DPDPoznamkaText']/div/div[2]/textarea</value>
      <webElementGuid>3de3733c-d10a-4317-97ff-fed051893b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div[2]/textarea</value>
      <webElementGuid>7c3eeb67-1642-4bc8-abdd-29591010389f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'textarea-DPDPoznamkaText']</value>
      <webElementGuid>e9e9bf19-5639-4f0d-b8ea-e58d9e1fc346</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
