<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Oznmenia_logoutBtn</name>
   <tag></tag>
   <elementGuidId>5081591a-0d1e-4d13-87c8-788fe8671495</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logoutBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='logoutBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0854e596-7a29-4e74-8462-10c0d12b0e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logoutBtn</value>
      <webElementGuid>663668f4-d652-49fa-a46e-047afb7a43cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/logout?returnurl=%2F</value>
      <webElementGuid>6df9d546-aa7b-4e93-b9df-59e23d9aaa5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Odhlásiť</value>
      <webElementGuid>1f2b1412-8b7a-4dd2-9b42-9bd3c5dfa7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;govuk-frontend-supported&quot;]/div[@class=&quot;wrapper-full header&quot;]/div[@class=&quot;govuk-header__wrapper&quot;]/header[@class=&quot;govuk-header idsk-shadow-head&quot;]/div[@class=&quot;govuk-predheader govuk-width-container&quot;]/div[@class=&quot;govuk-header__btns-search&quot;]/div[@class=&quot;govuk-header__actionPanel desktop mobile-hidden&quot;]/ul[@class=&quot;idsk-dropdown__options idsk-dropdown__options--down profil-options&quot;]/li[@class=&quot;idsk-dropdown__option idsk-pseudolabel__wrapper&quot;]/a[@id=&quot;logoutBtn&quot;]</value>
      <webElementGuid>39ab1c38-3e7b-477d-9385-cc0700b776fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='logoutBtn']</value>
      <webElementGuid>99f57382-1534-4893-8dbd-fff0def610e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Odhlásiť')]</value>
      <webElementGuid>3372cc20-4b83-4165-93f2-efe71655ce75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oznámenia'])[1]/following::a[1]</value>
      <webElementGuid>41bf8bdf-09fb-4a65-b0a3-88c074caee9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Môj profil'])[1]/following::a[2]</value>
      <webElementGuid>e5f3b035-2f6d-4c00-81cc-dc812cd388ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[2]/preceding::a[1]</value>
      <webElementGuid>ebd5673d-29dd-499f-a8d1-573f2c3204b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Správa prihlášok'])[1]/preceding::a[1]</value>
      <webElementGuid>4c6a1185-4848-4cfb-8d83-0a853adfc937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Odhlásiť']/parent::*</value>
      <webElementGuid>bea9d2cb-191c-4243-9e56-8eaea1610615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/logout?returnurl=%2F')]</value>
      <webElementGuid>fbdaaff4-d4d1-45c1-8fda-ee717522db1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>1faf1d49-adc6-4587-99ec-04b5b75b6900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'logoutBtn' and @href = '/logout?returnurl=%2F' and (text() = 'Odhlásiť' or . = 'Odhlásiť')]</value>
      <webElementGuid>4042e593-1a17-4dee-9992-655436d5964a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
