<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1</name>
   <tag></tag>
   <elementGuidId>986e964a-cec0-4731-aa9e-5d9e3ff9be27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pouzivatel-item > div.pouzivatel-name-wrapper > div > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sprava-pouzivatelov']/div/div/div/div[2]/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a7a6ee1e-cc7f-4cbc-8db7-aea172a55554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Martin Martinský</value>
      <webElementGuid>3789cfed-1173-4584-966a-e325cfd26a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sprava-pouzivatelov&quot;)/div[@class=&quot;govuk-main-wrapper&quot;]/div[@class=&quot;sprava-pouzivatelov-main&quot;]/div[@class=&quot;pouzivatel-item-container&quot;]/div[@class=&quot;pouzivatel-item&quot;]/div[@class=&quot;pouzivatel-name-wrapper&quot;]/div[1]/span[1]</value>
      <webElementGuid>e482907a-f8fb-4fc4-9f8d-348825687ced</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sprava-pouzivatelov']/div/div/div/div[2]/div/div/span</value>
      <webElementGuid>c84239d9-ea37-49e6-815e-ae9209bb4a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odstrániť'])[1]/following::span[1]</value>
      <webElementGuid>b75736ac-127c-4668-89ee-f3aa469c2a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Potvrdiť'])[1]/following::span[2]</value>
      <webElementGuid>83454fd7-d45a-4d98-88c2-500ba26d89f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EDUID: 930570706'])[1]/preceding::span[1]</value>
      <webElementGuid>3d082eb7-2532-4803-b493-d911edf0792d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rola'])[1]/preceding::span[1]</value>
      <webElementGuid>d14b77f9-da23-4347-90da-dda87266243b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Martin Martinský']/parent::*</value>
      <webElementGuid>c4ebe5d2-5ebe-45d5-9a9e-c017d185119f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/div/span</value>
      <webElementGuid>0f7b0468-aff4-4cf5-810f-58aa599cf737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Martin Martinský' or . = 'Martin Martinský')]</value>
      <webElementGuid>a876b406-1608-4790-bbc3-eaf269281f5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
