<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_R_sprava-nazov</name>
   <tag></tag>
   <elementGuidId>c3ccd3c5-6051-47d7-af3c-7261a2587a6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@class='sprava-nazov']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>48b18ed7-5c30-4c73-a223-11f43376a047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sprava-nazov</value>
      <webElementGuid>ba1bdbe1-bc33-40a8-af26-5003c7a82fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Riaditeľ  školy Základná škola pre AT požadoval ďalšie prílohy.</value>
      <webElementGuid>cc50fdb1-638e-46e7-8f3b-19f3e7f64693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skoly&quot;)/div[@class=&quot;panel-content&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;sprava-item&quot;]/div[@class=&quot;sprava-header&quot;]/div[@class=&quot;sprava-header-text&quot;]/span[@class=&quot;sprava-nazov&quot;]</value>
      <webElementGuid>ec08af51-d1dc-400a-ab9a-17b7ee814ce5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='skoly']/div[2]/div[10]/div/div/div[2]/span</value>
      <webElementGuid>d629ac78-f547-44eb-81f5-d506538c5e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R'])[2]/following::span[1]</value>
      <webElementGuid>5cf30596-7042-46e9-9a88-f4d07f8d423d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info'])[7]/following::span[1]</value>
      <webElementGuid>55cbfbc9-5e87-469c-b0bc-99e9e1f6c508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Typ prílohy:'])[2]/preceding::span[2]</value>
      <webElementGuid>91d65ae5-45ac-4e5a-b091-dfad77f182be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Čestné vyhlásenie zákonného zástupcu'])[2]/preceding::span[2]</value>
      <webElementGuid>37022527-cce8-4fc8-b409-606e1a6a0b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/span</value>
      <webElementGuid>082a6ec1-40c5-4d26-ba14-f9e6f565d771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Riaditeľ  školy Základná škola pre AT požadoval ďalšie prílohy.' or . = 'Riaditeľ  školy Základná škola pre AT požadoval ďalšie prílohy.')]</value>
      <webElementGuid>229a9fe8-6c0e-4913-bcd4-7d5238c7f0a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
