<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_test</name>
   <tag></tag>
   <elementGuidId>985e3b9d-7bae-4802-81e5-42a65cb8c65d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dpDietataPoznamka']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dpDietataPoznamka</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e14777fd-c55f-4264-9abb-bd5fcce53bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dpDietataPoznamka</value>
      <webElementGuid>ce88b5f6-ca05-4be3-ba6c-fea7a8de722a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>ecaa0ae2-a27e-461a-b72e-43428f0d833b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dpDietataPoznamka&quot;)</value>
      <webElementGuid>15b89558-2648-4c02-a14c-1e423695c314</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dpDietataPoznamka']</value>
      <webElementGuid>2624f983-e54a-445f-9820-67ae07283fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdpDietata']/div[2]/div[5]/div[7]/div[2]</value>
      <webElementGuid>a4b2c715-dae5-4ba4-8d5c-981f1c65ccb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Poznámka'])[1]/following::div[1]</value>
      <webElementGuid>3d054b76-da8f-45da-9fe1-4be19d591b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[18]/following::div[3]</value>
      <webElementGuid>483a3632-0ad8-4cbb-a52c-622491c859a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Späť'])[1]/preceding::div[1]</value>
      <webElementGuid>65ed60b8-8771-464f-874b-8ec8f11f6186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ďalej'])[1]/preceding::div[1]</value>
      <webElementGuid>529775bb-3473-49e3-919c-340c80ece8f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='test']/parent::*</value>
      <webElementGuid>d391d23e-a30d-4e18-842e-05fce06609b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div[5]/div[7]/div[2]</value>
      <webElementGuid>ce5375bf-115e-4ced-84da-7833c060636b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dpDietataPoznamka' and (text() = 'test' or . = 'test')]</value>
      <webElementGuid>01099141-bbbe-4f33-8042-ea7ded903104</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
