<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_mongolsk</name>
   <tag></tag>
   <elementGuidId>576a84d6-f6d3-494c-a961-56ecd6a54bac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dietaInyMaterinskyJazyk']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dietaInyMaterinskyJazyk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f0133236-a9fa-43f0-981d-845efc77239e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dietaInyMaterinskyJazyk</value>
      <webElementGuid>f0cf91d9-0700-4b0b-b8e3-5c91dfd67389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mongolský</value>
      <webElementGuid>576a88a7-683f-4e57-9f0c-fe07bd55a572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dietaInyMaterinskyJazyk&quot;)</value>
      <webElementGuid>6e4c3311-270e-4380-96b6-1432149ee436</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dietaInyMaterinskyJazyk']</value>
      <webElementGuid>7e32907c-d610-42a1-b3d8-d98c1613a4c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suhrnny-prehlad']/div[3]/div[2]/div[10]/div[2]</value>
      <webElementGuid>f1791ad1-b4f7-4447-bb62-2bbd9637cd8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iný materinský jazyk'])[2]/following::div[1]</value>
      <webElementGuid>29812943-f68e-450e-ad85-0ea4e97b1b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='slovenský'])[3]/following::div[3]</value>
      <webElementGuid>8882175a-af2a-43aa-889e-02195f80255b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adresa trvalého pobytu'])[1]/preceding::div[1]</value>
      <webElementGuid>346b3c58-f1ce-4261-ad9e-51bcdc60af66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lechkého 2/87, 62874, Banská Bystrica (Banská Bystrica), Slovenská republika'])[1]/preceding::div[2]</value>
      <webElementGuid>cb3416da-e2cf-4b15-963a-900a85e98d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[10]/div[2]</value>
      <webElementGuid>ad7c4876-c108-4e89-9291-34c137266dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dietaInyMaterinskyJazyk' and (text() = 'mongolský' or . = 'mongolský')]</value>
      <webElementGuid>e5d4c1d2-cb5f-4c0a-bfcc-00eff908e7b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
