<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_zsDPDSkolskyKlubRadio</name>
   <tag></tag>
   <elementGuidId>546d9a6f-6a65-4be8-a94d-dd7089aa3bc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='zsDPDSkolskyKlubRadio_option_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zsDPDSkolskyKlubRadio_option_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94310ee0-5a16-4693-b50b-9e4453ec138c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>da608c92-0125-4460-8ca9-37f0effc363b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zsDPDSkolskyKlubRadio_option_0</value>
      <webElementGuid>baba78e6-91f4-49ff-b993-414416391f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zsDPDSkolskyKlubRadio</value>
      <webElementGuid>19a2fea6-1f69-43a8-add0-86fda25e947b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5d8dd150-e284-403a-add2-2cd22d61fb78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>97dfd4cf-891a-4118-9fe1-32373132938a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zsDPDSkolskyKlubRadio_option_0&quot;)</value>
      <webElementGuid>4ceeb5a2-0865-4a7b-884d-ee9164e352e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zsDPDSkolskyKlubRadio_option_0']</value>
      <webElementGuid>ad7745db-eafb-4646-a68e-8df3a034dad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zsDPDSkolskyKlubRadio']/div/fieldset/div[3]/div/input</value>
      <webElementGuid>7f70d857-5211-45b9-b199-adbb2556e419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/fieldset/div[3]/div/input</value>
      <webElementGuid>3fbeb3c2-0c43-44cd-b232-5d67ab5fde8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'zsDPDSkolskyKlubRadio_option_0' and @name = 'zsDPDSkolskyKlubRadio' and @type = 'radio']</value>
      <webElementGuid>84abecfa-b704-4e4e-b524-54857991ca60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
