<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zadajte nzov predprimrneho vzdelvacie_6c01b6</name>
   <tag></tag>
   <elementGuidId>1379ee3a-b341-4316-9f6c-11d49b5021b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-predprimarneVzdelavanie']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-predprimarneVzdelavanie</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>514aa506-08ea-4629-8f06-aee2309da677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>4963ad32-e71b-433c-86e6-320a7750ddbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a7d13588-9da8-4112-9ca9-8d5ceb7d24a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-predprimarneVzdelavanie</value>
      <webElementGuid>28382a56-347a-475b-84ce-53103ac92f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>28ac9d03-7f5a-4091-b857-32e45c5ae7da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-predprimarneVzdelavanie&quot;)</value>
      <webElementGuid>b3cb6ed3-4f83-4b71-b923-d81db528ddd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-predprimarneVzdelavanie']</value>
      <webElementGuid>9dc81459-6333-4251-8d04-4edf280a27b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='predprimarneVzdelavanie']/div/div[2]/input</value>
      <webElementGuid>449f8b90-9ed3-43f0-bd3c-1d1a6fe1c9c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div[2]/input</value>
      <webElementGuid>5fe880a9-f41a-416b-a437-a0e12294c593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-predprimarneVzdelavanie']</value>
      <webElementGuid>f9ae965b-8ffa-4d96-98c0-169254423e9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
