<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Odstrni</name>
   <tag></tag>
   <elementGuidId>9a42def5-217b-48a7-a744-9b1317e7d22d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[3]/div[1]/div[1]/div[1]/div[1]/div[3]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1f0fb6c4-b6e1-412b-aa0d-47ef9db12085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button govuk-button--sec govuk-button--sec__warning</value>
      <webElementGuid>e349659e-626b-4843-975e-5c040358a10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-module</name>
      <type>Main</type>
      <value>govuk-button</value>
      <webElementGuid>47cb73cb-b7cb-46af-a55b-19938bd4903e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript: void(0);</value>
      <webElementGuid>e70339cd-000f-4b22-bce9-61ec0494a7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Odstrániť</value>
      <webElementGuid>40690324-32a3-478f-881b-51a61794cb93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sprava-pouzivatelov&quot;)/div[@class=&quot;govuk-width-container&quot;]/div[@class=&quot;govuk-main-wrapper govuk-width-container&quot;]/div[@class=&quot;sprava-pouzivatelov-main&quot;]/div[@class=&quot;pouzivatel-item-container&quot;]/div[@class=&quot;pouzivatel-item&quot;]/button[@class=&quot;govuk-button govuk-button--sec govuk-button--sec__warning&quot;]</value>
      <webElementGuid>c80a94b5-bf30-4236-be70-cf13277e1ad1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sprava-pouzivatelov']/div/div/div/div[2]/div[5]/button[2]</value>
      <webElementGuid>d854e7c9-bffb-49cb-9c02-29f33318176f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Potvrdiť'])[5]/following::button[1]</value>
      <webElementGuid>69c632b8-a3ea-4596-a74e-aefe88a14d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(nepovinné)'])[5]/following::button[2]</value>
      <webElementGuid>ee4f47bd-3385-4f13-9cf6-4cc7ed8e1832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pridať používateľa'])[1]/preceding::button[1]</value>
      <webElementGuid>2b4320e5-2835-4ea0-b666-3f11eeea2213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button[2]</value>
      <webElementGuid>2b5fe94c-6e03-4e7a-897b-e3c2ca91eac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@href = 'javascript: void(0);' and (text() = 'Odstrániť' or . = 'Odstrániť')]</value>
      <webElementGuid>5a60c1b1-af6c-404e-83a0-3c5178185605</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
