<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pouvatea ste spene odstrnili</name>
   <tag></tag>
   <elementGuidId>e001dcf8-a22d-403d-8198-04142126e277</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.govuk-panel__body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Používateľa ste úspešne odstránili.' or . = 'Používateľa ste úspešne odstránili.')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a85b25dc-757c-422b-b454-a6d80d6d9b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-panel__body</value>
      <webElementGuid>99870c20-f324-43a9-9b06-44bffdca6719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Používateľa ste úspešne odstránili.</value>
      <webElementGuid>77806333-fb94-4140-bb70-ae09c2b24826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sprava-pouzivatelov&quot;)/div[@class=&quot;govuk-width-container&quot;]/div[@class=&quot;govuk-main-wrapper govuk-width-container&quot;]/div[@class=&quot;govuk-panel govuk-!-margin-bottom-8 govuk-panel--confirmation&quot;]/div[1]/div[@class=&quot;govuk-panel__body&quot;]</value>
      <webElementGuid>efdece2c-5a3d-40f4-87d1-01cd999028a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sprava-pouzivatelov']/div/div/div/div/div</value>
      <webElementGuid>2b15d4b8-6ce9-457e-b1b6-ca81497dcfc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='check_circle'])[1]/following::div[2]</value>
      <webElementGuid>ff6257ab-8d3a-4af0-bf61-fcbd112f5291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pomoc a podpora'])[1]/following::div[6]</value>
      <webElementGuid>624b625b-1a8e-45e4-87c6-9ace1f727c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close'])[1]/preceding::div[1]</value>
      <webElementGuid>27625424-d980-44d6-8514-95d2ee21d223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div</value>
      <webElementGuid>86751a5a-c20d-4071-a74e-946e40953caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Používateľa ste úspešne odstránili.' or . = 'Používateľa ste úspešne odstránili.')]</value>
      <webElementGuid>f70c626f-c485-4524-9f21-e63c4a8eb788</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
