<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Odhlsi</name>
   <tag></tag>
   <elementGuidId>c94ae76a-5bbb-4ed0-b7ca-5a3fec93eb8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logoutBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='logoutBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4ea1bb33-cc25-4842-bd96-8d64aeedd32c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logoutBtn</value>
      <webElementGuid>faa4b800-6609-4a9f-8bf0-afd2b4060b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/logout?returnurl=%2F</value>
      <webElementGuid>8111e8ad-38a0-48d9-9b35-7b5b79f0cf38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Odhlásiť</value>
      <webElementGuid>8a140c57-a929-4606-b0f9-eb44cb73fb55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logoutBtn&quot;)</value>
      <webElementGuid>4609c249-b201-42e8-8f0a-30b71a942d98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='logoutBtn']</value>
      <webElementGuid>355906c3-d298-4d98-9e10-f823bf3f33e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Odhlásiť')]</value>
      <webElementGuid>f138bb63-38c2-4ce8-9748-302e0f310355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Môj profil'])[1]/following::a[1]</value>
      <webElementGuid>0209e8ce-7b3c-41e7-b345-991380c1b6a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KL'])[1]/following::a[2]</value>
      <webElementGuid>1c896416-c398-4650-b516-a0f504dcfc1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[2]/preceding::a[1]</value>
      <webElementGuid>6a254387-a2ca-4943-b33b-92dd6c0d067e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prihlášky a rozhodnutia'])[1]/preceding::a[1]</value>
      <webElementGuid>99fcb2e8-169e-456e-8e69-0621fa8108b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Odhlásiť']/parent::*</value>
      <webElementGuid>8b63a728-d6fc-4399-a3b2-f5e49a3e3e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/logout?returnurl=%2F')]</value>
      <webElementGuid>2e3bfef9-f156-4f4c-8fe3-fb837a96f4fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>10b0112a-4ba0-4e77-85ab-d233bfc02b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'logoutBtn' and @href = '/logout?returnurl=%2F' and (text() = 'Odhlásiť' or . = 'Odhlásiť')]</value>
      <webElementGuid>947cd626-578d-4b03-8eb8-eda1c187ee1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
