<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_-_1_2_3</name>
   <tag></tag>
   <elementGuidId>8a594e43-5d79-4ef8-bedb-ffb8cf4fafb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zakonnyZastupca2CisloElektronickejSchranky</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zakonnyZastupca2CisloElektronickejSchranky']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f514df72-ae7b-4539-b48a-2e518679d288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zakonnyZastupca2CisloElektronickejSchranky</value>
      <webElementGuid>7ea1f37a-3941-4fca-9f5c-ea4e48b5704b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>16a159bc-0bb9-440b-bbd9-771d71e63fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zakonnyZastupca2CisloElektronickejSchranky&quot;)</value>
      <webElementGuid>e320ffc6-a1b7-4582-9ea4-b6db3c34a245</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zakonnyZastupca2CisloElektronickejSchranky']</value>
      <webElementGuid>6b701f6a-5b7a-49b3-a35a-a49a7687036f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz2']/div[3]/div[2]</value>
      <webElementGuid>d4c05eb6-97b9-4b2e-a8d3-16a596f8fd4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Číslo elektronickej schránky'])[2]/following::div[1]</value>
      <webElementGuid>955c162e-4a6a-4cf9-8826-c781b5346a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum narodenia'])[3]/following::div[4]</value>
      <webElementGuid>9bf8d210-4ead-4a62-8390-29160e81e7e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adresa bydliska'])[2]/preceding::div[1]</value>
      <webElementGuid>02ecec09-5503-408a-9571-06c666175563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Námestie Svätého Egídia 45, Poprad, Slovenská republika'])[1]/preceding::div[2]</value>
      <webElementGuid>fa440b58-4b49-43fa-b1f1-92f4d5c428dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div[2]</value>
      <webElementGuid>8251399c-8d8f-401f-84f3-895b623ac406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zakonnyZastupca2CisloElektronickejSchranky' and (text() = '-' or . = '-')]</value>
      <webElementGuid>1c292f58-57e8-457b-bd88-9715fd88ceab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
