<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pernek 87, 05478, Pernek, Slovensk re_3cb149</name>
   <tag></tag>
   <elementGuidId>2d91230d-73d7-4c7d-b126-753753fbdc2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='trvalyPobytRadio_option_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#trvalyPobytRadio_option_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e3abe73-5111-47ee-87e3-51cbfafd07ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>605782b9-fa0a-42a5-9766-838826162f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trvalyPobytRadio_option_1</value>
      <webElementGuid>6f24d1fa-9815-42c8-b7d1-fdc475a0bd77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>trvalyPobytRadio</value>
      <webElementGuid>ffd37818-1f38-4947-8d61-86451f069e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>04751920-d57a-406c-aea3-b3f89569c94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a26563fb-8d8e-4118-9d06-3e70bf519f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trvalyPobytRadio_option_1&quot;)</value>
      <webElementGuid>6259758c-0e01-4cd6-9c59-03553eef9e9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='trvalyPobytRadio_option_1']</value>
      <webElementGuid>c930e0a7-02e8-4852-825b-a5d1f51390b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trvalyPobytRadio']/div/fieldset/div[3]/div[2]/input</value>
      <webElementGuid>922ecd5b-afd0-4a05-bbd7-b31337adefd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>538abdef-b7c2-485f-be2c-6cad3e6c4af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'trvalyPobytRadio_option_1' and @name = 'trvalyPobytRadio' and @type = 'radio']</value>
      <webElementGuid>a0d56d18-58fb-4138-86b4-8aa4dadd157a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
