<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_input-adresaTPSupisneCislo</name>
   <tag></tag>
   <elementGuidId>70a16b0e-1771-4c52-98fb-796312ad7207</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-adresaTPSupisneCislo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-adresaTPSupisneCislo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f5a2eba-ad4a-41a9-986a-f41c531a1f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>95ab26a9-a4f3-4551-9496-a849b8700d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9fa76006-5724-44c2-be87-c59647cae92e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-adresaTPSupisneCislo</value>
      <webElementGuid>7a728440-f182-4175-bcf4-09fdf6f4c4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>d205be4e-9137-4410-ab0a-fc1f2fe62578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-adresaTPSupisneCislo&quot;)</value>
      <webElementGuid>bb9ffe57-07d0-4802-a153-ec2b0b075ef5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-adresaTPSupisneCislo']</value>
      <webElementGuid>a62cc368-0de4-46bc-b93e-3c26aba12b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adresaTPSupisneCislo']/div/div[2]/input</value>
      <webElementGuid>a8b30edf-416d-4943-866d-851bccd6e797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div[4]/div/div/div[2]/input</value>
      <webElementGuid>bfc28ebf-c8f7-4ae3-9600-9294f51bd374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-adresaTPSupisneCislo']</value>
      <webElementGuid>ff5f6db3-a6b5-4eb2-bb93-939b3079968d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
