<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(nepovinn)_govuk-input autocomplete-input</name>
   <tag></tag>
   <elementGuidId>50b4fa6f-e9a3-47a3-9efe-93316b5e31c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.govuk-input.autocomplete-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8fe4c37-0225-4ac6-95bd-755f699f231b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input autocomplete-input</value>
      <webElementGuid>61bd05ce-63fa-4c12-817a-cdb5c64c3bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>670bbdf0-f927-46f5-b4f6-f06c837ef98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ab9f07b1-0d7a-450f-ba0b-dd533eebf74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>32e77bea-7b5f-4ce8-9daf-bec5a019be82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>autocomplete-label-adresaTPKrajina</value>
      <webElementGuid>adb97bf1-1367-489e-af64-feb27e20569b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>08c426bb-9418-4499-9cc7-e083ab81f80f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adresaTPKrajina&quot;)/div[@class=&quot;govuk-form-group autocomplete-control static-select required&quot;]/div[@class=&quot;input-wrapper&quot;]/input[@class=&quot;govuk-input autocomplete-input&quot;]</value>
      <webElementGuid>09c348f0-6f4e-4f27-9885-b4b8e33bf99b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[10]</value>
      <webElementGuid>bb7654c6-0b8a-4d16-ba0e-b919a8517f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adresaTPKrajina']/div/div[2]/input</value>
      <webElementGuid>6157de69-6172-4415-b3de-8ac600fbcb83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div/div[2]/input</value>
      <webElementGuid>af80b060-c821-42f4-9142-6fc3fefe1da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>fad73497-5a21-4a49-9fd4-e4b0c12a2166</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
