<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Vyhadvanie v prihlkach_fulltext-inpu_1e6782</name>
   <tag></tag>
   <elementGuidId>b7caf06a-ee13-4505-8375-b9ad96353f6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fulltext-input-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fulltext-input-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>89df5008-6a41-44fb-be5b-4b464fec2e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fulltext-input-button</value>
      <webElementGuid>753e1187-cae5-4ed9-98e8-44f1e7a21f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button govuk-button__basic button-search</value>
      <webElementGuid>b9d6a8f2-98f1-4191-8d8f-2d47644f47ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Hľadať</value>
      <webElementGuid>79d0c899-b92f-4909-ba39-9fe106f32035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        search
                    </value>
      <webElementGuid>0616d5f9-1005-477b-852d-cc475c41042a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;riaditel-prihlasky-na-strednu-skolu&quot;)/div[@class=&quot;riaditel-prihlasky-nasich-ziakov-container&quot;]/div[@class=&quot;filter-prihlasok&quot;]/div[@id=&quot;fulltext-input-wrapper&quot;]/div[@class=&quot;input-with-button&quot;]/button[@id=&quot;fulltext-input-button&quot;]</value>
      <webElementGuid>0bf8a222-4bb4-4d7d-a765-909150f69c42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='fulltext-input-button']</value>
      <webElementGuid>120d229f-b43a-4663-a617-820f046669f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fulltext-input-wrapper']/div/button[2]</value>
      <webElementGuid>8008e95e-ba40-4590-8f25-277b1a764770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vyhľadávanie v prihláškach'])[1]/following::button[2]</value>
      <webElementGuid>1fc4245b-694c-463e-b2bc-faf56d2f5179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vybrať všetky'])[1]/preceding::button[1]</value>
      <webElementGuid>521d1f12-9257-493a-bc3d-6765d1d9c61b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(nepovinné)'])[4]/preceding::button[1]</value>
      <webElementGuid>794e5aaa-7e73-4967-a239-b797f54c0b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>604d0ff7-db47-4a9f-a6b5-fe937b23791f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'fulltext-input-button' and (text() = '
                        search
                    ' or . = '
                        search
                    ')]</value>
      <webElementGuid>0c1d464e-a457-47f3-800c-2586ecd48783</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
