<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_421333222111</name>
   <tag></tag>
   <elementGuidId>ecf5a52e-e83d-415b-a9f3-f5e31d8745d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zakonnyZastupca2Telefon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zakonnyZastupca2Telefon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b4117eb5-c597-4c81-a0c0-a228fd6779bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zakonnyZastupca2Telefon</value>
      <webElementGuid>32fbabd0-0897-492c-8e5b-be3fa00ee2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+421333222111</value>
      <webElementGuid>e50fc889-d17d-4268-b308-057638fda8e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zakonnyZastupca2Telefon&quot;)</value>
      <webElementGuid>7ce510ed-4ac1-4cee-b543-d8200b1b08fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zakonnyZastupca2Telefon']</value>
      <webElementGuid>1129895c-3c0e-485b-98f9-39ddb6926d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz2']/div[6]/div[2]</value>
      <webElementGuid>6c26661f-1368-4c97-9ee1-6153bcfac5ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telefónne číslo'])[2]/following::div[1]</value>
      <webElementGuid>c5def034-9ac0-4308-9af6-73228e04948e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mail@test.sk'])[1]/following::div[3]</value>
      <webElementGuid>05a5fa90-7f05-4405-b25b-e05da5a07e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Súhlas druhého zákonného zástupcu'])[1]/preceding::div[1]</value>
      <webElementGuid>1d6ef465-536a-4694-bb4d-724e800c6b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nie'])[1]/preceding::div[2]</value>
      <webElementGuid>b0acd269-a971-4277-8215-bd12b3e4eb88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+421333222111']/parent::*</value>
      <webElementGuid>2d9db253-2145-46b7-9745-03abdc666ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[6]/div[2]</value>
      <webElementGuid>4869607b-cda9-4e69-b626-7be3d884880a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zakonnyZastupca2Telefon' and (text() = '+421333222111' or . = '+421333222111')]</value>
      <webElementGuid>5a32286b-752c-4978-966c-a0f78d13ff7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
