<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_mailtest.sk</name>
   <tag></tag>
   <elementGuidId>cfbd5e60-80d5-4401-8053-f9b032c5c032</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zakonnyZastupca2Email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zakonnyZastupca2Email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2977e5ab-b67b-444a-b83f-39eb2d363862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zakonnyZastupca2Email</value>
      <webElementGuid>974a8a2f-a31f-4d94-a8d8-47ad28f8e050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mail@test.sk</value>
      <webElementGuid>69f46286-d2c0-43c5-9630-7160931ed4d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zakonnyZastupca2Email&quot;)</value>
      <webElementGuid>b7ba5f35-311b-4c69-9ea7-04c207d2e6f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='zakonnyZastupca2Email']</value>
      <webElementGuid>71c6b880-4e04-4c30-97e4-a6e56faae6cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zz2']/div[5]/div[2]</value>
      <webElementGuid>e4dccd12-266d-4ff0-b014-a933ea683616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[2]/following::div[1]</value>
      <webElementGuid>09aade30-7cd8-4799-9991-d4d1ccd1bf3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gemerská cesta 18/99, 58264, Lučenec, Slovenská republika'])[1]/following::div[3]</value>
      <webElementGuid>25ce1f20-c9ab-4aaf-b919-0cc2658a4cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telefónne číslo'])[2]/preceding::div[1]</value>
      <webElementGuid>e7e3f23b-fc8f-4ee6-b95e-1a56e7ccbbf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Súhlas druhého zákonného zástupcu'])[1]/preceding::div[4]</value>
      <webElementGuid>11738ee1-b39d-427c-ae77-e8af2eeb4277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='mail@test.sk']/parent::*</value>
      <webElementGuid>a67c1591-1a27-4262-bc9e-e66f465e8979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[5]/div[2]</value>
      <webElementGuid>978854e5-cf47-4448-bfec-fdd6292d6fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'zakonnyZastupca2Email' and (text() = 'mail@test.sk' or . = 'mail@test.sk')]</value>
      <webElementGuid>ce243072-b5a5-4da6-a893-3c91e02827ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
