<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_EDUID zkladnej koly_eduidZSSuhrn</name>
   <tag></tag>
   <elementGuidId>71c5d4f3-6d28-4938-9855-c097c8fec0f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.eduidZSSuhrn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='info-o-zs']/div[2]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>83da477b-8f2d-4dcd-873e-2d3bfa21a6fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>eduidZSSuhrn</value>
      <webElementGuid>7991d7f8-41dd-4c46-b756-d50cfcd3dee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>910020024</value>
      <webElementGuid>e77e52a8-8ba5-4251-873f-0f8afe35936a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;info-o-zs&quot;)/div[@class=&quot;panel-content info-layout&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;eduidZSSuhrn&quot;]</value>
      <webElementGuid>de193edc-0677-4ae1-afc4-3e1d62ad2eef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='info-o-zs']/div[2]/div[2]/div[2]</value>
      <webElementGuid>4c1ee659-68f1-4a39-83e5-ec9fcd98f070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EDUID základnej školy'])[3]/following::div[1]</value>
      <webElementGuid>57e155f6-2e4f-4c0d-a009-ada72b977835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zo ZŠ na Slovensku'])[2]/following::div[3]</value>
      <webElementGuid>98034a63-b886-422e-8e9b-76e458d141d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov základnej školy'])[3]/preceding::div[1]</value>
      <webElementGuid>a98b3de5-0adb-44e6-8048-ad582886418b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Základná škola s materskou školou, Soblahov 404'])[1]/preceding::div[2]</value>
      <webElementGuid>ddbebb49-413a-4dde-a964-1a11bb1a6308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='910020024']/parent::*</value>
      <webElementGuid>cf374897-7803-4197-94d6-2743880b019c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div[2]/div[2]</value>
      <webElementGuid>872d4cf6-75f9-4810-918d-858c2c399a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '910020024' or . = '910020024')]</value>
      <webElementGuid>1c1fec1b-eeb2-4647-a0f3-9d85319efafb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
