<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Trieda_triedaSuhrn</name>
   <tag></tag>
   <elementGuidId>ab28a516-607b-4a9a-92da-946d01d5b5f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.triedaSuhrn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='info-o-zs']/div[2]/div[5]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>be4b747f-c36e-4858-823d-2163bb647035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>triedaSuhrn</value>
      <webElementGuid>8bd09395-09e9-455a-acf9-80c60ea87d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>9.A</value>
      <webElementGuid>4430e5fe-4172-4e0f-ba53-42103ead7f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;info-o-zs&quot;)/div[@class=&quot;panel-content info-layout&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;triedaSuhrn&quot;]</value>
      <webElementGuid>3cb36d82-9dfe-4dc6-8d4a-1470c6779a25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='info-o-zs']/div[2]/div[5]/div[2]</value>
      <webElementGuid>aba88756-4acd-40bc-95ed-c9f1cec8a996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trieda'])[3]/following::div[1]</value>
      <webElementGuid>9418cf90-d799-4cf8-8792-b1c0758a63e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ročník'])[4]/following::div[4]</value>
      <webElementGuid>223e8d6b-2909-4e58-bc99-ee2d298f2fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rok školskej dochádzky'])[4]/preceding::div[1]</value>
      <webElementGuid>07a25d5a-30d8-41bb-9d97-5a2c85dd0cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vyučovací jazyk v základnej škole'])[4]/preceding::div[4]</value>
      <webElementGuid>de26b06a-b631-4b0a-aee0-6d77b69a7eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='9.A']/parent::*</value>
      <webElementGuid>119be31b-5c7e-4fc3-9102-970ca3123781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div[5]/div[2]</value>
      <webElementGuid>c0f3de21-0cc7-4218-b803-99b53fb2c673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '9.A' or . = '9.A')]</value>
      <webElementGuid>1401d262-44bf-4578-a373-10b999560702</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
