<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Meno_zakonnyZastupcaMeno</name>
   <tag></tag>
   <elementGuidId>5f6ed81b-c5f3-4fd1-8dae-9c8e2cf80e1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.zakonnyZastupcaMeno</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zastupcovia']/div[2]/div[2]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>92748325-d9b2-4cda-ae35-1ea31990cc5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zakonnyZastupcaMeno</value>
      <webElementGuid>fce1ff9f-8ac5-4928-9ff1-28cce197c774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Petra</value>
      <webElementGuid>b15057f8-f553-496c-8c1e-883a5068db17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zastupcovia&quot;)/div[@class=&quot;panel-content&quot;]/div[@class=&quot;zz1 info-layout&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;zakonnyZastupcaMeno&quot;]</value>
      <webElementGuid>e8cf0e56-4c52-4814-a520-39e824d75fad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zastupcovia']/div[2]/div[2]/div/div[2]</value>
      <webElementGuid>0a2213f4-1325-49c0-b518-39a8bf87c4b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meno'])[6]/following::div[1]</value>
      <webElementGuid>a7c6a131-b743-4505-a671-d1079896e139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Osobné údaje zákonného zástupcu č. 1'])[1]/following::div[4]</value>
      <webElementGuid>8021a4ee-5dbf-438d-920d-00a94134e7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priezvisko'])[6]/preceding::div[1]</value>
      <webElementGuid>277ca302-d380-49a3-8026-b6a5f9afc655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Horváthová'])[2]/preceding::div[2]</value>
      <webElementGuid>76f97277-e846-4c17-935c-a27241647764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div[2]/div/div[2]</value>
      <webElementGuid>62deeded-eefc-4be9-98b3-ff179078f72d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Petra' or . = 'Petra')]</value>
      <webElementGuid>83cbe847-c829-4278-984a-ffa2e57ded50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
