<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Miesto narodenia_dietaMiestonarodenia</name>
   <tag></tag>
   <elementGuidId>8ff4c61a-9bd4-4740-86a5-65c475dca940</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dietaMiestonarodenia</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='suhrnny-prehlad']/div[4]/div[2]/div[7]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a77fd0b7-2f0f-4506-a2a3-60edd5425100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dietaMiestonarodenia</value>
      <webElementGuid>3f121dac-cad7-4b96-9532-4fb5abe908fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rožňava</value>
      <webElementGuid>5ae659d9-f45b-4ac9-8cd6-29f7e82246c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suhrnny-prehlad&quot;)/div[@class=&quot;panel-with-header&quot;]/div[@class=&quot;panel-content info-layout&quot;]/div[@class=&quot;panel-item&quot;]/div[@class=&quot;dietaMiestonarodenia&quot;]</value>
      <webElementGuid>92608a97-53ac-421e-8bd4-84b8c172923f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suhrnny-prehlad']/div[4]/div[2]/div[7]/div[2]</value>
      <webElementGuid>3d1f0eb6-3797-44bc-ba55-37dad2cc6ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Miesto narodenia'])[2]/following::div[1]</value>
      <webElementGuid>d6dea0c8-d98a-4b1e-b9a6-d16f58fdf9cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='žena'])[1]/following::div[3]</value>
      <webElementGuid>a2c9bab0-fb0c-46be-9ad4-b063931a30c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Národnosť'])[2]/preceding::div[1]</value>
      <webElementGuid>aa2d86e7-8053-48b6-8b92-5953ac2eb3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='slovenská'])[1]/preceding::div[2]</value>
      <webElementGuid>401e2e28-986f-48bf-926a-3758dac6a08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rožňava']/parent::*</value>
      <webElementGuid>bda1fe7f-678b-41da-9fa3-ab2e32c674a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[7]/div[2]</value>
      <webElementGuid>66017c2d-0a2c-4d12-b7ee-05afe0173bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Rožňava' or . = 'Rožňava')]</value>
      <webElementGuid>e387602f-3286-4532-b0f9-7f5669f839c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
